[Spring 장바구니 - 2단계] 쿤(홍동건) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #120
Opened 2022-06-09 02:52 UTC by Hongdonggeon

2022-06-10 07:30 UTC, lowoon commented
### 인수테스트와 통합테스트
말씀하신 부분은 팀마다 컨벤션을 정해서 진행을 하는 것 같은데요! **저의 개인적인 의견을 말씀드릴게요ㅎㅎ**
어떠한 곳에서 예외를 정하게 되면 누락이 되는 부분이 생기게되고, 이렇게 누락된 부분때문에 이슈가 발생을 하는 것 같아요!
그래서 인수테스트에서 테스트를 했다고 controller에서 안하기 보다는 controller에서는 다 하는 것이 낫지 않을까 생각하구요.
예외인 경우에 다른 프로세스가 있다면 인수테스트로 진행을 하는 것이 좋지만, 단지 메세지만을 보여주는 것이라고 한다면 따로 예외에 대한 인수테스트를 만들어야 하나 라는 생각이 드네요ㅎㅎ

2022-06-10 08:15 UTC, lowoon requested changes
반가워요 쿤! 2단계도 잘 부탁해요 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남겨주세요 ^-^

2022-06-10 08:15 UTC, lowoon commented on src/main/java/woowacourse/auth/config/WebConfig.java
> +    public void addInterceptors(InterceptorRegistry registry) {
interceptor의 url은 shoppingcart에 있는데 auth에서 관리하는 것이 맞을까요??
그리고 interceptor에서 검증을 하는데 검증하는 url에 모두 `@AuthenticationPrincipal`이 있는데요.
interceptor는 정말 특정 url을 제외하고 모든 url에 적용할 때 맞는 방법이지 않을까요?
Resolver에서 값을 전달해주기만 하는데 검증없이 전달해주어도 될까요?

interceptor의 역할의 필요성에 대해 의문이라고 했었는데요.
제가 생각하는 가장 큰 차이점은 resolver는 필요한 곳에 어노테이션을 활용해서 명시적으로 적용하게 하는 방법이고 interceptor는 url 기반으로 적용하고 싶은 url 전체에 적용하는 방법이라고 생각합니다!
경험했던 것을 말씀드리면 interceptor에서 검증을 하는데 제외해야하는 url이였는데 누락해서 제외하지 못한 경우가 있었습니다.
그래서 요청의 응답을 받지 못해 장애가 발생했던 적이 있는데요.
controller에 명시하지 않고 config에 url로 관리를 하다보니 미처 챙기지 못해 생긴 문제였어서 어노테이션 기반으로 필요한 곳에 어노테이션을 명시해서 controller에서 확인할 수 있게하고, url을 제외하는 방식을 사용하지 않도록 수정하고 있습니다!
혹시나 좀더 설명이 필요하시면 dm주세요ㅎㅎ 더 얘기해봐요

2022-06-10 08:15 UTC, lowoon commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    private final ProductService productService;
service 활용 👍

2022-06-10 08:15 UTC, lowoon commented on src/main/java/woowacourse/shoppingcart/dto/CartResponse.java
> +    public CartResponse(Cart cart) {
이런 부분에 정적팩토리 메서드를 활용해볼 수 있을것 같아요ㅎㅎ

2022-06-10 08:15 UTC, lowoon commented on src/main/java/woowacourse/shoppingcart/domain/cart/Cart.java
> +    private final Long id;
개인적인 궁금함인데요
cart를 하나의 주문 상세로 보고 List<Cart>를 주문이라고 본걸까요??

2022-06-10 08:15 UTC, lowoon commented on src/test/java/woowacourse/auth/application/AuthServiceIntegrationTest.java
>  @Transactional
전체적인 테스트를 작성하는게 쉽지 않았을텐데 대단하네요 💯

2022-06-10 08:15 UTC, lowoon commented on src/test/java/woowacourse/shoppingcart/application/CartServiceTest.java
> +        Customer customer = new Customer(1L, "kun", "kun@email.com", "qwerasdf123");
중복되는 객체들 같은 경우는 fixture나 util을 두어서 여러 테스트에서 가져다 쓸 수 있게하면 편할 수 있을 거 같아요ㅎㅎ

2022-06-14 03:52 UTC, Hongdonggeon commented on src/main/java/woowacourse/auth/support/AuthorizationExtractor.java
> +    private static Enumeration<String> extractHeaders(HttpServletRequest request) {
넵!! 메서드 분리하니 , 토큰을 추출하는 방식이 더 분명해지는 것 같네요 😀

2022-06-14 04:12 UTC, Hongdonggeon commented on src/main/java/woowacourse/shoppingcart/exception/bodyexception/DuplicatedProductInCartException.java
> +        super("1101", "중복된 물품입니다.");
넵 저도 이부분에 대해서 고민이 많았는데요! 도메인이 더 많이 추가된다면 검증하고 발생하는 예외 클래스가 많이 늘어날 것 같았어요!! 하지만 커스텀 예외 클래스로 관리한 이유로는 에러코드가 변경될 때, 에러코드를 에러 클래스에서만 관리함으로써 도메인에 영향을 받지 않기 위함이었습니다.

2022-06-14 04:13 UTC, Hongdonggeon commented on src/main/java/woowacourse/shoppingcart/exception/bodyexception/DuplicatedProductInCartException.java
> +        super("1101", "중복된 물품입니다.");
장바구니에 상품이 존재하지 않거나, 이메일이 중복하거나 그런 서비스적인 예외상황 이외에 도메인에서 잘못된 형식을 검증하는 부분은 ValidateException으로 관리하게 변경해주었습니다!! 더 좋은 방법인 것 같네요!!

2022-06-14 04:16 UTC, Hongdonggeon commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    private final ProductService productService;
제가 Service를 의존하게 한 이유에 대해서 말씀드릴게요!! 다음에 프로그램이 커지게 되면 Service 계층에서도 여러 계층으로 나뉠 수 있다고 들었어요!! 그래서 Service에서 Dao를 의존하게 되면 사이에 여러 계층을 무시하고 깊은 의존관게를 가질 수도 있다고 들어서 Service를 의존하게 했어요!! 
혹시 Service를 활용하는 것에 대한 로운의 의견도 말씀해주실 수 있을까요?! 궁금합니다 🤔

2022-06-14 04:47 UTC, Hongdonggeon commented on src/main/java/woowacourse/shoppingcart/dto/CartResponse.java
> +    public CartResponse(Cart cart) {
넵 좋은 생각인 것 같아요!! 한 생성자는 이용되고 있지 않네요!! 정적 팩토리 메서드를 이용하게 했습니다 😀

2022-06-14 04:48 UTC, Hongdonggeon commented on src/main/java/woowacourse/shoppingcart/domain/cart/Cart.java
> +    private final Long id;
Cart 하나를 장바구니에 추가된 하나의 상품이라고 생각했습니다. List<Cart>는 장바구니에 담긴 전체 상품입니다!!

2022-06-14 05:07 UTC, Hongdonggeon commented on src/test/java/woowacourse/shoppingcart/application/CartServiceTest.java
> +        Customer customer = new Customer(1L, "kun", "kun@email.com", "qwerasdf123");
넵 중복되는 Customer 객체와 Product 객체들을 TestFixture로 분리하여 중복제거해주었습니다!

2022-06-14 05:38 UTC, Hongdonggeon commented on src/main/java/woowacourse/auth/config/WebConfig.java
> +    public void addInterceptors(InterceptorRegistry registry) {
제가 정의한 Interceptor와 Resolver의 역할의 차이에 대해 설명드릴게요!!

### Interceptor
사용자가 지정한 URL에 접근하려고 할 때, Controller 요청이 들어오기 전, 인가된 회원인지 검증하는 역할을 한다고 생각했습니다!
그래서 Interceptor에서는 preHandle 메서드에서 토큰이 유효한 토큰인지 검증해주고 있고, 유효한 토큰이 아니라면 401에러를 발생시키게 하였습니다.

### ArgumentResolver
Resolver는 검증의 역할보다는, 검증된 토큰으로서 필요한 정보를 추출해주는 역할을 한다고 생각했습니다!!
Interceptor에서 유효한 토큰인지 검증을 한 번 해주었기 때문에, Resolver에서는 검증을 따로 하지 않고, 토큰에서 사용자를 식별하는 정보를 추출만 해주고 있습니다. Resolver가 없었다면, 인가가 필요한 Controller 핸들링 메서드마다 이메일을 추출하는 로직이 반복되었을텐데, Resolver가 그 문제를 해결해주고 있다고 생각했습니다!!

2022-06-14 06:22 UTC, Hongdonggeon commented on src/main/java/woowacourse/auth/config/WebConfig.java
> +    public void addInterceptors(InterceptorRegistry registry) {
인가가 필요한 Controller 핸들링 메서드에는 어노테이션을 붙여주어서 검증하게 해주었고, 인가가 필요없는 핸들링 메서드에는 어노테이션을 붙여주지 않음으로써 인터셉터에서 어노테이션이 없는 핸들링 메서드는 검증 없이 통과하게 해주었습니다!
Webconfig에서 URL을 추가하거나 제외하는 방식마다 어노테이션 기반으로 관리하는 것이 더 좋은 방식이고, 확장할 때도 더 좋을 것 같네요!! 👍  감사합니다 로운 😀

2022-06-14 08:55 UTC, lowoon commented on src/main/java/woowacourse/auth/config/WebConfig.java
> +    public void addInterceptors(InterceptorRegistry registry) {
코멘트를 시도해본것 좋네요 💯 
다만 제가 말씀드린 것은 한가지 방법, 의견이라는 것을 생각해주세요!
다른 더 좋은 방법이 있을 수도 있답니다ㅎㅎ

2022-06-14 09:16 UTC, lowoon approved these changes
안녕하세요 쿤!😄
이제 Spring 장바구니 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 Spring 장바구니 미션 수고하셨습니다!

2022-06-14 09:16 UTC, lowoon commented on src/main/java/woowacourse/shoppingcart/ui/CartItemController.java
> +        cartService.addCart(request.getProductId(), customer);
장바구니에 상품이 추가될 때마다 요청을 하게 되는 구조인 것 같은데요.
상품 하나를 추가할 때마다 요청을 받게되면 굉장히 많은 요청을 받을 수 있어서요.
front쪽에서 몇개까지는 관리를 하다가 필요할 때만 요청을 하는 방식으로도 할 수 있을 것 같아요ㅎㅎ
이렇게 하면 로그인을 하지 않은 사람도 장바구니를 사용할 수 있겠죠??
다만 이렇게 했을 때, 새로고침이나 다른 상황에서도 장바구의 상품을 어떻게 유지할 지에 대한 고민이 필요할 것 같아요!
이 부분은 front랑 한번 이야기해보면 좋을 것 같아요ㅎㅎ

2022-06-14 09:18 UTC, merged