[Spring 장바구니 - 1단계] 써머(최혜원) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #13
Opened 2022-06-01 04:22 UTC by hyewoncc

안녕하세요, 코니! 
닉네임이 익숙해서 보니 레벨1 체스 때 뵈었더라구요 
이번 장바구니 미션도 잘부탁드립니다 🙇

2022-06-01 23:01 UTC, choihz requested changes
안녕하세요, 써머!

장바구니 1단계 미션을 잘 구현해 주셨네요 👍 간단한 코멘트만 몇 개 남겨 두었는데 확인해 주시고, 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2022-06-02 08:28 UTC, hyewoncc commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
>      }
테스트 자체 메서드 명과 내부 요청 메서드명을 전부 한글로 통일했는데요, 
그래서 상태코드를 비교하는 부분도 분리해서 한글 이름을 붙여주면 테스트를 한 눈에 읽기 편하다고 생각했습니다

2022-06-02 08:44 UTC, hyewoncc commented on src/main/java/woowacourse/auth/support/Encryption.java
> +    }
아니어서 개선했습니다 😭

2022-06-03 02:03 UTC, hyewoncc commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
>      }
500번으로 변경했습니다!

2022-06-04 18:02 UTC, hyewoncc commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
>      }
모든 `dao` 클래스들에 들어가보니 `EmptyResultDataAccessException`가 발생할 수 있는 곳에서 try ~ catch로 해당 예외를 커스텀 예외로 바꿔주고 있었습니다 
그래서 컨트롤러에서 제거했는데요,, DB에서 발생한 예외가 컨트롤러까지 바로 올라오는 건 부적절한 것 같아요
개발해야 할 부분을 중점으로 코드를 읽어서 몰랐는데, 아래 400번 에러도 그렇고 기존 코드를 꼼꼼히 파악해야겠다 생각했습니다 😭

2022-06-04 18:09 UTC, hyewoncc commented
안녕하세요, 코니!  리뷰 남겨주신 내용은 모두 반영했습니다 
읽으면서 기존 코드를 더 꼼꼼히 분석해야겠구나를 깨달았어요 😅 
남은 기간도 잘부탁드려요

2022-06-05 17:11 UTC, choihz approved these changes
안녕하세요, 써머!

수정해 주신 부분 잘 확인했습니다 👍 이번에 남긴 피드백은 다음 단계를 진행하며 확인해 주세요. 그럼 2단계에서 다시 만나요~ 👋

2022-06-05 17:11 UTC, choihz commented on src/main/java/woowacourse/auth/config/LoginConfig.java
> +    }
`/api/customers/password`는 추가로 등록하는 이유가 있나요? 상위 경로를 등록하고 제외할 경로만 제외하면 되지 않을까요?

2022-06-05 17:11 UTC, choihz commented on src/main/resources/schema.sql
> +    username     varchar(255) not null,
코드 상으로는 최대 15자까지로 제약을 두고 있는데 여기선 다르군요. 의도하신 걸까요?

2022-06-05 17:11 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/domain/customer/values/Address.java
> +    }
여긴 길이 제한이 없어도 될까요?

2022-06-05 17:11 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
당연히 정답이 있는 문제는 아니지만, 이 부분은 경로가 적절한지 살짝 고민이 되네요 😅

2022-06-05 17:11 UTC, merged

2022-06-09 08:32 UTC, hyewoncc commented on src/main/java/woowacourse/auth/config/LoginConfig.java
> +    }
당시에 `장바구니, 주문` 경로가 `customers`로 묶여있어서, 임시 방편으로 이렇게 등록해뒀어요!  
현재는 묶여서 같이 추가해뒀습니다

2022-06-09 08:33 UTC, hyewoncc commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +@RequestMapping("/api/customers")
그냥 `/api/login`으로 해도 될 것 같네요 🤔

2022-06-09 08:35 UTC, hyewoncc commented on src/main/resources/schema.sql
> +    username     varchar(255) not null,
아니어서 수정했습니다!