[Spring 장바구니 - 2단계] 애쉬(김동호) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #136
Opened 2022-06-09 06:52 UTC by dongho108

안녕하세요 제이! 애쉬입니다!

기능구현 완료해서 제출합니다.!!

피드백 주실때 까지 리팩토링 하고 있겠습니다!
질문이 생기면 DM으로 드리겠습니다!

리뷰 감사합니다!

2022-06-10 14:30 UTC, JunHoPark93 requested changes
안녕하세요 애쉬!
2단계 잘 구현해주셨어요.
몇 가지 코멘트 남겼는데 확인 후 의견 및 반영부탁드려요~
리팩토링 하고 싶으신 부분이나 질문있으시면 다시 말씀부탁드려요!

2022-06-11 07:12 UTC, dongho108 commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +    public ResponseEntity<Void> checkPassword(@RequestBody PasswordDto passwordDto, HttpServletRequest request) {
비밀번호 확인 api입니다!
저희 팀 내에서 비밀번호 확인 api를 추가하기로 해서 추가했습니다!

2022-06-11 07:55 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +        validateCustomerCart(cartItemId, customerName);
검증은 있는데 테스트가 없었네요!! 테스트 추가했습니다!!

2022-06-11 08:05 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/domain/Product.java
> +            throw new IllegalArgumentException("현재 수량보다 더 많이 꺼낼 수 없습니다.");
`addStock()`에 음수도 들어올 수 있도록 열다보니 해당 메서드랑 맞지 않은 메세지가 생긴 것 같습니다.

그래서 음수가 들어오면 `removeStock()`을 호출하도록 하여 행위를 명시하도록 수정했습니다.

2022-06-11 08:05 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/dto/CartItemsResponse.java
> +    private List<CartItemResponse> cartItemResponseList;
팀끼리 정한 API 스펙에 맞추기 위해 수정해주었습니다!

2022-06-11 08:08 UTC, dongho108 commented on README.md
> +## 🧺 기능 요구사항 2
일단 피드백 주시는동안 `Request` 검증정도를 추가해놨습니다!

그리고 stock, quantity 두가지 비슷한 용어를 혼용하고 있는 부분도 어떻게 할지 고민중입니다.
1. 팀끼리 정한 API 스펙에 맞게 Quantity로 통일한다.
2. 도메인 로직을 미리 짜고 정해진 스펙이라 이렇게 두어도 괜찮다.

cartId 를 -> cardItemId 로 전부 통일 시키려고도 생각중입니다!

2022-06-11 08:11 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/ui/CartItemController.java
> +    public ResponseEntity<Void> updateQuantity(@PathVariable final Long cartItemId, @RequestParam int quantity) {
팀끼리 정한 API 스펙에서 쿼리파라미터로 받기로 결정했습니다!
다음 협업에서는 검증할 데이터는 바디로 받을 수 있도록 회의를 해보는게 좋을 것 같네요.

일단 지금은 quantity 검증을 하지 않고 들어오기때문에 domain 로직에서 반환되는 exception으로 처리되고 있습니다!

2022-06-12 11:17 UTC, JunHoPark93 commented on src/main/java/woowacourse/shoppingcart/dto/CartItemsResponse.java
> +    private List<CartItemResponse> cartItemResponseList;
개인적으로 자료구조 형이 변수명에 들어가는것을 지양하고있는데요, cartItems로 명시해도 나쁘지 않은것같으니 이거는 참고만 부탁드려요~

2022-06-12 11:18 UTC, JunHoPark93 commented on README.md
> +## 🧺 기능 요구사항 2
좋은 고민 해주시고 계시네요! 용어가 혼재되어있으면 생각보다 많은 혼란이 생기더라고요.
어떤 방식이 좋을 지 고민해보시고 선택의 이유도 같이 남겨주시면 좋을것같아요~

2022-06-12 11:20 UTC, JunHoPark93 commented on src/main/java/woowacourse/shoppingcart/ui/CartItemController.java
> +    public ResponseEntity<Void> updateQuantity(@PathVariable final Long cartItemId, @RequestParam int quantity) {
넵 다음에는 적절한 형태로 인자를 받으면 좋을것같아요. 추가적으로 프런트단 검증도있겠지만, 서버쪽에서도 이런 기본적인 것들은 컨트롤러에서 쳐내는걸 추천드려요~

2022-06-12 11:22 UTC, JunHoPark93 requested changes
안녕하세요 애쉬!
리뷰 잘 반영해주고 계시네요! 코멘트 달아놓은 부분도있는데 참고부탁드려요.
아직 고민중이신 부분이 있다고 하여 다시 request changes남겨요.
결정이 되면 다시 요청 남겨주시고 궁금한거 생기면 코멘트 달아주셔요~

2022-06-13 16:38 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/ui/CartItemController.java
> +    public ResponseEntity<Void> updateQuantity(@PathVariable final Long cartItemId, @RequestParam int quantity) {
아하.. 넵 감사합니다!!

2022-06-13 16:39 UTC, dongho108 commented on src/main/java/woowacourse/shoppingcart/dto/CartItemsResponse.java
> +    private List<CartItemResponse> cartItemResponseList;
cartItems도 자료구조 형으로 본다는 말씀이신가요?!

2022-06-14 04:45 UTC, dongho108 commented on README.md
> +## 🧺 기능 요구사항 2
1. 기존에 stock 용어로 사용하던 것들을 quantity로 통일 시켰습니다!
> 용어가 겹치는 메서드에서 혼란스럽다고 느낄 수 있다고 생각해 수정하는 것이 좋다고 판단했습니다!

2. cartId를 사용하던 코드도 전부 cartItemId를 사용하도록 수정해주었습니다!
> 저희가 팀 회의때 cart라는 개념을 없애고 cartItem 이라는 개념만 사용하도록 정했기 때문입니다.
그리고 실제 cartId의 변수명이 cartItemId를 가리키고 있기 때문에 수정해야 한다고 판단했습니다.

2022-06-14 12:14 UTC, JunHoPark93 commented on README.md
> +## 🧺 기능 요구사항 2
넵 좋네요!

2022-06-14 12:27 UTC, merged