[Spring 장바구니 - 2단계] 아스피(신동석) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #137
Opened 2022-06-09 06:53 UTC by shindong96

안녕하세요 토니 :) 아스핍니다!!

이번 협업 미션을 하면서 생각보다 구현 시간이 부족하다고 느껴졌어요. 그렇다보니 TDD에 소홀하게 코드를 짰어요...반성하겠습니다!ㅜ
또, 구조나 도메인 상관관계 등을 고민하다보니 구현이 너무 늦어져서 헐레벌떡하게 되었네요...그래서 지금 테스트가 많이 부족해요ㅜㅜ
너무나 부끄런 코드지만 피드백 기다리겠습니다...
항상 감사합니다!

2022-06-09 22:51 UTC, toneyparky requested changes
안녕하세요 아스피 좋은 방학식 아침이에요!!

두번째 미션 잘 확인했어요! 로직이 이해하기 쉬워서 좋았습니다. 적어주셨듯 시간이 부족해서 마무리 못한 느낌이 드는 코드가 보여서 리뷰 조금 남겼어요 확인 부탁드릴게요~!

주말도 있고 이제 방학이니 천천히, 차분하게 진행하셔도 좋아요. 조금만 더 힘내고 오늘은 방학식을 즐기시죠~

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/domain/cart/CartItem.java
> +    public void checkStock(ProductStock productStock) {
스톡을 확인하는 행위를 하는 메서드네요! 이름을 조금 더 구체화해볼까요?

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/domain/order/OrderDetail.java
> +public class OrderDetail {
Order라는 이름이 아니라 OrderDetail인 이유가 궁금하였으나 레거시 코드명을 그대로 가져간거군요 😂

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/domain/order/OrderRepository.java
> +package woowacourse.shoppingcart.domain.order;
레포지토리와 관련된 인터페이스는 도메인 패키지에, 구현체는 레포지토리 패키지에 위치시키셨군요~!

아스피의 의도가 궁금합니다~!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/CartItemRequest.java
> +    private Integer quantity;
`@NotNull`인데 Integer로 받으신 이유가 있을까요?

추가로 장바구니 생성 시에 사용되는  DTO로 보여지는데  -100 과 같은 값으로도 생성 가능할지 궁금해요!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/ThumbnailImageDto.java
> +public class ThumbnailImageDto {
아스피의 DTO 명명 규칙이 궁금해요~

 Request, Response, Dto  요런  postfix 를 붙이시는군요!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/ThumbnailImageDto.java
> +    public ThumbnailImageDto(String url) {
사용하지 않는 생성자는 지워도 좋겠죠?

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/UpdateCartItemRequest.java
> +    private Integer quantity;
장바구니를 갱신할 때에 사용하는 Dto 네요! 

사용자가 장바구니에 담긴 물건의 수량을 10개로 정한 뒤 5개로 수정하고 싶은 경우가 있을까요?

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/repository/CartItemRepositoryUsingDao.java
> +    public CartItems findByCustomer(long customerId) {
복수의 장바구니 아이템을 반환한다는 의미가 메서드 명에 충분히 표현되어 있나요~?

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        Product productById = productDao.findProductById(cartItemRequest.getProductId());
적절한 변수 명인지 고민해봐요~!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        CartItem updateCartItem = new CartItem(cartItem.getId(), cartItem.getProduct(),
카트에는 재고보다 많은 수량을 넣을 수 있지만 실제 주문을 할 때에 막는 정책을 가지고 가시는 군요~! 좋습니다!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        List<CartItem> deleteCartItems = cartItemDeletionRequest.getCartItemIds().stream()
변수명이 동사로 시작하네요~!

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/OrderService.java
> +    // TODO: 중복 제거 뺼 방법 고려
TODO가 남아있네요~! 

중복되는 코드를 뺄 방법을 고민하셨군요! 고민은 계속 진행중이신걸까요?

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/domain/cart/CartItems.java
> +    public boolean contains(CartItem cartItem) {
사용하지 않는 메서드가 있네요~

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/controlleradvice/ControllerAdvice.java
>  import woowacourse.shoppingcart.exception.IncorrectPasswordException;
변경사항에 없는 코드가 있어서 부득이하게 이곳에 몇가지 리뷰를 남길게요. 

1. Password, Price, Email 등의 VO에 대한 테스트를 작성해주셔야할거 같아요~
2. Username 클래스는 사용되지 않네요.

2022-06-09 22:51 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/entity/OrdersEntity.java
> +public class OrdersEntity {
사용하지 않는 객체에요~!

2022-06-13 04:28 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/domain/cart/CartItem.java
> +    public void checkStock(ProductStock productStock) {
해보겠습니다!!

2022-06-13 04:54 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/dto/ThumbnailImageDto.java
> +    public ThumbnailImageDto(String url) {
앗 수정하겠습니다!

2022-06-13 04:55 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/dto/UpdateCartItemRequest.java
> +    private Integer quantity;
버튼으로 수량을 변경하거나 입력으로 변경할 수 있는 경우를 고려했습니다!

2022-06-13 05:06 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/domain/cart/CartItems.java
> +    public boolean contains(CartItem cartItem) {
삭제하겠습니다...ㅜㅜ

2022-06-13 05:06 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/entity/OrdersEntity.java
> +public class OrdersEntity {
삭제하겠습니다...죄송합니다!ㅜㅜ

2022-06-13 05:16 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        List<CartItem> deleteCartItems = cartItemDeletionRequest.getCartItemIds().stream()
수정했습니다!!

2022-06-13 05:19 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        Product productById = productDao.findProductById(cartItemRequest.getProductId());
product가 더 좋을 것 같아요! 아니면 productToAdd도 괜찮을 것 같습니다!! 현재는 product로 수정했습니다!

2022-06-14 06:19 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/domain/order/OrderRepository.java
> +package woowacourse.shoppingcart.domain.order;
사실 저만의 생각이라기보다 크루와의 대화에서 들은 것이에요! 그런데 레포지토리 인터페이스는 도메인을 받고 반환하기에 도메인과 밀접한 연관을 가지고 있어서 도메인 패키지에 두는 것이 맞는 것 같다는 생각입니다! 서비스의 관점에서 봤을때, 레포지토리 인터페이스는 컬렉션과 같이 사용하니까요!
반면, DAO를 이용하는 구현체는 서비스와 DB 레이어에 그 사이에 있는 것이 맞다고 생각되는데 어느 한 곳으로 위치시키기에 의문이 들어 새로운 패키지를 사용했습니다!

2022-06-14 06:31 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/dto/CartItemRequest.java
> +    private Integer quantity;
-100과 같은 값으로 생성 불가능하게 도메인에서 막아두었는데 따로 Validation을 사용을 안했네요ㅜㅜ수정했습니다!!

Integer를 사용한 이유는 클라이언트에서는 null이 들어올 수 도 있다고 생각해요! 그때 NullPointException이 발생하는 것보다 만들어둔 MethodArgumentNotValidException 핸들러로 상황별로 처리할 수 있게 하는 것이 좋을 것 같다고 생각합니다

2022-06-14 06:32 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/repository/CartItemRepositoryUsingDao.java
> +    public CartItems findByCustomer(long customerId) {
수정해보겠습니다!!

2022-06-14 06:33 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/service/OrderService.java
> +    // TODO: 중복 제거 뺼 방법 고려
저 부분은 그때 말씀드렸던 도메인 주도 설계를 할 때의 해결을 생각했는데 현재 상황에선 좀 더 고민해봐야 할 것 같습니다ㅜㅜ

2022-06-14 06:36 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/dto/ThumbnailImageDto.java
> +public class ThumbnailImageDto {
Request와 Response의 경우는 말그대로 요청과 응답을 나타내고, 두 가지가 일치할 때나 두 가지안에 속해 있는 경우에 DTO를 붙였습니다! 그런데 생각해보니 Dto라는 postfix가 조금 어색한 것 같아요...

2022-06-14 06:53 UTC, shindong96 commented on src/main/java/woowacourse/shoppingcart/controlleradvice/ControllerAdvice.java
>  import woowacourse.shoppingcart.exception.IncorrectPasswordException;
VO 들의 검증 테스트를 만들고 UserName 클래스를 사용하게 수정했습니다!!

2022-06-14 06:59 UTC, shindong96 commented
안녕하세요 토니!
방학을 하고 시골 할머니댁에 다녀왔더니 미션을 빨리 제출해야한다는 공지가 나왔네요ㅜㅜ
늦어서 죄송합니다ㅜㅜ
또, 사용하지 않는 메서드나 클래스를 너무 많이 남긴 점 반성하겠습니다...

2022-06-14 12:12 UTC, toneyparky commented on src/test/java/woowacourse/shoppingcart/domain/customer/vo/PasswordTest.java
> +    }
이런 테스트를 통해 유효한 비밀번호, 유효하지 않은 비밀번호를 드러낼 수 있다고 생각해요. 만일 테스트가 없다면 코드를 읽는 사람은 정규표현식을 하나하나 읽어서 파악해야겠죠? 테스트 잘 짜주셨어요! 한 걸음 더 나아가면 조건을 더 잘 드러낼 수 있도록 테스트케이스를 추가해줄 거 같아요.

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/domain/cart/CartItem.java
> +    public void checkStock(ProductStock productStock) {
확인했어요~ 
앞으로 팀 프로젝트를 진행하면 크루들과 협업을 진행할텐데 메서드명을 잘 지어서 원활한 협업을 유도해보죠!

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/CartItemRequest.java
> +    private Integer quantity;
클라이언트에서 Null 이 들어올 경우 자세하게 안내하고 싶으셨군요. 그것도 괜찮네요. 다만 NotNull 어노테이션을 빼먹지 말자구요~!
또 중요한건 API 문서를 통해 null이 들어올 수 없음을 안내하는거라고 생각합니다!

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/ThumbnailImageDto.java
> +public class ThumbnailImageDto {
어차피 dto 패키지 내에 있으니까 postfix를 안 붙여도 괜찮아요. 충분히 이해할 수 있습니다~
요건 팀플 시작하면 팀원들과 협의하시고 결정하시길!

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/dto/UpdateCartItemRequest.java
> +    private Integer quantity;
여쭤봤던 포인트는 수정시 음수도 들어올 수 있지 않을까에 대한 부분이었어요. 현재는 0과 양수만 허락하니까요. 
팀플에서 비슷한 로직이 있을 경우에 이런 요구사항에 대해서 고려해봐도 좋겠다 싶네요~

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        Product productById = productDao.findProductById(cartItemRequest.getProductId());
네, 아무래도 product가 가장 기본적이고 좋죠!

2022-06-14 12:24 UTC, toneyparky commented on src/main/java/woowacourse/shoppingcart/service/CartItemService.java
> +        List<CartItem> deleteCartItems = cartItemDeletionRequest.getCartItemIds().stream()
확인했어요, update 관련된 변수도 수정하셨군요 👍👍

2022-06-14 12:26 UTC, toneyparky approved these changes
안녕하세요 아스피! 리뷰 반영 착실하게 잘 해주셨네요.

간만에 시골 방문하셨는데 당황스러우셨겠네요 😂😂
리뷰 반영 잘 해주셔서 머지하도록 할게요. 프로젝트 구조 개선과 같은 조금 더 이야기 나누고 싶은 내용은 DM 부탁드리구요. 
레벨 2를 잘 마무리하시고 재미있는 팀 프로젝트를 위해 준비하시길 바라요!

고생 많으셨어요~!

2022-06-14 12:26 UTC, merged