[1단계 - 상품 관리 기능] 연어(황재현) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #173
Opened 2023-04-26 06:26 UTC by nuyh99

안녕하세요 찰리!
오션과 함께 최대한 맞다고 생각하는 방향으로 이번 미션을 구현했습니다.
잘 부탁드려요!!

---
한 가지 질문이 있어요!!
Controller -> Service -> Persistence(DAO) 이러한 구조를 지키려고 노력하다보니, DTO 간 변환이 잦아진 상태입니다.

1. DAO에서는 Entity를 리턴하고, 서비스에서는 받은 Entity를 DTO로 변환해서 컨트롤러로 리턴합니다.
2. 서비스는 컨트롤러에게 DTO를 받아서 도메인 객체로 변환한 뒤, Entity로 변환해서 DAO에게 전달합니다.

사실  위에서 2번째 경우는 도메인 객체의 validation 메서드를 사용하기 위해서 중간에 도메인으로 변경하는 과정이 있습니다.
DTO를 바로 Entity로 변환하고 싶어요. 근데 그러면 Entity에 Validation 로직이 들어가게 되고 도메인 객체가 불필요해진다고 생각해요.

도메인 없이 Entity 클래스를 도메인으로 써도 될 지 의문입니다!

감사합니다!! 😃

2023-04-26 11:56 UTC, Gomding requested changes
안녕하세요 연어!
장바구니 미션 함께하게 된 찰리입니다 🙇 
1단계 미션 잘 구현해주셨네요 💯 
몇 가지 코멘트 남겼으니 확인 부탁드려요!

질문에 대한 답변은 해당 부분에 코멘트 남겼습니다!

궁금한 점 있으시면 시간 상관없이 편하게 DM 남겨주세요~!!

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/dao/ProductDao.java
> +public class ProductDao {
Application 을 실행하니 아래와 같은 경고문이 출력되고 있어요~

경고문은 무시하기 쉽지만 미래에 무서운 버그로 성장할 수 있다는 의미가 될 수 있어요 😈 
무엇이 문제인지 알아볼까요?

<img width="943" alt="image" src="https://user-images.githubusercontent.com/57378410/234557048-a66aff60-7437-407c-98a6-bbb7d780219d.png">

2023-04-26 11:56 UTC, Gomding commented on src/main/resources/templates/index.html
> +                    <p class="product-price" th:text=${product.price}></p>
Thymeleaf 로 잘 구현해주셨네요~ 👍 

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/57378410/234557715-2e8c3b42-6ccf-413c-bb18-54ead8ea197d.png">

2023-04-26 11:56 UTC, Gomding commented on src/main/resources/templates/index.html
> +<html lang="ko" xmlns:th="http://www.thymeleaf.org">
디테일하군요 💯 💯 💯

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/controller/CartController.java
> +    }
개인적으로 CartController 와 Product RestAPI는 관련이 없는 매핑이라고 생각됩니다!

product 용 RestAPI 관련 동작이니 RestController 로 분리해보는것은 어떨까요? 😄

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/service/CartService.java
> +public class CartService {
CartService 인데 내부 동작은 Product 관련 CRUD 군요 🤔 
CartService 로 이름을 지은 이유가 궁금해요!

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/dao/ProductDao.java
> +    }
MySQL 기준으로 EXISTS 쿼리가 존재합니다 😄 

```mysql
SELECT EXISTS (
     SELECT CustomerName 
     FROM Customers
     WHERE CustomerName = 'Alfreds Ftterkiste'
);
```

count(*) 의 경우 DB에 있는 전체 레코드를 조회하여 성능이 좋지 않습니다 😢 

만약 exists 를 지원하지 않는다면 아래와 같이 `Limit 1` 을 줘서 전체를 조회하지 않고 1개라도 찾으면 조회를 멈추도록 할 수 있어요
```mysql
SELECT 1
FROM Customers
WHERE CustomerName = 'Alfreds Futterkiste'
LIMIT 1
```

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/domain/Product.java
> +    }
꼼꼼한 validation 👍

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/dto/entity/ProductEntity.java
> +public class ProductEntity {
> 한 가지 질문이 있어요!!
Controller -> Service -> Persistence(DAO) 이러한 구조를 지키려고 노력하다보니, DTO 간 변환이 잦아진 상태입니다.
> 
> DAO에서는 Entity를 리턴하고, 서비스에서는 받은 Entity를 DTO로 변환해서 컨트롤러로 리턴합니다.
서비스는 컨트롤러에게 DTO를 받아서 도메인 객체로 변환한 뒤, Entity로 변환해서 DAO에게 전달합니다.
사실 위에서 2번째 경우는 도메인 객체의 validation 메서드를 사용하기 위해서 중간에 도메인으로 변경하는 과정이 있습니다.
DTO를 바로 Entity로 변환하고 싶어요. 근데 그러면 Entity에 Validation 로직이 들어가게 되고 도메인 객체가 불필요해진다고 생각해요.
> 
> 도메인 없이 Entity 클래스를 도메인으로 써도 될 지 의문입니다!

Entity 는 다양한 개념으로 사용될 수 있다고 생각해요.
비즈니스 로직을 포함하는 도메인 엔티티 라는 개념으로 사용될 수 있고, DB의 테이블과 매핑되는 영속성 엔티티로 사용될 수도 있죠

entity 를 도메인 객체처럼 사용하고 DB에 저장할 때도 사용했을 때 어떤 문제가 생길까요? 🤔 

만약 dto -> domain object -> entity 변환 과정에 크게 장점이 없다고 생각된다면
그냥 사용해버리면 안될까요? 😄

2023-04-26 11:56 UTC, Gomding commented on src/test/java/cart/controller/CartControllerTest.java
> +        productRequestDto = new ProductRequestDto(null, null, null);
name, imageUrl, price 각각이 null인 상황을 테스트해보는 것은 어떨까요?
하나의 테스트에 3가지가 포함된 느낌입니다!
3가지 중 하나가 잘못 동작할 때 무엇이 문제인지 파악하는 것이 느려지지 않을까요 🤔

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
GlobalExceptionHandler 구현 👍

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/controller/CartController.java
> +    public ResponseEntity<String> createProduct(@RequestBody @Valid ProductRequestDto productRequestDto) {
`@Valid` 사용 👍

2023-04-26 11:56 UTC, Gomding commented on src/main/java/cart/service/ProductMapper.java
> +    }
만능 Mapper 가 된 느낌이군요 🤔 

ProductMapper 가 너무 많은 책임을 가지고 있는것같아요 😢 
각각의 객체들이 변환을 담당하는건 어떨까요?

```java
Product product = productRequestDto.toEntity();
ProductEntity productEntity = ProductEntity.from(product);
ProductResponseDto response = ProductResponseDto.from(productEntity);
```

2023-04-26 12:27 UTC, nuyh99 commented on src/main/java/cart/dao/ProductDao.java
> +public class ProductDao {
헉 감사합니다!!
<img width="649" alt="image" src="https://user-images.githubusercontent.com/93072571/234574199-f482b5f4-147b-4c2a-add7-f49c6e87efdb.png">
위의 메서드를 사용한 것이 문제입니다...!

Varargs 문법을 사용한 다른 오버로딩 버전을 사용하라고 하는데, 왜 Deprecated인지는 공식 문서에 나와있지 않네요ㅠㅠ

2023-04-26 12:35 UTC, Gomding commented on src/main/java/cart/dao/ProductDao.java
> +public class ProductDao {
가변인자가 사용성이 더 좋다고 생각하여 메서드를 추가하면서 Deprecated 된것으로 생각돼요!
(왜 그런지는 [업데이트 문서](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#data-access-and-transactions)에도 없네요..)
```
Several JdbcTemplate signatures with Object[] arguments are deprecated, in favor of their existing varargs equivalents.
```

```java
// args 를 인자로 넣기 위해서는 꼭 배열로 만들어서 넘겨야함
	@Deprecated
	@Override
	public <T> T queryForObject(String sql, @Nullable Object[] args, Class<T> requiredType) throws DataAccessException {
		return queryForObject(sql, args, getSingleColumnRowMapper(requiredType));
	}

// 가변 인자로 꼭 배열이 아닌 단일 객체들을 나열해서 메서드 호출이 가능
	@Override
	public <T> T queryForObject(String sql, Class<T> requiredType, @Nullable Object... args) throws DataAccessException {
		return queryForObject(sql, args, getSingleColumnRowMapper(requiredType));
	}

```

2023-04-26 12:36 UTC, nuyh99 commented on src/main/java/cart/dao/ProductDao.java
> +    }
감사합니다!! 
Boolean.class로 매핑해서 결과를 리턴하도록 반영했습니다.

2023-04-26 12:53 UTC, nuyh99 commented on src/main/java/cart/controller/CartController.java
> +    }
당장은 메서드가 별로 없어서 더 추가될 때 분리하려고 생각했었어요!
하지만 관련이 없다는 의견은 매우 동의합니다. 반영했습니다👍

2023-04-26 12:56 UTC, nuyh99 commented on src/main/java/cart/service/CartService.java
> +public class CartService {
`CartController`와 마찬가지로 프로젝트의 공통적인 서비스 컴포넌트라고 생각했습니다!
이후에 추가적인 메서드들이 생긴다면 각자의 역할에 맞는 서비스로 분리해도 좋을 것 같다고 생각했어요.

하지만 처음부터 `ProductService` 등으로 네이밍을 구체화한다면 더 좋을 것 같네요...!
반영했습니다😃

2023-04-27 10:11 UTC, nuyh99 commented on src/main/java/cart/dto/entity/ProductEntity.java
> +public class ProductEntity {
entity를 도메인 객체처럼 사용한다고 해도 전혀 문제될 것 같지 않습니다.
지금의 제 코드에서 entity와 도메인은 로직의 유무 차이이고, 모든 게 같아요.
오히려 불필요하게 분리를 시킨 느낌이라서 도메인 엔티티를 사용하도록 반영하겠습니다!

2023-04-27 10:24 UTC, nuyh99 commented on src/main/java/cart/service/ProductMapper.java
> +    }
사실 없어도 되는 객체였네요ㅠㅠ
감사합니다!!

2023-04-27 12:05 UTC, nuyh99 commented
찰리 리뷰 감사합니다!!

올려주신 도메인과 엔티티 글은 잘 봤습니다!!
도메인 객체와 엔티티 객체를 따로 사용할 때의 이점을 정말 모르겠어요.
식별자를 가지는 도메인 객체가 엔티티라고 생각하는데, 이 객체를 사용하는 것이 이점이 많은 것 같아요.

코멘트들은 최대한 반영해봤습니다. 이번에도 잘 부탁드려요😃

2023-04-27 12:08 UTC, nuyh99 commented on src/main/java/cart/dao/ProductDao.java
> +public class ProductDao {
감사합니다!! 
varargs는 배열보다 성능면에서는 불리하지만 사용성은 좋아서 채택된 것 같군요.
하지만 그렇다면 배열을 사용한 오버로딩 버전을 제거할 이유는 없지 않을까 하는 생각이 듭니다...!

2023-04-28 13:09 UTC, Gomding commented on src/main/java/cart/service/ProductMapper.java
> +    }
만약 변환하는데 필요한 객체들이 많다거나 매핑하는데 과정인 복잡하다면 Mapper 를 고려해볼 수도 있을것같습니다!

현재는 하나의 객체를 다른 객체로 변환하는 과정이 단순하니 각각의 객체들이 변환을 담당해도 충분하다고 생각해요 😄

2023-04-28 13:17 UTC, Gomding commented on src/main/java/cart/dto/entity/ProductEntity.java
> +public class ProductEntity {
PR 코멘트에서 말씀해주신대로 `Entity` 는 `도메인 객체를 구현하는 하나의 방법`이고

Entit의 특징은 ID 와 같은 식별자를 가지고 객체를 구분하고 상태를 추적하는 것입니다.

도메인 객체라는 큰 범위안에 엔티티, VO 같은 것들이 포함된다고 표현할 수 있겠네요 😄

2023-04-28 13:53 UTC, Gomding approved these changes
안녕하세요 연어!
피드백 반영해주신 부분 확인했습니다!
이번 단계는 넘어가도 되겠어요 😄 
추가로 남긴 코멘트는 2단계 구현하면서 같이 고민해주세요 🙌 

1단계에서 추가로 궁금한 점 있으시면 언제든 DM 남겨주세요~!!

2023-04-28 13:53 UTC, Gomding commented on src/main/java/cart/dao/ProductDao.java
> +        return jdbcTemplate.queryForObject(sql, Boolean.class, id);
Exists 쿼리 잘 작성해주셨네요 👍

2023-04-28 13:53 UTC, Gomding commented on src/main/java/cart/controller/ProductRestController.java
> +    }
REST API 의 URI 표현 규칙을 확인해볼까요?
[REST API 제대로 알고 사용하기](https://meetup.nhncloud.com/posts/92)

약간 요약하여 설명하면
- Rest API 는 URI 에서 정보의 자원을 표현해야 한다. (리소스 명은 동사`보다는` 명사를 사용)
- 행위는 HttpMethod 를 통해 표현 (Post, Put, Delete, Get...)
- `/` 는 계층을 표현 (ex. `https://localhost:8080/animals/dogs`)
- 자원을 표현하는 Colllection과 Document
    - Collection: 문서의 집합 또는 객체들의 집합
    - Document: 문서 또는 한 객체

이걸 적용해보면 
`PUT : https://localhost:8080/products/13` 
-> `PUT 이라는 행위를 할 것이고 products 라는 컬렉션 중 13번(document) 상품에 접근할 거야` 라고 읽을 수 있겠죠?

요약한 것은 좀 더 와닿게 해드리고 싶어서이고 링크 내용이 굉장히 좋으니 한 번 읽어보시면서 REST API 에 대해 학습해보시면 좋겠습니다 😄

2023-04-28 13:53 UTC, Gomding commented on src/test/java/cart/controller/ProductRestControllerTest.java
> +    @Nested
`@Nested` 사용 👍 

테스트 구조에 대한 글 공유드립니다 😄 
- https://johngrib.github.io/wiki/junit5-nested/
- https://helloworld.kurly.com/blog/try-bdd/

2023-04-28 13:53 UTC, Gomding commented on src/main/java/cart/controller/GlobalExceptionHandler.java
>      }
오 좋은 로그 추가네요!
어떤 의도로 로그를 추가했는지 궁금해요!

2023-04-28 13:53 UTC, Gomding commented on src/main/java/cart/entity/Product.java
> +        }
아래와 같이 표현하면 이름 최대길이 값이 변경 됐을 때
예외 메시지를 깜빡하고 변경하지 않는 상황을 방지할 수 있을것같아요 😄 

```suggestion
        if (name.isBlank() || MAX_NAME_LENGTH < name.length()) {
            throw new IllegalArgumentException(String.format("상품 이름은 1 ~ %s 길이여야 합니다.", MAX_NAME_LENGTH));
        }
```

2023-04-28 13:53 UTC, Gomding commented on src/main/java/cart/service/ProductService.java
> +    public void deleteProduct(Long id) {
이 메서드는 Transaction 이 누락됐군요 🤔 

추가로 `@Transaction` 애너테이션이 있으면 어떤 효과가 있을까요?

2023-04-28 13:53 UTC, Gomding commented on src/test/java/cart/controller/ProductRestControllerTest.java
> +    }
상품 업데이트/삭제 시 해당 상품이 없는 경우도 테스트를 추가해볼까요?

2023-04-28 13:54 UTC, merged

2023-04-30 07:42 UTC, nuyh99 commented on src/main/java/cart/controller/ProductRestController.java
> +    }
Path Variable로 id를 나타내면 좋겠네요...! 감사합니다

2023-04-30 07:58 UTC, nuyh99 commented on src/main/java/cart/controller/GlobalExceptionHandler.java
>      }
`IllegalArgumentException`의 경우 예상 가능한 예외이고, 개발자가 발생시키기 때문에 그대로 뷰에게 출력해줘도 된다고 생각해요.
하지만 그 외의 알 수 없는 예외의 경우 클라이언트에게는 추상화된 메세지만 보내주고, 나머지는 로깅하면 좋을 것 같아서 추가했습니다!

2023-04-30 07:58 UTC, nuyh99 commented on src/main/java/cart/entity/Product.java
> +        }
헉 감사합니다!!

2023-04-30 08:10 UTC, nuyh99 commented on src/main/java/cart/service/ProductService.java
> +    public void deleteProduct(Long id) {
헉 빠뜨렸네요...! 감사합니다😃

1단계 미션 때 알아보고 포스팅 해봤습니다.
https://velog.io/@nuyh99/TransactionalreadOnly-true

DB의 트랜잭션처럼 애플리케이션 단에서도 트랜잭션의 이점을 얻기 위해서 사용합니다!

2023-04-30 08:29 UTC, nuyh99 commented on src/test/java/cart/controller/ProductRestControllerTest.java
> +    }
400을 확인하도록 반영했습니다!