[1단계 - 상품 관리 기능] 오잉(이하늘) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #183
Opened 2023-04-26 07:23 UTC by hanueleee

안녕하세요 춘식!
이번 장바구니 미션에 함께 하게 된 오잉이라고 합니다😆
아직 spring에도 api설계에도 익숙하지 않아서 모자른 점이 많을 것 같습니다..ㅎㅎ
잘 부탁드립니다!!

## 궁금한 점
### 1. ProductDao의 반환값
`save`, `update`, `delete` 메소드는 어떤 값을 반환해야 하나요?

현재 상태는 다음과 같습니다.
save : id 반환
update & delete : 영향 받은 row 수 반환 (영향 받은 row 수가 0일 경우 update, delete가 실패한 것이므로 Service에서 확인 후 예외 던지기

### 2. API의 반환값
create, update, delete `API`는 어떤 값을 반환해야 하나요?

현재 상태는 다음과 같습니다.
create : save결과 id & HttpStatus.OK
update : "ok" & HttpStatus.OK
delete : "ok" & HttpStatus.OK

추가적으로 예외가 발생했을 때에는 해당하는 에러메시지와 HttpStatus.BAD_REQUEST 또는 HttpStatus.INTERNAL_SERVER_ERROR을 반환하도록 했습니다!

2023-04-27 17:57 UTC, bimppap requested changes
안녕하세요 오잉, 춘식입니다! 미션 빠르게 잘 구현해주셨네요 👍
질문에 대한 답과 코멘트를 조금 남겨봤으니 확인 부탁드립니다.
궁금하거나 이해가 안 되는 부분은 편하게 DM 주세요!

2023-04-27 17:57 UTC, bimppap commented on src/test/java/cart/controller/ProductControllerTest.java
> +class ProductControllerTest {
> save, update, delete 메소드는 어떤 값을 반환해야 하나요?

CRUD를 실행할 때 어떤 값을 반환해야하는지는 정해진 게 없습니다만, 보통 저는 save는 id 또는 저장된 object을, update는 void, delete는 void 를 반환합니다. 🙂

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/MainController.java
> +public class MainController {
> create, update, delete API는 어떤 값을 반환해야 하나요?

API를 콜했을 때 객체를 반환하면 받는 쪽에서는 항상 json의 형태로 받게 됩니다. 🙂대신 Product 객체를 그대로 반환했을 때와 ResponseEntity로 감싸 반환할 때 어떤 차이가 있는지 한번 알아보면 좋을 것 같습니다!

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/MainController.java
> +public class MainController {
HttpStatus에 대해 얘기해보자면, 응답이 항상 200(ok)일 필요는 없습니다. 저는 [이 글](https://www.moesif.com/blog/technical/api-design/Which-HTTP-Status-Code-To-Use-For-Every-CRUD-App/)을 재밋게 읽었는데 참고하면 좋을 것 같아요.

개인적으로 저는 생성은 201(created), 읽기는 ok(200), 업데이트는 200(ok), delete는 204(no content)를 쓰는 편입니다.

2023-04-27 17:57 UTC, bimppap commented on src/test/java/cart/ProductIntegrationTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
<img width="371" alt="image" src="https://user-images.githubusercontent.com/48675973/234929828-59d592b2-3053-4276-bbf2-bb4a8334bddb.png">

실패하는 테스트가 있는 것 같습니다! 👀

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
![image](https://user-images.githubusercontent.com/48675973/234932292-793cab87-5d49-4ca3-9961-de994d566fd5.png)

Dto는 레이어드 아키텍쳐에서 계층 간 데이터 교환을 위해 사용하는 객체이지만, 보통 웹 레이어와 서비스 레이어 사이를 오갈 때 사용하고 레포지토리 레이어까지 내려오는 건 지양하는 편입니다. 왜 그런지 한번 알아보고 Dao에서 dto를 사용하지 않도록 리팩토링해보는 건 어떨까요?

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/dto/ProductDto.java
> +public class ProductDto {
ProductDto가 도메인처럼 쓰이고 있는 것 같은데, Product라는 도메인을 따로 만들지 않은 이유가 있을까요?

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/MainController.java
> +@Controller()
`@Controller`와 `@RestController`는 무슨 차이가 있을까요?

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
500 에러가 날 경우 에러 메세지를 보내지 않는 이유가 궁금합니다!

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
로깅에 대해 한번 찾아보고 가볍게 적용해보는 건 어떨까요? 로깅을 왜 사용하는지 정리해보면 더 좋을 것 같습니다!

2023-04-27 17:57 UTC, bimppap commented on src/main/resources/data.sql
> +    imgUrl VARCHAR(255) NOT NULL,
imgUrl라면 길이가 255보다 긴 경우도 많을 것 같습니다. smalltext 나 text 자료형을 고려해보는건 어떨까요?

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/ProductController.java
> +    public ResponseEntity<Integer> productAdd(@Validated @RequestBody ProductRequest productRequest) {
`@Valid`와 `@Validated`는 어떤 차이가 있을까요?

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/controller/ProductController.java
> +    @PostMapping("/{id}")
수정을 할 때는 post 보단 put, patch를 쓰는 편입니다! 둘의 차이점에 대해 알아보고 이 API가 적절한 매핑을 하도록 수정해봅시다 🙂

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/dto/ProductRequest.java
> +public class ProductRequest {
ProductRequest가 생성, 업데이트 할 때 같이 쓰이고 있군요. 작은 프로젝트에서는 API가 dto를 공유해도 상관없지만 프로젝트가 좀 더 커지고 복잡해진다면 한 API를 바꾸려고 할 때 다른 API도 고려해야 되는 식으로 변경이 어려워질 수 있습니다. 엔드포인트가 다르면 dto도 따로 만드는게 유지보수에 도움이 됩니다! 🙂

2023-04-27 17:57 UTC, bimppap commented on src/test/java/cart/controller/ProductControllerTest.java
> +    class 상품_저장_테스트 {
값들이 정상적으로 저장이 됐는지 Dao를 이용하거나 get api를 통해 확인하면 좋을 것 같습니다. 업데이트나 삭제에서도 마찬가지고요!

2023-04-27 17:57 UTC, bimppap commented on src/test/java/cart/controller/ProductControllerTest.java
> +        @DisplayName("상품 가격이 음수일 경우 예외가 발생한다.")
예외 처리 테스트도 꼼꼼하게 해주셨네요 👍

2023-04-27 17:57 UTC, bimppap commented on src/main/java/cart/dao/ProductDao.java
> +        MapSqlParameterSource mapSqlParameters = new MapSqlParameterSource()
이전에는 preparedStatment를 썼는데 이번엔 쓰지 않았길래 서치하다가 [재미난 글](https://stackoverflow.com/questions/37464791/spring-jdbctemplate-vs-preparedstatement-performance-difference)을 읽어서 한번 공유해봅니다ㅎㅎ

2023-04-28 04:39 UTC, hanueleee commented on src/test/java/cart/ProductIntegrationTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
전체 테스트를 돌리는 것을 놓쳤네요..!! 꼼꼼하게 보도록 하겠습니다 😂

2023-04-28 04:42 UTC, hanueleee commented on src/test/java/cart/controller/ProductControllerTest.java
> +class ProductControllerTest {
그러면 혹시 `update`나 `delete`가 실패하였을 경우에는 어떻게 처리하나요??
저는 영향받은 row수를 반환해서 0인경우 service에서 예외를 발생시키도록 했는데, 이 방법이 맞는지 모르겠습니다..!

2023-04-28 05:34 UTC, hanueleee commented on src/test/java/cart/controller/ProductControllerTest.java
> +class ProductControllerTest {
또는 service에서 update나 delete 전에 `findById`를 사용해서 미리 확인한 후 없으면 예외를 던지고, 있으면 실행하는 것이 좋을까요?

2023-04-28 05:38 UTC, hanueleee commented on src/main/java/cart/dto/ProductDto.java
> +public class ProductDto {
이번 미션에서는 딱히 비즈니스 로직이라고 느껴지는 부분이 없어서 도메인을 따로 만들지 않았습니다!

2023-04-28 05:47 UTC, hanueleee commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
500에러가 날 경우 세부 에러 메시지를 보내지 않았던 이유는
클라이언트에게 너무 상세한 예외 메시지가 전달되는 것을 방지하기 위해서였습니다!

하지만 다시 보니 위에 IllegalArgumentException관련 예외는 그대로 클라이언트에게 전달되도록 작성해놨네요..ㅎㅎ

2023-04-28 05:50 UTC, hanueleee commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
예외가 발생했을 경우 4xx 5xx 이런 상태코드만 제대로 설정해주는 것이 좋은지 또는 적절한 예외 관련 메시지도 body에 넣어주는 것이 좋은지 궁금합니다!

2023-04-28 06:14 UTC, hanueleee commented on src/main/java/cart/controller/MainController.java
> +public class MainController {
1. 객체를 반환했을 때(@ResponseBody와 객체)
- 기본적으로 HTTP 상태 코드 200 OK와 함께 객체를 반환
- @ResponseStatus를 활용하여 응답 코드를 설정할 수는 있지만, 아무래도 어노테이션이기 때문에 유연성이 떨어진다
2. ResponseEntity로 반환했을 때 (ResponseEntity 속 객체)
- 본문 데이터 뿐 아니라 상태 코드 및 헤더까지 설정할 수 있다. 즉 클라이언트에게 더 많은 정보를 전달할 수 있다. 
- HTTP 응답을 명시적으로 제어할 수 있다.

2023-04-28 06:30 UTC, hanueleee commented on src/main/java/cart/controller/MainController.java
> +public class MainController {
단순하게 객체를 반환하는 것 보다는 ResponseEntity로 헤더, 상태코드까지 설정할 수 있기 때문에 현재는 ResponseEntity로 반환하도록 구현했습니다.
근데 이 body에 어떤 데이터가 들어가야 하는지 고민이 됩니다.
create, update, delete 모두 처리된 객체정보를 body에 담아 반환하는 것이 좋을까요?? 아니면 지금 처럼 body는 빈상태로 상태코드만 적절히 처리해주는 것이 좋을까요??

2023-04-28 06:39 UTC, hanueleee commented on src/main/java/cart/controller/MainController.java
> +@Controller()
- `@RestController`는 `@Controller`에 `@ResponseBody`가 포함되어있습니다.
- `@Controller`는 View를 반환하기 위해 주로 사용되고, `@RestController`는 JSON, XML 등의 데이터를 반환하기 위해 주로 사용됩니다.

2023-04-28 06:43 UTC, hanueleee commented on src/main/java/cart/controller/MainController.java
> +@Controller()
저는 기존에 view를 반환하는 MainController와 ResponseEntity를 반환하는 ProductController에 모두 `@Controller`를 붙여줬었습니다.
그 이유는 `@RestController`는 `@ResponseBody`가 모든 메소드에 달릴 때에 사용하는 것이라고 생각해서 ResponseEntity를 반환하는 경우에는 굳이 필요없다고 판단했습니다.

하지만 다시 생각해보니 `@ResponseBody` 적용 여부도 중요하지만 `@RestController`라는 명칭만으로 "아 이 controller는 view가 아닌 데이터를 반환하는 애구나"라는 점을 드러낸다는 점도 메리트라는 생각이 들어서
ProductController는 `@RestController`로 수정했습니다!

2023-04-28 06:54 UTC, hanueleee commented on src/main/java/cart/controller/ProductController.java
> +    @PostMapping("/{id}")
PUT : 리소스를 대체
- 리소스가 있으면 대체, 해당 리소스가 없으면 생성 (쉽게 이야기해서 덮어버림)
- 클라이언트가 리소스를 식별 (클라이언트가 리소스 위치를 알고 URI 지정) <- POST와의 차이점
PATCH : 리소스 부분 변경
- 변경된 리소스만 변경

2023-04-28 06:56 UTC, hanueleee commented on src/main/java/cart/controller/ProductController.java
> +    @PostMapping("/{id}")
현재 코드에서는 변경된 리소스만 따로 얻어올 수 없기 때문에 리소스를 통째로 덮어쓰는 방식으로 동작합니다.
그렇기 때문에 리소스를 덮어버리는 PUT 메소드로 매핑하도록 수정하였습니다!

2023-04-28 07:11 UTC, hanueleee commented on src/main/java/cart/dto/ProductRequest.java
> +public class ProductRequest {
헉 `엔드포인트가 다르면 dto도 따로 만드는 것이 유지보수에 도움이 된다`..!!
감사합니다!!

2023-04-28 07:44 UTC, hanueleee commented on src/test/java/cart/controller/ProductControllerTest.java
> +    class 상품_저장_테스트 {
넵 테스트 보완했습니다!

2023-04-28 08:29 UTC, hanueleee commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
로그의 장점
- 쓰레드 정보, 클래스 이름 같은 부가 정보를 함께 볼 수 있고, 출력 모양을 조정할 수 있다.
- 로그 레벨에 따라 개발 서버에서는 모든 로그를 출력하고, 운영서버에서는 출력하지 않는 등 로그를 상황에 맞게 조절할 수 있다.
- 시스템 아웃 콘솔에만 출력하는 것이 아니라, 파일이나 네트워크 등, 로그를 별도의 위치에 남길 수 있다. 특히 파일로 남길 때는 일별, 특정 용량에 따라 로그를 분할하는 것도 가능하다.
- 성능도 일반 System.out보다 좋다.

ControllerAdvice에 간단하게 로그를 적용해보았습니다!!

2023-04-28 09:11 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
검색해보니 Dto가 레포지토리 레이어까지 내려오는 것을 지양하는 이유는 다음과 같았습니다.

 1. 불필요한 데이터 전송: Repository Layer는 DB와 직접적인 연결을 가지는데, 여기에 DTO를 통해 데이터를 전달하면 DB에 불필요한 데이터까지 전달될 가능성이 높아진다. 이는 네트워크 부하를 증가시키고 응답 시간을 늦추는 원인이 될 수 있다.
2. 비지니스 로직과의 분리: Repository Layer는 비지니스 로직과 직접적인 관련이 없는 데이터 엑세스 계층이다. 따라서 Repository Layer에서 DTO를 직접적으로 사용하면, 데이터베이스 구조나 SQL 쿼리 변경 등과 같은 Repository Layer의 변경 사항이 Service Layer에까지 영향을 미칠 수 있다.

2023-04-28 09:21 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
좀 더 찾다보니 `Entity`라는 개념을 접하게 되었습니다.
- Entity객체는 데이터베이스의 테이블과 매핑된다
- Entity는 데이터베이스의 각 레코드를 객체 지향 프로그래밍에서 사용되는 객체로 표현한 것
- DTO는 보통 Entity 객체와 매핑되지 않으며, 필요에 따라 Entity 객체와 DTO 객체 간의 변환 작업이 필요하다

2023-04-28 09:27 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
그럼 Entity란 데이터베이스의 테이블과 매핑되는 객체이면서
동시에 service-repository간 정보 전달용 dto의 다른 명칭일까?
라는 결론에 도달하였습니다..! 혹시 춘식은 이 생각에 대해서 어떻게 생각하시나요??

2023-04-28 13:26 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
service-repository 사이 정보전달에 dto대신 entity를 사용하도록 수정했습니다!

2023-04-28 13:30 UTC, hanueleee commented on src/main/resources/data.sql
> +    imgUrl VARCHAR(255) NOT NULL,
TEXT 자료형으로 수정하였습니다!

2023-04-28 13:40 UTC, hanueleee commented on src/main/java/cart/controller/ProductController.java
> +    public ResponseEntity<Integer> productAdd(@Validated @RequestBody ProductRequest productRequest) {
`@Validated` 는 스프링 전용 검증 애노테이션이고, `@Valid` 는 자바 표준 검증 애노테이션입니다.
`@Validated`는 `@Valid`의 기능을 포함하고 있으며, 추가적으로 유효성을 검증할 옵션에 대한 그룹을 지정할 수 있는 기능이 있습니다!

2023-04-28 13:53 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +        MapSqlParameterSource mapSqlParameters = new MapSqlParameterSource()
- JdbcTemplate은 Statement를 사용하기 때문에 PrepareStatement에 비해 성능이 좋지 않다. 
- 이유 : PreparedStatement를 사용하는 경우에는 엑세스 경로가 미리 계산되어 캐시되기 때문
- 하지만 JdbcTemplate에도 PreparedStatement를 사용하는 메서드가 있긴 하기 때문에(ex. batchUpdate) 이를 사용하면 성능 차이를 줄일 수 있다.

신기하네요..!!

2023-04-29 08:24 UTC, bimppap commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
> 예외가 발생했을 경우 4xx 5xx 이런 상태코드만 제대로 설정해주는 것이 좋은지 또는 적절한 예외 관련 메시지도 body에 넣어주는 것이 좋은지 궁금합니다!

케이스마다 다르지만 bad request 와 같은 이유라면 클라이언트에게 무엇이 잘못되었는지 정확하게 알려주는 게 좋습니다. (예시: 비밀번호는 문자 숫자 특수문자의 조합으로 8 이상으로 입력해주세요) 그러나 이 부분은 프론트와도 조율이 필요한 부분이라 프로젝트 또는 팀마다 정책이 달라질 수 있습니다. 🙂

internal server error 등의 5xx 에러들은 에러 메세지를 그대로 내보낼 경우 내부 정보(디비, 테이블명, 필드 변수 등)가 유출되어 보안에 문제가 생길 여지가 있기 때문에 클라이언트 쪽엔 알 수 없는 에러가 발생했다고 하고 로그로 남기는 게 좋습니다.

2023-04-29 08:28 UTC, bimppap commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
적절한 로그 레벨에 대해서도 고민해보면 좋을 것 같습니다. 현재는 에러가 나면 모두 error 레벨로 처리하고 있는데, 예상한 에러들(클라이언트가 잘못된 값을 보냈다던지)은 서버에서 대응할 부분이 크게 없어 info 레벨로 설정해도 충분합니다. 하지만 예상치 못한 에러라면 서버쪽 대응이 필요할 수 있기 때문에 error 레벨로 설정하는 게 좋습니다. 레벨 정책 또한 팀바팀인 점 참고해주세요!

2023-04-29 08:49 UTC, bimppap commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
> 그럼 Entity란 데이터베이스의 테이블과 매핑되는 객체이면서
동시에 service-repository간 정보 전달용 dto의 다른 명칭일까?
라는 결론에 도달하였습니다..! 혹시 춘식은 이 결론에 대해서 어떻게 생각하시나요??

엔티티는 도메인 영역의 일부이기 때문에 DTO와는 목적이 다릅니다. 도메인+데이터베이스의 테이블과 매칭되는 객체라고 생각해주시면 됩니다!

쉽게 말하자면 DTO는 웹, 서비스 레이어를 오가는 기차 같은 거고, 엔티티는 데이터베이스 내 테이블의 분신(?)이라고 보면 됩니다ㅎㅎ

2023-04-29 08:54 UTC, bimppap commented on src/main/java/cart/controller/MainController.java
> +public class MainController {
api가 응답할 때 body에 넣어줘야 할 값은 사실 프론트와 조율해서 정해야 할 부분입니다. 🙂 때문에 이렇게 하는 게 정답이다! 라는 건 없어요. 현재 js 파일 내 로직들을 보면 api를 콜했을 때 반환되는 response를 사용하지 않고 리로드를 하고 있기 때문에 body에 데이터를 넣지 않아도 됩니다. 때문에 지금처럼 body는 빈 상태로 적절한 상태코드만 보내줘도 됩니다.

2023-04-29 09:05 UTC, bimppap commented on src/test/java/cart/controller/ProductControllerTest.java
> +class ProductControllerTest {
> 그러면 혹시 update나 delete가 실패하였을 경우에는 어떻게 처리하나요??
저는 영향받은 row수를 반환해서 0인경우 service에서 예외를 발생시키도록 했는데, 이 방법이 맞는지 모르겠습니다..!

만약 '춘식' 이라는 이름을 '춘식'으로 업데이트하면 영향 받는 row 수가 0일겁니다. 이걸 실패했다고 볼 수 있을까요? 저는 업데이트는 **성공**했지만 **영향 받은 row수가 없었을 뿐**이다. 라고 보고 싶네요. 🙂 하지만 '춘식'을 '오잉'으로 바꾸려는데 이미 '오잉'이라는 이름이 있어 바꿀 수 없어 영향 받는 row수가 0이 됐다면, 이 경우엔 실패라고 볼 수 있습니다.

삭제도 마찬가지로, 이미 없는 걸 삭제하면 삭제는 성공했지만 영향 받은 row수가 없다고 보는 게 맞고요. 있는 걸 삭제했는데 실제로는 삭제가 안 됐다면 실패했다고 볼 수 있습니다.

결론적으로 영향 받는 row 수는 실패의 원인이 되기엔 애매하므로 더 정확한 요구사항으로 성공 영부를 분류하는게 맞다고 봅니다.

2023-04-29 09:16 UTC, bimppap approved these changes
안녕하세요 오잉, 춘식입니다!
피드백 빠르게 반영해주셨네요 👍
이번 단계는 여기서 머지하도록 하겠습니다.
질문에 대한 코멘트들 남겨놨으니 확인 부탁드립니다. 🙂
궁금하거나 이해가 안 되는 점은 편하게 DM 주세요.
다음 단계에서 만나요!

2023-04-29 09:16 UTC, bimppap commented on src/main/java/cart/controller/CartControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorMessage);
```suggestion
        return ResponseEntity.badRequest().body(errorMessage);
```

이렇게 바꿀 수도 있습니다ㅎㅎ

2023-04-29 09:17 UTC, merged

2023-05-06 05:01 UTC, hanueleee commented on src/main/java/cart/dao/ProductDao.java
> +    public int save(ProductRequest productRequest) {
무슨 느낌인지 알 것 같습니다!! 감사합니다!!

2023-05-06 05:15 UTC, hanueleee commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
로그 레벨 : 소프트웨어에서 발생한 이벤트를 기록하는 로그의 중요도를 나타내는 단계
(디버깅, 모니터링 및 분석을 위해 로그를 사용하는 개발자나 운영자에게 중요)

- DEBUG: 디버깅을 위한 상세한 정보를 제공 -> 주로 개발 환경에서 사용
- INFO: 시스템이 정상적으로 작동하는지를 확인하는 정보를 제공
- WARNING: 잠재적인 문제가 발생할 수 있는 경고 메시지를 제공 (이벤트가 발생했지만 시스템이 여전히 작동 중인 경우)
- ERROR: 심각한 문제가 발생하여 시스템이 작동을 멈추거나 중단되는 경우
- CRITICAL: 매우 심각한 문제가 발생하여 시스템이 완전히 멈추는 경우(이러한 경우는 드물지만, 대응이 즉시 필요)

2023-05-06 05:15 UTC, hanueleee commented on src/main/java/cart/controller/CartControllerAdvice.java
> +    }
감사합니다!!