[1단계 - 상품 관리 기능] 주노(최준호) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #203
Opened 2023-04-26 11:38 UTC by Choi-JJunho

안녕하세요 웨지! 🥔
장바구니 미션을 리뷰받게된 주노입니다.

고민되는 내용 같이 작성하여 리뷰요청드립니다!
잘부탁드립니다!

# 💬 테스트 이렇게 하는게 맞나?

페어와 함께 테스트를 작성하면서 테스트를 계층별로 어떻게 수행할 지 고민이 되어 다음과 같이 이야기를 나눠봤습니다.

## Controller 테스트

어떤 요청에 대한 응답코드만 확인하는 테스트를 작성했다.
이렇게 하는게 맞나?

### 왜 Controller에서 SpringBootTest를 하지 않았지?

- 주노 : 다양한 레이어를 거치는 테스트가 되면서 향후 기능 변경에 따라 해당 테스트의 유지보수가 어려워 질 것 같다.

- 레오 : 컨트롤러는 요청과 Service를 맵핑해주는 역할을 수행하기 때문에 Controller보다는 Service에서 통합테스트 수행이 설득력 있다.

### Controller에서 통합 테스트를 수행한다면 뭐가 좋을까?

- 주노 : 사용자의 요청에 따른 실제 시나리오를 수행해볼 수 있어서 단위테스트로는 확인할 수 없는 요인을 발견할 수 있다.

- 레오 : 모든 계층을 검증할 수 있다.

→ 지금은 서비스 테스트로도 시나리오를 충분히 검증할 수 있다고 생각되어 SpringBootTest를 Service계층에서 수행하는걸로 하자!

## Service 테스트

SpringBootTest를 통해 비즈니스로직이 정상 수행되는지 확인했다.

> Q : 해당 테스트를 통합테스트라고 할 수 있을까?

## DAO 테스트

JDBCTest를 이용해 CRUD에 대한 단위테스트를 진행했다.

> Q : save(), find()에 대한 단위테스트를 진행하는 과정에서 각각을 검증하기 위해서 `save()`와`find()`를 서로 사용해야 검증할 수 있는데...
이렇게 되면 단위테스트가 아닌가?
> > 개인적으로 `저장, 조회의 흐름를 하나의 단위로 묶어서 생각할 수 있다`라는 기준을 세웠고, 때문에 단위테스트라고 말할 수 있다고 생각합니다
웨지는 `저장, 조회가 하나의 단위로 묶인다`라는 의견에 어떻게 생각하시나요?

2023-04-26 15:56 UTC, sihyung92 requested changes
안녕하세요 주노~ 웨지입니다!
깔끔하고 빠르게 구현해주셨군요 ㅎㅎ 👍
고민되는 내용도 작성해주셔서 좋았습니다
리뷰 남겼으니 확인해주세요!

---
### Q&A

Q. Service 테스트는 통합테스트 인가요?
- 통합테스트와 단위테스트, End To End 테스트는 부르는 사람마다 용어를 다르게 쓰는 경향이 있는거 같아요. 예컨데 통합 테스트는 두 개 이상의 레이어가 결합되면 통합 테스트라고 부르는 사람도 있고, 실서버 환경처럼 모든 컴포넌트가 결합한 채로 요청부터 응답까지 보는 E2E (end to end) 테스트를 통합테스트 라고 부르는 사람도 있습니다. 또 단위테스트 같은 경우 단 하나의 클래스만 테스트 해야 단위 테스트라고 부르는 사람이 있는 반면 여러 클래스를 활용하더라도 단일 레이어에서만 테스트 되면 단위 테스트 라고 부르는 사람도 있는 등 용어가 상충하는 지점이 있음을 감안하고 생각해야 합니다. 어쨌든 대강의 그림은 
  - 통합테스트 - 여러 요소의 결합을 테스트 하는 것
  - 단위 테스트 - 단일 요소를 테스트 하는 것

이라고 생각하면 좋을 것 같은데요, (이 때 요소의 정의가 사람마다 다르겠죵 크루들이랑 많이 토론해보셔요 :ultra-past-farrot: ) Service에서 persistence layer 까지 들여와 테스트하면 저는 일단 통합 테스트라고 부릅니다 ㅎㅎ

Q. save()랑 findById()는 서로 사랑하는 관계
- 이건 좀 애매한 지점이라 어느정도 타협을 하셔야 합니다 ㅎㅎ 저라면 일단 저장테스트(), 조회테스트() 로 나눈 후 save() 때는 findById()로 검증하고, findById()는 save()로 픽스쳐를 만들어서 하는, 뭔가 중복느낌 나게 할거 같긴 합니다 ㅋㅋ 나중에 저장기능과 조회기능이 어떻게 진화해 나갈지 모르는 일이니까요 
- 그런데 전 이게 단위테스트냐 아니냐 하는 식의 사고는 안 하는거 같아요. `기능이 충분히 테스트 되었는가?` 
 / `내가 이 시스템을 믿고 쓸 수 있을 정도로 테스트 되었는가?` 이런 것들을 생각하는 편이라서요, 굳이 따지자면 묶이거나 안 묶이거나 단위 테스트라고 생각하긴 하는데 저한테 의미 있는 말은 아닙니다 ㅎㅎ
 
 다음에 봐용~~~

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/domain/Image.java
> +        }
empty String만 검증하는 것으로 충분할까요? hack.sql 같은 이미지 리소스가 아닌 데이터가 들어올 일은 없을까요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/domain/Price.java
> +    private final Integer value;
반드시 값이 있음이 보장되는 데이터인데 랩퍼 타입을 사용한 이유가 있을까요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/dto/ProductRequest.java
> +    private final Integer price;
위 리뷰와 이어집니다. Positive, NotNull 빈 벨리데이션을 하는데 Integer여야 하나요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.internalServerError().body(e.getMessage());
서버에서 발생하는 모든 예외 메시지를 그대로 내려주어도 괜찮을까요? 예컨데 DB Exception은 비즈니스 오류 상황 (find 했는데 없다) 등 에만 쓰이고 있는데, 만약 Unique Key Constaint 등을 어겨 DB 예외가 발생하면 디비 스키마가 응답으로 노출될거 같습니다.

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/service/ProductService.java
> +                .orElseThrow(() -> new DBException("데이터가 정상적으로 저장되지 않았습니다."));
DB Exception은 지나치게 추상적인 것  같습니당! 뭔가 DB 인프라단에서 발생한 에러라고 느껴져요. ResourceNotFound 같은 비즈니스 오류로 수정하면 어떨까요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/service/ProductService.java
> +                .orElseThrow(() -> new NoSuchElementException("해당 상품을 찾을 수 없습니다." + System.lineSeparator() + "id : " + id));
ㅎㅎ 아 이 부분을 보고 이해했습니다. save에서 orElse인 경우는 인프라 예외라고 파악하셨군요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/service/ProductService.java
> +                .orElseThrow(() -> new DBException("데이터가 정상적으로 저장되지 않았습니다."));
요 부분은 Optional<ProductEntity>가 아니라 객체를 바로 반환하는 식으로 변경하는게 나을거 같아요 ㅎ 트랜잭션으로 인해 보장받는 생성이므로 orElse가 발생하지 않고, 문제가 생기면 DB 내부 예외가 발생할거에요

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/domain/Product.java
> +                new BigDecimal(productRequest.getPrice())
Price는 int 타입의 VO인데 BigDecimal로 받아서 전환하는 이유가 있을까요? 100.1원을 의도하고 넣었는데 정작 결과는 100원이 들어가서 속상할거같아요

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/domain/Product.java
> +    public static Product from(ProductRequest productRequest) {
도메인 모듈에서 dto를 의존하면 뷰 변경사항이 도메인까지 전파됩니다.
패키지 의존 방향에 맞춰서 메서드 위치를 결정하는 연습을 해보셔용
controller -> service -> dao (뒤쪽 패키지 객체들은 앞쪽 패키지에 속한 객체를 몰라야함)

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/entity/ProductEntity.java
> +public class ProductEntity {
엔티티와 도메인 객체를 분리한 이유가 있을까요? 엔티티 객체는 왜 행위는 가져가지 않나요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/resources/data.sql
> +    name  VARCHAR(50) NOT NULL,
ㅎㅎ 비즈니스 정책과 동일한 스키마 👍

2023-04-26 15:56 UTC, sihyung92 commented on src/test/java/cart/controller/ProductControllerTest.java
> +        when(productService.findAll())
mocking과 mockMvc를 잘 활용하고 계시군요 👍

2023-04-26 15:56 UTC, sihyung92 commented on src/test/java/cart/controller/ProductControllerTest.java
> +                .andExpect(status().isCreated());
```suggestion
                        .contentType(MediaType.APPLICATION_JSON_VALUE))
                 .andDo(print())
                .andExpect(status().isCreated());
```
프린트도 찍어 실제 요청된 값과 응답값을 확인하시는 걸 권장합니다 👍 테스트는 기능명세의 의미도 있어서 결과가 이해하기 쉬운 형태일수록 좋습니다

2023-04-26 15:56 UTC, sihyung92 commented on src/test/java/cart/fixture/ProductFixture.java
> +public class ProductFixture {
Fixture를 활용하셨군요 ㅎㅎ 👍  
좀더 객체화 해서 PIZZA의 요청과 응답이 PIZZA_REQUEST, PIZZA_RESPONSE와 연결되도록 구성해주시면 사용이 더 편리할거같아요.

2023-04-26 15:56 UTC, sihyung92 commented on src/test/java/cart/service/ProductServiceTest.java
> +
2줄이 개행되어버린!

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
경험상 Advice들은 별도 패키지 (/aop라던지 /config 라던지) 로 모아두는게 관리가 편했습니다. 도메인 별로 분리되어있으면 어떤 횡단관심사들이 있는지 한눈에 파악하기 어려웠어요

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/dao/ProductDao.java
> +public interface ProductDao {
Dao는 왜 인터페이스일까요? 주노는 추상화하는 기준을 어떻게 잡고계신가요?

2023-04-26 15:56 UTC, sihyung92 commented on src/main/java/cart/dao/ProductDaoImpl.java
> +        BeanPropertySqlParameterSource parameters = new BeanPropertySqlParameterSource(product);
SimpleJdbcInsert로 편리하게 저장로직을 처리하고 계신군요 👍

2023-04-26 15:56 UTC, sihyung92 commented on src/main/resources/data.sql
> +    image TEXT        NOT NULL
entity엔 audit성 데이터 (created_at, updated_at) 이 추가되어있으면 아주 큰 도움이 됩니다 :)

2023-04-27 06:28 UTC, Choi-JJunho commented on src/main/java/cart/domain/Image.java
> +        }
앗..! 왜 빈값만 체크했을까요.. ㅎㅎ
new URL()을 이용해 파싱하는 과정에서 MalformedURLException 예외를 잡아 핸들링해줬습니다

```java
try {
    new URL(url);
} catch (MalformedURLException e) {
    throw new IllegalArgumentException("적절한 형태의 url이 아닙니다.");
}
```

2023-04-28 02:01 UTC, Choi-JJunho commented on src/main/java/cart/service/ProductService.java
> +                .orElseThrow(() -> new DBException("데이터가 정상적으로 저장되지 않았습니다."));
헉 `ResourceNotFound` 너무 좋은데요..??!

2023-04-28 02:06 UTC, Choi-JJunho commented on src/main/java/cart/domain/Product.java
> +                new BigDecimal(productRequest.getPrice())
사용자의 무지막지한 숫자 입력을 염두에 두고 Price를 BigDecimal로 설계했었는데
`ProductRequest (DTO)`단에서 해당 검증을 수행해줌으로써 위와같은 문제를 도메인이 신경쓰지 않아도 된다는 상황으로 이해했습니다.
Price의 값을 BigDecimal 대신 long으로 수정했습니다.

2023-04-28 06:27 UTC, Choi-JJunho commented on src/main/resources/data.sql
> +    image TEXT        NOT NULL
audit 데이터 좋은 것 같아요!!

created_at, updated_at을 보다가 (뜬금없지만) 갑자기 데이터의 soft delete가 생각났습니다.
혹시 웨지는 is_deleted와 같은 컬럼을 두고 soft delete를 수행하는 것에 대해 어떻게 생각하시나요?

저는 현재 두 가지 관점에서 아래와 같은 생각이 드는데 웨지의 의견이 듣고싶습니다!

1. soft delete를 적용한다.
- 잘못된 요청 혹은 시나리오 대한 데이터 복원이 용이하다.
- 연관된 데이터에 대한 보존이 가능함.

2. soft delete를 적용하지 않는다. 
- DB에 데이터가 과도하게 축적되어 조회 시 성능상 문제가 될 것이 우려됨.
- 특정 데이터가 실제 삭제되지 않음에 대해 사용자의 불안감을 야기할 수 있지 않을까 우려됨.

사내 혹은 팀에서의 정책에 따라 컬럼을 soft  delete로 지정할 수 있겠지만 그렇다면 어떤 경우에 정책을 사용하는지 궁금합니다.

혹시 실무에서도 soft delete를 적용하는 사례가 있는지도 궁금합니다!

2023-04-28 07:22 UTC, Choi-JJunho commented on src/main/java/cart/domain/Price.java
> +    private final Integer value;
엇 그러게요...?! 왜 래퍼타입을 사용했을까요 😂
아마도 상위 레이어의 요청에서 null이 넘어올 수 있다는 생각에 위와같이 래퍼타입으로 작성했었는데 하위 도메인을 primitive type으로 두면 불필요한 null check요인이 없겠네요!!

2023-04-28 07:24 UTC, Choi-JJunho commented on src/main/java/cart/dto/ProductRequest.java
> +    private final Integer price;
Integer에 값이 할당된 뒤 검증을 수행하는 것으로 예측했었는데 값이 할당되기 전에 검증을 진행하네요 😂
primitive type으로 수정했습니다!

2023-04-28 07:25 UTC, Choi-JJunho commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.internalServerError().body(e.getMessage());
클라이언트에게는 알려줄 필요가 없는 정보를 내주고 있었네요?!
단순하게 서버에서 오류가 발생했다고만 알려주는 형태로 변경했습니다.

2023-04-28 07:38 UTC, Choi-JJunho commented on src/main/java/cart/entity/ProductEntity.java
> +public class ProductEntity {
1. 엔티티와 도메인 객체를 분리한 이유

크게 영속성 엔티티와 도메인 엔티티로 분류를 했습니다.

Entity `DB의 데이터와 매핑되는 객체`로 정의를 했습니다.
다시 말하자면 영속성 엔티티를 `Entity`로 명명하였고 도메인 엔티티는 행위를 가지는 도메인 객체로 뒀습니다.

2. 엔티티 객체는 왜 행위는 가져가지 않나요?

엔티티 객체가 행위를 가지면 DB에서 가져온 정보가 부정확해질 수 있다는 단점이 있다고 생각합니다.
도메인의 행위는 도메인 객체에서 처리한다고 생각하기 때문에 엔티티는 행위를 가지지 않습니다.

현재 update를 수행하기 위한 `replace()`라는 메소드가 존재하는데 이 부분이 현재는 바로 이전에 말씀드린 `DB에서 가져온 정보가 부정확해질 수 있다는 단점`에 해당하고 있습니다.

해당 문제는 AOP를 이용해서 객체의 값을 이용했을 때 DB의 정보를 최신화하는 방법을 통해 해소할 수 있을것이라 기대하고있습니다.

2023-04-28 07:43 UTC, Choi-JJunho commented on src/main/java/cart/dao/ProductDao.java
> +public interface ProductDao {
DAO를 추상화 한 이유은 `H2`, `MySQL` 혹은 다른 `NoSQL`을 통해 관리될 것을 생각했습니다.
DB별로 상이한 Dialect를 고려하여 추상화를 진행했습니다.

말씀드리다보니 구현체의 이름을 H2ProductDao 정도로 수정하는 것을 생각해볼 수 있겠네요...!

SpringBoot 설정 혹은 외부라이브러리를 통해서 DB별 Dialect를 관리해준다면 해당 추상화는 불필요하게 되어 없어질 수 있을 것 같습니다.

2023-04-28 07:43 UTC, Choi-JJunho commented on src/main/java/cart/domain/Product.java
> +    public static Product from(ProductRequest productRequest) {
객체간 직접 변환에 관련된 로직을 가지는 행위를 객체간 변환을 담당하는 Mapper에게 책임을 위임했습니다!

2023-04-28 17:44 UTC, sihyung92 commented on src/main/resources/data.sql
> +    image TEXT        NOT NULL
중요한 엔티티는 거의 대부분 soft-delete입니다 ㅎㅎ 특정 데이터는 다른 데이터와 연관되어 있는 경우가 많은데 잘 못 삭제하면 더 큰 시스템 이슈로 이어져서요. 또 지워지고난 데이터는 복구하기가 매우 까다롭습니다. (과거 스냅샷으로 부터 어쩌고저쩌고... 달라진 부분 있으니까 보정하고 어쩌고..)

hard-delete는 개인정보 보호법 등 법상 보관이 불가한 경우나 지나치게 스토리지 용량을 낭비하는 경우 hard-delete 처리 하는거 같아요 
말씀해주신 `사용자의 불안감`은 개인정보 비식별화 처리를 하는 방법도 있습니다

2023-04-29 07:29 UTC, sihyung92 commented on src/main/java/cart/entity/ProductEntity.java
> +public class ProductEntity {
엔티티는 항상 디비 정보와 일치해야하나요? `DB에서 가져온 정보가 부정확하다` 는 건 어떤 종류의 데이터 조작이던간에 즉시 DB에 반영되어야 한다는 의미일까요? 그럴거라면 replace라는 함수를 쓸 게 아니라 즉시 DB에 업데이트 하는 sql 쿼리를 날려야 하는것 아닐까요?
왜 굳이 AOP 같은 기술을 써서 해결해야할까요?

2023-04-29 07:42 UTC, sihyung92 approved these changes
안녕하세요 주노~~ 웨지입니다!
빠르게 리뷰 반영 해서 올려주셨군요! 
1단계 요구사항은 만족한 것 같아 머지하겠습니다

몇가지 코멘트 남겨 놓았으니 확인해주세요~! 
특히 엔티티에 관한 부분은 각자의 생각이 다른 부분이 있는 거 같아 같이 토의해봐도 좋을 것 같아요 😽

2023-04-29 07:42 UTC, sihyung92 commented on src/main/java/cart/dao/ProductDaoImpl.java
> +    private final RowMapper<ProductEntity> productEntityRowMapper = (resultSet, rowNum) ->
해당 객체는 static 했어도 되었을것 같아요 ㅎㅎ 함수이기 때문에 인스턴스 별로 가지고 있지 않아도 될거같습니다

2023-04-29 07:42 UTC, sihyung92 commented on src/test/java/cart/dao/ProductDaoImplTest.java
> +    JdbcTemplate jdbcTemplate;
ProductControllerTest 에선 필드가 private 이었는데 여기선 default 접근제어자네요 ㅎㅎ 기준이 있을까요?

2023-04-29 07:42 UTC, sihyung92 commented on src/main/java/cart/domain/Product.java
> +            throw new IllegalArgumentException("상품명은 비어있을 수 없습니다.");
리뷰에서 의도했던 건 IllegalArgumentException, NoSuchElementException 등 도 커스텀 화 해주는 걸 의도하긴 했는데요, (기타 라이브러리 의존성의 예외와 구분하기 위함)
사실 지금 미션 수준에선 예외 고도화는 과한 감도 있어서 추가로 리뷰는 드리지 않겠습니다 ㅎㅎ 이 부분은 자유롭게 해주셔요

2023-04-29 07:42 UTC, sihyung92 commented on src/main/java/cart/dao/ProductDao.java
> +public interface ProductDao {
넵 추상화 한 부분과 추상화 하지 않은 부분이 나뉘어 있어 기준이 궁금했습니다 ㅎㅎ
저도 항상 고민하는 부분이었다가 최근에 [안정된 의존관계 원칙과 안정된 추상화 원칙에 대하여](https://techblog.woowahan.com/2561/) 라는 포스팅을 보고 어느정도 느낀 바가 있어 공유해봅니다

2023-04-29 07:42 UTC, sihyung92 commented on src/main/java/cart/domain/Image.java
> +        }
기존 라이브러리를 활용해 잘 처리해주셨네요 ㅎㅎ

2023-04-29 07:42 UTC, merged

2023-05-01 10:34 UTC, Choi-JJunho commented on src/test/java/cart/dao/ProductDaoImplTest.java
> +    JdbcTemplate jdbcTemplate;
엇 단순 미스였습니다 😂