[1단계 - 상품 관리 기능] 헙크(정현승) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #204
Opened 2023-04-26 11:42 UTC by HubCreator

안녕하세요, 찰리! 백엔드 5기 크루 헙크입니다.
이번에 져니와 레벨 2 두 번째 미션인 장바구니 기능을 구현해보았어요.
조금 더 이것저것 해보고 싶어서 상품에 대한 카테고리 필드 추가 및 단일 상품 조회 기능을 추가해두었어요! ㅎㅎㅎ
그리고 몇 가지 간단하게 질문드리고 싶은 부분이 있습니다.

✔️ 1. E2E 테스트를 꼭 진행해야 하는가?
저는 E2E 테스트를 사실 꼭 작성해야 하는지 아직 필요성을 느끼지 못하고 있어요 ㅠㅠㅠ
특히 이번처럼 SSR을 사용하는 상황에서는 뷰 네임을 컨트롤러에서 반환하고 있는데, 이런 경우 상태 코드 외에 어떤 식으로 검증을 해야 할지 모르겠어서 단순히 상태 코드만 200으로 떨어지는지 검증하였어요. (html 자체를 검증하는 것도 이상할 것 같아서...) 이런 식으로 작성하는 게 맞을까요?
또한, 잘 작성된 단위 테스트, 통합 테스트가 있다면 E2E 테스트는 오히려 비용적으로 부담이 될 수 있는 부분이 아닌가? 라는 생각이 드는데, 실제로 현업에서도 E2E 테스트를 많이 진행하는지 궁금합니다!

✔️ 2. 리다이렉트는 언제 사용하는 것인지
뷰 네임을 반환할 때 String 값에 "redirect:/" 이런 식으로 작성하게 되면 해당 url로 리다이렉트 하면서 재요청하는 것으로 이해했는데 (그래서 상태 코드가 3xx대로 떨어진다고 생각했어요!) 지금처럼 뷰 네임을 반환하는 상황은 리다이렉트로 봐야 할까요? 현재는 단순히 뷰 네임만 반환하면서 상태 코드가 200으로 나오고 있는데, 이게 맞게 작성한 것인지 궁금합니다. 또한, 리다이렉트를 마음대로 사용하게 되면 무한대로 계속 리다이렉션되는 문제도 발생할 수 있기 때문에 조심해서 작성해야 할 것 같은데, 보통 이런 처리를 서버 측에서 해주는 게 맞을까요? 🤔

✔️ 3. 도메인과 엔티티에 대해서
이번 미션에서는 도메인 객체로서 가지고 있는 비즈니스 로직이 따로 존재하지 않는다고 판단해서 따로 도메인 객체를 두지 않고, 엔티티를 통해서 DB에 접근하는 객체를 두었습니다. 실제로 JPA의 경우 https://github.com/entity 어노테이션을 사용하면서 해당 객체를 엔티티로서 사용하는 경우가 많은 것 같은데, 지금 같은 상황에서도 도메인 객체를 두지 않고 엔티티로만 설계하는 게 괜찮은 방향일까요?

✔️ 4. Dao와 서비스의 예외 반환
현재 Dao에서 findById의 경우 조회했을 때 없는 경우 Dao에서 예외를 잡아서 공통으로 사용하는 GlobalException으로 잡고 있고, update와 delete의 경우 쿼리가 처리된 개수를 보고 1개가 아니라면 예외가 발생하도록 만들었어요. (아예 아무 일도 일어나지 않았거나, 다중 컬럼이 어떠한 이유로 영향을 받는 경우) 이에 대한 책임을 공통적으로 서비스, 혹은 Dao 한 곳에서 하는 게 맞을 것 같은데 조회의 경우 에러가 발생한 클래스 자체가 EmptyResultDataAccessException이다 보니까 dao에서만 알고 있으면 되는 예외 클래스인 것 같아서 Dao 레벨에서 처리하였어요. (실제로 해당 예외 클래스의 패키지가 org.springframework.dao라서 서비스 레이어가 굳이 알 필요가 없을 것 같다고 생각했어요.) 하지만 update나 delete의 경우 쿼리를 날리는 것까지가 책임이지, 그 뒤로 몇 개의 컬럼이 영향을 받았는지 체크하는 것은 어떻게 보면 서비스에서 해야 하는 역할 같기도 해서 이렇게 해두었는데, 어떤 방향이 맞는 것인지 궁금합니다!

감사합니다!

2023-04-27 13:35 UTC, Gomding requested changes
안녕하세요 헙크!
장바구니 미션 함께하게 된 찰리입니다 🙇 
1단계 구현하느라 고생하셨습니다.
상품의 카테고리까지 구현해주셨네요 👍 👍 
몇 가지 코멘트 남겼으니 확인 부탁드려요!!

---
## QnA

> ✔️ 1. E2E 테스트를 꼭 진행해야 하는가?

E2E 테스트는 말씀대로 테스트를 작성하는 비용도 부담되고, 테스트 신뢰도 또한 떨어질 수 있다고 생각해요
시스템을 구축하는 모든 프로세스를 관통하여 (실제 환경과 동일하게)테스트하기 때문에
예를들면 사용하는 외부 시스템 서버가 다운됐을 때 테스트가 실패한다면 신뢰할 수 있을까요?
팀마다 컨벤션이 다르겠지만 현업에서도 단위 테스트, 통합 테스트의 비율과 중요도가 더 높다고 생각해요~!

> ✔️ 2. 리다이렉트는 언제 사용하는 것인지

뷰 네임을 반환하는 상황을 리다이렉트로 봐야하는 이유가 궁금해요 🤔 

말씀대로 잘못 사용하면 무한 리다이렉션이 생길 수도 있고, 그냥 view 를 바로 반환하면 되는데 리다이렉트로 리소스를 더 사용할 필요가 있을지 고민해봐야겠네요 😄 
마침 [리다이렉트의 유스 케이스](https://developer.mozilla.org/ko/docs/Web/HTTP/Redirections#%EC%9C%A0%EC%8A%A4_%EC%BC%80%EC%9D%B4%EC%8A%A4) 에 관한 문서가 있어 공유드립니다!

> ✔️ 3. 도메인과 엔티티에 대해서

우선은 용어 정리가 필요할 것같아요!
`도메인` 이라는 것은 해결하고자 하는 문제를 나타내고
`도메인 객체` 는 도메인이라는 것을 나타낸 객체 또는 무언가겠죠 
엔티티는 도메인 객체를 표현하기 위한 방법 중 하나 입니다. (id 와 같이 식별자 구분하는 객체)
따라서 엔티티를 도메인 객체로서 사용할 수 있다 라고 생각해요

추가로 구현하신 엔티티 관련하여 코멘트 남겼으니 확인 부탁드려요 🙏 

> ✔️ 4. Dao와 서비스의 예외 반환

잘 이해하고 구현해주신 것으로 보입니다!
EmptyResultDataAccessException의 경우 DB 관련 예외사항으로 호출하는 쪽에는 조회가 됐는지 안됐는지 인지할 수 있는정도만 응답해주면 된다고 생각해요 😄 
비어있는 응답이니 알아서 처리해 라고하여 호출하는 쪽에서 예외 상황에 대해 유연하게 처리할 수 있다는 점이 있습니다.
update 나 delete 의 경우에도 잘 구현해주셨다고 생각해요!

2023-04-27 13:35 UTC, Gomding commented on src/main/resources/templates/index.html
> +                    <p class="product-category" th:text="${product.getCategory()}"></p> <!-- 상품 카테고리 -->
카테고리 구현 👍

2023-04-27 13:35 UTC, Gomding commented on src/main/resources/static/js/cart.js
> +    window.location.replace(`/${productId}`)
`window.location.replace` vs `window.location.href` 어떤 차이가 있을까요? 😄 
(상품 상세에 들어가고 나서 뒤로가기로 home 화면에 돌아가지 못해 아쉬웠습니다 😢 )

https://opentutorials.org/module/2919/22904

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/AdminController.java
> +    @PutMapping("/{id}")
현재는 Product 라는 id 만을 받고 있지만 나중에 다른 id를 받게되면 변경될 가능성이 있어보여요

productId 로 PathVariable 이름을 지어보는건 어떠신가요?

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<Void> deleteProduct(@PathVariable final Long id) {
해당 부분은 RestAPI 로 보이고 AdminController가 가져야할지 의문이 들었어요 🤔 
ProductController 로 분리해보는건 어떨까요?

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/AdminController.java
> +    @ModelAttribute("categorys")
ModelAttribute 를 사용해주셨군요!

어떤 장점이 있어 사용했는지 궁금해요 😄

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/GlobalControllerAdvice.java
> +public class GlobalControllerAdvice {
이 부분은 취향에 따라 GlobalExceptionHandler 라는 이름으로 짓기도 합니다 😉

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/GlobalControllerAdvice.java
> +    @ExceptionHandler(GlobalException.class)
커스텀 예외를 사용 👍 
어떤 장점이 있었는지 궁금해요!

추가로 GlobalException 이라고 광범위하게 잡고 enum으로 예외를 표현해주고 있는것으로 보이네요 😄 
또 다른 방법으로는 GlobalException을 상속하는 하위 예외들을 만들어줄 수 있습니다.

어떤 장단점이 있을지 비교해보면 좋겠어요!

```java

public class GlobalException extends RuntimeException {

    private final String message;

    ~~
}

public class InvalidCategoryException extends GlobalException {
    public InvalidCategoryException() {
        super("유효하지 않은 카테고리입니다.");
    }
}
```

정말 세부적으로 나누면
GlobalException 하위 예외로
BadRequestException 과 같이 HTTP StatusCode 별로 하위 메서드들을 나눠보는 방법들도 있습니다 🤔 

```java
public class GlobalException extends RuntimeException {

    private final String message;
    private final HttpStatus httpStatus;

    public GlobalException(String message, HttpStatus httpStatus) {
        this.message = message;
        this.httpStatus = httpStatus;
    }
}

class BadRequestException extends GlobalException {
    public BadRequestException(String message) {
        super(message, HttpStatus.BAD_REQUEST);
    }
}
```

정답이 없는 부분이라 생각하고 헙크가 앞으로 미션들을 해보면서 느껴보셨으면하여 코멘트 남겼습니다 :)

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<Void> addProduct(@RequestBody @Valid final ProductDto productDto) {
`@Valid` 사용 👍

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/persistence/entity/Product.java
> +    }
Dto 에는 Valid 를 사용하여 validation 을 진행하지만 도메인은 따로 검사가 없군요 🤔 

검사하지 않아도 괜찮을까요?

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/controller/dto/ErrorResponse.java
> +    private final List<String> errorMessage;
ErrorResponse의 errorMessage가 컬렉션 타입인 이유가 궁금해요!

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/service/ShoppingService.java
> +public class ShoppingService {
클래스의 함수들은 보면 Product 관련 CRUD 로 이해했어요.

Shopping 이라는 것과 어떤 연관이 있는지 의문이 들었어요 🤔

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/service/ShoppingService.java
> +        if (deletedCount != 1) {
DB가 잘못되어 deleteCount 2가 나오면 어떻게 에러응답이 가고있을까요?

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/service/ShoppingService.java
> +                productDto.getPrice(), productDto.getCategory()));
Dto 에게 Entity 로 변환하는 함수를 만들어보는건 어떨까요?

```java
Product product = ProductDto.toEntity();
```

2023-04-27 13:35 UTC, Gomding commented on src/main/java/cart/persistence/dao/ProductDao.java
> +                            ProductCategory.from(result.getString("category"))), id);
findById, findAll 모두 동일한 RowMapper 를 사용하는것으로 보여요 😄 

RowMapper 를 하나 생성해놓고 사용하는건 어떠신가요?

2023-04-27 13:35 UTC, Gomding commented on src/test/java/cart/controller/AdminControllerTest.java
> +    void getProducts() throws Exception {
`@DisplayName` 으로 테스트가 무엇을 의미하는지 정보를 전달해주면 어떨까요?

`@DisplayName` 을 사용하면 두괄식으로 테스트를 설명할 수 있다고 생각해요!

2023-04-28 00:28 UTC, HubCreator commented on src/main/resources/static/js/cart.js
> +    window.location.replace(`/${productId}`)
제가 놓쳤네요 ㅠㅠㅠ 앞으로는 js도 더 신경쓰도록 하겠습니다 감사합니다!

2023-04-28 01:45 UTC, HubCreator commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<Void> deleteProduct(@PathVariable final Long id) {
현재 admin 페이지 하위에서만 add, update, delete가 수행되므로 AdminController 하위에 해당 기능들을 두었습니다. 또한 요청 url도 "/admin" 하위이기도 하구요! 

RestAPI 이긴하지만 ProductController로 두기엔 admin이 아닌 사용자들은 요런 기능들이 필요하지 않고, 분리한다고 한다면 ProductController에도 AdminController에서 사용하는 url("/admin" 하위)을 사용하며 method만 달리하는 구조로 만들어야 한다고 생각합니다.

이에 따라, 같은 url이지만 메서드에 따라 컨트롤러를 두 개 두어야 하는 상황인데 요런방식이 더 좋은 방법인지 아직 확신은 들지 않네요 ㅠㅠ

어떻게 생각하는 것이 좋을까요? 분리하는 것이 어떤 관점에서 더 좋다고 할 수 있을까요?

2023-04-28 04:00 UTC, HubCreator commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<Void> deleteProduct(@PathVariable final Long id) {
저는 `/admin`에서 사용하는 것들은 하나의 컨트롤러에서 관리하는 것이 좋다고 생각했고, `/admin/{productId}`의 url로 요청이 오도록 설계했기 때문에, 이들을 ProductController로 분리한다는 것이 조금 어색하다고 생각했습니다. 왜냐하면 하나의 url에서 관련 요청들을 핸들링하는 것이 아니라 add, update, delete는 다른 클래스에서 처리하는 것이 유지보수할 때 조금 더 혼란스러울 것 같았기 때문입니다 ㅎㅎㅎ

하지만 오늘 우테코에서 진행한 API 설계 강의를 들었는데, 제가 설계한 방식이 조금 어색하더라구요! product에 대해 crud를 진행하는데, 정작 url 자체에서는 product에 대해서 crud를 진행하는지 알기 어렵더라구요. 그래서 `/admin/products/{productId}` url로 설계하는 것이 좋다는 생각이 들었고, 그렇다면 찰리가 말씀해주신 방법대로 컨트롤러를 분리하는 것이 좋을 것 같다는 생각이 들었습니다.

REST에 관해서 직접적으로 언급해주지 않으셨지만, url을 변경하면서 컨트롤러를 분리했던 저의 흐름이 합당한가요? 아니면 url과 상관 없이 RestAPI는 RestAPI끼리, 뷰를 반환하는 것은 뷰를 반환하는 것 끼리 분리시켜야 했던 것일까요? 😂

2023-04-28 04:08 UTC, HubCreator commented on src/main/java/cart/controller/AdminController.java
> +    @ModelAttribute("categorys")
뷰 템플릿에서 카테고리를 셀렉트 박스로 보여주고자 하였습니다!! 상품을 추가할 때에, 어떤 카테고리를 선택할 수 있는지 보여줘야했기 때문에 `@ModelAttribute("categorys")`를 사용해 뷰 템플릿에서 넘겨받아 렌더링하였습니다ㅎㅎㅎ 필요한 정보만 뷰 템플릿에 넘겨 간단하게 사용할 수 있다는 장점이 있는 것 같습니다!

2023-04-28 04:34 UTC, HubCreator commented on src/main/java/cart/controller/GlobalControllerAdvice.java
> +    @ExceptionHandler(GlobalException.class)
표준 예외는 간단하게 사용할 수 있지만, 어떤 예외 상황인지 구체적으로 알려줄 수 있는 방법이 `String` 타입의 예외 메시지를 전달하는 것이 전부여서 커스텀 예외를 사용하였습니다 ㅎㅎㅎ 커스텀 예외에 `ErrorCode`의 `enum`값을 주어서 어떤 메시지를 렌더링할지 `value`로 가지게 하였습니다! 

말씀해주신 것처럼 `GlobalException`이라는 커스텀 예외를 두고, 하위에 Http status code 별로 어떤 처리를할지 두는 방식은 넘 좋은 것 같습니다 ㅎㅎㅎ 제가 기존에 했던 방식은 어떤 예외 메시지를 가지고 있는지 한 번 더 `enum`값을 확인했어야 했는데, 찰리가 말씀해주신 방식으로는 클래스이름 그 자체로 예외 상황을 구분할 수 있고, 조금 더 구체적인 타입으로 `catch`하여 처리할 수도 있을 것 같네요!

한편으로는, 이런 예외들은 도메인에서 발생하게될텐데 그렇다면 도메인에서 예외를 던질 때 httpStatus를 지정해주어야 할 것입니다. 또한 클라이언트에게 보여질 메시지도 도메인에서 관여하게 될 것 같네요 😂  이는 도메인에서 뷰에 의존하는 것이 아닐까 생각이 듭니다ㅠㅠ

찰리는 이에 대해서 어떻게 생각하시나요!? 저는 이런 예외 처리가 아직은 정확하게 어떻게 해야한다는 기준이 잡히지 않아 헷갈리는 것 같네요 ㅠㅠㅠ

2023-04-28 04:35 UTC, HubCreator commented on src/main/java/cart/persistence/entity/Product.java
> +    }
컨트롤러의 요청에서부터 넘어온 것이 아니라, 내부적으로 product 객체를 생성하는 경우라면 위험할 것 같습니다! 제가 처리하지 못했네요 ㅎㅎㅎ 검증 로직 추가하겠습니다. 감사합니다 :)

2023-04-28 05:16 UTC, HubCreator commented on src/main/java/cart/controller/dto/ErrorResponse.java
> +    private final List<String> errorMessage;
현재 사용자의 입력을 받는 부분에서, 올바르지 않은 입력이 들어오면 js쪽에서 alert하도록 하였습니다. 이때 예외 메시지를 보여주도록 하고 있는데, 만약 여러 부분에서 입력 검증에서 걸린다면 해당하는 모든 메시지를 보여주고 싶어서 컬렉션 타입으로 두었습니다ㅎㅎㅎ

![image](https://user-images.githubusercontent.com/44110749/235060228-2eb5a6d4-fa94-43c6-8640-0e0dda91bc6b.png)

2023-04-28 06:07 UTC, HubCreator commented on src/main/java/cart/service/ShoppingService.java
> +public class ShoppingService {
ProductService라고 이름을 바꿨습니다!  😀

2023-04-28 06:24 UTC, HubCreator commented on src/main/java/cart/persistence/dao/ProductDao.java
> +                            ProductCategory.from(result.getString("category"))), id);
제가 놓쳤습니다! 감사합니다

2023-04-28 06:44 UTC, HubCreator commented on src/main/java/cart/service/ShoppingService.java
> +        if (deletedCount != 1) {
delete의 결과가 0일 때와, 2개 이상일 때를 구분해야 할 것 같네요!
0일 때는 해당 제품을 찾을 수 없는 것이고, 2개 이상일 때에는 db에 중복된 값이 있다는 것이네요 ㅎㅎ(이럴 일은 발생하지 않을 것 같긴 합니다)

어찌됐든 상황에 따라 에러메시지를 달리하였고, 로깅처리도 해봤습니다!!

2023-04-28 08:13 UTC, HubCreator commented on src/test/java/cart/controller/AdminControllerTest.java
> +    void getProducts() throws Exception {
넵! 반영하겠습니다 ㅎㅎㅎ

2023-04-28 13:56 UTC, Gomding commented on src/main/resources/static/js/cart.js
> +    window.location.replace(`/${productId}`)
앗 중요한 부분은 아니었습니다 😮 
헙크가 구현해주신 부분들을 재밌게 탐사하면서 우연히 발견하여 코멘트 드린것입니다 😄

2023-04-28 14:26 UTC, Gomding commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<Void> deleteProduct(@PathVariable final Long id) {
> 저는 /admin에서 사용하는 것들은 하나의 컨트롤러에서 관리하는 것이 좋다고 생각했고, /admin/{productId}의 url로 요청이 오도록 설계했기 때문에, 이들을 ProductController로 분리한다는 것이 조금 어색하다고 생각했습니다. 왜냐하면 하나의 url에서 관련 요청들을 핸들링하는 것이 아니라 add, update, delete는 다른 클래스에서 처리하는 것이 유지보수할 때 조금 더 혼란스러울 것 같았기 때문입니다 ㅎㅎㅎ

좋은 의견이네요 👍 

제가 생각했던 방향은 /admin/{productId} ~~ 라고 admin 에 한정지어야할까 라는 생각이 들어서였습니다.
해당 부분은 Product 에 대한 CRUD 이고 Admin 에서 사용한다고 고정지어버리면 재사용성이 감소하는 API 가 된다고 생각해요 :)
물론 Admin 에서만 사용하는 것이 확실하고 Admin 에서만 필요한 특별한 인증이 필요하다면 /admin/~~ 으로 표현하는 것도 괜찮다고 생각합니다.

> 하지만 오늘 우테코에서 진행한 API 설계 강의를 들었는데, 제가 설계한 방식이 조금 어색하더라구요! product에 대해 crud를 진행하는데, 정작 url 자체에서는 product에 대해서 crud를 진행하는지 알기 어렵더라구요. 그래서 /admin/products/{productId} url로 설계하는 것이 좋다는 생각이 들었고, 그렇다면 찰리가 말씀해주신 방법대로 컨트롤러를 분리하는 것이 좋을 것 같다는 생각이 들었습니다.

좋은 방향이라고 생각해요~

> REST에 관해서 직접적으로 언급해주지 않으셨지만, url을 변경하면서 컨트롤러를 분리하는 것이 질문해주신 의도일지 궁금합니다. 아니면 REST와 상관 없이 RestAPI는 RestAPI끼리, 뷰를 반환하는 것은 뷰를 반환하는 것 끼리 분리시켜야 했던 것일까요? 🤔

`RestAPI는 RestAPI끼리, 뷰를 반환하는 것은 뷰를 반환하는 것 끼리 분리` 저는 이쪽을 더 선호합니다!
RestAPI 는 필요한 비지니스 로직을 실행하고 만들어진 순수한 데이터를 반환한다고 생각해요. 그래서 뷰를 반환하는 컨트롤러와는 분리해놓는게 좋다고 생각하구요 :)
(지금 처럼 서버사이드 렌더링을 하는 경우는 편의성을 위해 ModelAttribute 에 데이터를 넣어 뷰를 제공할때 비지니스 로직을 거칠 수도 있지만요!)
분리했을 때 Rest API 만 모여있으므로 관리하기도 편하다고 생각합니다 😄 

REST API 관해서는 아래 아티클을 보고 학습해보시면 도움될거라 생각합니다!
- https://meetup.nhncloud.com/posts/92

2023-04-28 14:46 UTC, Gomding commented on src/main/java/cart/controller/GlobalControllerAdvice.java
> +    @ExceptionHandler(GlobalException.class)
> 한편으로는, 이런 예외들은 도메인에서 발생하게될텐데 그렇다면 도메인에서 예외를 던질 때 httpStatus를 지정해주어야 할 것입니다. 또한 클라이언트에게 보여질 메시지도 도메인에서 관여하게 될 것 같네요 😂 이는 도메인에서 뷰에 의존하는 것이 아닐까 생각이 듭니다ㅠㅠ

현재도 예외 메시지들이 클라이언트에게 노출되고 있지 않을까요? 🤔 
Http Status 를 도메인이 알고 던져줘야한다는 부분은 동의합니다!
도메인 친화적으로 Status Code 들을 표현하고 ExceptionHandler 에서 자세하게 잡아주는 방법도 있겠네요.

400 BadRequest -> ClientBadRequestException

```java
@ExceptionHandler(ClientBadRequestException.class)
public ResponseEntity<ErrorResponse> clientBadRequestException(final ClientBadRequestException e) {
    final ErrorResponse errorResponse = new ErrorResponse(e);
    return new ResponseEntity<>(errorResponse, HttpStatus.BAD_REQUEST);
}
```

개발에는 정답이다 라는 방법이 없어서 헙크가 이것저것 사용해보며 기준을 잡아보면 좋겠어요 🙇

2023-04-28 15:07 UTC, Gomding requested changes
안녕하세요 헙크!
피드백에 의견 공유해주셔서 감사해요 😄 
1단계는 이만 merge 하겠습니다!!
추가로 남긴 코멘트는 2단계에서 함께 고민해주세요 🙏 
다음 단계도 화이팅입니다 🔥 

추가로 궁금한 점이 있다면 언제든 댓글이나 DM 보내주세요!

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/controller/admin/AdminController.java
> +    public String getProducts(final Model model) {
view의 이름을 반환하는데 메서드 이름과 일치하지 않는것같아요!

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/controller/admin/AdminProductController.java
> +@RequestMapping("/admin/products")
url로 resource 표현 👍

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/persistence/entity/Product.java
> +            throw new IllegalArgumentException();
예외 메시지로 어떤 상황인지 알려줄 수 있으면 좋겠어요 😄

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/persistence/entity/Product.java
> +        if (name.length() < 1 || name.length() > 25) {
매직 넘버에게 상수로 의미를 부여해볼까요?

2023-04-28 15:07 UTC, Gomding commented on src/test/java/cart/ProductIntegrationTest.java
> +                .statusCode(HttpStatus.CREATED.value());
CREATED 상태코드 사용 👍 
해당 결과에`Location` 이라는 header 값이 있을 텐데 해당 부분도 검증해볼 수 있을까요?

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/service/ProductService.java
> +        int updatedCount = productDao.update(productDto.toEntity());
잘 반영해주셨네요 👍

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/persistence/dao/ProductDao.java
> +            );
RowMapper 생성 💯

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/controller/admin/AdminController.java
> +    // TODO: 관리자의 권한으로 접근하면, 소비자가 접근할 때와 다른 화면을 보여줄 필요가 있지 않을까
좋은 고민이네요 👍

2023-04-28 15:07 UTC, Gomding commented on src/main/java/cart/controller/admin/AdminProductController.java
> +        return ResponseEntity.created(URI.create("/admin/" + productId)).build();
Location 값이 잘못된 듯 해요!

```suggestion
        return ResponseEntity.created(URI.create("/admin/product/" + productId)).build();
```

2023-04-28 15:07 UTC, Gomding commented on src/main/resources/templates/index.html
> +        <li class="product" th:each="product : ${products}" th:onclick="showDetail([[${product.id}]])">
현재는 상품 상제 페이지로 이동하면 404 에러 페이지가 나오네요 😢

2023-04-28 15:08 UTC, Gomding approved these changes

2023-04-28 15:09 UTC, merged

2023-05-01 00:06 UTC, HubCreator commented on src/main/java/cart/controller/GlobalControllerAdvice.java
> +    @ExceptionHandler(GlobalException.class)
넵! ㅎㅎㅎㅎ 감사합니다

2023-05-01 03:01 UTC, HubCreator commented on src/test/java/cart/ProductIntegrationTest.java
> +                .statusCode(HttpStatus.CREATED.value());
넵넵!! 추가하겠습니다 :)