[1단계 - 상품 관리 기능] 콩하나(최한빈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #208
Opened 2023-04-26 12:09 UTC by kong-hana01

2023-04-27 13:30 UTC, xrabcde requested changes
안녕하세요 콩하나 ~ 바다입니다 🌊
레벨2 두번째 미션을 함께 하게 되어 반갑습니다 ㅎㅎ
질문에 대한 답변과 몇 가지 리뷰 남겼는데 확인해보시고
궁금한 점은 언제든 코멘트나 DM으로 알려주세요~

2023-04-27 13:30 UTC, xrabcde commented on README.md
> +    - 하던 코드까지는 마무리 한다.
페어 규칙도 작성해주셨네요 👍🏻

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/controller/AdminController.java
> +@Controller
Controller와 RestController는 어떻게 다를까요? 콩하나는 왜 Controller 어노테이션을 사용하셨나요?

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/controller/AdminController.java
> +    @ResponseBody
[Http Method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) 중에 수정과 삭제를 나타내는 method들도 있는데
POST를 이용해 전부 구현하신 이유가 있나요?

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/controller/AdminController.java
> +    @PostMapping("/items/add")
[RESTful한 API 설계](https://sanghaklee.tistory.com/57)에 대해 학습해보시면 좋을 것 같아요

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
ExceptionHandler 적용 👍🏻

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/dto/ItemResponse.java
> +    private final String name;
json 필드와 자바 필드의 네이밍이 일치하는 경우는 JsonProperty를 작성하지 않아도 될 것 같아요

2023-04-27 13:30 UTC, xrabcde commented on src/test/java/cart/controller/AdminControllerTest.java
> +    @CsvSource(value = {":상품명은 공백일 수 없습니다.", "    :상품명은 공백일 수 없습니다.", "ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ:상품명의 길이는 30자 이하여야합니다."}, delimiter = ':')
ParameterizedTest 활용 👍🏻👍🏻
개인적으로 이런 경우에는 예외 케이스마다 테스트를 분리해주는 게 어떤 예외를 테스트하는 건지 파악하기 더 좋다고 생각하는데 콩하나는 어떻게 생각하시나요?
예외메시지도 parameter로 넣어주는 것보다 함수 내에서 명시해주는 게 좋을 것 같아요

2023-04-27 13:30 UTC, xrabcde commented on src/test/java/cart/dao/JdbcItemDaoTest.java
> +                () -> assertThat(items.size()).isEqualTo(3),
```suggestion
                () -> assertThat(items).hasSize(3),
```
이렇게 작성할수도 있어요 ㅎㅎ

2023-04-27 13:30 UTC, xrabcde commented on src/test/java/cart/dao/JdbcItemDaoTest.java
> +                () -> assertThat(items.get(1).getPrice()).isEqualTo(2000)
[usingRecursiveComparison()](https://tecoble.techcourse.co.kr/post/2020-11-03-assertJ_methods/) 에 대해 학습해보시면 좋을 것 같아요

2023-04-27 13:30 UTC, xrabcde commented on src/main/resources/data.sql
> +    );
sql 파일은 자동포맷팅 할 때 제외해주는 게 좋아요 😂

2023-04-27 13:30 UTC, xrabcde commented on src/main/java/cart/dto/ItemRequest.java
> +    @JsonProperty("image-url")
> dto와 도메인 중 어디에서 검증 책임을 가지는게 좋을까요?
처음에는 도메인과 dto 모두 중복된 검증을 해주는 것이 안정적인 구조가 된다고 생각했는데요.
중복된 검증을 두는 경우에는 유지 보수가 어려워진다는 단점이 생기더라고요.
검증에 대한 요구사항이 변경되면 dto와 도메인 모두 수정해야하니까요!

> 그래서 dto나 도메인 한쪽에서만 검증을 하거나, 도메인과 dto에 각각 검증 책임을 분리해서 나눠주는 방법을 생각했습니다!
만약 한쪽에만 검증 책임을 두는 경우에는 도메인에 두는 것이 좋다고 판단했었습니다.
여러 dto가 하나의 엔티티로 변환되는 경우 dto에서 검증 책임을 두는 것보단 엔티티에서 검증 책임을 갖는 것이 유지보수에 훨씬 용이해지기 때문이에요!
(사실 지금은 dto가 하나라서 이러한 측면보단 편의성 + validation 사용 경험에 더 초점을 맞춰서 dto에 검증 책임을 두었습니다.)

> 두번째로 도메인과 dto에 각각 검증 책임을 두는 경우에는 기준 설정을 어떻게 해야할지 감이 안잡히더라고요.
그래서 나름대로 이 정도까지 생각해보았는데, 실제 현업에서는 어떻게 사용하고 있는지 궁금합니다!

dto에서 검증이라는 게 spring validation을 말씀하시는거겠죠? ㅎㅎ
현업에서의 사용형태에 대해 질문주셨으니 제가 요즘 사용하는 방법으로 말씀드리면 
공백인지, 글자수, 최소최댓값 등과 같이 데이터만으로 검증이 가능한 경우는 dto에서 검증을 하는 편이고
다른 값과 비교하거나 계산을 통해 검증해야하는 비즈니스 로직적인 부분은 (ex. 시작날짜가 종료날짜보다 빠른지 등) 
주로 도메인에서 검증을 하는 것 같아요 고민이 조금 해결되셨을까요?

2023-04-28 07:28 UTC, kong-hana01 commented on src/main/java/cart/controller/AdminController.java
> +@Controller
@RestController는 @Controller에 @ResponseBody 어노테이션 기능도 확장되어있는 것으로 알고 있습니다!

기존 코드에서는 admin 기반 url에서는 모두 리턴 값에 리다이렉트를 사용하고 있었기 때문에 단순히 @Controller만 사용했습니다.

그런데 js에서 post 요청을 보낼 때마다 새로고침을 해준다는 것을 알게돼서 각 메서드별로 @ResponseBody를 추가해서 리턴값을 json 형태로 바꿔주는 식으로 api를 변경했습니다.

그래서 기존의 @Controller 어노테이션을 미처 바꾸지 못했네요...!!

개인적으로 메서드의 대부분이 json 형태로 통신하지 않고 뷰를 랜더링하는 경우에는 그냥 @Controller를 사용하는 것이 더 좋다고 생각하는데, 혹시 바다는 어떻게 생각하시나요?

(물론 지금은 @RestController로 변경하는 것이 더 좋다고 생각합니다! 😄 )

2023-04-28 07:49 UTC, kong-hana01 commented on src/main/java/cart/controller/AdminController.java
> +    @ResponseBody
http method에서 put이나 delete도 있기야하지만 대부분 post 요청을 사용하는 것으로 알고 있어서 그렇게 사용했습니다.

흠... 제가 생각해도 막 크게 이유가 있지는 않네요...!! 

한번 공부하고 추가로 답변을 달도록 하겠습니다.

--- 

![image](https://user-images.githubusercontent.com/79015120/235086862-fcf648bf-1dd9-4d0a-8c05-cc87cba4dcb4.png)

가장 큰 이유로는 html에서 form을 전달할 때 get과 post 외에는 method를 설정할 수 없기 때문이라고 하네요!
그래도 put과 delete를 사용하고 싶다면 value에다가 사용할 http methods를 적어주는 방법이 있군요!
근데 해당 방법을 사용하면서까지 delete와 put 메서드를 고려하는 것이 과연 얼마나 의미가 있을까하는 의문은 드는데요! (rest api로만 통신하는 경우가 아니라면 말이죠!)

바다는 이에 대해서 어떻게 생각하시나요? 실제로는 delete와 put을 사용하나요?

2023-04-28 08:07 UTC, kong-hana01 commented on src/main/java/cart/controller/AdminController.java
> +    @PostMapping("/items/add")
오! 감사합니다 ㅎㅎ

---

동사를 url로 사용하지말라는 내용이 있군요!

그런데 컨트롤 자원은 동사형도 가능하다는 것 같네요!

그러면 이렇게 정리해볼 수 있겠네요!

- put, delete를 없애는 경우 -> url에 동사형 표현을 사용해서 어떤 동작을 하는지 표현한다.
- put, delete를 사용하는 경우 -> url에 동사형 표현을 모두 없앤다. method로 동작을 나타내고 url에서는 자원만 나타낸다.

현재 코드에서는 put, delete를 사용하지 않고 get, post를 사용하고 있기 때문에 동사형으로 표현이 가능할 것 같네요!
그런데 지금 보니까 표현 자체가 깔끔해보이지는 않는 것 같습니다! ㅎㅎ

적절한 url 주소를 생각해보고 변경해보도록 하겠습니다~

2023-04-28 08:11 UTC, kong-hana01 commented on src/main/java/cart/dto/ItemResponse.java
> +    private final String name;
여기에서는 ItemResponse 내의 통일성을 유지해주기 위해 사용했었습니다!

흠... 근데 사실 굳이 사용할 이유도 없긴 해서 지워도 좋을 것 같습니다!!

혹시 여기서 더 생각해볼 부분이 있을까요?? 

가령 @JsonProperty를 사용할 때 내부적으로 어떻게 돌아가서 더 나빠진다던가... 그런 이유가 있을까요?

2023-04-28 08:12 UTC, kong-hana01 commented on src/test/java/cart/controller/AdminControllerTest.java
> +    @CsvSource(value = {":상품명은 공백일 수 없습니다.", "    :상품명은 공백일 수 없습니다.", "ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ:상품명의 길이는 30자 이하여야합니다."}, delimiter = ':')
오호 그러네요!

단순히 편의를 위해서 위와 같이 작성했었습니다. ㅎㅎ

그런데 생각을 해보니까 각각 다른 예외에 대한 테스트인데 편의를 위해  하나의 테스트로 검증하는 것은 좋아보이지 않네요!

이는 분리하는 것이 더 좋을 것 같아요! 👍

2023-04-28 08:13 UTC, kong-hana01 commented on src/test/java/cart/dao/JdbcItemDaoTest.java
> +                () -> assertThat(items.size()).isEqualTo(3),
앗 그러네요!! ㅎㅎㅎㅎ

2023-04-28 08:14 UTC, kong-hana01 commented on src/test/java/cart/dao/JdbcItemDaoTest.java
> +                () -> assertThat(items.get(1).getPrice()).isEqualTo(2000)
핳핳... 이전 마지막 리뷰에서도 리뷰어분께서 알려주셨던 부분인데 또 까먹었네요...! 😭😭 

꿀팁 감사합니다. ㅎㅎ

2023-04-28 08:16 UTC, kong-hana01 commented on src/main/resources/data.sql
> +    );
앗! 포멧팅하고 매번 sql은 이전 포멧팅으로 되돌려줬는데 깜빡했네요...!!

감사합니다 ㅎㅎ

2023-04-28 08:26 UTC, kong-hana01 commented on src/main/java/cart/dto/ItemRequest.java
> +    @JsonProperty("image-url")
아 그렇군요!!

혹시 그렇게 설계하고 있는 이유가 있을까요??

비즈니스 로직은 도메인에서, 그 외의 데이터 형태에 대해서는 dto에서 검증한다는 것이 좋은 기준인 것 같네요!

그런데 도메인에서 공백, 글자수 등에 대해 직접 검증하지 않는다면 의도하지 않는 도메인이 생성될 위험이 언제나 존재할 것 같은데요!

이런 잠재적인 위험보다는 dto에서 검증하는 것의 편의성이 더 높다고 판단하신걸까요? 
아니면 위와 같은 잠재적인 위험이 발생할 일은 거의 없으니까 아예 판단하실 때 고려의 대상이 아니었나요?

---

저는 위와 같은 문제가 발생할 수도 있으니 **도메인과 dto를 동일한 패키지**에 두어 `dto에서만 도메인을 생성`할 수 있도록 제한하는 것은 어떨까 생각해보기도 했거든요!
그렇게 하면 도메인에 대한 생성을 제한할 수 있기 때문에 위와 같은 잠재적인 문제를 해결할 수 있을 것이라고 생각했습니다.

프로젝트의 크기가 커지면 복잡도가 증가할 수 있겠다는 생각이 들기도 하는데, 정확히 어떤 부분이 문제가 될지는 잘 모르겠습니다...

혹시 바다는 이에 대해서 어떻게 생각하시나요?

2023-04-29 11:36 UTC, kong-hana01 commented
안녕하세요 바다!

리뷰 주신 내용에 더해서 더 다루면 좋을만한 부분에 대해서 조금 더 보강해서 다시 리뷰요청드립니다!

지난번과 크게 달라진 부분은 없지만 아래의 부분이 변경되었습니다!

- `데이터베이스에 저장되지 않은 상품 번호가 입력`되었을 때 `커스텀 예외 발생`하도록 변경
- `테스트 코드 보강`
- `테스트 코드 내 데이터 베이스 연동 오류 해결`

감사합니다~!!

2023-04-29 12:56 UTC, xrabcde approved these changes
안녕하세요 콩하나 ~ 바다입니다 🌊
피드백 잘 반영해주셨네요 ㅎㅎ
이번 단계는 여기서 merge 하겠습니다 
추가 코멘트 확인해보시고 이어서 다음 단계도 진행해주세요 ~!
2단계에서 만나요 🙌

2023-04-29 12:56 UTC, xrabcde commented on src/test/java/cart/service/ItemServiceTest.java
> +                        .isEqualTo(itemResponseExpected)
👍🏻👍🏻

2023-04-29 12:56 UTC, xrabcde commented on src/test/java/cart/controller/AdminControllerTest.java
> +    void newItemPriceNegativeFailTest() {
예외테스트 👍🏻👍🏻

2023-04-29 12:56 UTC, xrabcde commented on src/main/java/cart/controller/AdminController.java
> +@Controller
네 굳이 HTTP Response Body에 담아 보내지 않아도 되는 경우라면 controller를 사용해도 되겠지만 
그런 경우는 거의 없긴 합니다 😂

2023-04-29 12:56 UTC, xrabcde commented on src/main/java/cart/controller/AdminController.java
> +    @ResponseBody
현업에서는 보안 취약점과 같은 다양한 이유 때문에 어쩔 수 없이 제한되는 HTTP method들이 있지만
현재는 REST한 API를 학습하는 단계이기 때문에 다양한 HTTP method 들에 대해 학습해보고 사용해보는 것이 좋다고 생각합니다 ☺️

2023-04-29 12:56 UTC, xrabcde commented on src/main/java/cart/dto/ItemRequest.java
> +    @JsonProperty("image-url")
네 말씀하신 것처럼 프로젝트의 규모가 커진다면 멋지고 아름다운 설계보다는
일관성있고 유지보수가 편한 설계가 필요하기 때문에 한 곳에서 (보통은 도메인에서 하게 됩니다) 검증이 이루어지도록 하는 편입니다 ~

2023-04-29 12:56 UTC, merged