[Spring 장바구니 - 1단계] 로마(김범수) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #21
Opened 2022-06-01 11:09 UTC by kbsat

안녕하세요 앨런! 로마입니다! 예전에 앨런의 브이로그를 본 적이 있었는데 이렇게 리뷰어로 뵈니 반갑네요~ 😁
이번 협업 미션에서는 프론트 크루들과 함께 API를 설계하는 작업을 진행해보았습니다! [API 명세 보러가기](https://kbsat.notion.site/d225a8ae7fe244168c3d531cd3a63d57)

이번에 레거시 코드가 주어졌기 때문에 `Customer`, `Auth` 관련한 것을 제외한 나머지 부분에 대해서는 테스트만 통과하도록 수정해놓았습니다. 아마 이 부분은 2단계 때 뜯어 고칠 것 같습니다!

리뷰 잘 부탁드립니다 🙇‍♂️

2022-06-02 13:10 UTC, hongbin-dev requested changes
안녕하세요 로마~! 앨런입니다!
미션과 테스트코드 잘 작성해주셨군요! 꼼꼼한 부분들이 잘 보였습니다 👍
프론트엔드와 협업할 때 어떠셨나요? 노션으로 API 스펙을 공유하는데 어려운점은 없으셨나요?
또 몇 가지 피드백과 질문남겼으니 확인해주세요~!

2022-06-02 13:10 UTC, hongbin-dev commented on src/main/java/woowacourse/shoppingcart/dto/customer/CustomerCreateRequest.java
> +    private String password;
도메인 내의 검증로직은 없는데, Request객체에 검증은 조금 무겁다고 느껴지네요. 이렇게 작성하신 이유가 있을까요?

2022-06-02 13:10 UTC, hongbin-dev commented on src/main/resources/schema.sql
> +    email    varchar(100) not null unique,
👍

2022-06-02 13:10 UTC, hongbin-dev commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +        ExtractableResponse<Response> response = 회원조회_요청("testToken", 1L);
토큰을 보내지않아도 유효하지않는 토큰으로 나타내는 것 같은데요. 이런 부분을 서버에서 더 구체적으로 알려줄 순 없을까요?

2022-06-04 13:00 UTC, kbsat commented on src/main/java/woowacourse/auth/application/AuthService.java
> +        }
오 앨런의 의견에 동의합니다! 👍

2022-06-04 13:04 UTC, kbsat commented on src/main/java/woowacourse/auth/config/AuthenticationPrincipalConfig.java
> +    }
앨런 의견에 동의합니다~!
현재 레거시코드가 있어서 이런식으로 임시적으로 처리해놓았습니다. 
2단계 리팩토링을 진행하면서 해당 내용을 적용해보도록 하겠습니다!😃

2022-06-04 13:17 UTC, kbsat commented on src/main/java/woowacourse/auth/dto/TokenResponse.java
> +    private CustomerResponse customer;
먼저, 현재 API 명세에는 회원조회, 회원정보 수정, 회원 탈퇴를 보면 ID와 토큰 모두를 필요로합니다.

저희는 회의를 통해 path variable로 ID를 받게 했습니다. 현재 프로젝트에서는 마이페이지, 내정보 조회, 수정밖에 없지만 추후 관리자가 Customer의 정보를 조회, 수정, 탈퇴를 할 수 있다는 요구사항이 추가될 경우를 고려했습니다. 또한 토큰과 ID로 일치하는지 한번 더 검증해주는 것이 좋겠다는 의견이 나와 이런 의사결정을 내렸습니다. 그래서 토큰으로만 정보를 받는 것 보다 범용적인 API로 설계를 해보았습니다.

그런데 이런식으로 짜다 보니 프론트에서 Customer의 ID를 토큰만으로는 알 수 없게되었습니다. 그래서 Customer의 ID값을 넘겨줄 필요가 있었고 저희는 CustomerResponse를 반환해주는 방식으로 회의를 통해 결정해보았습니다.

앨런은 마이페이지 구현과 같은 곳에서`/me` 와 같은 특수한 API를 열어주는 편인가요 혹은 범용적인 조회 API를 사용하시는 편인가요?

2022-06-04 13:20 UTC, kbsat commented on src/main/java/woowacourse/auth/support/JwtTokenProvider.java
> +                .claim("email", payload)
수정하겠습니다! 😃

2022-06-04 13:40 UTC, kbsat commented on src/main/java/woowacourse/auth/support/PasswordEncoder.java
> +        return builder.toString();
축약된 단어들을 최대한 제거해보았습니다!

2022-06-04 13:41 UTC, kbsat commented on src/main/java/woowacourse/auth/support/PasswordEncoder.java
> +        } catch (NoSuchAlgorithmException e) {
엘런의 방식이 훨씬 깔끔해보이는 것 같아요!
저도 엘런의 방식처럼 도입해봐야겠어요 😋

2022-06-04 14:40 UTC, kbsat commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +        ExtractableResponse<Response> response = 회원조회_요청("testToken", 1L);
팀과 협의를 통해 수정해야할 내용 같습니다 😅
당장 수정은 못하지만 제 생각에도 엘런처럼 서버에서 구체적인 메세지로 알려주는 것이 협업하는 입장에서 효율적이라고 생각이 드네요 !!

2022-06-04 23:35 UTC, kbsat commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        request.setPassword(passwordEncoder.encode(request.getPassword()));
엘런의 말대로 DTO를 그대로 넘겨줘도 좋을 것 같아 보이네요!

2022-06-05 00:16 UTC, kbsat commented on src/main/java/woowacourse/shoppingcart/dto/customer/CustomerCreateRequest.java
> +    private String password;
Request DTO 내에서 모든 유효성 검증을 하기 때문에 검증이 무겁지만 들어오는 과정에서 검증을 미리 한다면 서비스 레이어까지 도달하지 않아도 미리 예외 처리할 수 있어 좋은 방식이라고 생각했습니다. 또한 검증을 통과해서 들어왔기 때문에 도메인 내에서 따로 검증을 하지 않아도 유효한 값들만 들어온 도메인 객체를 생성할 수 있겠다고 생각을 했었습니다.

하지만 다른 크루들과 이야기를 해보니 서비스 단에서 도메인을 직접 생성할 때 우리의 요구사항에 맞지 않는 잘못된 형식의 도메인 객체가 생성될 우려가 있다는 것을 깨달았습니다. 그리고 해당 검증 사항들도 우리의 비즈니스 사항이다 라는 의견이 많았고 이를 도메인 객체에서 검증을 해줘야한다는 의견이 다분했습니다.

그래서 이를 고민중입니다. 값이 들어올 때 DTO + `@Valid` 를 통해 요청이 들어올 때 모든 검증을 끝마칠 것인지 혹은 도메인 생성단에 검증로직이 들어가게 해서 도메인 객체 생성시에 이를 검증할 것인지 혹은 두 검증을 모두 처리할 것인지가 고민이 되네요.
두 검증을 모두 하게된다면 코드 중복일 수 있겠다는 생각이 들기도 하는데.. 참 고민이 됩니다..

앨런은 이러한 검증의 책임을 어디로 두는 것이 좋다고 생각하시는지 궁금하네요 🤔

2022-06-05 00:20 UTC, kbsat commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        request.setPassword(passwordEncoder.encode(request.getPassword()));
만일 도메인 객체에서 유효성에 대한 검증을 해준다면 이와같이 해주는 것이 좋겠지만
현재 제가 짠 코드에서는 유효성 검증이 DTO에 가있기 때문에 entity로 변환하는 과정이 불필요하겠다는 생각이 드네요! 😊

2022-06-05 01:51 UTC, kbsat commented on src/main/java/woowacourse/auth/support/LoginInterceptor.java
> +        }
제공해주신 자료들을 찾아보고 고민해본 결과 Global Configuration을 사용하는 지금 방식에서 Cors를 담당하는 Filter를 만들어 처리하는 방식으로 변경해보았습니다!

Global Configuration 방식에서는 로그인 검증을 해야하는 요청의 경우 인터셉터에서 preflight에 대한 처리를 해줬어야했지만 Filter를 따로 만들어서 필터 내부에서 미리 OPTIONS에 대해서는 response.ok로 반환하도록 설정해주어서 인터셉터에 존재했던 Preflight의 책임을 분리해보았습니다.

```JAVA
@Component
@WebFilter("/api/**")
public class CorsFilter implements Filter {

    public static final String ALLOWED_METHOD_NAMES = "GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH";
    public static final String ALLOWED_HEADER_NAMES = "Origin, X-Requested-With, Content-Type, Accept, Authorization";
    public static final String PREFLIGHT_MAX_AGE = "3600";

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {
        HttpServletRequest servletRequest = (HttpServletRequest) request;
        HttpServletResponse servletResponse = (HttpServletResponse) response;

        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");
        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_CREDENTIALS, "true");
        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, ALLOWED_METHOD_NAMES);
        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_MAX_AGE, PREFLIGHT_MAX_AGE);
        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_HEADERS, ALLOWED_HEADER_NAMES);
        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, HttpHeaders.LOCATION);

        if (CorsUtils.isPreFlightRequest(servletRequest)) {
            servletResponse.setStatus(HttpServletResponse.SC_OK);
        } else {
            chain.doFilter(request, response);
        }
    }
}
```

2022-06-05 02:08 UTC, kbsat commented on src/main/java/woowacourse/auth/support/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
토큰이 발행되었다는 것은 해당 로그인이 완료 되었기 때문에 발행이 되었고 만료시간이 도달되지 않았다는 생각이 들어서 토큰이 유효하다면 로그인이 되었다고 확인할 수 있다고 생각했습니다. 
또, 로그인이 되었는지 검증을 하기 위해서 토큰을 검증하기 위한 매번 서비스에서 조회해오는 작업을 인터셉터에서 처리를 하는게 옳은지에 대한 의문도 들었기에 이와같이 인터셉터에서는 토큰의 유효성만 체크해주기로 결정했었습니다.

`토큰만 믿어도 되는가?`에 대한 질문에는 아직은 잘 모르겠네요...🥲 그래도 로그인 후 이뤄지는 회원관련 요청을 보낼 때 ID를 추가로 받게 설계해서 Path에서 얻은 ID와 argumentResolver를 이용해 토큰을 까서 얻은 Customer의 ID를 비교해서 권한이 있는 사람인지를 한번 더 체크하게 하는 방법으로 추가 검증을 하긴 했습니다.

2022-06-05 02:12 UTC, kbsat commented on src/main/java/woowacourse/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +                                    NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
보통 argumentResolver에서 토큰을 까서 그 토큰 값을 주건 Customer 객체를 반환해주거나 방법이 갈리는 것 같았습니다.

저희 페어는 Customer 객체를 반환하기로 결정했는데 조회를 한번 함으로써 해당 유저가 존재하는지 여부를 판단해줄 수 있고 Customer 객체를 반환함으로써 이를 사용하는 Controller 단에서 로그인된 유저 정보를 보다 범용적으로 사용할 수 있다고 생각했기 때문에 객체를 반환했습니다.

2022-06-05 02:24 UTC, kbsat commented
안녕하세요 앨런! 리뷰주신 내용 모두 확인했고 그에 대한 고민들을 적어보았습니다!
확실히 로그인 기능에 들어가니 낯선 용어도 많이나오고 내가 과연 옳게 이해하고 사용하고있는건가? 에 대한 의문이 자꾸 드는 것 같습니다.🥲
앞으로도 앨런에게 열심히 배워보겠습니다 🙇‍♂️

> 프론트엔드와 협업할 때 어떠셨나요? 노션으로 API 스펙을 공유하는데 어려운점은 없으셨나요?
-  프론트와의 협업은 재밌었습니다! 생각보다 빠르게 일정 조율을 했고 이야기를 나누니 수월하게 진행되었던 것 같습니다. 우테코 와서 처음하는 협업이다 보니 아직 각 파트에 대해 잘 모르고 어느정도까지 처리를 해줘야하는지에 대해서 미숙한 점이 많았습니다. 그래도 앞으로 쭉 협업을 진행할 것이니 레벨 3 들어가서는 이에 대해서 많은 것을 배울 수 있을 것 같아 기대가 됩니다!😁
-  또, 노션으로 API 스펙을 공유하면서 일일히 작성을 해줘야하는 게 좀 귀찮고 휴먼에러로 인해 놓치는 부분이 있을 것 같다는 생각이 들었습니다. 추후에 스웨거나 RestDocs를 학습하여 도입한다면 더 수월한 명세 작성이 되지 않을까 생각이 드네요!

2022-06-05 02:25 UTC, kbsat commented on src/main/java/woowacourse/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +                                    NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
보통 argumentResolver에서 토큰을 까서 그 토큰 값을 주건 Customer 객체를 반환해주거나 방법이 갈리는 것 같았습니다.

저희 페어는 Customer 객체를 반환하기로 결정했는데 조회를 한번 함으로써 해당 유저가 존재하는지 여부를 판단해줄 수 있고 Customer 객체를 반환함으로써 이를 사용하는 Controller 단에서 로그인된 유저 정보를 보다 범용적으로 사용할 수 있다고 생각했기 때문에 객체를 반환했습니다.

2022-06-06 05:03 UTC, hongbin-dev commented on src/main/java/woowacourse/auth/dto/TokenResponse.java
> +    private CustomerResponse customer;
네 로마! 
우선 이 의견을 드린 건 토큰발급/회원정보 조회 API를 분리했으면 좋겠다는 의견이었습니다. API가 2가지 역할을 하고있다라고 생각이 들었습니다.

> 추후 관리자가 Customer의 정보를 조회, 수정, 탈퇴를 할 수 있다는 요구사항이 추가될 경우를 고려했습니다

지금은 사용자 API에 집중해주셨으면 좋겠어요! 관리자 API의 고려는 나중에 해도 좋을 것 같습니다. 
만약 나중에 관리자 API가 생긴다고하더라도 보안적인 측면이나, 같은 API를 사용하면 문제가 생길 수 있는 여지가 있어서 새로운 API 만들 확률이 큽니다. 즉 사용처(일반사용자, 관리자)마다 별도의 API를 만들려고 노력하고있습니다.

2022-06-06 05:09 UTC, hongbin-dev commented on src/main/java/woowacourse/auth/support/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
영속성에서 식별자가 유효한지 검사하는게 좋을 것 같다는 의견이었습니다. 만약 탈퇴를 했는데, 클라이언트에 토큰이 남아있으면 좀비유저가 서비스를 이용하는 꼴이 될 수도 있습니다.

>  로그인 후 이뤄지는 회원관련 요청을 보낼 때 ID를 추가로 받게 설계해서 Path에서 얻은 ID와 argumentResolver를 이용해 토큰을 까서 얻은 Customer의 ID를 비교해서 권한이 있는 사람인지를 한번 더 체크하게 하는 방법으로 추가 검증을 하긴 했습니다.

이렇다면 LoginInterceptor가 완벽하게 로그인을 검증하지 못한게 아닐까요? 또 권한은 막았지만, argumentResolver를 사용하지않은 API도 만들어질 수 있지 않을까요?

2022-06-06 05:11 UTC, hongbin-dev commented on src/main/java/woowacourse/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +                                    NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
네 저도 합당한 이유라고 생각합니다 의견 감사합니다~!

2022-06-06 05:14 UTC, hongbin-dev commented on src/main/java/woowacourse/shoppingcart/dto/customer/CustomerCreateRequest.java
> +    private String password;
이것도 책임에 관련된 내용인 것 같습니다. 만약 컨트롤러가 WEB API에서 console 컨트롤러로 변경된다면, 새로 검증로직을 작성해야할까요?
컨트롤러가 갖은 책임의 범위는 어디까지일까요?

2022-06-06 05:22 UTC, hongbin-dev commented
> 또, 노션으로 API 스펙을 공유하면서 일일히 작성을 해줘야하는 게 좀 귀찮고 휴먼에러로 인해 놓치는 부분이 있을 것 같다는 생각이 들었습니다. 추후에 스웨거나 RestDocs를 학습하여 도입한다면 더 수월한 명세 작성이 되지 않을까 생각이 드네요!

이 부분은 프론트엔드와 어떤 API, 요청, 응답을 같이 정해보는 시간을 갖아도 좋을 것 같아요. 스웨거나, RestDocs같은 툴도 좋고, OPENAPI로 문서먼저 만들고 개발하는 것도 좋은 경험이었던 것 같아요 🙂

2022-06-06 05:32 UTC, hongbin-dev approved these changes
안녕하세요 로마!
피드백 반영 잘 해주셨네요! 
코멘트 확인해주시고, 다음 단계 진행해주세요~!

2022-06-06 05:32 UTC, hongbin-dev commented on src/main/java/woowacourse/shoppingcart/filter/CorsFilter.java
> +        servletResponse.setHeader(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, HttpHeaders.LOCATION);
추후 도메인이 생성된다면 ACCESS_CONTROL_ALLOW_ORIGIN를 변경해주어야겠군요~

2022-06-06 05:33 UTC, merged

2022-06-07 08:29 UTC, kbsat commented on src/main/java/woowacourse/auth/support/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
탈퇴 예시를 보니 어떤 경우인지 정확히 이해가 가네요!
그렇다면 인터셉터에서도 충분히 이런 검증 ( 토큰에 들어간 email이 현재 DB에 Customer가 가지고 있는 값인가?? 라는 검증 ) 을 추가해주어서 좀비 유저를 막아볼 수 있겠다고 생각이 드네요!
생각해보니 이런 검증을 위해 들어가는 Select 쿼리 하나는 충분히 감안할만 하다는 생각이 들기도 하네요. 처음에는 Interceptor에서 검증 한 번, Resolver에서 검증 한 번 하는 것이 불필요한 작업인가 라는 생각이 들었지만 쿼리 하나 추가되는 것 보다 좀비 유저와 같은 예외 상황을 처리하는 것이 더 중요하다는 생각이 들었습니다.