[1단계 - 상품 관리 기능] 로건(정다빈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #216
Opened 2023-04-26 15:20 UTC by jyeost

f

2023-04-28 14:20 UTC, joseph415 commented
케로 안녕하세요~!

어제 공유드린것 처럼 워크샵때문에 오늘 리뷰 진행해요! 오늘 새벽이나 내일 진행될것 같아서 토욜까지는 확인 가능하도록 하겠습니다~!

2023-04-28 19:26 UTC, joseph415 requested changes
안녕하세요 케로.

리뷰어 서브웨이입니다. 1단계 구현 잘해주셨네요.
1차적으로 리뷰 달았습니다! 확인 부탁드려요!

궁금한 사항은 DM 또는 리뷰 코멘트 달아주세요! 확인이 완료된 리뷰는 resolve conversation 눌러주시면 감사하겠습니다~!

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/AdviceHandler.java
> +public class AdviceHandler {
서버 내부에서 발생하는 exception은 처리 안해도 될까요?

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +@Controller
rest controller 와 controller 분리하니까 더 좋아보이네요ㅎㅎ

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<String> updateProduct(@Valid @RequestBody ProductRequestDto productRequestDto, @PathVariable int id) {
Put 과 Patch 차이를 아실까요?
해당 api는 Put보다 Patch의 기능을하고있는 것 같아서 한번 어떤 차이가 있는지 찾아보셔도 좋을 것 같습니다.

한번 깊게 찾아보셔도 좋아보여요~

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
api들을 구현해주셨는데요. api 인터페이스를 어떤 생각을 갖고, 어떻게 설계 하신건지 적어주시면 감사하겠습니다~
확인 차 여쭤보아요~

혹시 restful 에대해서 들어보셨나요? 만약에 restful 하게 한다면 admin이라는 prefix가 확장과 api 설계에 약간 걸림돌이 될 수도 있겠네여!..

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +    @GetMapping("/products")
Product List를 get해야하는 api가 추가되야 한다면, 제약이 생길 수 있겠네요~ 
restful 하게 하시려면 api를 변경해볼수 있을 것 같습니다!

2023-04-28 19:26 UTC, joseph415 commented on README.md
> +    - [x] 상품 목록 조회
~~상품 목록조회 api는 미작성 된거 같습니다.~~ 
path가 수정된것 같네요!.. 문서 수정 부탁드립니다!

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
만약에 어드민이 아니라 다른 컴포넌트에서 해당 api를 호출해야한다면, prefix를 admin으로 잡는게 맞을지 한번 생각해봐도 좋을 것 같습니다!

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/dao/InMemoryProductDao.java
> +public class InMemoryProductDao implements ProductDao {
사용하지 않는 객체는 제거하는게 좋다고 생각합니다.

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/entity/ProductEntity.java
> +    public void setName(String name) {
도메인엔티티에서는 setter는 제거해보는게 어떤가요? 아직 요구사항이 없어서 로직이 없긴하지만, 나중에 요구사항이 생기면, setter보단 도메인적으로 네이밍을 풀면 좋을 것 같ㅅ아서요.

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/entity/ProductEntity.java
> +    public void setName(String name) {
현재 사용하는 곳도 없네요

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +        List<ProductEntity> productEntities = adminService.selectAllProducts();
도메인 엔티티가 view로 나가지 않도록 리펙토링 부탁드립니다. 
왜 이렇게 분리를 해야할까요?

2023-04-28 19:26 UTC, joseph415 commented on src/main/java/cart/service/AdminService.java
> +    public List<ProductEntity> selectAllProducts() {
서비스에서 도메인 엔티티를 리턴하도록 하셨군요~ :)

2023-04-28 19:26 UTC, joseph415 commented on src/main/resources/static/js/admin.js
> +    console.log(product);
불필요한 로깅은 지워주세요~

2023-04-28 19:26 UTC, joseph415 commented on src/test/java/cart/controller/AdminControllerTest.java
> +    void updateProduct() {
업데이트를 제대로 테스트 할거면 디비에 데이터가 들어가 있어야하지 않을까요? status만 확인하면, 해당 api가 정상작동하는지 확인이 불가할 것 같은데요.

프린트 찍어서 확인해보니까, 업데이트 개수가 0 으로 나옵니다.

2023-04-28 19:26 UTC, joseph415 commented on src/test/java/cart/controller/AdminControllerTest.java
> +public class AdminControllerTest {
해당 테스트에서 add하고 사후처리를 하지 않으면 다른 테스트에 영향을 줄텐데, 테스트 격리를 시켜야할 것 같습니다.

테스트 순서에 따라 다른 테스트에 영향을 줄 수도 있겠네요 (add test후 select test)

2023-04-28 19:54 UTC, joseph415 commented
request는 도메인개념이라고 보면 안될 것 같아요.

도메인 요구사항이라고 생각하시면, 도메인에 validation check 를 넣으면 더 좋을 것 같습니다.
request에서 하는 유효성 체크는 제 생각엔, request 유형에 대한 체크정도면 좋아보여요ㅎㅎ
예를들어, String 인데 int가 들어왔거나 요정도요.

도메인요구사항이라고 생각하시면 validate가 도메인으로 옮겨야한다고 생각하고,
도메인에 validate가 작성된다면 valid 어노테이션은 사용안하고 로직으로 풀면 좋을 것 같아요.

이거 관련해서는 제 다른 리뷰이 로건 리뷰에 달아두었습니다.
https://github.com/woowacourse/jwp-shopping-cart/pull/215#discussion_r1180684442

---

컨트롤러에서 초기화를 해주는 것이 좋다고 생각합니다. 컨트롤러 테스트에서 발생한것은 거기서 처리하는게 좋다고 생각해요.

> 이는 서비스 테스트의 결과에 영향을 끼쳤기 때문에 서비스테스트에서 각 테스트를 진행하기 전에, 테이블을 delete 해주는 방식으로 초기화 하도록 했습니다만... 다른 방법은 없을지, 컨트롤러에서 초기화를 해주는 것이 좋을지 고민이였습니다...

컨틀롤러에서 randomport로 사용하고 각 테스트 사후처리 안해주면,  서비스가 아니라 컨트롤러 테스트에 영향을 주는것 아닌가요?

컨트롤러와 서비스는 SpringBootTest가 걸려있어서 다른 테스트 컨텍스트라 영향이 없을텐데요.
그리고, service 에는 @Transational 을  적용되어있어서 테이블 제거 안해도 될 것 같은데,
@Transational 을 메서드에 적용해보세요.

---

> @Repository 의 변경이 있어도 상관 없이 테스트를 할 수 있다고 생각해서 서비스에만 구현 하였습니다... 

repositroy를 인터페이스로 작성한거랑은 연관이 없는 것 같습니다.  이런 의도였으면 서비스를 단위테스트로 작성하시는게 맞지 않나 생각이 드는데요~  인터페이스로 얻을 수 있는 이점은 단위테스트시 목객체를 사용할 수 있는 장점이 있는것일거에요~

서비스를 통합테스트로 작성하신 거면, dao 까지 통합적으로 기능이 잘 동작하는지 확인하는 것이라서, 저는 따로 작성 안해도 상관없다고 생각합니다.

dao 테스트로 쿼리 동작을 테스트해야 하는 의도가 있다면 둘다 작성해주시면 될것 같아요.

테스트 범위를 잘 생각해보시면, 기준이 생기실 겁니다.

---

보통은 string 형태로 메시지만을 전달하지는 않습니다. 구체적인 상황이 표현이 어려울 뿐더러, 클라이언트에서 스트링값만으로 처리할 수 없는 상황들이 있을거에요~

그래서 보통 에러코드, 에러메시지 등 에러를 객체로 보냅ㄴ디ㅏ.

2023-05-01 19:04 UTC, jyeost commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<String> updateProduct(@Valid @RequestBody ProductRequestDto productRequestDto, @PathVariable int id) {
put 메서드는 리소스의 전체 수정 
1. 해당하는 자원이 없을시 생성
2. 해당하는 자원이 존재할 시, 리소스로 대체

patch 메서드는 리소스의 부분수정

현재는 상품 수정에 대한 요청으로 update만 진행하고 있기 때문에 patch의 기능이 더 적합한 것이군요,,,,!

2023-05-01 19:34 UTC, jyeost commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
이번 미션에서 저와 페어 모두 api 설계가 처음이라 rest api에서 자주 쓰이는 방식으로  구현해보기로 했습니다 !

그래서 uri 는 collection이나 collection/{id}의 형식으로 고정하고 메서드를 통해서 구별하도록 select - get, insert - post , update - put(현재는 patch), delete - delete , 를 지정해서 나눴습니다.

설계를 하는 중에, 사용자의 products와 admin의 products를 나눠야 하지 않을까? 하는 생각에 admin이라는 prefix를 붙였던것 같습니다. 그러다 restful api의 uri path는 계층적인 형태로 구현해야 한다는 것을 알았습니다. 그래서 uri가 지정되어 있었던 select를 제외한 나머지 uri의  /admin을 제외하니 좀더 보기 쉬워진 것 같습니다. 사용자의 uri는 carts 라는 path로 구분하면 좀 더 기능적으로도 분리가 잘 될 것 같아요..!! 

서브웨이가 말한 restful하지 않다는 것이 이 부분에 대한 의견이 맞을까요...??

2023-05-02 10:48 UTC, jyeost commented on src/main/java/cart/controller/AdviceHandler.java
> +public class AdviceHandler {
핸들러로 남은 exception을 처리해주었는데, 이런식으로 하면 될까요?

2023-05-02 10:58 UTC, jyeost commented on src/main/java/cart/controller/PageController.java
> +@Controller
컨트롤러를 이렇게 view를 반환하는 controller와 객체를 반환하는 컨트롤러로 나눠서 쓰는 방법도 있다고 들어서 나눠 보았습니다...! 
같은 페이지 그룹으로 묶는 것이 나을지 지금처럼 뷰와 json을 반환하는 객체로 나누는 것이 가독성이 더 좋은지 고민중이였습니다..

2023-05-02 11:37 UTC, jyeost commented on src/main/java/cart/controller/PageController.java
> +    @GetMapping("/products")
해당 메서드는 제거하고, "/" 으로만 잡아주었습니다

2023-05-02 11:39 UTC, jyeost commented on README.md
> +    - [x] 상품 목록 조회
수정했습니다!

2023-05-02 11:39 UTC, jyeost commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
수정하였습니다 !

2023-05-02 11:39 UTC, jyeost commented on src/main/java/cart/dao/InMemoryProductDao.java
> +public class InMemoryProductDao implements ProductDao {
수정했습니다!

2023-05-02 11:40 UTC, jyeost commented on src/main/resources/static/js/admin.js
> +    console.log(product);
수정했습니다 :)

2023-05-02 11:59 UTC, jyeost commented on src/test/java/cart/controller/AdminControllerTest.java
> +public class AdminControllerTest {
컨트롤러에서 `@TestExecutionListeners`를 사용해서 테스트를 격리하고, service 단은 `@transitional` 처리해주었습니다!

2023-05-02 12:59 UTC, jyeost commented on src/main/java/cart/entity/ProductEntity.java
> +    public void setName(String name) {
수정하였습니다! 다음 단게에서 도메인 로직 추가하도록 하겠습니다 !

2023-05-02 13:00 UTC, jyeost commented on src/test/java/cart/controller/AdminControllerTest.java
> +    void updateProduct() {
업데이트와 딜리트 작업이 행해지지 않으면 exception을 던지도록 구현하고 테스트 수정하였습니다!

2023-05-02 13:02 UTC, jyeost commented on src/main/java/cart/service/AdminService.java
> +    public List<ProductEntity> selectAllProducts() {
dto로 리턴하도록 수정했습니다 !

2023-05-02 13:11 UTC, jyeost commented on src/main/java/cart/controller/PageController.java
> +        List<ProductEntity> productEntities = adminService.selectAllProducts();
제가 알아본 바로는
1. 엔티티의 내부 구현을 캡슐화하여, 테이블 설계를 노출하지 않도록 하고 자원이 실수로 변경됨을 막는다.
2. view에 필요한 속성들만 선별하기 때문에 필요 이상의 정보를 전송하는 수고를 아낄 수 있다.
3. 순환 참조를 방지할 수 있다. <- request 방향의 dto와 response 방향의 dto를 따로 써야 한다
4. dto에서 validation 을 일정부분 해줌으로써, 엔티티의 validation 로직을 줄일 수 있다.

이 정도 특징이 있는 것 같아요! 
아직 이런 장점들이 와 닿지 않아서 좀 더 사용해봐야 알 것 같아요 ㅜㅜ

2023-05-02 17:09 UTC, joseph415 commented on src/main/java/cart/controller/AdviceHandler.java
> +public class AdviceHandler {
넵 그러면 디폴트로 모든 exception을 잡아서 처리할거라 서버에러를 디폴트로 잡아서 내리겠네요

2023-05-02 17:10 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +@Controller
뷰와 json을 반환하는 것으로 나누는것이 더 파악하기 편할 것 같습니다!

2023-05-02 17:15 UTC, joseph415 commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<String> updateProduct(@Valid @RequestBody ProductRequestDto productRequestDto, @PathVariable int id) {
만약에 해당 api 가 put으로 열려있어서 누군가, 1번을 예상하고 호출한다면 버그가 나지 않을까요? 
그리고, 객체를 대체하기 때문에 자원이 없을 시 생성되는겁니다. Put은 수정의미보단 대체한다는 의미가 들어가요. id를 찾아서 리소스를 수정하고 있는데 patch가 아닐까요?

2023-05-02 17:17 UTC, joseph415 commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
네넵 제가 생각한대로 변경이 된것 같네요ㅎㅎ 하나 더 의견드리자면, AdminController -> ProductContoller로 하는게 더 와닿지 않을까 합니다!

2023-05-02 17:18 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +    @GetMapping("/products")
네넵! product list를 get 하는 api 를 AdminController 에서 작성할 수 도 있겠다는 생각을  했습니다~

2023-05-02 17:21 UTC, joseph415 commented on src/main/java/cart/controller/PageController.java
> +        List<ProductEntity> productEntities = adminService.selectAllProducts();
네네. 그리고 도메인이 외부로 나가게 되면, 도메인을 변경하는데 큰 제약이 생겨버립니다.
그리고, view는 굉장히 자주 바뀌는 곳인데, 이로인해서 도메인이 비지니스 요구사항이외의 것으로 영향도 받게 되고요!..

지금은 저희가 client, server를 학습 차원에서 둘다 작업하다 보니까 잘 와닿지 않을텐데 고민을 계속 해보시면 와닿는순간이 오실거에요!

2023-05-02 17:25 UTC, joseph415 approved these changes
안녕하세요. 케로!

1단계 리뷰 잘 적용해주셨네요💯 
몇가지 코멘트 추가로 남겨두었는데, 그건 2단계에서 고민해보시고 적용해주세요! 2단계 구현을 위해 이번단계는 이만 merge 하겠습니다!  2단계 미션 진행해주세요.

2023-05-02 17:25 UTC, merged

2023-05-05 06:54 UTC, jyeost commented on src/main/java/cart/controller/AdminController.java
> +@RequestMapping("/admin")
수정하였습니다 !

2023-05-05 07:04 UTC, jyeost commented on src/main/java/cart/controller/AdminController.java
> +    public ResponseEntity<String> updateProduct(@Valid @RequestBody ProductRequestDto productRequestDto, @PathVariable int id) {
저는 id를 포함한 모든 자원을 전부 받아서 리소스를 대체해 준다고 생각했는데, 서브웨이 답변이 더 정의에 맞는 사용법 같네요...! 수정하겠습니다 !