[Spring 장바구니 - 1단계] 렉스(오성원) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #25
Opened 2022-06-01 13:37 UTC by Seongwon97

안녕하세요 에단👋🏻
저는 4기 크루 렉스입니다!!

장바구니 미션 1단계 구현을 마쳐 PR을 보냅니다!!

이번 미션에서는 아래의 내용들을 중점으로 학습한 것 같습니다.
- Interceptor, Resolver, Token의 개념 및 사용법 학습
- @Valid 어노테이션
- 프론트, 백엔드 팀과의 API 설계

특히 API 설계의 경우 팀원 모두 처음 하다보니, 많은 수정이 필요하다 생각됩니다.
이는 지속적인 회의를 통해 개선해가겠습니다.

미션을 진행하며 궁금한 점은 아래에 남겼습니다
리뷰 잘 부탁드립니다🙇🏻‍♂️

--- 
## 미션을 진행하며 궁금하였던 점
### 1. @Valid 어노테이션의 장점 및 사용 범위
이번 미션을 진행하며 Valid 어노테이션을 페어와 처음 사용해봤습니다.
이전까지 미션을 진행하면서는 모든 요청값에 대한 검증들을 도메인 내에서 진행하였었는데, Valid어노테이션을 사용해보려고하니 해당 기능으로 어디까지 검증을 하는 것이 좋을지 의문이 들었습니다.(예를 들면 비밀번호 입력값의 형태의 경우 Password 도메인의 제약 조건인데 Valid에서 비밀번호 패턴을 검증해도 되는걸까?라는 의문이 들었습니다.)
학습을 해본 결과 Valid 어노테이션을 사용하면 입력값이 잘못된 경우에 Controller dto에서 검증이 되어 Service까지 내려오지 않는다는 장점이 있는데, 이러한 장점을 이용하고자 요청 값들을 Dto에서 검증을 하고 Password객체 생성에서는 검증을 안하게 된다면 객체의 안정성이 떨어질 수 있다고 생각됩니다.
그래서 현재 코드에서는 Dto에서는 `@NotBlank`를 통한 검증만을 진행하고 남은 요청값들의 검증은 도메인 내에서 하도록 진행하였습니다.
에단은 보통 @Valid를 통한 검증은 어느정도로 진행하는지 여쭙고 싶습니다.

### 2. Token의 사용범위
토큰이라는 지식에 대해 처음 학습을 하다보니 토큰의 사용 범위에 대해 궁금증이 생겼습니다.
현재 작성한 코드 내에서는 Interceptor에서 토큰에대한 검증을 진행하고 Resolver를 통해 토큰의 ID를 추출하여 해당 값을 통해 요청(정보조회, 회원 정보 업데이트, 삭제)를 진행하도록 하였습니다.

이와같이 진행을 하다보니 Token을 복호화하여 토큰 내부의 값을 이용해도 되는 것일까?라는 의문이 들었습니다.
현재 페어와 제가 내린 결론으로는 토큰의 경우 Filter나 Interceptor에서 올바른 회원인지에 대한 인증만을 위해 사용하는 것이 올바르고, 비즈니스 로직을 위해 토큰을 복호화하는 것은 좋지 못한 방법이라고 결론을 내렸습니다. (이를 위해 요청 URL에 회원 id를 추가하도록 API 수정을 하고자 합니다.)

실제 실무에서는 토큰을 저희가 생각한대로 인증만을 사용하는지, 아니면 토큰의 내부 값을 비즈니스 로직에 사용하기도 하는지 여쭙고 싶습니다!

### 3. Delete Request의 Body값
![image](https://user-images.githubusercontent.com/57744251/171417256-0360de15-32e6-4842-8bdf-3603070d4c5f.png)

[RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231)에서 delete 메서드에는 payload body값을 포함하지 않는 것을 권장하더라구요. 하지만 저희는 회원을 삭제할 때 member의 비밀번호를 확인하고 삭제합니다. 이럴때는 비밀번호를 확인하는 api와 삭제하는 api를 분리하는 것이 좋을까요?

2022-06-02 12:31 UTC, Laterality requested changes
안녕하세요 렉스.

리뷰어 에단입니다 👋 

잘 구현해주셨어요!

몇가지 코멘트 남겨드렸는데, 확인 부탁드려요.

궁금하신 점은 언제든 DM 주세요 :)

 ## Q&A

1. `@Valid` 어노테이션의 장점 및 사용 범위
    `@Valid` 어노테이션을 사용한 검증을 뷰(컨트롤러)에서 사용하셨는데요. 이 계층의 관심사는 어디까지일까요?
2. Token의 사용범위
    마찬가지로 토큰이 어느 영역의 관심사인지 고민해보시면 답을 찾으실 수 있을거라 생각해요 :)
3. Delete Request의 Body값
    포함하지 않는것을 권장한다기보다는 "포함할 수 있는지를 명시하지 않았다"고 보는 게 정확하겠네요. 때문에 구현체마다 동작이 일관되지 않을 수 있다는 점을 나타내는 것으로 보여요([Section 1.1.](https://datatracker.ietf.org/doc/html/rfc7231#section-1.1)에 기술돼 있기도 하고, 대부분 RFC 문서에서 요구 수준은 [RFC2119](https://datatracker.ietf.org/doc/html/rfc2119)에서 정의한 용어를 사용합니다). 실제로 body를 포함시켜도 무시하는 형태로 동작하는 경우가 있는 것으로 보이고요(e.g., [Grails](http://blog.leekyoungil.com/?p=390), [.NET](https://stackoverflow.com/a/299696)). 비밀번호를 함께 보내야 한다면 다른 HTTP 메서드를 사용하거나 URL 쿼리로 보내는 방법 등을 사용해야겠네요.

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/globalException/GlobalControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ErrorResponse(e.getMessage()));
DB 예외의 경우 예외 메시지에 쿼리가 포함되기도 하는데, 응답에 이를 노출해도 문제 없을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public Long authenticate(LoginRequest request) {
`AuthController`에서만 사용되고 있고 사용자 인증을 처리한다는 점에서 `AuthService`에 두는 게 더 어울리지 않을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void updateName(long id, UpdateNameRequest request) {
서비스 입장에서 `id` 인자를 `request`와 별도로 받아야 하는 이유가 있을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void withdrawal(long id, WithdrawalRequest request) {
메서드명은 동사로 시작하면 어떨까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/domain/Member.java
> +    }
`Password`를 인자로 받으면 어떨까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/domain/Password.java
> +    private static final Pattern casePattern = Pattern.compile("(?=.*?[a-z])(?=.*?[A-Z])");
상수에 맞는 네이밍 규칙을 사용하면 어떨까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/domain/Password.java
> +    }
`Password.value`가 암호화된 문자열과 암호화되지 않은 문자열 두가지 다 가질 수 있는 것 같은데, 클라이언트 입장에서는 `Password` 객체가 암호화된 값을 갖고 있는지 어떻게 알 수 있을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/domain/Password.java
> +        if (value.length() < 6) {
매직넘버네요!

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/domain/Password.java
> +    public boolean isSameAs(String input) {
`input`이 평문이어야 정상적으로 비교될텐데, 이 점을 나타낼 수 있는 방법이 있을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/dto/DuplicateEmailRequest.java
> +public class DuplicateEmailRequest {
"duplicate email"(이메일을 중복시키다, 복제하다)이라는 의미로 오해할 수도 있어보여요. 더 적절한 이름이 있을까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/member/dto/MemberInfoResponse.java
> +public class MemberInfoResponse {
`Info`를 빼더라도 클래스의 역할을 나타내는 데는 문제 없어보이네요.

2022-06-02 12:31 UTC, Laterality commented on src/main/java/woowacourse/shoppingcart/exception/NotInMemberCartItemException.java
> +    public NotInMemberCartItemException(final String msg) {
필요한 생성자일까요?

2022-06-02 12:31 UTC, Laterality commented on src/main/resources/schema.sql
> +    password varchar(255) not null,
생성되는 해시값은 최대 몇자일까요?

2022-06-03 15:24 UTC, Seongwon97 commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void withdrawal(long id, WithdrawalRequest request) {
withdrawal이 명사였네요..
동사 형태인 withdraw로 수정했습니다!!

2022-06-04 05:51 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Password.java
> +        if (value.length() < 6) {
domain에 위치한 모든 매직넘버들을 상수로 변경했습니다😁

2022-06-04 05:51 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Password.java
> +    private static final Pattern casePattern = Pattern.compile("(?=.*?[a-z])(?=.*?[A-Z])");
매직 넘버를 상수로 변경하며 해당 상수의 네이밍도 수정하였습니다!

2022-06-04 06:05 UTC, Seongwon97 commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void updateName(long id, UpdateNameRequest request) {
만약 ID와 Request를 하나의 DTO로 묶어서 보낸다면 회원 관련 모든 요청들에 대한 DTO가 하나씩 더 만들어져야 할 것 같습니다.

이렇게 된다면 각각 요청에 대해 컨트롤러에서 요청 body값을 매핑하도록 사용하는 커멘드 객체(dto)와 controller layer에서 service layer로 넘겨주기 위해 사용하는 dto, 이렇게 2개가 필요하다 생각됩니다.

Service입장에서 하나의 dto만을 받아 serivce로직에서는 깔끔하게 보일 수 있지만 이로인해 layer간 통신을 위한 많은 dto가 만들어져야한다 생각하여 다음과 같이 id와 커멘드 객체로 사용한 dto 같이 넘겨주도록 하였습니다.

2022-06-04 06:47 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Password.java
> +    public boolean isSameAs(String input) {
Password객체에 equals,hashCode를 재정의하며 해당 메서드는 사용하지 않게 되었는데..삭제하는 것을 깜빡했었네요..!

해당 메서드는 사용하지 않아 제거하였습니다!

2022-06-04 07:28 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Member.java
> +    }
리뷰를 반영하여 Password 객체를 외부에서 생성하여 Member생성자에 String이 아닌 Password를 넘겨주도록 수정하였습니다.

Password객체를 넘겨주니 정적 팩터리 메서드도 제거가 되어 코드도 깔끔해진 것 같네요..!

2022-06-04 07:37 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Password.java
> +    }
저도 미션을 진행하며 가장 큰 고민하였던 내용 중 하나가 Password객체 관련 문제였습니다.

- password.value가 어떻게 해야지 암호화된 문장이 들어간다는 것을 보장할 수 있을까?
- password를 생성할 때, 암호화된 문장을 다시 암호화되는 상황을 어떻게 방지할 수 있을까?

위와 같은 두가지 고민을 하였고..에단의 리뷰를 받으며 추가적인 고민을 해본 결과 현재는 아래와 같은 방법들이 떠오릅니다.
- Password 인터페이스를 상속받는 암호화된 비밀번호를 받아 처리를 하는 객체, 암호화되지 않은 비밀번호를 받아 처리하는 객체를 만들어 처리를 하는 방법
- token의 validation과 같이 해당 프로그램의 암호화 알고리즘으로 암호화된 값인지 확인을 해주는 방법

저는 개인적으로 2번째 방법으로 진행을 하고싶어..방법을 찾고있으나 구현 방법을 아직까지 찾지 못하였습니다...

해당 문제는 다른 리뷰들 수정 후에 더 많은 고민을 해보고 다시 수정해보겠습니다

2022-06-04 07:49 UTC, Seongwon97 commented on src/main/java/woowacourse/member/dto/DuplicateEmailRequest.java
> +public class DuplicateEmailRequest {
에단의 말을 듣고보니 "이메일 중복 검사 요청"이 아닌 "이메일을 중복시키는 요청"으로 오해될 수 있겠다는 생각이 드네요..!

해당 네이밍을 `EmailDuplicateCheckReqeust`로 수정하여 이메일 중복검사!!라는 뜻으로 받아들일 수 있게 변경하였습니다!

2022-06-04 08:02 UTC, Seongwon97 commented on src/main/java/woowacourse/shoppingcart/exception/NotInMemberCartItemException.java
> +    public NotInMemberCartItemException(final String msg) {
이번 1단계는 회원관련 기능을 구현을 하는 미션이었어 member 패키지를 새로 생성하고 해당 패키지 내에서만 미션을 진행하다보니 기본 제공 코드들을 신경쓰지 못한 것 같습니다..!

아래 리뷰의 불필요한 생성자 삭제와 같이 수정하였습니다!😁

2022-06-04 08:15 UTC, Seongwon97 commented on src/main/java/woowacourse/globalException/GlobalControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ErrorResponse(e.getMessage()));
이전 미션을 진행하며서도 받았던 내용의 리뷰인데..같은 실수를 반복했네요..ㅠㅠ

아래와 같이 로직상에서 다루지 못한 오류들은 예외 메시지를 반환하는 것이 아닌 다른 메시지를 반환하도록 수정하였습니다!!
```java
    @ExceptionHandler(DataAccessException.class)
    public ResponseEntity<ErrorResponse> handleDataAccessException() {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new ErrorResponse("데이터 처리중 문제가 발생하였습니다."));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handlerException() {
        return ResponseEntity.badRequest().body(new ErrorResponse("다뤄지지 않은 에러입니다."));
    }
```

2022-06-04 13:29 UTC, Seongwon97 commented on src/main/java/woowacourse/member/dto/MemberInfoResponse.java
> +public class MemberInfoResponse {
회원 정보 조회 관련 메서드 및 기능들의 네이밍을 `findMember`, `MemberResponse`
와 같이 할 수도 있으나 저는 MemberInfo라는 이름이 코드를 처음 보는 사람들이 이해하기 쉬울 것이라 생각됩니다.

그리고 `findMember()`, `MemberResponse`라는 이름의 메서드와 dto는 내 정보 조회가 아닌 "아이디/비밀번호 찾기"등 회원 검색등에 사용되는 코드들로 보일 수 있다고 생각됩니다.

2022-06-04 13:59 UTC, Seongwon97 commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public Long authenticate(LoginRequest request) {
지난 미션부터 "[1]서비스 클래스에는 하나의 Dao또는 Repository만을 갖도록 하고 이를 합쳐주는 서비스 클래스를 만드는 것이 좋을까??(퍼사드 패턴) 아니면 [2]서비스 레이어에 중복 코드가 발생하더라도 서비스별로 여러개의 Dao를 갖게하여 하나의 서비스 로직을 만들어 주는 것이 좋을까?"라는 고민을 하였습니다.

지난 미션에서는 2번째 방법으로 미션을 진행하였어서 이번에는 1번째 방법으로 미션을 진행해 둘의 장단점을 느껴보고자 하였습니다.. 그래서 `authenticate()`를 `MemberService`에서 갖고  이를 서비스에서 호출하도록 하였었는데, 제가 생각한 1번(퍼사드 패턴)을 이용하려고 한다면 `MemberService`를 `AuthController`에서 갖는 것이 아닌 `AuthService`에서 갖도록 해야했었네요...

리펙터링 초기에는 `AuthService`에서 `MemberService`를 갖도록 코드를 수정하였었는데, 생각을 해보니 1번 방법으로 진행을 한다면 회원 관련 기능들이 커졌을 때, `MemberDao`를 갖는 `MemberService`가 너무 커지고, 로직 관리가 어려울 것 같다고 판단하여 최종적으로는 에단의 말대로 `authenticate`메서드를 `AuthService`로 이동시켰습니다.

2022-06-04 14:55 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/Password.java
> +    }
최종적으로 수정한 방법은 `Password` 기본 객체를 생성하고 그를 상속받는 `NewPassword`와 `ExistPassword`를 만들어 DB에서 암호화된 비밀번호 객체를 생성할 때는 `ExistPassword`로 생성하고, 외부에서 입력받은 비밀번호로 새로운 비밀번호 객체를 만들때는 `NewPassword`를 생성하도록 수정하였습니다.

다만 여기서 `NewPassword`의 네이밍이 좀 마음에 걸리는 것 같습니다. 새로운 비밀번호 생성, 기존 비밀번호 생성의 의미로 `NewPassword`와 `ExistPassword`로 네이밍을 정하였는데 `NewPassword`의 경우 인스턴스 생성을 할 때 `new NewPassword`와 같은 형태의 코드가 만들어져 네이밍 수정이 필요하다 생각됩니다..

따로 떠오르는 좋은 네이밍이 떠오르지 않는데..혹시 괜찮은 네이밍이 없을까요😭

2022-06-04 15:02 UTC, Seongwon97 commented on src/main/resources/schema.sql
> +    password varchar(255) not null,
sha-256의 경우 256비트의 출력을 하여 이를 문자열로 바꾸게되면 64의 크기가 됩니다!!

Password의 크기를 64로 수정하였습니다. 뿐만 아니라 다른 컬럼들의 크기도 수정하였습니다.

2022-06-04 15:06 UTC, Seongwon97 commented on src/main/resources/schema.sql
> +    password varchar(255) not null,
질문이 하나 있습니다..! 
이전에 DB 테이블 컬럼의 크기는 보통 비즈니스 로직에서 제한하는 크기보다 조금은 크게 한다고 들은적이 있습니다! 
실제로도 테이블의 크기를 비즈니스 로직의 제약사항보다 조금씩 크게 설계를 하는 것이 좋은지 여쭙고 싶습니다

2022-06-04 15:39 UTC, Seongwon97 commented
안녕하세요 에단!
보내주신 리뷰를 반영하여 코드 리펙터링을 해봤습니다!!

첫번쨰 리뷰 요청때 답해주신 답변에 대해서도 추가적으로 생각을 해봤습니다.

1. @Valid 어노테이션의 장점 및 사용 범위
@Valid 어노테이션을 사용한 검증을 뷰(컨트롤러)에서 사용하셨는데요. 이 계층의 관심사는 어디까지일까요?
> 해당 계층에서의 관심사는 프로그램 요구사항(도메인 제약사항)의 내용을 갖는 것이 아닌 빈 값이 들어왔는지 등의 최소한의 검증만을 가져야한다고 생각합니다. 이번에 여러 크루들, 코치들과 많은 이야기를 나누어 보면서도 여러 의견들이 있었지만, **저는 컨트롤러의 커멘드 객체에서는 빈 값 체크와 같은 최소한의 검증을 하고, 도메인에서 도메인 제약사항에 맞는 검증을 하는 것이 옳다고 생각됐습니다.** 물론 두 곳에서 같은 검증을 하며 @Valid어노테이션을 통해 잘못된 값이 들어오면 서비스 레이어로까지 내려오지 않는다는 장점을 얻을 수 있지만, 그렇다면 제약사항이 바뀌었을 때 dto와 도메인 두 곳에서 수정을 해야한다는 문제가 있을 것 같아 위와 같은 스타일로 개발을 할 것 같습니다.

2. Token의 사용범위
마찬가지로 토큰이 어느 영역의 관심사인지 고민해보시면 답을 찾으실 수 있을거라 생각해요 :)
> 토큰은 인증 인가를 하며 사용자를 구분, 판단하는 역할을 한다고 생각됩니다. 이 고민은 rest api의 url에서는 자원을 표현하여야하는데 "api/members/me"보다는 특정 회원의 자원을 표현하는 "api/members/{memberID}"가 좋지 않을까? 하는 생각으로부터 시작되었습니다. 하지만 해당 내용에 대해서도 여러 크루들과 이야기를 나누어보고 깃헙의 url등을 참고해보니 제가 고민을 한 내 정보 조회와 같이 본인 또는 특정 유저만 접근할 수 있는 정보에 관해서는 url에 정보가 노출되지 않고 token의 값을 이용해 로직을 처리하는 것이 더욱 보안상 안전하다고 생각되었습니다. 제가 내린 결론으로는 **"토큰은 인증, 인가를 하는데 사용된다. 하지만 인증, 인가 뿐만 아니라 개인정보 조회와 같이 민감한 데이터들에대한 요청에서는 token값을 비즈니스 로직에 이용하기도 한다!!"** 입니다!!

감사합니다🙇🏻‍♂️

2022-06-05 03:22 UTC, Laterality approved these changes
안녕하세요 렉스.

피드백 잘 반영해주셨어요 👍 

이번 단계는 이만 머지하도록 할게요.

질문 주신 부분과 몇군데에 코멘트 남겨드렸어요. 다음 단계 진행하면서 참고해주세요.

고생 많으셨습니다 :)

2022-06-05 03:22 UTC, Laterality commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void updateName(long id, UpdateNameRequest request) {
1. `id`와 `request`를 별도로 나눠 받는 것은 컨트롤러의 관심사 아닐까요?

2. 만약 API에 새 버전을 추가하게 된다면 필요한 기능은 동일하더라도 요청 객체가 다르면 새 버전 API의 요청 객체를 수용하는 서비스를 또 만들어야 할까요?

```java
@PatchMapping("/api/v1/users/{id}", params="prop=name")
void updateUserName(
    @PathVariable id: Long,
    @RequestBody UpdateNameRequest request) {
    service.updateName(id, request);
}

@PatchMapping("/api/v2/users/{id}", params="prop=name")
void updateUserNameV2(
    @PathVariable id: Long,
    @RequestBody UpdateNameRequestV2 request) {
    service.updateNameV2(id, request);
}
```

2022-06-05 03:22 UTC, Laterality commented on src/main/java/woowacourse/globalException/GlobalControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ErrorResponse("다뤄지지 않은 에러입니다."));
처리되지 않은 예외는 처리되도록 이후에 코드를 수정해야 할텐데요. 어떤 예외가 어디서 발생했는지 남겨두면 어떨까요?

2022-06-05 03:22 UTC, Laterality commented on src/main/java/woowacourse/member/domain/password/ExistPassword.java
> +public class ExistPassword extends Password {
이 클래스의 책임은 무엇일까요?

2022-06-05 03:22 UTC, Laterality commented on src/main/java/woowacourse/member/domain/password/Password.java
> +public class Password {
서비스에서 실수로 `NewPassword` 대신 `new Password("password")`로 생성해도 문제 없을까요?

2022-06-05 03:22 UTC, merged

2022-06-08 06:58 UTC, Seongwon97 commented on src/main/java/woowacourse/member/dto/MemberInfoResponse.java
> +public class MemberInfoResponse {
- 아이디/비밀번호 찾기 등에 사용되는 DTO는 `FindPasswordResponse`, `FindIdResponse`등의 네이밍이 올바를 것 같습니다.
- 회원 정보 조회 반환 DTO의 네이밍으로는 더 명확하게 `FindMemberInfoResponse` 또는 축약하여 에단이 말해주신 `MemberResponse`가 좋을 것 같습니다.

2022-06-08 07:16 UTC, Seongwon97 commented on src/main/java/woowacourse/globalException/GlobalControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ErrorResponse("다뤄지지 않은 에러입니다."));
앗..그렇네요..! 실제로 2단계 미션을 진행하면서도 예외에 대한 로그를 남기지 않다보니 에러 위치를 찾기 힘들었던 경험이 있었어요ㅠㅠ

에러를 프론트까지 반환해주지는 않더라도 로그로 찍어주는 것이 확실히 좋은 것 같습니다!!

2022-06-09 03:02 UTC, Seongwon97 commented on src/main/java/woowacourse/member/domain/password/Password.java
> +public class Password {
Password를 추상 클래스로 변경하며 생성을 막도록 수정했습니다😁

2022-06-09 05:13 UTC, Seongwon97 commented on src/main/java/woowacourse/member/application/MemberService.java
> +    public void updateName(long id, UpdateNameRequest request) {
1. 에단이 말한대로 컨트롤러 내에서 id와 reqeust를 나누어 받은 것을 Service까지 넘겨주는 것은 컨트롤러의 관심사를 서비스 계층까지 넘겨주는 것은 좋은 방법은 아니라고 생각합니다. 하지만 이를 위해 Controller-Service 사이의 데이터 전송을 위한 DTO를 새로 생성하는 것 보다 관심사를 넘겨주는 것이 더 괜찮다고 생각됩니다..!

2. 에단의 말을 확실하게 이해를 하지 못하겠습니다..요청 값이 다른 새로운 컨트롤러가 생겨난다면 DTO의 계층화 또는 서비스를 새로운 요청 값에 맞게 생성해줘야 한다고 생각됩니다. 혹시 해당 내용에 대해..구체적으로 말해주실 수 있으실까요..?😭