[2단계 - 상품 관리 기능] 로건(정다빈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #267
Opened 2023-05-01 03:16 UTC by BackFoxx

### 변경사항
* TDD 방식으로 구현해 보았습니다. 그래서 리포지토리와 컨트롤러에 대한 유닛 테스트가 많이 있습니다. :)
* 레이어 아키텍처 패키지 구조에서 도메인 단위의 패키지 구조로 분류하였습니다.

### 궁금증
* Cart 하나를 데이터베이스에서 삭제하는 코드를 테스트하려고 합니다.
```
@Test
    @DisplayName("장바구니에 담은 상품이 삭제되면 장바구니 내역도 함께 사라진다.")
    void deleteProduct() throws MemberPersistenceFailedException, CartPersistenceFailedException {
        // given : 장바구니에 하나가 저장되어 있다.
        Member member = memberRepository.save(new Member("test@gmail.com", "password1234!"));
        Product product = productRepository.save(new Product("product", "product.png", new BigDecimal(4000)));
        cartRepository.save(new Cart(member.getEmail(), product.getId()));
        assertThat(cartRepository.findAllByMemberEmail(member.getEmail())).hasSize(1);

        // when : 상품을 삭제한다.
        productRepository.deleteById(product.getId());

        // then : 삭제된 상품에 대한 장바구니 내역도 사라져있어야 한다.
        assertThat(cartRepository.findAllByMemberEmail(member.getEmail())).hasSize(0);
    }
```
Cart는 Member와 Product의 id 두 개를 기본키로 사용하고 있습니다.
그래서 Cart를 삭제하는 메서드를 실행하기 전
1. Member를 저장하는 코드
2. Product를 저장하는 코드
3. Cart를 저장하는 코드
이렇게 3개의 작업을 given 절에 작성해두어야 하고,
결과적으로 정말로 테스트하고자 하는 코드보다 훨씬 긴 코드를
테스트 환경을 갖추는 데에 작성해야 합니다.

이는 테스트 코드의 가독성을 해치는 문제도 있지만
deleteById를 테스트하는 코드에서 사실상 1,2,3 코드를 테스트하는 역할까지 같이 수행하고 있다는 점에서
단일책임원칙을 위배하는 테스트코드가 아닌가 걱정이 됩니다.

동료들과 논의한 결과 두 가지 해결방법이 떠오르게 되었는데,
1. Member, Product, Cart를 저장하는 쿼리가 있는 Sql 문서를 작성하고, @Sql을 통해 가져오는 방법
2. Texture 클래스를 만들고 위 1,2,3 코드만 들어있는 메서드를 만든 후, 호출해 사용하는 방법
이 둘 중에 어떤 방법이 더 나은 선택인지 고민중입니다. 춘식이라면 어떤 방법을 사용하시나요?
혹시 이보다 더 나은 방법이 있다면, 꼭 조언해주시면 좋겠습니다!

2023-05-01 09:47 UTC, bimppap requested changes
안녕하세요 여우, 춘식입니다!
2단계도 빠르게 구현해주셨네요! 커밋이력을 보니 TDD도 잘 적용해주셨고요 👍
질문에 대한 답과 코멘트들 조금 남겨봤어요. 확인 부탁드립니다.
궁금한거나 이해가 안 되는 부분은 편하게 DM 주세요🙂

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/repository/JdbcCartRepository.java
> +            throw new CartPersistenceFailedException("존재하지 않는 멤버 또는 상품으로 장바구니에 담을 수 없습니다.", exception);
멤버, 회언, Member 등 에러 메세지에서 멤버를 지칭하는 단어가 여러 개로 나누어져 사용되고 있는데, 이는 통일시키는 게 좋습니다🙂

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/repository/JdbcCartRepository.java
> +            throw new CartPersistenceFailedException("존재하지 않는 멤버 또는 상품으로 장바구니에 담을 수 없습니다.", exception);
만약 에러가 점점 더 많아진다면 나중에 유지보수나 테스트가 어려워질 수도 있습니다. 그런 점에서 에러 메세지들을 한 곳에 모아볼 수 있도록 enum화 시키는 건 어떨까요?

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/controller/ShoppingCartController.java
> +package cart.cart.controller;
ShoppingCartController는 홈 화면을 보여주기 위한 컨트롤러인데, 특정 도메인 패키지에 종속되어 있는게 맞는 걸까요? 🤔

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/controller/CartController.java
> +
> 2단계에서 추가 요구사항이 생기고 이 요구사항을 컨트롤러에서 감당하기 힘들다는 느낌이 오면
그 때에 서비스 레이어를 분리하기로 했습니다.

1단계 리뷰 때 여우가 남겼던 코멘트인데, '컨트롤러에서 감당하기 힘들다'의 기준이 어떻게 되는 걸까요? 👀

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/controller/CartController.java
> +
1단계 구현 때 적용한 YANGI 원칙은 익스트림 프로그래밍(이하 XP)에 나온 원칙입니다.

XP는 비즈니스 상 `요구사항의 변동이 빠르게 변하는` 소규모 프로젝트에 적용하기 좋은 애자일 방법론이에요. 조직적인 개발보다는 개개인의 역량을 중시하기 때문에, 문서 작성을 최소화하고 빠른 의사소통과 피드백으로 개발 효율을 증가시키는 걸 지향합니다.

하지만 그렇기 때문에 대규모 프로젝트엔 적용이 어렵고 개인의 실력 또는 성향에 따라 프로젝트 품질 차이가 발생하기 쉬운 방법론이기도 합니다.

여우가 짠 코드가 잘못되었다는 뜻은 아닙니다. 이러한 원칙에 대해 알아보고 적용한 건 굉장히 좋은 시도라고 봐요 👍하지만 이번 미션의 경우 요구사항이 확실하고, 변동이 크게 일어나지도 않는 구조이기 때문에 방법론적으로 보면 과연 적합한가? 라는 의문이 듭니다. (물론 개발에 있어 정답이라는 건 없습니다. 더 좋은 접근법이 있을까? 에 대한 고민을 해보라는 겁니다ㅎㅎ)

Spring Web MVC를 이용하여 구현하는 미션인만큼, 해당 구조를 최대한 많이 활용해보면서 관련된 기능을 깊이 학습해보면 더 좋지 않을까 하는 아쉬움이 들어 말을 길게 늘어봤습니다ㅎㅎ

개발 방향은 이대로 진행하셔도 됩니다 🙂 다만 Spring Web MVC 구조에 대해서 정리해보는 시간을 꼭 가지면 좋을 것 같아요. 👍

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/product/controller/ProductController.java
> +    @ResponseBody
post, put, delete는 responseBody가 없어도 되나요? 👀

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/product/entity/Product.java
> +    private BigDecimal price;
BigDecimal 잘 적용해주셨네요 👍

2023-05-01 09:47 UTC, bimppap commented on src/test/java/cart/controller/CartControllerTest.java
> +    }
dto를 사용하면 테스트 코드의 가독성이 좋아질 거 같네요 🙂

2023-05-01 09:47 UTC, bimppap commented on src/test/java/cart/controller/CartControllerTest.java
> +@WebMvcTest(CartController.class)
> 테스트할 때 필요한 데이터는 어떻게 가져오는 게 좋은가

사실 테스트는 가능한 독립적으로 매번 새로운 오브젝트를 생성해 사용하는 것이 원칙입니다. 통합 테스트는 말 그대로 '통합'이기 때문에 단일책임원칙을 적용하기엔 조금 어려워보이네요. 하지만 애플리케이션 컨텍스트처럼 생성에 많은 시간과 자원이 소모되는 경우에는 테스트 전체가 공유하는 테스트 데이터를 만들기도 합니다. 🙂

테스트 데이터를 만드는 방법은 여우가 제시한 대로 sql을 사용하거나 fixture를 만드는 두 가지 케이스가 있습니다. 저는 **재사용하기가 쉬운** fixture를 만드는 후자를 선호하는 편이라 2번으로 진행해보는 건 어떨까 싶네요. (제가 알기로 캡틴은 그때그때 생성자를 만들어 쓰는 걸 선호한다고 들었습니다🤓)

(심화) 참고로 fixture를 만드는 방식 중에는 Test Data Builder 패턴과 Object Mother 패턴도 있습니다. 두 패턴에 대해 한번 정리해보고 원하는 방식을 적용해봐도 좋을 것 같습니다.

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/authentication/AuthenticationArgumentResolver.java
> +    private static final String BASIC_TYPE = "Basic";
Basic 인증을 사용하셨군요! 이 방식은 토큰 값이 노출이 되면 이메일 또는 패스워드 등이 노출될 수 있어 보안에 취약하다는 단점이 있는데, 다른 인증 방식에 대해서도 알아보고 정리해보는 건 어떨까요?

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/controller/CartController.java
> +import cart.cart.exception.CartPersistenceFailedException;
이건 사용하지 않고 있군요 😎

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/authentication/Authentication.java
> +public @interface Authentication {
현재 이 어노테이션을 사용하는 곳들을 보면 Member 객체 내에 있는 email만 꺼내 쓰고 있습니다. 그럼 Member 객체가 아닌 email을 반환하면 되지 않을까요?

2023-05-01 09:47 UTC, bimppap commented on src/main/resources/schema.sql
> +    primary key (member_email, product_id),
복합키를 사용한 이유가 있을까요? 대표 id PK를 쓰는 방법도 있었을텐데요 🤔

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/product/controller/ProductController.java
>      @PostMapping("/create")
REST API 에서 URI는 행위보다 자원을 표현하는 데 중점을 둬야 합니다. NHN에서 관련해 정리한 [좋은 글](https://meetup.nhncloud.com/posts/92)이 있으니 한번 정독해보면 좋을 것 같네요.

2023-05-01 09:47 UTC, bimppap commented on src/main/resources/templates/cart.html
>              // TODO: [2단계] 장바구니 CRUD API에 맞게 변경
이건  지워도 되겠네요 😎

2023-05-01 09:47 UTC, bimppap commented on src/test/java/cart/controller/IntegrationTest.java
>  class IntegrationTest {
IntegrationTest와 타 컨트롤러 테스트와의 구분 기준이 어떻게 되나요?

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/entity/Cart.java
> +    private final Long productId;
Cart가 memberEmail, productId 가 아닌 Member, Product를 들고 있어도 됐을텐데, 이런 구조로 짠 이유가 궁금합니다!

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/entity/Cart.java
> +    private final Long productId;
또한 기본적으로 Cart를 생각해보면 유저별로 하나의 장바구니를 가지고 여러 개의 품목이 장바구니 안에 담겨있는 구조를 떠올릴 거 같아요. 도메인 의존 관계를 이렇게 짠 이유가 있을까요?

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/config/CommonControllerAdvice.java
> +public class CommonControllerAdvice {
로깅 적용은 일단 보류하기로 한 걸까요?ㅎㅎ

2023-05-01 09:47 UTC, bimppap commented on src/main/java/cart/cart/repository/JdbcCartRepository.java
> +            exception.printStackTrace();
에러 관련 처리는 ControllerAdvice에서 하도록 합시다!

2023-05-01 10:49 UTC, BackFoxx commented on src/main/java/cart/cart/repository/JdbcCartRepository.java
> +            throw new CartPersistenceFailedException("존재하지 않는 멤버 또는 상품으로 장바구니에 담을 수 없습니다.", exception);
피드백 내용 반영했습니다! 스프링 프레임워크에서는 MessageConverter라는 기능으로 메시지를 하나의 properties 파일에서 관리할 수 있게 해주던데, 아쉽게도 이 기능은 컨트롤러에서 뷰로 넘어갈 때 뷰에 보여주는 메시지에만 적용되는 거네요 🥲 아숩습니다

2023-05-01 10:51 UTC, BackFoxx commented on src/main/java/cart/cart/controller/ShoppingCartController.java
> +package cart.cart.controller;
맞는 말씀이에요! 도메인 별로 패키지를 나누다 보니, 홈 화면 보여주기용 컨트롤러처럼 특정 도메인에 속하지 않는 객체들은 어디에 보관해야 할 지 고민이 많이 듭니다. 일단 common 이라는 패키지 하위에 두기로 결정했습니다.!

2023-05-01 14:44 UTC, BackFoxx commented on src/main/java/cart/cart/controller/CartController.java
> +
'감당' 의 기준을 정확히 정하지 않고서
주관적인 느낌만으로 아키텍처를 설계했던 제 행동을 반성하게 되는 피드백이네요!

제가 보기에 '컨트롤러의 역할을 벗어나는 작업'은
'단순히 다른 레이어의 메서드를 호출하고 받은 리턴값을 모델에 담는 일' 이외에 행하는 **모든 연산작업**이 해당된다고 생각합니다.

제 코드에서는 딱 아래의 컨트롤러가 그 예시가 되겠네요!
```
    @GetMapping("/carts")
    public ResponseEntity<List<Product>> findByEmail(@Authentication Member member) {
        List<Cart> carts = cartRepository.findAllByMemberEmail(member.getEmail());

        List<Long> productIds = carts.stream()
                .map(Cart::getProductId)
                .collect(Collectors.toList());

        List<Product> products = productIds.stream()
                .map(productRepository::findById)
                .collect(Collectors.toList());

        return ResponseEntity.ok(products);
    }
```

위 코드에서는 Email에 해당하는 Cart 목록을 가져온 후,
Cart에서 ProductId만 또 뽑아 리스트로 만들고
이 리스트로 Product를 찾는 작업을 수행하고 있으니
이는 컨트롤러의 역할보다 더 많은 연산작업을 하고 있는거라고 판단합니다.
이 경우에는 서비스 레이어를 만들어 작업을 분리해도 좋을 것 같아요!

2023-05-01 14:53 UTC, BackFoxx commented on src/main/java/cart/cart/controller/CartController.java
> +
이번 미션에서 서비스 레이어를 제거해버렸던 이유는 사실
@Service 어노테이션이 @Component의 다른 이름인 것 외에 사실 아무런 기능을 하지 않는다는 것을 알게 되었기 때문이었습니다.
'비즈니스 계층에서 할 일이 얼마나 많은데 왜 아무기능도 넣지 않은걸까' 라는 생각을 오랫동안 하다가,
'스프링에서 어노테이션 이름을 통해 계층형 아키텍처 방식을 유도하고는 있지만 **강제하고 있지는 않기 때문이** 아닐까? 필요에 따라 서비스 레이어를 넣을 수도 있고 생략할 수도 있고, 다양한 아키텍처 구조로 프로젝트를 만들 수 있도록 선택지를 주기 위해 일부러 기능을 비워둔 것은 아닐까' 라는 생각을 했습니다.
그래서 머릿속에 '스프링과 mvc는 별개다. 스프링을 사용한다고 해서 mvc구조로 프로젝트를 맞추어야 하는 건 아니다' 라는 생각으로 약간의 반항을 해보았어요 🥹
다음 프로젝트부터는 mvc구조를 지켜서 코딩하려 합니다. 그 모시기 최소 놀람 법칙이라고 .. 동료들이 제 코드를 보고 서비스 레이어가 왜 없냐고 기겁하게 하는 것도 좋은 개발자는 아니니까요.

2023-05-01 15:00 UTC, BackFoxx commented on src/main/java/cart/product/controller/ProductController.java
> +    @ResponseBody
[스프링 문서](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-jackson)에 따르면 ResponseEntity는 @ResponseBody가 없어도 동작하네요!
GetMapping 아래에 있는 @ResponseBody가 불필요한 거였네요 🥹

2023-05-01 15:21 UTC, BackFoxx commented on src/test/java/cart/controller/CartControllerTest.java
> +    }
json을 객체로 파싱하였더니 테스트코드가 훨씬 깔끔해졌어요! '0'
프로덕트 코드에서 dto를 사용하지 않고 Product를 그대로 넘겨주기 때문에
해당 테스트 코드에서도 따로 ProductDto를 만들지 않고 Product[]로 파싱해 테스트하였습니다 :)

2023-05-01 15:22 UTC, BackFoxx commented on src/main/java/cart/authentication/AuthenticationArgumentResolver.java
> +    private static final String BASIC_TYPE = "Basic";
다양한 인증 방식에 대해 공부하고 정리하겠습니다!

2023-05-01 15:25 UTC, BackFoxx commented on src/main/java/cart/cart/controller/CartController.java
> +import cart.cart.exception.CartPersistenceFailedException;
Reformat code로 코드를 최적화했습니다!

2023-05-01 15:31 UTC, BackFoxx commented on src/main/resources/schema.sql
> +    primary key (member_email, product_id),
이 cart를 어떻게 사용하게 될까 곰곰히 생각해 보았습니다.
Cart는 고유의 id로 조회할 일이 사실상 없이
거의 항상 findByEmail이나 findByProductId처럼 Email 또는 ProductId를 활용해 조회하게 될 것이고,
Email, ProductId 둘 중 하나라도 존재하지 않거나 유효하지 않으면 저장되지 않으며
둘 중 하나라도 데이터베이스에서 사라지면 따라서 사라져야 한다는 것을 알았습니다.

이렇게나 두 값에 깊이 종속적이라면
의미없는 auto_increment PK id를 쓰는 것보다
이 둘을 엮어서 복합키로 사용하는 것이 더 합리적일 것이라 판단했어요!

2023-05-01 15:38 UTC, BackFoxx commented on src/test/java/cart/controller/IntegrationTest.java
>  class IntegrationTest {
* IntegrationTest : 컨트롤러 뿐만 아니라 컨트롤러와 의존성을 가진 모든 세부 구현체(Repsotitory)를 테스트합니다.
* 타 컨트롤러 테스트 : 컨트롤러를 제외한 의존성을 Mockmvc로 모킹하고, 컨트롤러 고유의 기능만 테스트합니다.

적고보니 IntegrationTest가 controller 패키지에 있는 게 이상하네요! 별도의 패키지로 분리했습니다.

2023-05-01 15:38 UTC, BackFoxx commented on src/test/java/cart/controller/IntegrationTest.java
>  class IntegrationTest {
그리고 @AutoConfogureTestDatabase라는 어노테이션은 처음 보네요 👀 신기하네요 .. 기능을 공부해서 기록해 두겠습니다. 감사합니다!

2023-05-01 16:08 UTC, BackFoxx commented on src/main/java/cart/cart/entity/Cart.java
> +    private final Long productId;
'장바구니' 라는 도메인을 표현하는 도메인 객체라면 춘식의 피드백대로 객체를 설계하는 것이 훨씬 좋았을 거에요! 하지만 Member, Product, Cart가 위치한 패키지 이름을 'entity'로 지정한 것을 보면 제가 이 객체를 어떤 용도로 사용중인 지 알 수 있으실 거에요.
저에게 있어 entity는 '데이터베이스 컬럼과 1:1로 매핑되는 객체' 라는 정의를 가지고 있고, 데이터베이스의 Cart 테이블에는 Member_id와 Product_id 두 컬럼이 있으므로 객체 설계도 이를 그대로 따라갔습니다.

만약 춘식이 생각하시는 Cart를 설계하고자 한다면 저는 이를 entity 패키지에 있는 Cart 객체를 수정하지 않고, domain 패키지를 하나 만든 후 그 안에 '도메인 객체'인 Cart를 따로 만들어 사용할 것 같습니다.

2023-05-01 16:09 UTC, BackFoxx commented on src/main/java/cart/config/CommonControllerAdvice.java
> +public class CommonControllerAdvice {
네🥲

2023-05-01 16:11 UTC, BackFoxx commented on src/main/java/cart/cart/repository/JdbcCartRepository.java
> +            exception.printStackTrace();
디버깅용으로 작성한 코드가 남아있었네요! 삭제 완료했습니다 :)

2023-05-02 14:45 UTC, BackFoxx commented on src/main/java/cart/authentication/Authentication.java
> +public @interface Authentication {
'0' 그러네요. 짱!!

2023-05-02 14:49 UTC, BackFoxx commented on src/test/java/cart/controller/CartControllerTest.java
> +@WebMvcTest(CartController.class)
'0' 오늘 리뷰토론스터디에서 해당 주제로 한 2~30여분동안 힘차게 토론하는 시간을 가졌는데,
춘식의 말씀처럼 '많은 시간과 자원, 코드가 소모되는 테스트 데이터' 가 특별히 없는 현재의 프로젝트에서
테스트 데이터 생성을 분리하기 위해 sql를 쓴다거나 Object mother를 사용하는 것은 다소 불필요하다는 의견으로 합치되었습니다.
따라서 이번 프로젝트에서는 테스트마다 새로운 오브젝트를 만들어 사용하는 쪽으로 가닥을 잡았어요!

하지만 이후에 프로젝트의 복잡도가 커질 때에는
춘식의 피드백대로 fixture를 만들어 자바 코드로 데이터를 다루는 것이
재사용성이나 유지보수 측면에서 더 나은 선택일 것 같습니다. 이후의 미션에서 반영해 보겠습니다!

2023-05-02 14:54 UTC, BackFoxx commented on src/main/java/cart/product/controller/ProductController.java
>      @PostMapping("/create")
URL은 자원을 표현하고, 행위는 HTTP METHOD를 통해 표현한다. 중요한 규칙을 알려주셔서 감사합니다!

2023-05-04 13:15 UTC, bimppap commented on src/main/java/cart/cart/controller/ShoppingCartController.java
> +package cart.cart.controller;
common 패키지로 분리 잘하셨네요 👍
추가로 궁금한 점이 생겼는데, 패키지 분리 기준을 레이어에서 도메인으로 변경한 이유가 있을까요? 🙂

2023-05-04 13:36 UTC, bimppap commented on src/main/java/cart/cart/controller/CartController.java
> +
계층형 아키텍처를 강제하고 있다는 게 무슨 느낌인지는 이해가 됩니다ㅎㅎ 프로젝트 스케일이 작을 땐 과한 분리라고 느껴질 수 있을 거에요.

사실 충분히 납득된다면 아키텍처 구조를 조금 변형해도 괜찮습니다. 1단계에서 구조에 대해 얘기를 하지 않은 것도 당시 요구사항으로는 납득되는 부분이기 때문이었고요. 2단계에서는 위에 여우가 말한 컨트롤러의 'Model이 데이터를 어떻게 처리할지 알려주는 역할'을 벗어나는 코드가 있어 피드백을 드려본 겁니다.

그래도 지금은 배우는 과정이기에 이런저런 반항(?)을 시도해봐도 좋습니다ㅋㅋ 동의되지 않은 권위에 굴복하지 말라는 포비의 명언도 있으니까요 😎 (놀란 건 사실이지만 재밋었습니다ㅋㅋ)

(+) 계층별 분리가 왜 필요한지는 아래에 피드백을 좀 더 달아두겠습니다. 참고해주세요. 🙂

2023-05-04 13:37 UTC, bimppap commented on src/test/java/cart/controller/CartControllerTest.java
> +@WebMvcTest(CartController.class)
오 리뷰토론스터디가 있군요! 재밋을 거 같네요ㅎㅎ 화이팅입니다!

2023-05-04 15:19 UTC, bimppap commented on src/main/java/cart/cart/entity/Cart.java
> +    private final Long productId;
엔티티도 엄연히 따지면 도메인 영역에 속하며 더 크게 보면 자바에서 쓰이는 하나의 객체입니다. 객체를 테이블에 맞추게 되면 객체지향적인 모델링보다는 데이터베이스 중심 모델링이 더 맞는 모양새가 됩니다. 🤔 이 부분에 대해선 한 번 더 고민해보면 좋을 것 같아요! (개인적으로 엔티티를 객체지향적인 모델링으로 시도를 해본 후 JPA를 공부하게 된다면 JPA의 이점이나 특성이 잘 와닿을거라고 생각합니다 🙂)

2023-05-04 15:48 UTC, bimppap commented on src/main/resources/schema.sql
> +    primary key (member_email, product_id),
반은 맞고 반은 틀렸네요ㅎㅎ 🤓

대표 id pk를 사용하면 조회는 빠르지만 인덱스 추가로 인해 데이터의 저장/변경/삭제에 대한 비용이 발생할 수 있습니다. 그러니 고유 id로 조회할 일이 없으면 사용하지 않는 것이 맞습니다. 👍

두 값이 cascade한 것은 복합키가 적합하다는 것과 상관관계가 없습니다. 복합키든 아니든 cascade는 걸 수 있으니까요.

여기서 복합키를 쓰는 게 적합한 이유는 현재 email과 productId를 통해 조회를 하는데, 두 칼럼에 복합키를 걸면 PK 인덱스를 타게 되어 쿼리 성능이 개선될 수 있기 때문입니다. (물론 카디널리티와 복합키 순서까지 고려해야 가시적인 개선이 될 겁니다🙂)

대표 id pk와 복합키를 사용하는 더 자세한 기준은 직접 찾아보고 정리해보면 좋겠습니다!

2023-05-05 03:07 UTC, bimppap approved these changes
안녕하세요 여우, 춘식입니다.
리팩토링 잘 해주셨습니다 👍같이 얘기 나누면서 저도 공부가 된 것 같네요ㅎㅎ
이번 단계는 여기서 어푸르브 하겠습니다.
추가적으로 단 코멘트들이 있으니 확인 부탁드립니다.
궁금하거나 이해가 안 되는 부분은 편하게 DM 주세요. 수고 많으셨습니다!

2023-05-05 03:07 UTC, bimppap commented on src/main/java/cart/authentication/controller/MemberController.java
> +        model.addAttribute("members", memberRepository.findAll());
지금은 요구사항 때문에 괜찮지만 실무에서 member 와 같은 객체를 그대로 반환하면 중요 정보가 노출될 수 있습니다. 이 때 dto를 사용하면 원하는 필드만 넘겨줄 수 있어 보안성이 강화됩니다.

2023-05-05 03:07 UTC, bimppap commented on src/main/java/cart/authentication/AuthenticationArgumentResolver.java
> +
이건 메서드 분리가 가능할 것 같네요!

2023-05-05 03:07 UTC, bimppap commented on src/main/java/cart/authentication/AuthenticationArgumentResolver.java
> +
나중에 여러 인증 수단이 생기면 abstrctArgumentResolver가 생길 수도 있습니다. 그 때 이런 파싱하는 부분은 인증 방식마다 다를 수 있어서 메서드로 분리시키면 추상화시킬 수 있을 겁니다.

2023-05-05 03:07 UTC, bimppap commented on src/main/resources/schema.sql
> +create table if not exists product
테이블에 created_at, updated_at 와 같은 audit을 넣으면 더 좋습니다ㅎㅎ

2023-05-05 03:07 UTC, bimppap commented on src/test/resources/truncate.sql
> +SET
이건 이제 사용하지 않으니 삭제해도 되겠네요ㅎㅎ

2023-05-05 03:07 UTC, bimppap commented on src/main/resources/static/js/cart.js
> +        url: '/carts',
콘솔로 에러를 찍으면 클라이언트는 무슨 에러가 나는지 확인할 수 없겠네요 🥲

2023-05-05 03:10 UTC, merged

2023-05-05 03:11 UTC, bimppap commented
추가로, 다음 미션까지 시간이 남은 만큼 포크 딴 개인 레포에서 리팩토링 작업을 좀 더 진행해도 될 것 같습니다 🙂
만약 할 예정이라면 DM 주세요. 따로 더 봐드리겠습니다ㅎㅎ

그리고 [이 부분](https://github.com/woowacourse/jwp-shopping-cart/pull/267#discussion_r1184999804) 제가 많이 궁금해서요. 머지됐어도 답은 꼭 해주세요! ^ㅡ^

2023-05-06 01:32 UTC, BackFoxx commented on src/main/java/cart/cart/entity/Cart.java
> +    private final Long productId;
감사합니다!

2023-05-06 01:35 UTC, BackFoxx commented on src/main/resources/schema.sql
> +    primary key (member_email, product_id),
인덱스에 대한 지식이 부족해 거기까지는 생각해보지 못했는데, 덕분에 추가로 공부할 키워드를 알아가게 되었어요!
* 인덱스
* 대표 id pk와 복합키를 사용하는 기준
이 두개를 더 깊이 공부해 보겠습니다. 감사합니다!

2023-05-06 01:36 UTC, BackFoxx commented on src/main/java/cart/cart/controller/CartController.java
> +
이해해주셔서 감사합니다!

2023-05-06 01:44 UTC, BackFoxx commented on src/main/java/cart/cart/controller/ShoppingCartController.java
> +package cart.cart.controller;
크게 복잡한 생각을 하고 설계를 변경한 것은 아닙니다!
컨트롤러나 리포지토리의 개수가 많아지다보니, 이것을 도메인별로 분리하면 
나중에 특정 도메인과 관련된 클래스를 찾기 편하겠구나 하는 마음으로 도메인 별로 묶어보았어요.

이와 관련해 리뷰토론스터디에서 이야기를 나눈 적이 있는데,
'회원정보 뷰 페이지를 보여주는 컨트롤러가 있다. 그런데 페이지가 필요로 하는 데이터는 MemberRepository, CartRepository, ProductRepository 모두로부터 가져와야 한다. 그렇다면 이 컨트롤러는 member, car, product 패키지 중 어디에 속해야 하는가?'
라는 이야기가 나왔고, 이 때 도메인 별로 패키지를 분리하는 것의 한계점을 느꼈습니다.

그래서 패키지를 레이어 별로 나누는 것과 도메인 별로 나누는 것 중 어떤 선택을 해야 할지 아직 헷갈립니다!