[2단계 - 상품 관리 기능] 져니(이지원) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #270
Opened 2023-05-01 11:26 UTC by Cl8D

안녕하세요, 코다! 🙇‍♀️
지난 1단계 미션 때 빠르게 피드백 해주셔서 2단계도 금방 진행할 수 있었어요. 감사드려요!
개인적인 욕심으로 여러 가지 기능을 더 구현하고 싶기는 했는데, 먼저 미션 요구사항에 집중하여 피드백을 한 번 받은 다음 추가적으로 더 구현하면 좋을 것 같아서 이렇게 먼저 PR을 날려요 ㅎㅎ 
시간이 되면 아마 더 이것저것 추가해볼 것 같아요. 재밌었어요 😊

개인적으로 미션을 진행하면서 도메인 - 엔티티의 모호한 경계를 계속해서 고민을 했었는데... 사실 아직까지 명확한 해답을 쉽게 내리지 못했어요 🥲 그래서 이와 관련해서 질문을 하나 드리고 싶어요. 

---

### ✔️ CartDao에 관해서
지난 번 피드백을 받으면서 도메인은 비즈니스 문제를 해결하기 위한 단위, 그리고 application layer와 조금 더 밀접한 연관을 가지고 있는 객체라고 생각했어요. 반대로 엔티티의 경우 DB와 더 관련이 있는, persistence layer와 조금 더 밀접한 연관을 가지고 있는 객체라고 생각했구요! 
2단계로 들어오면서 미션 요구사항 중 하나가 '`사용자의 장바구니 목록을 조회`'하는 것이 추가되었어요. 
그러다 보니 장바구니 정보를 담은 Cart, 사용자 정보를 담은 Member, 상품 정보를 담은 Product 3가지가 엮여있는 상황이 발생하게 되었어요. 

처음에는 각 dao들이 할 수 있는 일들을 명확하게 하기 위해서 다음과 같이 설계하였었어요.
```
1. 멤버 조회 
2. 해당 멤버의 장바구니 정보 조회 - 해당 사용자의 cart 정보 전부 조회
3. cart 정보에 담긴 productId를 바탕으로 상품 리스트 조회
```
하지만 이러다 보니까 오히려 비즈니스 로직으로서 처리해야 하는 일들이 더 많아지고, 불필요하게 쿼리가 3번 날라가야 한다는 생각이 들었어요. 그래서 **join을 사용**하였는데... join 쿼리의 주 테이블이 cart이다 보니까 cartDao에서 이와 같은 처리를 진행하였어요. 이때, 반환하는 정보들은 'MemberCartEntity'라는 이름의 객체가 정보를 담도록 했구요. (테이블의 정보를 담는 객체이기 때문에 entity에 더 가깝다는 생각이 들었어요.)

Dao의 경우 DB 테이블과 매핑되는 계층이다 보니 두 개의 dao를 엮은 `MemberCartRepository`를 생성하였어요. 
(개인적으로 dao는 db와 1:1로 연관되는 부분이고, repository는 이를 엮어서 비즈니스 로직을 해결하기 위한 조금 더 상위 레이어라고 생각했습니다!) 그래서 cartDao와 memberDao를 가지고 정보를 조회하여 조합하거나, 혹은 삽입하거나 하는 일들을 담당하도록 만들었어요. MemberCartEntity의 경우 두 테이블을 조합한 정보를 가지고 있으면서도, 사실 **문제를 해결하기 위한 '도메인'으로서의 역할**도 충분히 할 수 있다는 생각이 들어서 별도의 도메인 객체를 생성하지 않고 바로 Dto로 변환하여 controller에 반환하는 형식으로 만들었는데... 이러다 보니까 가장 처음에 정의했던 '엔티티와 도메인의 차이점'이 모호해지기 시작하더라구요.
-> 사실 여기서 CartDao가 MemberCartEntity에 대해 알기 시작하는 부분부터 뭔가 SRP 위반인 건 아닐까...? 라는 생각도 들었습니다 🥲 Repository를 만들지 않고 그냥 Service에서 바로 참조하도록 할 걸 그랬나 싶기도 하구요. (이 부분에 대해서도 코다의 의견이 궁금하네요 ㅠ_ㅠ)

물론 저는 '*엔티티는 도메인으로서도 역할을 할 수 있다, 다만 이는 정보를 가공하지 않고 그대로 전달하는, 정보 전달에 가까운 객체일 경우 가능하다*'라는 결론을 내려서 위와 같은 구조를 채택하기는 했는데, 혹시 이에 대해 코다는 어떻게 생각하는지 궁금해요!

이번 리뷰도 잘 부탁드립니다~
항상 감사드려요 🙇‍♀️ 좋은 하루 되세요!

2023-05-02 11:16 UTC, Cl8D commented on src/main/resources/static/js/header.js
> +// 그래서 임시적으로 인터셉터에서 관리자 메인 페이지 (상품 목록 조회)는 통과하지 않도록 만들어두기는 했어요...!
CSR에 익숙하지 않아서 이런 상황에 대해서 어떻게 처리해야 할지 감이 잘 안 오네요… 🥲 Interceptor를 연속으로 2번 타는 상황이 발생하는데, 제가 생각한 이유가 맞는지, 그리고 괜찮다면 어떻게 이런 상황을 해결할 수 있을지 솔루션을 부탁드려도 괜찮을까요…? ㅠ_ㅠ

2023-05-02 11:20 UTC, Cl8D commented on src/main/java/cart/common/auth/AdminAuthInterceptor.java
> +
인터셉터를 처음 사용해봐서 다소 구조가 어색하게 느껴졌습니다! ㅠ_ㅠ
인터셉터가 특정 서비스에 의존해도 괜찮은 형태인 건지, 그리고 특정 서비스에 의존하다 보니 스프링 컨테이너에 의해 관리되는 빈을 가져오고 싶어서 인터셉터를 빈으로 등록했는데, 괜찮을까요?!

2023-05-02 11:27 UTC, Cl8D commented on src/main/java/cart/common/config/WebMvcConfig.java
> +
지금 같은 상황에서는 리졸버도, 인터셉터도 개수가 1개씩이라 괜찮겠지만… 만약 리졸버나 인터셉터 개수가 증가하게 된다면 여기서 선언해야 하는 필드가 엄청 증가할 것 같아요. (물론 명시적으로 new로 선언하더라도 빈이라면 스프링 컨테이너에서 관리되는 싱글턴 객체가 반환될 것 같기는 하지만요…!) 학습 테스트에서는 리졸버나 인터셉터를 빈으로 등록하지 않고 여기서 매번 new로 선언하는 형태던데, 보통 어떤 식으로 사용하나요?

2023-05-02 11:29 UTC, Cl8D commented on src/main/java/cart/controller/MemberController.java
> +    }
미션 요구사항의 URI가 setting이다 보니까 여기다 뺐는데, 별도의 컨트롤러 (SettingController)를 두는 게 나을까요? 근데 내부에서 memberService를 의존하다 보니까 memberController가 더 어울리는 구조가 아닐까…라는 생각이 들었습니다 🥲

2023-05-02 11:30 UTC, Cl8D commented
안녕하세요, 코다! 
오늘 수업을 듣고 인터셉터 적용을 해보고 싶어서 admin에 대해서는 인터셉터를 적용해봤는데, 구조가 뭔가 어색하네요 🥹
피드백은 늘 환영입니다...! 
다시 한 번 잘 부탁드려요!!

2023-05-03 18:00 UTC, yjksw requested changes
안녕하세요 져니 🙇‍♀️ 코다 입니다. 

리뷰가 늦어서 죄송합니다 ! 
2단계 정말 즐기면서 미션 수행 잘 해주신 것 같아요 👍

질문 주신 부분에 대해서 리뷰에 언급한 것도 있고 
별도 코멘트로 답변드리려는 부분도 있습니다. 

혹시 추가 질문이 있다면 언제나 댓글이나 DM 주세요 🙌

2023-05-03 18:00 UTC, yjksw commented on src/docs/asciidoc/admin.adoc
> +
docs까지 💯

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/common/auth/AdminAuthInterceptor.java
> +
아하 ! 
저는 큰 문제는 없어보이는데 혹시 우려되는 부분이 따로 있으셨나요 ?

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/common/auth/AdminAuthInterceptor.java
> +        }
email만 인증에 사용되고 있는 것 같은데 맞을까요 ? 
password도 검증하면 어떨까요 ? ㅎㅎ

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/common/config/WebMvcConfig.java
> +
져니가 말씀해주신 두 방법을 모두 사용하는 것 같아요 ~! 
말씀해주신대로 리졸버와 인터셉터 개수가 매우 많아지는 문제가 발생합니다 ㅠㅠ 
이때 디자인 패턴 등을 활용해서 코드를 조금 더 간결하게 만들기도 하구요 ㅎㅎ 
실무에서는 스프링에서 제공해주는 기능을 사용하여 이렇게 직접 인터셉터를 등록하는 일이 드문 것 같아요 !

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/AdminRestController.java
> +@RequestMapping("/admin")
`@Controller`, `@RestController` 나누니까 훨씬 보기 편하군여 ! 👍

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/CartRestController.java
> +    @DeleteMapping("/{targetMemberId}/{productId}")
현재 사용자가 자신의 장바구니가 아닌 다른 사람의 장바구니도 열람할 수 있나요 ? 
그렇다면 지금 구현하신 것처럼 targetMemberId로 방어로직을 작성하는게 맞을텐데요,
그렇지 않으면 요 pathVariable은 불필요하지 않을까 싶네요 ~

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/MemberController.java
> +    }
저도 이대로 보기 좋은 것 같습니다 ㅎㅎ
꼭 URI 명칭따라 컨트롤러가 생성될 필요는 없는 것 같아요 !
져니가 보기에 추후 유지보수 할 때 이 기능을 어떤 컨트롤러에서 찾을지 고민해보고 그것에 맞게 구현해주신 것 같아 좋은 것 같습니다

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/dto/CartDto.java
> +public class CartDto {
이 dto의 위치가 controller 패키지 내부에 있게 되므로서 
service -> controller -> service로 이루어진 순환참조가 형성된 것 같아요 😊

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/dto/CartResponse.java
> +public class CartResponse {
이 Response로 한번 더 감싼 이유가 무엇인가요 ? 🤔

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/dto/MemberDto.java
> +public class MemberDto {
이 dto도 위 CartDto와 마찬가지네요 ! 
의존방향은 단방향으로 정리해보면 좋을 것 같아요 ㅎㅎ

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/controller/dto/MemberDto.java
> +    @Pattern(regexp = "010-\\d{4}-\\d{4}", message = "올바른 전화번호 형식을 입력해 주세요.")
크 정규표현식도 잘 쓰시는군여 ! 👍

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/domain/Member.java
> +    public Member(final String email, final MemberPassword password, final String nickname,
```suggestion
    private Member(final String email, final MemberPassword password, final String nickname,
```

팩토리 메서드가 있으니 생성자는 private으로 닫을 수 있겠군요 ㅎㅎ 다른 곳은 잘 해주셨네요

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/domain/Member.java
> +            throw new GlobalException(MEMBER_EMAIL_LENGTH);
개인적인 의견 코멘트 드립니다 ㅎㅎ 
java에서 제공하는 많은 exception들 (IllegalArgument, IllegalState 등등) 대신 GlobalException을 사용했을 때 얻어지는 이점이 다소 적은 것 같아요. 

우선 java 제공 exception은 많은 개발자들이 이미 인지하고 있는 것이기 때문에 클래스만 보더라도 어떤 맥락에서 발생한 예외인지 유추할 수 있어요. 또한 상황에 따라서 다른 클래스 excpetion을 던질 수 있고, 현재 errorCode로 넣고 있는 메시지를 넣을 수도 있습니다 ㅎㅎ 

반면 GlobalException은 커스텀 예외이기 때문에 한번 더 들어가서 어떤 예외인지 확인해야하는 번거로움이 있을 것 같은데 
져니 생각은 어떤가요 ?

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(errorResponse, HttpStatus.BAD_REQUEST);
```suggestion
        return ResponseEntity.badRequest().body(errorResponse);
```

이런 형태의 가독성은 어떤가요 ? ㅎㅎ

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/persistence/repository/MemberCartRepository.java
> +public class MemberCartRepository {
질문 주신 클래스군요 ! 
따로 코멘트에서 언급하겠습니다 😊

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/service/MemberService.java
> +    public long save(final MemberDto memberDto) {
```suggestion
    @Transactional
    public long save(final MemberDto memberDto) {
```

`@Transactional(readOnly=true)` 빠르게 잘 학습하셨네요 👍

2023-05-03 18:00 UTC, yjksw commented on src/main/java/cart/service/ProductService.java
>      }
여기도 `@Transactional` 필요하겠군요 ㅎㅎ

2023-05-03 18:00 UTC, yjksw commented on src/main/resources/static/js/header.js
> +// 그래서 임시적으로 인터셉터에서 관리자 메인 페이지 (상품 목록 조회)는 통과하지 않도록 만들어두기는 했어요...!
아하 ! 이 부분은 져니가 말씀해주신대로, 
axios 요청 후 `then((response) => { window.location.href = '/admin';}`  으로 페이지를 다시 로딩하는데
해당 요청에는 auth가 없어서 그렇습니다 ㅠㅠ

타임리프의 한계라고 봐야하지 않나 싶네요 ! 혹시 좋은 방법을 찾으면 공유드릴게요

2023-05-03 18:00 UTC, yjksw commented on src/test/java/cart/common/auth/BasicTokenProviderTest.java
> +class BasicTokenProviderTest {
테스트가 다양한 케이스로 정말 다양하군요 ㅎㅎ

2023-05-03 18:00 UTC, yjksw commented on src/test/java/cart/controller/MemberControllerTest.java
> +            "test1234", "코다", "010-4321-8765");
☺️

2023-05-03 18:00 UTC, yjksw commented
져니 남겨주신 질문에 대한 코멘트 추가하도록 하겠습니다 🙏

2023-05-04 02:27 UTC, Cl8D commented on src/main/resources/static/js/header.js
> +// 그래서 임시적으로 인터셉터에서 관리자 메인 페이지 (상품 목록 조회)는 통과하지 않도록 만들어두기는 했어요...!
아하... 기술적 한계군요 🥲
감사합니다!!

2023-05-04 02:28 UTC, Cl8D commented on src/main/java/cart/common/auth/AdminAuthInterceptor.java
> +
앗 그건 아니구, 학습 테스트에서는 빈으로 등록하는 과정이 없길래 원래 안 붙이는 건가... 라고 생각했어요!! ㅎ_ㅎ

2023-05-04 02:31 UTC, Cl8D commented on src/main/java/cart/common/config/WebMvcConfig.java
> +
아하! 스프링에서 제공해주는 기능이라면 약간... 스프링 시큐리티 같은 것을 사용하다 보니까 직접 등록하는 일이 적은 걸까요 ?_?
디자인 패턴이라면 어떤 패턴을 사용할 수 있을까요?! 제가 디자인 패턴 쪽은 잘 모르는데, 리졸버를 등록하는 별도의 객체를 만드는 의미일까요?

2023-05-04 02:35 UTC, Cl8D commented on src/main/java/cart/controller/MemberController.java
> +    }
감사합니다!
위의 답변과 상관없이 개인적으로 궁금한 것이 있는데, 코다는 패키지 구조를 계층형 vs 도메인형 중 어떤 것을 선호하시나요? [관련 레퍼런스](https://velog.io/@sunil1369/Spring-boot-%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B5%AC%EC%A1%B0)
현재 패키지 구조는 계층형이긴 한데, 도메인형도 실제로 많이 사용하는지 궁금합니다! (코다는 어떤 걸 더 선호하시는지 궁금하네용)

2023-05-04 02:39 UTC, Cl8D commented on src/main/java/cart/common/auth/AdminAuthInterceptor.java
> +        }
앗 그 생각을 못했네요!!!!
비밀번호도 함께 넣어서 검증하도록 하겠습니다!

2023-05-04 03:06 UTC, yjksw commented on src/main/java/cart/common/config/WebMvcConfig.java
> +
넵 져니 말씀대로 스프링 시큐리티를 사용해서 그렇습니다 ! 
다양한 디자인 패턴이 있을 수 있을 것 같아서 만들어내기 나름일 것 같아요 ㅎㅎ (정답이 있는 것은 아닙니다) 
지금 단계에서 반드시 구현해야하는 것은 아니고, 참고차 말씀드려요.
비슷한 상황에서 팀원이 데코레이터 패턴 사용하는 것을 본 적은 있습니다 😊

2023-05-04 04:40 UTC, Cl8D commented on src/main/java/cart/controller/CartRestController.java
> +    @DeleteMapping("/{targetMemberId}/{productId}")
생각해보면 현재 @MemberEmail 어노테이션을 통해서 인증된 사용자인지 검증하고, 해당 어노테이션에 있는 인증 정보를 바탕으로 장바구니를 조회하고 있기 때문에 방어로직이 필요없을 것 같네요! 😮 수정해두겠습니다!!

2023-05-04 04:55 UTC, Cl8D commented on src/main/java/cart/controller/dto/CartDto.java
> +public class CartDto {
앗 그러네요!!!... 단방향으로 데이터가 흘러야 하는데 이를 고려하지 못한 것 같아요 🥲
controller 대신에 service 패키지 쪽에 위치하도록 수정하겠습니다!

2023-05-04 04:59 UTC, Cl8D commented on src/main/java/cart/controller/dto/CartResponse.java
> +public class CartResponse {
```java
 @GetMapping("/me")
  public ResponseEntity<CartResponse> getCartByMember(@MemberEmail String memberEmail) {
      final List<CartDto> cartDtos = cartService.getProductsByMemberEmail(memberEmail);
      final CartResponse cartResponse = new CartResponse(cartDtos);
      return ResponseEntity.ok().body(cartResponse);
  }
```
뭔가 여기서 ResponseEntity<List<CartDto>>로 반환하는 것보다, 리스트에 대해 감싸서 반환하는 것이 다른 협업자가 봤을 때 더 이해하기 쉬울 것 같다고 생각했고, 만약 장바구니 정보를 반환할 때 나중에 상품 정보만 반환하는 게 아니라 별도의 정보 (음... 결제 정보 같은?)를 반환하게 된다면 하나의 객체로 담아서 반환하는 게 더 좋지 않을까 생각했습니다! (말하고 나니 좀 불필요한 래핑인 것 같다는 생각이 드네요 🥲)
근데 CartDto라는 이름 자체가 내부적으로 상품 정보만 담고 있다 보니까 네이밍이 잘못되었다는 생각이 들어서, 기존의 CartDto는 ProductDto로 수정하려고 합니다! 래핑에 대해서는 어떻게 생각하시나요 ?_?

2023-05-04 05:58 UTC, Cl8D commented on src/main/java/cart/domain/Member.java
> +            throw new GlobalException(MEMBER_EMAIL_LENGTH);
그렇게 생각하면 어떤 예외인지 알아보기 힘들 것 같기는 해요...!
하지만, 현재는 예외를 던질 때 내부 인자로 항상 예외가 어떤 오류인지 메시지를 나타내는 ErrorCode enum 값을 함께 전해주기 때문에 그런 점이 조금 해소되지 않을까? 생각했어요. throw를 통해 예외를 던지는 행위 + 내부 인자로 나타난 에러 코드 = 해당 에러 코드와 관련된 에러가 발생하지 않을까? 라고 쉽게 이해할 수 있을 거라고 생각했습니다!

물론 IllegalArgumentException 등을 사용할 수 있지만, 내부로 string message를 건네게 된다면 결국 도메인에서 뷰의 메시지를 의존하는 형태가 나타날 것 같아서 (레벨 1, 2 때 이 부분에 대해 피드백을 많이 받았어서 더 고민하게 되는 것 같아요 🥲) enum을 참조하는 것으로 합의를 본 상태입니다...! 어떻게 생각하시나요?!

2023-05-06 06:36 UTC, yjksw approved these changes
안녕하세요 져니 ~! 코다 입니다 🙇‍♀️

피드백을 모두 꼼꼼하게 잘 반영해주셨어요 👍
하나하나 깊이 고민하시며 미션하신 것 같아서 저도 리뷰하는데 즐거웠습니다 ㅎㅎ

마지막 PR은 코멘트 할 것이 많이 없군요 ! 
몇가지 코멘트 남겼는데 확인 부탁드려요.  
머지 되더라도 추가 논의하고 싶은 것 있으면 DM 주세요 🙌

2023-05-06 06:36 UTC, yjksw commented on src/main/java/cart/service/MemberService.java
> +            .orElseThrow(() -> new GlobalException(ErrorCode.MEMBER_NOT_FOUND));
지금은 로그인 하는 형태가 아니니 문제가 없겠지만,
비밀번호만 틀렸을 경우에 `MEMBER_NOT_FOUND` 면 조금 어색할 수 있겠군요 ! 
참고차 코멘트 드립니다 ㅎㅎ

2023-05-06 06:36 UTC, yjksw commented on src/main/java/cart/service/CartService.java
> +    private Cart convertToCart(final MemberEntity memberEntity, final List<CartDto> cartDtos) {
convert용 메서드가 많아지니 mapperClass를 둬도 좋겠네요 😊

2023-05-06 06:36 UTC, yjksw commented on src/main/java/cart/service/CartService.java
> +    }
고민을 많이 했던 로직이군요.

```
service -> persistence
service -> domain 
```

이렇게 유지하기 위해서 보일러플레이트 코드 (dto, entity 등등)이 많아져서 구현하시면서도 힘드셨을 것 같아요 ! 
막상 domain은 하는 일 없이 bypass 되고 있구요 

요 이상한 구조를 해결하기 위한 방법들이 있는데, 지금 했던 고민들을 기억하시며 앞으로 더 알아가면 좋을 것 같네요 👍
(키워드는 DIP 입니다)

2023-05-06 06:37 UTC, yjksw commented on src/main/java/cart/controller/dto/CartResponse.java
> +public class CartResponse {
현재는 리스트를 그대로 반환해도 될 것 같다는 생각이 저도 드네요 ㅎㅎ
나중에 추가 반환 데이터가 생기면 그때 래핑해도 될 듯 해요 !
네이밍은 좋다고 생각합니다 😊

2023-05-06 06:40 UTC, yjksw commented on src/main/java/cart/domain/Member.java
> +            throw new GlobalException(MEMBER_EMAIL_LENGTH);
아하 그렇군요 ! 
져니가 해주신 말씀 이해가 잘 됩니다ㅎㅎ

> 내부로 string message를 건네게 된다면 결국 도메인에서 뷰의 메시지를 의존하는 형태가 나타날 것 같아서

이 부분에 대한 개인적인 생각은 예외에 대한 대상이 하나 이상일 수 있을 것 같아요 ! 
1. 개발자 
2. 클라이언트

지금은 져니가 2번을 생각하셔서 도메인이 뷰의 메시지를 의존하는 형태라고 보일 수 있을 것 같아요. (맞는 말씀입니다 ㅎㅎ) 
반대로, 위 예외를 개발자 대상을 둬서 예외에 대한 자세한 내용을 로깅하고, 예외에 대한 클라이언트 메시지는 뷰에서 추상화하여 노출하도록 하는 방법도 있습니다.

2023-05-06 06:41 UTC, merged

2023-05-06 06:43 UTC, yjksw commented on src/main/java/cart/controller/MemberController.java
> +    }
저두 계층형을 주로 선호하는 것 같아요 ! 

도메인을 기준으로 나누는 방법을 초반에 사용해보려고 했는데, 
생각보다 도메인이 서로 완전히 격리되지 않더라구요 ㅎㅎ

2023-05-06 14:42 UTC, Cl8D commented on src/main/java/cart/service/MemberService.java
> +            .orElseThrow(() -> new GlobalException(ErrorCode.MEMBER_NOT_FOUND));
오오 리팩터링 해야겠어요! 감사합니다 ㅎ_ㅎ