[2단계 - 장바구니 기능] 두둠(최영훈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #284
Opened 2023-05-03 08:42 UTC by younghoondoodoom

안녕하세요 코다! 백엔드 크루 두둠입니다. 좋은 리뷰 부탁드립니다🙇‍♂️
이번 미션에서는 효율적인 패키지 구조와 Spring의 다양한 기능을 이용해 책임 분리를 하는 것에 집중 했습니다!

## Questions
1. 데이터베이스부터 Controller까지 테스트가 필요하다고 생각되는 모든 부분에 단위 테스트를 진행 했습니다. 그래서 굳이 통합 테스트를 작성해야하는가 의문이 듭니다. 잘 동작하는지는 로컬에서 실행해보면 되고, 나머지 부분은 단위 테스트가 작성 되어있는데 통합 테스트를 작성해야할까요? 만약에 그렇게 생각하신다면 코다의 생각이 궁금합니다.
2. controller 구분 기준?
controller를 구분하는데 어떻게 해야 가독성이 좋을지 모르겠습니다. 코다의 Controller를 나누는 기준이 어떻게 되나요? 코다의 인사이트로 힌트를 얻고싶습니다!
3. 현재 인증을 진행할 때, interceptor를 활용하고 있습니다. 이 역할을 interceptor에서 하는게 좋을지, filter에서 하는게 좋을지 모르겠습니다. 구분 기준이 있으신가요?
4. 현재 장바구니에 담을 때, db에 논리적으로 중복되는 데이터가 있는지 확인하고 있다면 예외를 던지도록 하고 있습니다. 즉, 비즈니스 계층에서 dao에 데이터가 있는지 확인하는 과정이 들어가는데, 그냥 dao에서 insert를 할 때 중복이 있다면 예외를 던지던 메세지를 주던 하는게 나을까요? db에 논리적으로 중복된 데이터가 허용되지 않는다는 요구사항이 비지니스 레이어의 책임인지, DataAccess 레이어의 책임인지 잘 모르겠습니다.

많이 성장할 수 있는 리뷰 부탁드립니다!

2023-05-04 06:06 UTC, younghoondoodoom commented
안녕하세요 코다🙌 주신 질문에 대한 답변은 여기에다가 남기겠습니다! 좋은 키워드 던져주셔서 감사합니다👍
### 1. 200 ok vs 204 no content
DELETE 메소드 실행 후 204를 내려준다는 의미는 해당 데이터를 영구적으로 삭제했다라는 의미에 비슷한 것 같습니다. 앞으로 해당 데이터는 어떤 식으로든 제공하지 못한다라는 의미에 가까운 것 같습니다. 그에 반해 200을 내려주는 의미는 해당 데이터를 영구적으로 삭제하지 않았고, 상태가 바뀌었다는 것을 표현할 수 있을 것 같습니다. 
https://www.linkedin.com/pulse/delete-rest-200-204-response-code-abhijit-mazumder

### 2. 비즈니스 유효성 검사도 dto에서 검사하는 것이 맞을지?
dto에서는 요청과 관련된 유효성 검사를 하는게 맞을 것 같네요! 비즈니스 유효성 검사는 객체를 생성할 때가 맞는 것 같습니다.

### 3. @Transactional 키워드에 대해서 공부하고 적용할 수 있는 곳에 적용해보면 어떨까요?
놓치고 있었네요. 적용했습니다!

### 4. entity vs. 도메인 차이?
Entity는 DB의 테이블과 매칭 되는 객체이고, 도메인은 비즈니스 로직의 책임을 가지는 객체라고 생각합니다. 즉, Entity는 DB의 데이터를 객체 세상으로 가져오려고 사용하는 객체인 것 같습니다. 이 둘을 분리하여 만드려고 하다가 도메인 객체의 역할이 많이 없고, Entity 역할도 같이 해도 되겠다고 생각이 들어서 굳이 구분하지 않았습니다!

### 5. DAO vs Repository
DAO는 단순히 DB에 접근하여 쿼리를 날려서 데이터를 가져오는 계층이고, Repository는 받아온 데이터를 객체로 만들고, 객체를 DAO가 사용하기 쉬운 형태로 만드는 계층이라고 생각했습니다. 처음에 Repository를 만든 의도는 DAO가 데이터를 가져오는 역할만 하고 Repository에서 객체로 매핑할 목적으로 만들었습니다만 하다보니 굳이 Repository가 없어도 될 것 같아서 삭제했습니다!

2023-05-04 17:07 UTC, yjksw requested changes
안녕하세요 두둠 ~! 코다 입니다 🙇‍♀️

2단계 빠르게 잘 구현해주셨어요 ㅎㅎ
드렸던 질문에 대한 답변도 잘 확인했습니다. 

몇가지 코멘트 남겼으니 확인해주세요 🙌

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/config/WebConfig.java
> +            .addPathPatterns("/cart");
저는 `장바구니` 페이지 진입 시 이 인터셉터로 인해서 500에러가 발생하던데 
혹시 두둠은 잘 실행되시나요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/controller/CartController.java
> +    @PostMapping("")
빈 string을 모두 넣어주신 이유가 있나요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/controller/MainController.java
>  public class MainController {
View와 관련된 것과 다른 RestController를 나누니까 좋네요 👍
이름이 MainController보다 더 자세한 것이면 어떨까요 ? (예를 들어, ViewController와 같이요) 
지금은 요 네이밍으로 이 컨트롤러가 무슨 책임을 가진 클래스인지 유추하기 좀 어려운 것 같아요 !

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/controller/MemberController.java
> +        return ResponseEntity.created(URI.create("/")).body(response);
여기서 반환하는 URI는 생성된 자원에 대한 위치랍니다 😊
지금은 / 로 가서 생성된 자원과 관련된 위치는 아닌 것 같아요

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/controller/CartController.java
> +    }
질문에 대한 답변을 해주신 경우군요 ㅎㅎ
잘 학습해 주셨어요 !

HTTP Status 관련해서 주로 MDN 문서를 참고하는데요, 
[200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) vs. [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)
200 보면 POST 요청에 대한 응답 결과를 body에 첨부하여 보내줄 때 주로 사용한다고 되어 있어요. 
지금도 크게 잘못되지는 않았지만, POST요청에 대해서도 `noContent()` 응답을 하기도 해서 말씀드려요.

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/auth/service/AuthService.java
> +        if (!member.getPassword().equals(memberInformation.getPassword())) {
member에게 메시지 요청을 보내도 좋겠군요 !

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/auth/service/AuthorizationExtractor.java
> +    public MemberInformation extract(final String header) {
여기 개행도 다른 파일과 맞추면 좋을 것 같아요 😊

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/cart/dao/CartDao.java
> +@Component
`@Repository`가 아닌 `@Component` 로 두신 이유가 있으신가요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/cart/service/CartService.java
> +public class CartService {
Service를 domain 패키지 하위에 두셨군요 ㅎㅎ 
그렇게 하신 이유가 무엇인가요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/member/dao/MemberDao.java
> +    public Member save(final Member member) {
전체적으로 일관성 있는 개행을 하면 더 좋답니다 🙌

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/member/dao/MemberDao.java
> +public class MemberDao {
요것도 domain 패키지 하위에 있는 이유가 무엇인지 궁금해요 !

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/member/service/MemberService.java
> +        madeMember.setPassword(passwordEncoder.encode(madeMember.getPassword()));
요 부분에서 password만 final 선언하지 않고, 
Member에 row한 password를 지정한 뒤, 다시 인코딩해서 set하는 구조가 복잡한 것 같아요 ! 

애초에 인코딩 된 비밀번호를 넘겨 완전한 Member객체를 생성하면 어떨까요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/domain/member/service/PasswordEncoder.java
> +public class PasswordEncoder {
꼭 컴포넌트로 등록해야하는 객체일까요 ? 
스프링에 의존하는 객체는 꼭 필요한 경우가 아니라면 사용하지 않는 것이 좋답니다 😊

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/dto/CartCreateRequest.java
> +package cart.dto;
현재 요 dto 패키지가 마치 조커처럼 모든 의존관계를 가로지르고 있어요 ! 
`controller -> domian(service)` 간 단방향 의존방향을 유지하는 것이 좋은데, 
이 dto 패키지로 의존관계나 레이어간 격리가 깨지는 듯 보여서 고민해보시고 개선하면 좋을 것 같네요 ㅎㅎ

2023-05-04 17:07 UTC, yjksw commented on src/main/java/cart/dto/MemberCreateRequest.java
> +    }
dto가 domain을 알고 있으면 어떤 단점이 있을까요 ?

2023-05-04 17:07 UTC, yjksw commented on src/main/resources/templates/settings.html
> +                <div th:text="${member.password}" class="cart-item-price"></div> <!-- 사용자 비밀번호 -->
class 이름이 cart로 유지되어 있네요 😉

2023-05-04 17:07 UTC, yjksw commented on src/test/java/cart/controller/MemberControllerTest.java
> +        assertThat(result.getUpdatedAt()).isEqualTo(expectedResponse.getUpdatedAt());
`extracting` 사용하여 간결하게 바꿔보아요 !

2023-05-04 17:07 UTC, yjksw commented on src/test/java/cart/domain/auth/service/AuthServiceTest.java
> +    public void testCheckAuthenticationHeaderFail() {
실패하는 테스트까지 꼼꼼하게 작성해주셨네요 💯

2023-05-04 17:07 UTC, yjksw commented on src/test/java/cart/domain/cart/dao/CartDaoTest.java
> +        final ProductDao productDao = new ProductDao(jdbcTemplate);
이 부분은 `setUp()` 에 뺄 수 있겠네요 !

2023-05-04 17:07 UTC, yjksw commented on src/test/java/cart/domain/member/dao/MemberDaoTest.java
> +@Sql("/test-data.sql")
Dao 테스트에 어노테이션이 참 많군요 ㅎㅎ
좀 줄여서 간결하게 바꿔보면 어떨까요?

2023-05-04 17:29 UTC, yjksw commented
두둠 남겨주신 질문 답변 드립니다 🙇‍♀️

> 1. 데이터베이스부터 Controller까지 테스트가 필요하다고 생각되는 모든 부분에 단위 테스트를 진행 했습니다. 그래서 굳이 통합 테스트를 작성해야하는가 의문이 듭니다. 잘 동작하는지는 로컬에서 실행해보면 되고, 나머지 부분은 단위 테스트가 작성 되어있는데 통합 테스트를 작성해야할까요? 만약에 그렇게 생각하신다면 코다의 생각이 궁금합니다.

맞아요 ! 그렇게 여겨지는 것이 이해가 잘 갑니다. 저도 개인적인 우선순위는 단위테스트 에요 ㅎㅎ 
그런데 리소스가 허용이 된다면 통합 테스트도 반드시 작성하려고 하는 편 입니다. 

> 잘 동작하는지는 로컬에서 실행해보면 되고

CI/CD를 하면서 이 부분을 매번 로컬에서 실행하기도 어렵고, 역할이 다르다고 생각하기 때문에 여건이 되는대로 구현하려고 하는 편인 것 같아요 ! 

> 2. controller 구분 기준?
controller를 구분하는데 어떻게 해야 가독성이 좋을지 모르겠습니다. 코다의 Controller를 나누는 기준이 어떻게 되나요? 코다의 인사이트로 힌트를 얻고싶습니다!

아하 ! 저는 이번 두둠이 나누어주신 view, 유스케이스별로 나눈 형태 좋다고 생각해요 ㅎㅎ 저도 이렇게 하는 것 같네요 ! 

> 3. 현재 인증을 진행할 때, interceptor를 활용하고 있습니다. 이 역할을 interceptor에서 하는게 좋을지, filter에서 하는게 좋을지 모르겠습니다. 구분 기준이 있으신가요?

오오 좋은 질문이군여 ! 
면접 단골질문이기도 한데요 😉 두둠이 한번 필터와 인터셉터의 차이를 공부해보고 알려주실 수 있나요 ? 
그럼 위 질문에 대한 답이 얼추 나올 수 있을 것 같아요 ! 

> 4. 현재 장바구니에 담을 때, db에 논리적으로 중복되는 데이터가 있는지 확인하고 있다면 예외를 던지도록 하고 있습니다. 즉, 비즈니스 계층에서 dao에 데이터가 있는지 확인하는 과정이 들어가는데, 그냥 dao에서 insert를 할 때 중복이 있다면 예외를 던지던 메세지를 주던 하는게 나을까요? db에 논리적으로 중복된 데이터가 허용되지 않는다는 요구사항이 비지니스 레이어의 책임인지, DataAccess 레이어의 책임인지 잘 모르겠습니다.

어려운 질문인 것 같네요. 저도 두둠의 질문을 보니 참 고민이 많이 되는데요,
우선 현업에서는 데이터베이스에 유니크 키를 통해서 중복값을 제어하고, 
애플리케이션에서 중복이 반드시 일어나지 않도록 비즈니스 로직을 짜는 편 입니다. 

하지만 지금 장바구니 미션을 보면 중복 상품을 담을 수 없다는 비즈니스 규칙을 유추할 수 있는 부분이 DB에 밖에 없다면 
코드를 파악하기 힘들 것 같아요. 
그래서 저는 이번 미션에서는 비즈니스 레이어의 책임에 가깝게 느껴지네요 ㅎㅎ

2023-05-05 06:25 UTC, younghoondoodoom commented on src/main/java/cart/config/WebConfig.java
> +            .addPathPatterns("/cart");
Authentication 헤더 없이 접근하니까 npe가 나네요.. 감사합니다!

2023-05-05 07:02 UTC, younghoondoodoom commented on src/main/java/cart/controller/CartController.java
> +    @PostMapping("")
딱히 없습니다ㅠㅠ 빼도록 하겠습니다!

2023-05-05 07:20 UTC, younghoondoodoom commented on src/main/java/cart/controller/CartController.java
> +    }
그렇군요! 200은 body 값이 있을 때 사용해야되는 것 같습니다. 
생각해보니 이 경우는 201이 조금 더 적절할 것 같습니다!

2023-05-05 07:30 UTC, younghoondoodoom commented on src/main/java/cart/domain/cart/dao/CartDao.java
> +@Component
굳이 `@Repsotory`로 할 이유가 없다고 생각했는데 예외 변환을 생각하니까 이게 맞겠네요!

2023-05-05 07:34 UTC, younghoondoodoom commented on src/main/java/cart/domain/cart/service/CartService.java
> +public class CartService {
service가 도메인 로직이라고 봤습니다. 코드를 처음보는 개발자가 Cart에 관련된 비즈니스 로직을 보고싶을때 제일 먼저 domain -> cart에 들어가서 볼 것 같아 패키지 구조를 이렇게 해봤습니다!
조금 어색한 부분이 있나요??

2023-05-05 07:39 UTC, younghoondoodoom commented on src/main/java/cart/domain/member/dao/MemberDao.java
> +public class MemberDao {
음 생각해보니 dao는 여러 비즈니스 로직에서 사용될 수 있고, dao에 관련된 코드를 보려고하면 너무 찾기 어렵게 되어있네요. domain에 동등한 위치에 있는게 더 좋을 것 같습니다. 코다의 생각은 어떠신지 궁금합니다!

2023-05-05 08:45 UTC, younghoondoodoom commented on src/main/java/cart/domain/member/service/MemberService.java
> +        madeMember.setPassword(passwordEncoder.encode(madeMember.getPassword()));
RequestBodyAdvice를 구현하여 encode를 해서 service에 넘겨주도록 수정했습니다. 
학습할 겸 RequestBodyAdvice를 이용해봤는데 다운캐스팅을 사용하고, type을 확인하는 것도 reflection을 사용하는 것 같아서 좋은 방법인가 싶습니다. 
controller method 안에서 하는게 더 좋을까요?

2023-05-05 09:00 UTC, younghoondoodoom commented on src/main/java/cart/domain/member/service/PasswordEncoder.java
> +public class PasswordEncoder {
해당 객체는 한 곳에서만 사용되기 때문에 꼭 컴포넌트로 등록할 필요는 없는 것 같네요!
코다는 어떤 기준으로 컴포넌트를 등록하시나요??

2023-05-06 11:27 UTC, younghoondoodoom commented on src/main/java/cart/dto/MemberCreateRequest.java
> +    }
domain이 바뀌었을 때, dto도 수정해야한다는 단점이 있습니다. 하지만 그 역할을 service에서 해준다면 해당 단점을 service가 가져가기 때문에 dto에 그 책임을 위임하는 것이 좋다고 생각했습니다!

2023-05-06 13:34 UTC, younghoondoodoom commented
안녕하세요 코다! 필터와 인터셉터 관련된 답변 남기겠습니다.
필터와 인터셉터의 가장 큰 차이점은 작동하는 영역인 것 같습니다. 필터는 WAS가 제공하는 기능이므로 Spring Context 밖에서 작동하고, 인터셉터는 Spring이 제공하는 기능으로 Spring Context 내에서 작동합니다. 이러한 이유로 이전 Spring은 Filter를 통제하지 못했기 때문에 Filter에서 Spring Bean을 사용하지 못했습니다. 만약 그런 상황이었다면 주저없이 Spring Bean을 사용할 수 있는 Interceptor를 사용했을 것 같습니다. 하지만 Spring Boot가 Filter 또한 Spring Bean을 사용할 수 있게 해주기 때문에 고민이 생겼습니다!

둘 다 인증 관련된 기능 구현이 가능할 것 같지만 제 생각에는 Interceptor가 적절한 것 같습니다. 만약 Filter에서 처리하면 Spring을 거치지않으므로 Spring에서 제공해주는 여러가지 이점을 사용하지 못하고, 바로 DB를 거치면 예상하지 못하는 문제가 발생할 수 있을 것 같습니다. Interceptor를 활용하면 Spring을 통해 처리하므로 여러가지 이점(ex -> exception handle)을 이용할 수 있고, Spring을 통해 DB를 거치기 때문에 조금 더 안정적인 것 같습니다.

공부해본 결과 Filter는 Spring과 무관한 작업(ex -> 문자열 인코딩, 공통 보안 작업)을 처리한다고 하는데, 현업에서는 구체적으로 어떤 경우가 있을까요??

2023-05-07 14:34 UTC, yjksw commented on src/main/java/cart/domain/member/service/PasswordEncoder.java
> +public class PasswordEncoder {
저는 스프링에 관리되면 좋을 객체일 때 사용해요 ! 
즉, 객체 생성의 책임이 다른 객체에 있기보다 분리되어 자동주입 되도록 하는 것이 유용할 때 사용하는 것 같네요.
다른 좋은 이유도 있을텐데 지금 생각나는 것은 요 부분이에요 ㅎㅎ

2023-05-07 14:40 UTC, yjksw commented on src/main/java/cart/dto/MemberCreateRequest.java
> +    }
추가로, 현재는 domain을 controller에서 분리하기 위해 연관관계를 controller -> service -> domain 형태로 설계해주셨는데요
이 dto를 통해서 controller -> domain 접근이 가능하게 되는 문제가 있어요 😊

2023-05-07 15:10 UTC, yjksw requested changes
안녕하세요 두둠 🙇‍♀️ 코다 입니다 ~! 

2단계 피드백 너무 잘 반영해주셨어요 💯
웹 계층 관련 피드백을 남겼는데, 그 부분을 논의해보면 좋을 것 같아서 코멘트 남겼습니다. 
확인 부탁드려요 😊

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/domain/cart/service/CartService.java
> +public class CartService {
아하 그러셨군요 ㅎㅎ
레벨1부터 구현하면서 스프링 MVC 구조 기반을 학습하셨을 텐데요, 
이번 애플리케이션에서 두둠이 생각한 서비스 레이어는 있는지 궁금해요 🤔

https://youngjinmo.github.io/2021/04/spring-web-layer/

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/domain/member/dto/MemberCreateRequest.java
> +public class MemberCreateRequest {
요 Request, Response dto가 domain 패키지 내에 있어도 될지 고민해보면 좋을 것 같아요 ! 
어떤 요청과 응답이 뷰에서 들어오는지 도메인이 알 필요가 있을까요 ?

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/dao/CartDao.java
> +package cart.dao;
> 음 생각해보니 dao는 여러 비즈니스 로직에서 사용될 수 있고, dao에 관련된 코드를 보려고하면 너무 찾기 어렵게 되어있네요. domain에 동등한 위치에 있는게 더 좋을 것 같습니다.

요렇게 이유를 작성해주셨는데, 맞는 말씀입니다 ㅎㅎ 
추가로 아래 위에 남긴 웹 계층과 관련하여 왜 dao와 domain이 분리되어야 하는지도 학습해보면 좋을 것 같아요 ~!

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/common/RequestBodyControllerAdvice.java
> +public class RequestBodyControllerAdvice implements RequestBodyAdvice {
> RequestBodyAdvice를 구현하여 encode를 해서 service에 넘겨주도록 수정했습니다.
학습할 겸 RequestBodyAdvice를 이용해봤는데 다운캐스팅을 사용하고, type을 확인하는 것도 reflection을 사용하는 것 같아서 좋은 방법인가 싶습니다.
controller method 안에서 하는게 더 좋을까요?

아하 ! 이런 방법도 있군요 ㅎㅎ 저도 처음 알게된 방법이네요. 
리뷰를 남길 당시 service내에서 흐름을 정도하는 정도만 생각하고 남기긴 했어요. 
이 방법은 두둠이 말씀해주신대로 캐스팅이나 인코딩 위치를 판별하기 조금 어렵다는 단점이 있겠네요 ㅎㅎ 
무엇이 더 좋다라고 말하기는 어려울 것 같아서 두둠이 장단을 잘 비교해보시고 선택하면 될 듯 해요

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/common/EncodePassword.java
> +package cart.common;
요 패키지 이름이 common이라서 어떤 용도인지 유추하기 어려운 것 같아요 !
common이라는 이름은 어떤 책임을 가진 패키지인지 나타내지 않기 때문에 되도록 이런 네이밍을 사용하지 않는 것이 좋습니다 ㅎㅎ
이 패키지가 가진 책임을 유추하기 어려워서 common이라는 이름이 붙게 된 거라면 설계에 오류가 있는 지점이라는 뜻도 될 수 있어요

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/domain/member/dto/MemberCreateRequest.java
> +    }
> domain이 바뀌었을 때, dto도 수정해야한다는 단점이 있습니다. 하지만 그 역할을 service에서 해준다면 해당 단점을 service가 가져가기 때문에 dto에 그 책임을 위임하는 것이 좋다고 생각했습니다!

두둠의 생각도 잘 이해가 가는군요 ! 
다만 현재는 domain을 controller에서 분리하기 위해 연관관계를 controller -> service -> domain 형태로 설계를 해오고 있는데 (레벨1, 레벨2 학습내용) 이 dto에서 도메인을 알기 때문에, controller -> domain 접근이 가능하게 되는 문제가 있어요 😊

2023-05-07 15:10 UTC, yjksw commented on src/test/java/cart/domain/member/dao/MemberDaoTest.java
> +class MemberDaoTest {
크 훨씬 간결하게 잘 바꾸어 주셨네요 💯💯
이번 리팩토링을 통해서 dao 와 domain 패키지가 분리되었는데, 테스트코드에서도 이를 적용하면 좋겠네요 !

2023-05-07 15:10 UTC, yjksw commented on src/test/java/cart/controller/MemberControllerTest.java
> +    }
👍👍

2023-05-07 15:10 UTC, yjksw commented on src/main/java/cart/config/WebConfig.java
> +    }
장바구니 페이지 진입 안되던 문제를 잘 해결하셨군요 💯

2023-05-07 15:12 UTC, yjksw commented
두둠 남겨주신 질문에 대한 답변 입니다 😊

> 공부해본 결과 Filter는 Spring과 무관한 작업(ex -> 문자열 인코딩, 공통 보안 작업)을 처리한다고 하는데, 현업에서는 구체적으로 어떤 경우가 있을까요??

정말 잘 학습해주셨네요 ! ㅎㅎ 
저도 현업에서 직접 필터를 사용해보지는 못했는데요, 
학습해주신대로 주로 로깅이나 요청, 응답에 대한 가공이 필요한 경우에 사용해요 ~!

2023-05-08 02:49 UTC, younghoondoodoom commented on src/main/java/cart/domain/member/dto/MemberCreateRequest.java
> +    }
계층의 독립성을 생각하면 dto에서 domain 생성의 책임이 있으면 안되겠군요. 감사합니다!

2023-05-08 03:07 UTC, younghoondoodoom commented on src/main/java/cart/domain/member/dto/MemberCreateRequest.java
> +public class MemberCreateRequest {
알 필요가 없다고 생각은 합니다만, request, response를 service가 모르게 하려고 한다면 controller-service 사이의 dto가 따로 있어야할 것 같습니다. dto 객체를 하나 더 만들어서 controller에서 request->dto를 한 다음 service로 넘겨주는 것이 더 나은 방법일까요?

2023-05-08 06:29 UTC, younghoondoodoom commented on src/main/java/cart/dao/CartDao.java
> +package cart.dao;
dao는 데이터 계층이고, domain은 비지니스 계층이라 분리되어야 할 것 같습니다. 계층형 구조 관점으로 생각해도 dao 패키지는 따로 분리 되는게 맞을 것 같네요!

2023-05-08 06:59 UTC, younghoondoodoom commented
안녕하세요 코다! 이번 리펙토링에서는 presentation 계층과 business 계층을 독립 시키는데에 집중 했습니다! 두 계층이 소통할 때 Dto만을 이용하고, presentation 계층에서는 domain을 모르게, business 계층에서는 요청, 응답을 모르게 했습니다. 
다만, 이렇게 하는 독립하는 이유가 한 계층의 코드가 바뀌었을 때, 변화를 최소화 시키기 위함이라고 생각을 하는데 오히려 더 많이 바뀔 여지가 있다고 생각합니다. 만약 응답으로 내보내는 데이터가 수정 됐다고 가정하면, 최악의 경우 response dto 뿐만 아니라 presentation과 business 사이의 dto도 바뀔 수도 있을 것 같습니다. 그 대신에 business 로직은 보호 되긴 할 것 같습니다. 
실제 프로덕션 코드를 짤 때에도 이렇게 dto를 세세하게 나누어서 짜게되나요?? 살짝 오버 엔지니어링이라고 생각될 여지가 있는 것 같습니다! 
추가로 dto 정적팩토리 메소드에서 domain 객체를 받아서 생성하는데, 이것도 controller가 domain 객체를 알게된다고 할 수 있는 건가요? 파라미터로 받아서 생성만 할 뿐 접근할 수 없으니 모른다고 할 수 있는건가요? (ex : domain -> cart -> dto -> CartDto)

2023-05-09 15:29 UTC, yjksw commented on src/main/java/cart/domain/member/dto/MemberCreateRequest.java
> +public class MemberCreateRequest {
이 dto는 controller에서 사용하는 dto이기 때문에 domain 패키지에 위치하게 된다면 controller -> domain 의존성이 생기는 구조 입니다 😊

2023-05-09 16:03 UTC, yjksw approved these changes
안녕하세요 두둠 ~! 코다 입니다 🙇‍♀️

피드백 적용해주신 것 잘 확인했어요. 
웹 계층과 패키지 구조에 대해서 추가 학습하고 다음 미션 진행하면
더 재미있게 미션 진행할 수 있을 것 같습니다 😊

장바구니 미션 넘 수고하셨어요.
앞으로 남은 우테코도 화이팅 입니다 🙌

2023-05-09 16:03 UTC, yjksw commented on src/main/java/cart/dto/request/MemberCreateRequest.java
> +package cart.dto.request;
이 dto 패키지는 view에 최적화 된 것이니 controller 패키지 하위에 있어도 좋겠군요  ㅎㅎ

저는 개인적으로 dto 패키지를 최상단에 별도로 두는 것을 지양하는 편 입니다. 
의존성을 무시한 채 dto를 생성하게 유도할 수 있어서 입니다.

2023-05-09 16:03 UTC, yjksw commented on src/main/java/cart/domain/product/service/ProductService.java
지난 피드백에 요런 [코멘트](https://github.com/woowacourse/jwp-shopping-cart/pull/284#discussion_r1186867251)를 단 적이 있는데요, 
이번 미션이 마무리 되더라도, service를 domain하위 패키지에 두는 것이 맞는지에 대한 고민을 해보셨으면 좋겠어요 ! 
지금 구조에는 service 레이어가 없는 설계입니다. 
왜 service 레이어가 필요하고, domain과 별도로 존재해야할까요? 

> 이번 리펙토링에서는 presentation 계층과 business 계층을 독립 시키는데에 집중 했습니다!

요렇게 말씀해주셨는데 현재 구조로선 business계층이 모호한 것 같아요 🤔

2023-05-09 16:03 UTC, yjksw commented on src/main/java/cart/dto/response/CartResponse.java
> +public class CartResponse {
두둠 [이 코멘트](https://github.com/woowacourse/jwp-shopping-cart/pull/284#issuecomment-1537852313)에서  남겨주신 질문에 대한 답변 드립니다 😊

두둠 말씀이 맞습니다 ㅠㅠ 비즈니스가 보호되는 만큼 생성되는 클래스가 많고, 수정 시 변경해야하는 부분이 더 많아지는 문제가 발생할 수 있어요. 
(회사마다, 팀마다 다를 순 있지만) 현업에서도 계층을 이동할 때 dto를 사용하고, 단방향으로 유지하기 위해 다수의 dto 클래스를 생성합니다. 그 이유는, 말씀해주신 번거로움보다 dto를 통해 계층간 불필요한 정보를 알고, 의존성이 꼬이는 것을 지양하는 것이 더 중요하기 때문이에요. 
계층간 의존도가 높아지고, 의존성이 꼬이게 된다면, 두둠 말씀대로 변경 시 한 곳만 변경하면 된다는 장점이 있을 수 있지만, 그만큼 서로 많은 영향을 받는다는 뜻도 될 수 있어요. 
자주 기능이 추가되는데, 한 줄 고친 코드가 어디서 어떤 사이드 이펙트를 일으킬지, 변경의 여파가 어디까지 미칠지에 대한 파악이 어렵고 거기서 발생하는 장애가 잦아질 수 있기 때문에 그 부분을 잘 고려하여 구현하는 편 입니다. 

> 추가로 dto 정적팩토리 메소드에서 domain 객체를 받아서 생성하는데, 이것도 controller가 domain 객체를 알게된다고 할 수 있는 건가요? 파라미터로 받아서 생성만 할 뿐 접근할 수 없으니 모른다고 할 수 있는건가요? (ex : domain -> cart -> dto -> CartDto)

인자로 domain을 받고 있더라도 dto -> domain에 대한 의존성이 있는 부분이긴 합니다. 하지만 두둠 말씀해주신 것 처럼 그것을 통해 controller가 domain 접근을 할 수 있지는 않고, 의존방향에 큰 문제가 있는 것은 아니기 때문에 이정도는 용인하기도 해요 ㅎㅎ 
하지만 개인적으로 저는 지양하는 편 입니다. 클래스 상단에 import를 보고 의존성을 파악할 수 있는데, dto에 domain 의존성이 있는 것이 제거 가능한 의존성이라고 생각해서 입니다.

2023-05-09 16:03 UTC, yjksw commented on src/test/java/cart/dao/MemberDaoTest.java
> +    public void testFindAll() {
요 테스트가 별도로 test를 돌렸을 때는 잘 수행되는데, 
전체 test패지키에 대한 테스트를 돌리면 깨지더라구요!  
테스트 메서드 간 분리가 잘 안된 부분이 있는 것 같아요 ㅎㅎ

우선 일정이 촉박하여 머지하지만 꼭 찾아서 수정하시는 것을 추천드립니다. 
test에서 코드중복을 감수하고서라도 꼭 확보해야하는 것이 test 메서드 간 독립성입니다. 
한 곳에서 독립성이 깨지고 애플리케이션 규모가 크다면 모래사장 속 바늘 찾는 것처럼 힘들 수 있답니다 ㅎㅎ

2023-05-09 16:03 UTC, merged