[2단계 - 장바구니 기능] 연어(황재현) 미션 제출합니다
woowacourse/jwp-shopping-cart pull request #289
Opened 2023-05-03 12:10 UTC by nuyh99

찰리 안녕하세요!
처음 써보는 기능들을 공부하고 찾아보느라 2단계 제출이 늦어졌습니다..ㅠㅠ
2단계도 잘 부탁드립니다. 감사합니다😀

---

### Interceptor 관련 질문
현재 `Interceptor`를 통해서 `DispatcherServlet`과 컨트롤러 사이에서 Authorization 헤더가 있는 지 검증해줍니다.
적용하고 보니 지금처럼 쓴다면 필터를 사용해서 `DispatcherServlet` 보다 앞단에서 처리하면 더 좋을 것 같다는 생각이 듭니다.

현재는 `ExceptionHandler`를 사용하고 있는데, 여기서 401 반환 부분을 필터에서 직접 status code를 401로 바꿔준다면 필터로 바꿔도 좋지 않을까요??

2023-05-04 12:00 UTC, Gomding requested changes
안녕하세요 연어님!!
2단계 잘 구현해주셨네요 😄 
질문에 대한 답변과 함께 몇 가지 코멘트 남겼으니 확인 부탁드립니다 :)

궁금한 점 또는 코멘트에서 이해안되는 부분 있으시면 언제든 DM 남겨주세요!!

2023-05-04 12:00 UTC, Gomding commented on README.md
> +- [x] 사용자 기능 구현
요구사항 리스팅 👍

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +        return null;
null을 리턴하는 것보다 Optional 반환 또는 예외를 발생 시켜주는 것은 어떨까요?
바깥에서 깜빡하고 null 처리를 안하면 뜬금없는 NullPointerException 이 발생할 것 같습니다 😭 
연어는 어떻게 생각하시나요!

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
Interceptor 사용 👍 

질문 주신 부분은 여기서 다뤄보겠습니다!

> Interceptor 관련 질문
현재 Interceptor를 통해서 DispatcherServlet과 컨트롤러 사이에서 Authorization 헤더가 있는 지 검증해줍니다.
> 
> 적용하고 보니 지금처럼 쓴다면 필터를 사용해서 DispatcherServlet 보다 앞단에서 처리하면 더 좋을 것 같다는 생각이 듭니다.
> 
> 현재는 ExceptionHandler를 사용하고 있는데, 여기서 401 반환 부분을 필터에서 직접 status code를 401로 바꿔준다면 필터로 바꿔도 좋지 않을까요??

Interceptor 대신 Filter를 사용하는 것에 어떤 장점이 있어 질문 주신 것인지 궁금해요 😄

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +    }
인터셉터에서 처리하는 것이 `header 에 Authorization 값이 있는가?` 만을 검사하도록 구현하셨는데요

Interceptor 에서 해당 부분만 검사하면 되는 것일까요? 🤔 
인증이라는 책임을 다 하려면 추가로 검사해야하는 부분이 있을것 같아요! 😄

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/service/UserService.java
> +    }
userInfo 와 user 의 비교를 인증이 필요한 기능마다 호출해주고 있군요 🤔 
멋지게 구현해주신 Interceptor 를 더 활용해보면 어떨까요?

2023-05-04 12:00 UTC, Gomding commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS user_product
테이블 이름으로 `cart` 를 표현해볼 수 도 있을 것 같아요

user_product 로는 데이터베이스만 봤을 때 어떤 테이블인지 파악하기 힘들 것 같네요 😭 
만약 `user_id` 와 `product_id` 를 연결해주는 두 번째 테이블이 나오면 어떤 이름을 가져야할까요!

2023-05-04 12:00 UTC, Gomding commented on src/main/resources/static/js/settings.js
> +    localStorage.setItem('credentials', Base64Encode(string));
어떤 방식으로 암호화하는지 클라이언트가 알고 있는것이 맞을까요? 🤔 

브라우저의 개발자 도구만 켜서 어떤 암호화 방식인지 바로 알아내버렸습니다 😈 
(물론 현재는 view에 email 과 password과 모두 노출된 상태지만요 😄 )

![image](https://user-images.githubusercontent.com/57378410/236193025-34d5a287-8dc2-4c6f-9419-d48902dc00ee.png)

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/controller/UserRestController.java
> +    @GetMapping("/user/cart/all")
RestAPI 의 URL에 대해서 학습해볼까요?
`all` 이라고 명시한 것이 마음에 걸렸습니다 😄 

https://meetup.nhncloud.com/posts/92

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/dao/UserDao.java
> +        final String sql = "SELECT id, email, password FROM users WHERE email = ?";
UserDao 에서는 users 테이블에만 접근해보면 어떨까요?

하나의 DAO 에서 여러 테이블에 접근하니 메서드를 읽을 때 마다 `이 메서드는 어떤 테이블에 접근하는 것이지?`를 인식해야 하네요 😢 
하나의 테이블에 접근하면 가독성이 올라가고 유지보수에도 좋다고 생각해요!

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/dto/ProductResponse.java
> +public final class ProductResponse {
오 DTO 에 final을 명시하는것 좋네요 👍 
배워갑니다..!

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/controller/UserRestController.java
> +        return ResponseEntity.ok().build();
`해당 요청은 성공했고 반환 값은 없다` 라는것을 표현하는 [No Content](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/204) 라는 상태값이 있습니다!

2023-05-04 12:00 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +    }
애너테이션 기준으로 Resolver 구현 👍

2023-05-04 15:10 UTC, Gomding commented on src/main/resources/static/js/settings.js
> +    localStorage.setItem('credentials', Base64Encode(string));
라고 했는데 이번 미션 뼈대 코드였군요!

무시하고 지나가셔도 됩니다 😇

2023-05-05 12:00 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +        return null;
예외를 발생시키는 것이 맞는 것 같아요!
감사합니다👍

2023-05-05 12:39 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
![spring-request-lifecycle](https://user-images.githubusercontent.com/93072571/236459029-517c27f1-4761-4f19-aedf-3c1c544cde4c.jpg)

위의 그림과 같이 단순히 Filter에서 빠르게 처리하고 `chain.doFilter`를 호출하거나 끝내거나 하면 `HandlerInterceptor`보다 빠르게 처리할 수 있을 것 같아서 그랬습니다!

`@ServletComponentScan`과 `@WebFilter`를 사용해서 원하는 url의 필터로 등록하면 좋지 않을까요...?

2023-05-05 12:42 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +    }
DB의 email, password와 비교까지 해야할 것 같아요!!
유저 서비스에서 인증에 대한 예외를 발생시킬 필요는 없을 것 같습니다.
감사합니다!!

2023-05-05 13:30 UTC, nuyh99 commented on src/main/java/cart/service/UserService.java
> +    }
인터셉터에서 인증까지 하도록 넘겼습니다.
하지만 이렇게 하니 인터셉터에서 Basic -> UserInfo 파싱, ArgumentResolver에서도 Basic -> UserInfo 파싱을 하게 됩니다.

따라서 인터셉터에서 UserInfo로 변환해서 `HttpServletRequest`에 넣어주고 `ArgumentResolver`없이 컨트롤러에서 바로 받아서 쓰도록 한다면 문제가 있을까요...? 파싱 과정을 한 번만 거치도록 하고 싶어요.

지금 생각나는 것은 다음과 같아요!
1. 해당 인터셉터가 인증, 헤더 -> UserInfo 변환의 책임까지 가진다.
2. 컨트롤러에서 `HttpServletRequest.getAttribute()`로 받기 때문에 인터셉터를 알아야 한다.

하지만 지금 당장 위 두가지가 문제가 된다고 생각되지 않아요...
2번의 경우는 지금처럼 어노테이션 기반 ArgumentResolver를 쓰더라도 리졸버를 알아야 하니까요!

2023-05-05 13:35 UTC, nuyh99 commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS user_product
훨씬 좋은 것 같습니다!

2023-05-05 13:46 UTC, nuyh99 commented on src/main/resources/static/js/settings.js
> +    localStorage.setItem('credentials', Base64Encode(string));
모르는 게 맞다고 생각해요!
클라이언트는 raw id, pw를 보내고 서버에서 받아서 암호화를 하는 등이 나은 것 같습니다.

하지만 Basic Authentication으로 인증한다는 점은 클라이언트가 알아야 하지 않나요...?
이후에 비밀번호를 DB에 암호화해서 저장하거나 하는 수준은 몰라도 Base64로 인코딩해서 Basic id:pw로 보내야 한다는 점은 알아야 한다고 생각해요!!

2023-05-05 13:54 UTC, nuyh99 commented on src/main/java/cart/controller/UserRestController.java
> +    @GetMapping("/user/cart/all")
그렇군요!! 감사합니다 😃

2023-05-05 14:11 UTC, nuyh99 commented on src/main/java/cart/dto/ProductResponse.java
> +public final class ProductResponse {
헉 프록시 객체 생성이 필요하지 않은 곳에는 모두 final을 사용했는데 빼먹은 클래스들이 있네요ㅠㅠ
반영했습니다!

2023-05-05 14:11 UTC, nuyh99 commented on src/main/java/cart/controller/UserRestController.java
> +        return ResponseEntity.ok().build();
오...감사합니다. 반영하겠습니다!

2023-05-05 14:45 UTC, nuyh99 commented on src/main/java/cart/dao/UserDao.java
> +        final String sql = "SELECT id, email, password FROM users WHERE email = ?";
감사합니다!!
CartDao로 분리를 하면 장바구니 관련은 CartDao를 보기 때문에 유지보수가 더 좋을 것 같다고 생각이 듭니다👍

하지만 join을 하기 때문에 여전히 다른 테이블에도 접근을 하게 돼요ㅠㅠ
DB와의 커넥션 횟수를 줄이기 위해서 어쩔 수 없는 trade-off 일까요...?

2023-05-05 14:54 UTC, nuyh99 commented
섬세한 답변 정말 감사합니다!!
달아주신 내용들 최대한 생각해보고 반영했습니다.
여전히 부족하지만 이번에도 잘 부탁드려요😃😃😃

2023-05-06 14:33 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
좋습니다 ㅎㅎㅎ
연어만의 Filter 를 쓰고싶다는 이유가 공감되네요! 
- 디스패처 서블릿 내부로 오기전에 인증을 진행하고 오류가 있다면 빠르게 처리

Interceptor 와 Filter 중 무엇을 사용하느냐는 상황에 따라 적절하게 사용하면 된다고 생각합니다!
Interceptor의 장점으로는 doAfter 같은 Controller 처리가 끝난 후 처리도 가능하다는 점이 있습니다. 그리고 Spring 에서 관리하기 때문에 예외처리 같은 관리가 더 쉽지않을까 라는 생각을 해봤습니다 :)

2023-05-06 14:57 UTC, Gomding commented on src/main/java/cart/service/UserService.java
> +    }
1. Interceptor에서 `HttpServletRequest` 라는 `클라이언트가 요청보낸 값`에 어떤 값을 추가(조작)한다라는 것이 옳을지 고민해봐야겠어요 🤔 

2. UserInfo 파싱이 두 번 일어나지만 인터셉터 와 리졸버를 하나의 흐름으로 봐야할지도 고민해봐야겠네요 🤔 
꼭 인터셉터가 인증 처리를 하고 UserInfo 를 컨트롤러에 건내주는 상황이 항상 있을까요?

2023-05-06 15:00 UTC, Gomding commented on src/main/resources/static/js/settings.js
> +    localStorage.setItem('credentials', Base64Encode(string));
해당 부분은 반영 안하셔도 됩니다!

저는 login 이라는 API 가 있고
클라이언트는 로그인을 요청하고 API는 암호화된 인증값만 넘겨주면 되지 않을까요 🤔

2023-05-06 15:07 UTC, Gomding commented on src/main/java/cart/dao/UserDao.java
> +        final String sql = "SELECT id, email, password FROM users WHERE email = ?";
join을 통해 다른 테이블에 접근하는 것은 허용한다고 생각해요 😄 
편의를 위해 객체를 가져오기 위함이죠!

2023-05-06 15:34 UTC, Gomding requested changes
안녕하세요 연어!
피드백 반영해주신 부분 확인했습니다~
질문 주신 부분과 인증관련하여 몇 가지 코멘트 남겼으니 확인 부탁드려요 🙏 

궁금한 점 있으시면 언제든 DM 남겨주세요 😄

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +            throw new AuthenticationException("사용자 인증이 필요합니다.");
잘 반영해주셨네요 😄

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +    private BasicAuthExtractor basicAuthExtractor;
이곳은 필드 주입을 사용하신 이유가 있을까요?

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +public final class BasicAuthExtractor {
인증값 추출 로직 분리 👍

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +    public UserInfo extract(String header) throws AuthenticationException {
해당 메서드는 인자로 header 를 받는것이 아닌 인코딩된 인증값이라 생각해요? 🤔 
연어는 어떻게 생각하시나요?

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +        return new UserInfo(credentials[0], credentials[1]);
0번 Index 와 1번 index는 무엇을 의미하고 있을까요?

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/dao/CartDao.java
> +    }
`user_id` 도 함께 조건에 있어야할까요? 🤔 

`해당 장바구니 상품이 특정 user 의 것인지 확인`하는 것은 Service 의 역할이 되지 않을까 라는 생각을 해봤습니다 😄 

인가가 어떤것인지도 확인해보아요 :)
[인증과 인가](https://www.youtube.com/watch?v=TXWUNePimAc&t=155s)

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        final String header = request.getHeader(AUTHORIZATION);
헤더에서 꺼낸 값에 대한 변수명이 header 가 적절할지 의문이 들었어요 😄

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        throw new IllegalArgumentException(INVALID_USER_INFO);
해당 부분에서 발생하는 예외를 401 대신 400으로 처리하신 이유가 있을까요?

2023-05-06 15:34 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
인증에 대한 테스트도 작성해볼 수 있을까요?

2023-05-07 09:07 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
서블릿으로 들어오지 않기 때문에 Exception Handling을 하려면 또 다른 필터를 추가해야 하는 군요!
감사합니다👍

2023-05-08 05:28 UTC, nuyh99 commented on src/main/java/cart/service/UserService.java
> +    }
1. 안하는 것이 좋을 것 같아요. 컨트롤러를 만들 때 항상 인터셉터를 염두에 둬야 할 것 같네요!
2. 말씀하신 대로 항상 그런 것은 아닙니다. 지금처럼 두 번 파싱이 일어나도 놔두는 것이 나을 것 같아요. 만약 성능 상의 이슈가 있다면 캐싱을 하는 등의 방법을 취할 것 같습니다.

2023-05-08 05:37 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthArgumentResolver.java
> +    private BasicAuthExtractor basicAuthExtractor;
리졸버나 인터셉터를 빈으로 등록하지 않고 `WebMvcConfigurer`에서 `new Interceptor()` 등으로 쓰다가 필드가 필요해져서 저렇게 했습니다.
필드 주입은 권장하는 방법도 아니기 때문에 모두 컴포넌트로 등록해서 생성자 주입하는 것이 훨씬 좋은 것 같아요!
감사합니다!!

2023-05-08 05:44 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +    public UserInfo extract(String header) throws AuthenticationException {
<img width="525" alt="image" src="https://user-images.githubusercontent.com/93072571/236743145-dcc5b3b3-a54e-4bf8-b89f-76c497c315ed.png">

`getHeader()` 메서드를 통해서 꺼낸 헤더를 파라미터로 넘겨주게 돼서 `header`라는 변수명이 적절하다고 생각합니다!

2023-05-08 07:52 UTC, nuyh99 commented on src/main/java/cart/dao/CartDao.java
> +    }
### deleteProductInCart 메서드로 유저 장바구니의 상품을 삭제하는 방법
1. 유저의 id에 해당하는 장바구니 상품을 조회해서 같은 지 확인 후 `deleteProductInCart(Long userProductId)` 호출
2. `deleteProductInCart(Long userProductId)`만 호출해서 인증 및 인가 없이 삭제
3. 자신의 장바구니를 볼 때 인증된 상태이므로 해당 유저의 장바구니 상품만 들어온다 -> `deleteProductInCart(Long userProductId)`만 호출해서 인증된 상태로만 삭제
4. `deleteProductInCartByUserIdAndUserProductId(Long userId, Long userProductId)` 를 호출해서 단순히 조건에 따른 DELETE문 실행

---

제가 생각했을 때 위의 네가지 방법이 있을 것 같습니다.

* 1번은 DB와의 커넥션 횟수가 제일 많습니다. 
또한 저렇게 메서드를 분리해서 썼을 때 다른 곳에서 해당 메서드가 쓰이는 상황이 현재 없기 때문에 하나의 쿼리로 끝내고 싶습니다.
* 2번은 인터셉터 등에서 유저의 Basic Auth 인증이 안됐을 때의 내용이라서 해당하지 않습니다.
* 3번은 클라이언트단에서 조작하지 않는 이상은 다른 유저의 장바구니 id가 들어오지 않고, 다른 유저의 장바구니 상품을 제거해도 UX를 저하시키겠지만 큰 문제는 아닐 것 같습니다. 하지만 굳이 이러한 단점을 수용할 이유가 없어서 안 좋은 방법이라고 생각합니다.
* 4번은 저 메서드를 만들었을 때 위의 메서드명처럼 생각해서 만들었는데, 말씀하신 `해당 장바구니 상품이 특정 user 의 것인지 확인`의 목적보다는 `해당하는 조건의 행이 존재하지 않도록 하기`의 목적이여서 괜찮다고 생각했습니다.

따라서 현재처럼 놔둬도 괜찮을 것 같다는 제 개인적인 생각입니다!
제가 틀렸다면 말씀해주시면 감사합니다!!😃

2023-05-08 07:53 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        final String header = request.getHeader(AUTHORIZATION);
https://github.com/woowacourse/jwp-shopping-cart/pull/289#discussion_r1187044706
위의 생각과 같습니다!!
다른 더 좋은 변수명이 있을까요ㅠㅠㅠ?

2023-05-08 07:56 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        throw new IllegalArgumentException(INVALID_USER_INFO);
없습니다!! 정신 없이 만든 것 같습니다...ㅠ

2023-05-08 08:01 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
컨트롤러 통합 테스트에서 해당 유스케이스에 대해서 작성했었습니다!!
하지만 400으로 리턴하던 부분을 401로 바꿨습니다.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/93072571/236769072-b0893b25-4bd3-49f6-b36b-813e5322d245.png">

혹시 인터셉터에 대한 단위 테스트를 말씀하신 걸까요??!

2023-05-08 08:05 UTC, nuyh99 commented
찰리 이번 피드백도 감사합니다😁
여러 부분에 대해서 생각해볼 수 있었어요.

하지만 제 결론으로는 위의 코멘트 남긴 것들과 같아서 반영 안한 부분이 많네요ㅠㅠ
제가 잘못 생각한 부분에 대해서 지적해주시면 최대한 빨리 반영하겠습니다!!

다시 한 번 리뷰 감사드려요!!

2023-05-09 00:31 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +    public UserInfo extract(String header) throws AuthenticationException {
앗 저는 getHeader 로 꺼내서 넘겨주는 부분은 외부이고
BasicAuthExtractor의 extract 는 해당 값이 header 의 value 인지는 중요하지 않다고 생각했어요
단지 "Basic dasdeqw=인코딩된모시깽이" 라는 Authorization 값이 넘어갈 뿐이죠 ㅎㅎ

따라서 authorizationValue 정도로 명명해도 되지않을 까요 :)

2023-05-09 00:36 UTC, Gomding commented on src/main/java/cart/dao/CartDao.java
> +    }
타당한 이유군요 👍 
연어의 의견이 합리적이라 생각합니다 ㅎㅎ

2023-05-09 00:37 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        final String header = request.getHeader(AUTHORIZATION);
이미 header 에서 Authorization 의 value 를 꺼냈으니

그에 맞는 이름을 부여해도 되지않을까요 ? 😸 
가볍게 생각했을 때는 `authorizationValue` 같은 이름이 생각나네요

2023-05-09 00:38 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +public final class BasicAuthInterceptor implements HandlerInterceptor {
앗 제가 해당 테스트를 발견못했었군요 😢 
죄송합니다 이미 잘 작성해주셨네요~

2023-05-09 09:06 UTC, Gomding requested changes
안녕하세요 연어 🙌 
리뷰가 늦어져서 죄송합니다.
자신만의 의견을 만들어가시는 것이 인상깊네요 👍 
추가로 몇가지 코멘트 남겼으니 확인 부탁드립니다 🙏 

궁금한 점은 언제든 DM 주세요!!
얼른 쾌차하시길 바랍니다 😭

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/dao/CartDao.java
> +                "WHERE user_id = ?";
이 부분이 대상 user_id 를 기준으로 장바구니 항목 전체를 가져오는 것으로 보이는데요

Product 객체로 가져오지만 c.id(cart_id) 를 product 의 id 로 넣어주고 있군요 🤔 
상당히 헷갈릴 수 있는 포인트로 우려됩니다 😭 
(실제로 클라이언트에게 cart_id 를 주는 부분을 찾는데 오래걸렸습니다.)

CartItem 라는 객체를 만들어보면 어떨까요?

```java
public class CartItem {
    private final Long id;
    private final User user;
    private final Product product;
}
```

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/entity/Product.java
> +    }
toString 을 재정의하신 것은 디버깅을 위한 것이었을까요? 🤔

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/controller/GlobalExceptionHandler.java
>          logger.info("info log = {}", e.getMessage());
ExceptionHandler 에서 예외를 알리는 로그는 error 레벨로 찍어보면 어떨까요?

로그 레벨을 적절하게 표현해주면 
모니터링할 때 error 레벨만 트리거를 걸어서 알림을 받는다던지,
error 레벨 로그는 빨간색으로 표시해준다던지
로그 레벨에 따라 해줄 수 있는 것들이 있습니다 ㅎㅎ

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        }
인증 과정을 AuthService 같은 서비스 객체에게 맡겨볼 수 있을 것 같아요

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/config/WebConfig.java
> +    private final BasicAuthInterceptor basicAuthInterceptor;
구체적인 타입에 의존할 필요가 있을까요!
의존성 주입의 장점은 무엇일까요? 😄

2023-05-09 09:06 UTC, Gomding commented on src/test/java/cart/dao/UserDaoTest.java
> +    }
개인적으로 테스트에서는 스크립트에 적힌 더미데이터에 의존하지 않는것을 좋아합니다 ㅎㅎ
테스트에서 스크립트에 의존하게되면 테스트코드와 스크립트를 계속 읽어야 하기 때문이죠!

저는 `given` 절에서 데이터를 insert 해서 준비하고

`when` 에서 테스트 대상을 실행

`then` 에서는 insert 해줬던 데이터 값을 [하드코딩하여 검증](https://jojoldu.tistory.com/615)합니다.

테스트 코드 또한 가독성이 중요하다 생각해요 😄 
매번 insert 하기위해 객체를 매번 생성하는것이 너무너무 귀찮다! 라면
TestFixture 객체를 만들어주는것도 좋습니다.

```java
package cart.test-fixture

public class ProductFixture {
    private ProductFixture() { }

    public static Product create() {
        return new Product( ~~~ );
    }
}

```

2023-05-09 09:06 UTC, Gomding commented on src/test/java/cart/entity/UserTest.java
> +    }
꼼꼼한 테스트 👍

2023-05-09 09:06 UTC, Gomding commented on src/test/java/cart/dao/UserDaoTest.java
> +    }
이 부분은 `검증하고자 하는 대상 실행` + `검증` 을 하고 있으므로 주석에 `// when then` 으로 적어주셔도 됩니다 😄

2023-05-09 09:06 UTC, Gomding commented on src/test/java/cart/service/UserServiceTest.java
> +                        .hasMessage("잘못된 유저 정보입니다."));
가능하면 하나의 테스트에서는 하나의 행위를 검증하는 것이 좋습니다

테스트가 실패했을 때 어디서 실패했는지 빠르게 캐치할 수 있게 됩니다 😄 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/57378410/237045559-83b733cb-761b-46a2-908e-c714431d6a11.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/57378410/237045984-a9ce29f8-3391-4b77-ab2d-2cf846fb068b.png">

2023-05-09 09:06 UTC, Gomding commented on src/test/java/cart/controller/ProductRestControllerTest.java
> +                    .statusCode(HttpStatus.CREATED.value());
상품을 추가한 후
단일 조회 API 가 있다면 그것으로 생성된 리소스를 조회하여 검증하는 방법도 있습니다~

현재는 단일 조회 API 가 없으니 그런것이 가능하다 정도만 인지하고 계시면 될것같습니다 ㅎㅎ

2023-05-09 09:06 UTC, Gomding commented on src/main/java/cart/controller/UserRestController.java
> +    @PostMapping("/user/cart")
url 설계에 질문이 있어요!

1. 중복된 url 은 class 에 `@RequestMapping` 애너테이션을 사용하여 생략할 수 있습니다.
    - 하지만 이 방법에도 팀마다 컨벤션이 다를 수 있습니다.
    - a. 코드 검색에서 `/user/cart` 처럼 full path 로 검색하는것이 용이하여 `@RequestMapping` 사용을 지양할 수 있음
    - b. 중복 코드를 없애기 위해 `@RequestMapping` 을 사용
2. 해당 path 에 user 가 포함됨 이유가 궁금해요!

2023-05-09 14:17 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthExtractor.java
> +    public UserInfo extract(String header) throws AuthenticationException {
아하!! 저도 좋다고 생각해요👍

2023-05-13 05:34 UTC, nuyh99 commented on src/main/java/cart/dao/CartDao.java
> +                "WHERE user_id = ?";
처음부터 CartItem이라는 도메인 엔티티로 모든 로직을 수행하면 좋았을 것 같은데 객체와 관계형 DB 간의 매핑이 너무 혼란스러웠던 것 같습니다!!
말씀하신 대로 CartItem으로 리턴해주는 CartDao의 메서드를 만들었습니다👍

2023-05-13 05:36 UTC, nuyh99 commented on src/main/java/cart/entity/Product.java
> +    }
앗 그렇습니다!!
현재 사용하지 않으므로 제거했습니다.
하지만 남겨둬도 나쁠 건 없지 않을까 생각해요...!

2023-05-13 05:45 UTC, nuyh99 commented on src/main/java/cart/controller/GlobalExceptionHandler.java
>          logger.info("info log = {}", e.getMessage());
감사합니다!! 반영했습니다.
출력할 로깅 레벨을 설정할 수도 있군요!

2023-05-13 05:50 UTC, nuyh99 commented on src/main/java/cart/auth/BasicAuthInterceptor.java
> +        }
고민은 했었는데 너무 간단한 부분이라서 분리를 안했었어요!!
말씀하신 대로 반영했습니다👍

2023-05-13 06:36 UTC, nuyh99 commented on src/main/java/cart/config/WebConfig.java
> +    private final BasicAuthInterceptor basicAuthInterceptor;
결합도를 낮춰주고 그로 인해서 유지 보수가 용이해진다는 장점이 있습니다!

다만 인터셉터나 리졸버의 기본 구현체들이 이미 있어서 @Autowired가 제대로 안될 줄 알았습니다.
그래서 관련해서 코드를 열심히 들어가봤어요.
결론부터 말하면 해당 타입의 기본 구현체들은 스프링 빈이 아닌 것 같네요!

1. 스프링 부트의 `WebMvcAutoConfiguration`은 `WebMvcConfigurationSupport`가 Bean으로 없을 때 설정으로 등록된다

![image](https://github.com/woowacourse/jwp-shopping-cart/assets/93072571/87071b12-bac2-4f3d-ac16-48f5d155353f)
2. `WebMvcAutoConfiguration` 안에 있는 위의 빈 등록할 때 `setInterceptors()`에서 기본 인터셉터가 등록된다. 
3. ConversionService와 ResourceUrlProvider를 인터셉터에게 setAttribute() 해주는 두 인터셉터가 등록된다.
![image](https://github.com/woowacourse/jwp-shopping-cart/assets/93072571/6656bae1-6d8c-46c4-a1a0-7bc1d0b6924e)
4. 근데 이 두 인터셉터는 Bean으로 관리되지 않고 `new`를 통해서 생성된다.
5. 따라서 내가 `implements HandlerInterceptor` 등으로 만든 커스텀 인터셉터들은 유일한 해당 타입의 빈이다.

추가 정보:
위의 1번에서 `WebMvcConfigurationSupport`가 Bean으로 없을 때의 조건은 @EnableWebMvc를 통해서 불만족시킬 수 있다.
@EnableWebMvc에서는 `DelegatingWebMvcConfiguration`을 Import하는데 이 클래스는 `WebMvcConfigurationSupport`를 상속한 클래스이기 때문이다.

틀린 부분이 있다면 알려주세요...!!

2023-05-13 06:40 UTC, nuyh99 commented on src/test/java/cart/dao/UserDaoTest.java
> +    }
앗 확실히 왔다갔다 읽기는 힘들겠네요!
유저를 미리 넣어줘야 해서 스크립트에 넣어줬지만, 해당 데이터들을 테스트 코드에서 쓰는 것보다는 새로 넣어서 쓰는 것이 좋네요.
감사합니다👍

2023-05-13 06:41 UTC, nuyh99 commented on src/test/java/cart/dao/UserDaoTest.java
> +    }
좋은 것 같아요!
습관화 하는 중입니다ㅎㅎ

2023-05-13 06:43 UTC, nuyh99 commented on src/test/java/cart/service/UserServiceTest.java
> +                        .hasMessage("잘못된 유저 정보입니다."));
저도 모르게 귀찮아서 저렇게 했나봐요...
죄송합니다!

2023-05-13 06:44 UTC, nuyh99 commented on src/test/java/cart/controller/ProductRestControllerTest.java
> +                    .statusCode(HttpStatus.CREATED.value());
헤더에서 "Location"의 값을 읽어서 GET 요청으로 조회하면 될 것 같아요!!

2023-05-13 06:49 UTC, nuyh99 commented on src/main/java/cart/controller/UserRestController.java
> +    @PostMapping("/user/cart")
UserRestController에 만약 유저 추가 등의 API가 생긴다면, '/cart' 부분은 공통이 아닐 것이라고 생각했습니다!

따라서 "/user" 부분만 공통으로 묶고, 나머지 "/cart~" 부분은 남겨뒀어요!!
ProductRestController의 경우는 모두 "/products"로 시작할 것 같아서 중복 부분을 모두 없앴습니다.

2023-05-13 06:53 UTC, nuyh99 commented
찰리 오랜만이에요!!
이번 주 내내 아파서 리뷰 반영이 늦어졌습니다ㅠㅠ
다행히 지금은 괜찮아져서 밀렸던 공부들을 하는 중이에요ㅎㅎ

섬세한 리뷰 감사합니다.
DAO 부분은 그동안 RDB와 객체 간의 패러다임으로 고생했더니 저번 주보다 성장한 느낌이에요!
만족하실 때까지 리뷰 날리겠습니다. 이번에도 잘 부탁드려요😄

2023-05-14 00:11 UTC, Gomding commented on src/main/java/cart/controller/GlobalExceptionHandler.java
>          logger.info("info log = {}", e.getMessage());
로깅 관련한 영상입니다 ㅎㅎ

- [[10분 테코톡] ☂️ 검프의 Logging(로깅) #1](https://www.youtube.com/watch?v=1MD5xbwznlI&t=13s&pp=ygUG66Gc6rmF)
- [[10분 테코톡] ☂️ 검프의 Logging(로깅) #2](https://www.youtube.com/watch?v=JqZzy7RyudI&t=562s&pp=ygUG66Gc6rmF)

2023-05-14 00:32 UTC, Gomding commented on src/main/java/cart/config/WebConfig.java
> +    private final BasicAuthInterceptor basicAuthInterceptor;
깊이있게 학습해주셨네요 💯 💯 💯 
결론부터 말씀드리면 지금처럼 구현체 타입으로 주입받아도 되겠네요..!!

근데 생각해보니 Interceptor 는 여러 가지가 생길 수 있겠네요 🤔
스프링 진영은 왜 `Interceptor 를 빈으로 등록하지 않고 생성자 사용했을까` 라는 고민을 잠깐 해봤는데
의존성 주입을 사용하기에 HandlerInterceptor 는 너무 넓은 범위의 추상화 개념이라고 생각되네요 ㅎㅎ
너무 넓은 범위의 추상화 개념이기에 interface 를 통해 주입받는 것은 위험한 선택이 될 수 있겠네요! 
(선택되는 빈이 여럿이라 에러를 발생시키거나, 원하는 빈을 받아올 수 없음)

정말 특정 Interceptor(로그인 인터셉터 같은) 의 구현체가 달라지는 경우가 있어 의존성 주입의 이점을 누려보겠다 라고 하면
아래와 같이 구현해볼 수 있겠네요 😄 

```java
public interface LoginHandlerInterceptor extends HandlerInterceptor {

}

@Component
public class LoginHandlerInterceptorImpl implements LoginHandlerInterceptor {
    ~~~
}
```

하지만 현재는 이런 구현도 `굳이?` 라는 생각이 듭니다 ㅎㅎㅎ
연어가 기존에 구현해주신것 처럼 구현체 타입으로 빈을 주입받는 방법도 나쁘진 않다고 생각해요~

2023-05-14 00:35 UTC, Gomding commented on src/main/java/cart/controller/UserRestController.java
> +    @PostMapping("/user/cart")
> UserRestController에 만약 유저 추가 등의 API가 생긴다면, '/cart' 부분은 공통이 아닐 것이라고 생각했습니다!
이때 "/user"가 사용될 것이라고 생각해서 그렇게 만들었어요.

그렇다면 User 추가등의 기능은 `UserRestController` 에 남겨두고 CartRestController 를 분리해보는것은 어떨까요 🤔 
카트에 대한 API 인데 User 관련 기능과 함께 둬야할까? 라는 의문이 들었어요 ㅎㅎ

2023-05-14 07:36 UTC, Gomding approved these changes
안녕하세요 연어!
피드백 반영해주신 부분 확인했어요 :)
이번 미션에서 경험해야할 것은 다 해보신것 같아 이만 merge 하겠습니다 🙏 
미션 진행하느라 수고하셨습니다.

추가로 궁금한 점 있으시면 언제든 편하게 DM 남겨주세요 😄 

대댓글에 남겨주신 의견에 대한 답글입니다 :)
- https://github.com/woowacourse/jwp-shopping-cart/pull/289#discussion_r1193055898
- https://github.com/woowacourse/jwp-shopping-cart/pull/289#discussion_r1193054309
- https://github.com/woowacourse/jwp-shopping-cart/pull/289#discussion_r1193055689

2023-05-14 07:36 UTC, Gomding commented on src/main/java/cart/controller/UserRestController.java
> +        final List<UserCartResponse> products = userService.getAllProductsInCart(userInfo);
Cart 조회시 `ProductResponse` 를 재사용하지 않고 `UserCartResponse`를 따로 만들어주셨군요 👍 

저도 Response 를 재사용 하게되면 다른 쪽에서의 응답값 변경에 영향을 받아야하므로 
Response 는 각각 만들어주는것이 좋다고 생각해요!

2023-05-14 07:36 UTC, merged