[2단계 - 상품 관리 기능] 이리내(성채연) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #292
Opened 2023-05-04 02:27 UTC by hectick

1단계 미션들에서 질문에 대한 답변들입니다!
https://github.com/woowacourse/jwp-shopping-cart/pull/196#discussion_r1184476021
https://github.com/woowacourse/jwp-shopping-cart/pull/196#discussion_r1182118882
https://github.com/woowacourse/jwp-shopping-cart/pull/196#discussion_r1184479833

2023-05-04 08:43 UTC, hectick commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
### Interceptor와 ArgumentResolver
`CartItemController`에서는 사용자가 인증되어야 장바구니에 상품을 추가, 삭제, 조회할 수 있는데요, 중복되는 사용자를 인증로직에 대한 코드는 `ArgumentResolver`로 뺐습니다. 이번에 학습테스트로 공부를 하면서, `Interceptor`와 `ArgumentResolver`를 둘 다 써보려고 했는데, 둘 다 써보려고 하니 사용자인증이라는 과정을 굳이 쪼개는 것 같고, 각각의 역할이 애매해지는 느낌을 받아서 그냥 `ArgumentResolver`에 몽땅 몰아넣어보았습니다. 왜냐면 컨트롤러에서 `@AuthenticationPrincipal AuthenticatedMember authenticatedMember` 이런식으로 인증된 사용자의 정보를 받아오는 게 더 간지나기 때문이었습니다. 하지만 `interceptor`도 간지가 덜할 뿐, 비슷한 책임을 줄 수 있을 것 같습니다. 사실 언제  `Interceptor`를 쓰고 언제 `ArgumentResolver`를 써야할지 감이 오지 않습니다. 실무에서는 일반적으로 로그인을 어떤식으로 구현하는지도 궁금합니다.

2023-05-04 08:43 UTC, hectick commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +
### Controller에 도달하기도 전에 DB에 접근하는게 가능한가요...?!
이번에 사용자를 인증하는 기능을 구현하면서, 실제 존재하는 사용자인지 DB에 접근하는 과정이 필요했습니다.
그런데 그동안은 `Controller->Service->DB` 순서로 접근해왔는데, 현재 코드처럼 컨트롤러에 도달하기도 전에 DB에서 접근하는 것이 흔한 일인가요? 아무래도 찝찝해서 질문드려봅니다.

2023-05-04 08:43 UTC, hectick commented on src/main/java/cart/controller/ViewController.java
> +
[지난 리뷰](https://github.com/woowacourse/jwp-shopping-cart/pull/196#discussion_r1181215338)에서 `@Controller`와 `@RestController`의 차이에 대해 언급하셨길래, 한번 이 둘을 분리해보려고 했습니다. 그런데 이렇게 뷰를 반환하는 부분을 모두 모아놓아도 괜찮을까요? 아직 서비스나 컨트롤러를 어떻게 나누어야할지 잘 모르겠어서, 일단 사용하는 자원이 비슷한 기능끼리 묶고, 뷰를 반환하는 부분을 따로 모아보았습니다

2023-05-04 14:14 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
`이런식으로 인증된 사용자의 정보를 받아오는 게 더 간지나기 때문이었습니다.` [GDD](https://kin33.tistory.com/62) 멋지네요! 😎 👍 

저는 Interceptor 에서 사용자 인증을 하고
ArgumentResolver 는 사용자 정보를 Controller 함수의 인자에 매핑해주는 용도로 사용합니다.

이렇게 나눌 때의 장점은

---
- Interceptor 에서 사용자 인증을 하고

아래는 인터셉터를 설정 코드인데 addPathPattern 라는 독특한 설정이 있습니다! 이 부분은 학습해보시면 좋겠어요 😄 
```java
    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SomethingInterceptor())
                .addPathPatterns("/admin/**");
    }
```

---

- ArgumentResolver 는 사용자 정보를 Controller 함수의 인자에 매핑해주는 용도로 사용합니다.

Controller 에서 현재 로그인한 회원의 정보가 필요한 이유는 무엇일까요?
a라는 회원이 1번이라는 Product의 주인이고
b라는 회원이 2번이라는 Product의 주인이라고 가정해볼게요

a라는 회원이 로그인하여 2번 Product 를 삭제하고 싶어해요
이것을 허락해줘야 할까요?

`인증과 인가` 라는 키워드로 학습해보시면 좋겠어요!
[[10분 테코톡] 🌳 나봄의 인증과 인가](https://www.youtube.com/watch?v=TXWUNePimAc)

2023-05-04 14:17 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +
만약 인증하는 기능에 특별한 비즈니스 흐름이 없다면 가능하다고 봅니다 😄 

하지만 구현해주신 내용을 보니 validation을 진행하는 등의 비즈니스 흐름이 존재하고 있네요!
그렇다면 인증용 Service 를 사용해서 인증 비즈니스 흐름을 가져보는것은 어떨까요?

2023-05-04 14:23 UTC, Gomding commented on src/main/java/cart/controller/ViewController.java
> +
이 부분은 구현하기 나름이라고 생각해요!

한 군데 모아서 보는것이 편하다면 모아 놓는것이 좋겠구요
ViewController를 봤는데 너무 복잡하고 지저분하다 라면 각각 나눠볼 수 있겠네요 🙌 
저는 View 의 개수가 많지않아 현재는 모아놓는 것이 좋은 방법이라 생각합니다 👍 

`@RestContoller` 분리에 대해 질문드린것은 RestController 는 순수한 데이터들(Json 응답값)을 반환한다는 의미도 줄 수 있어서 였습니다!

2023-05-04 15:08 UTC, Gomding requested changes
안녕하세요 이리내!
2단계 멋지게 구현해주셨네요 👏 👏 
질문과 의견 남겨주셔서 감사해요!!
몇 가지 코멘트 남겼으니 확인 부탁드려요 🙏 

궁금한 점 있으시면 언제든 DM 주세요 😄 

1단계 댓글에서 질문 주신 부분에 대한 답변입니다!
- https://github.com/woowacourse/jwp-shopping-cart/pull/196#discussion_r1185015758

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
애너테이션 기준으로 Resolve 해주도록 구현하셨네요!👍

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/auth/BasicAuthenticationExtractor.java
> +        return null;
null을 반환하는 대신 Optional 이나 예외를 반환하는 것에 대해서 어떻게 생각하시나요?

바깥에서 null 처리를 깜빡하면 뜬금없이 NullPointerException과 마주칠 수 있겠어요!

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/config/WebMvcConfiguration.java
> +public class WebMvcConfiguration implements WebMvcConfigurer {
WebMvcConfigurer 를 구현한 웹 설정 추가 💯

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/controller/ExceptionController.java
> +        return ResponseEntity.badRequest().body(exceptionResponse);
500 코드의 InternalServerError 에서 400코드의 BadRequest로 바꾸신 이유가 궁금해요!
`Exception 타입`을 핸들링 한다는 의미는 예상치 못한 에러 처리를 한다고 생각해요
이것이 클라이언트의 잘못된 요청이라고 응답해야할지 고민해보아요 😄

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationPrincipal.java
> +    boolean required() default true;
required 값은 어떤 부분에서 사용되고 있는지 궁금해요!

2023-05-04 15:08 UTC, Gomding commented on src/main/resources/data.sql
> +    image text               NOT NULL,
varchar 와 text는 어떤 차이가 있을까요?

2023-05-04 15:08 UTC, Gomding commented on src/main/resources/static/js/cart.js
> +
이미 처리한 TODO 주석은 삭제해주셔도 됩니다 :)

2023-05-04 15:08 UTC, Gomding commented on src/test/java/cart/controller/CartItemControllerTest.java
> +        void successTest() {
좀 더 깊게 검증을 한다면 상품을 조회하는 GET API 를 사용하여 응답값 까지 검증을 해볼 수 있습니다 :)

현재 응답 상태코드가 CREATED 이고 Location 헤더에 해당 리소스에 대한 주소가 있을테니
GET 요청하는것은 더욱 쉽겠네요!

현재는 단일 리소스 조회가 없으니 무시하셔도 됩니다.

2023-05-04 15:08 UTC, Gomding commented on src/test/java/cart/controller/CartItemControllerTest.java
> +                    .statusCode(HttpStatus.CREATED.value());
상태 코드가 CREATED 이고 Location 헤더에 값을 넣었으니

응답에서 Location 헤더도 검증해보는건 어떨까요?

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/domain/entity/MemberEntity.java
> +public class MemberEntity {
Entity 라고하여 `~~Entity`라고 명명하지 않으셔도 됩니다 😄 
우리가 값 객체를 `PriceVO` 라고 하지 않는것처럼요!
물론 취향차이 입니다 🙏

2023-05-04 15:08 UTC, Gomding commented on src/main/java/cart/service/CartItemManagementService.java
> +        int deletedRowCount = cartItemDao.deleteById(id);
장바구니에 있는 담긴 것을 제거할 때, 제거 대상이 현재 로그인한 회원의 것이 아니라면 어떻게 해야할까요?

접근 권한을 열어줘도 괜찮을까요?

2023-05-05 06:36 UTC, hectick commented on src/main/java/cart/controller/ExceptionController.java
> +        return ResponseEntity.badRequest().body(exceptionResponse);
서버의 에러가 맞는 것인데, 위에 다른 핸들러를 badRequest()로 바꾸다가 이것도 바꿔버린 것 같네요 수정하겠습니다!!

2023-05-05 07:54 UTC, hectick commented on src/main/java/cart/auth/AuthenticationPrincipal.java
> +    boolean required() default true;
앗 이부분은 학습테스트에 있는 어노테이션 형태를 복붙해 온 것인데요,
저도 왜 있는 건지 궁금했는데, 어노테이션을 만들려면 이런게 있어야하나? 라는 생각만 잠깐 들고 말았던 것 같아요.
저것을 빼고 돌려봐도 프로그램이 잘 돌아가는 걸 보니 필요없는 부분이었네요
복붙을 하더라도 왜 이런게 있는지, 나한테 필요한건지를 알고 복붙해야겠네요 반성합니다. 😭

2023-05-05 07:57 UTC, hectick commented on src/main/resources/static/js/cart.js
> +
아무래도 Js나 html 코드에 익숙하지 않다보니, 제가 어느 부분을 고쳤는지를 매번 커밋 기록으로 까는 것보단 주석이 있는 부분을 확인하는 것이 빠를 것이라 생각해서 남겨두었습니다!

2023-05-05 08:21 UTC, hectick commented on src/main/resources/data.sql
> +    image text               NOT NULL,
둘 다 문자를 저장한다는 건 동일하지만, varchar는 위에 코드에서와 같이 255 처럼 최대 바이트 크기를 지정해줄 수 있다는것이 가장 큰 차이같습니다!
상품 이름은 무진장 길어질 일은 없을 것이라 예상이 가능해서, 255를 통해 크기를 제한해 주었고,
이미지 url은 제가 그 길이를 예상하지 못하기도 하고, 그동안 특정 url을 복사했을 때 링크가 매우 길었던 적이 있어서 따로 크기를 제한해주지 않았습니다.

이외의 다른 차이를 구글링해보니, 주로 인덱싱의 차이가 나오는데요. 아직 이런 성능적인 부분은 제게는 와닿지 않는 것 같습니다😂

2023-05-05 09:20 UTC, hectick commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
`Interceptor`에서는 DB에 존재하는 사용자인지 아닌지 여부만 인증하여 사용자가 아닐때만 예외를 터뜨리도록 하고,
`ArgumentResolver`에서는 로그인한 사용자의 정보(사용자id, email, password)와 다른 요청정보들을 조합해서 컨트롤러로 넘겨보려고 했습니다!
그런데, 사용자의 id를 얻으려면 결국 DB에 접근해야 하는데요,

- Interceptor에서 이미 DB에 한번 접근하는데, ArgumentResolver에서 또 DB에 접근해서 id를 가져오는 것이 좋을까요?
- 아니면 ArgumentResolver에서는 (email, password)만 넘기고, CartItemController쪽으로 넘어간 뒤에 또 다시 DB에 접근해서 id를 가져오는 것이 좋을까요?
- 아니면 Interceptor에서 id를 가져와서 ArgumentResolver에 넘겨주는 방법이 있을까요?

2023-05-05 10:10 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
좋은 고민이네요~ DB에 두 번 접근하는 것이 비효율적이라고 느껴서 나온 고민으로 이해하면 될까요?

저는 Interceptor와 Resolver 가 각각 사용되는 트리거가 달라서 DB를 조회하는 로직도 각각 가지고 있어야한다고 생각해요
Interceptor 는 전체 path 에 적용 또는 특정 path에 적용하여 실행하는 로직이고
Resolver 는 특정 파라미터 타입 또는 애너테이션 등에 매핑시켜주는 역할을 하죠

각각의 트리거가 다른데 `너는 나한테 클라이언트의 Request값 안에 ID를 넣어서 넘겨줘` 라고 약속하는것이 괜찮을지 의문이 들어요 🤔 

> ArgumentResolver에서는 로그인한 사용자의 정보(사용자id, email, password)와 다른 요청정보들을 조합해서 컨트롤러로 넘겨보려고 했습니다!

인증은 Interceptor 에서 했는데 ArgumentResolver 에서 사용자 ID를 가져오는 목적이 궁금해요! :)
email 과 password 만 넘겨주면 어떨까요 🤔

2023-05-06 07:21 UTC, hectick commented on src/main/java/cart/service/CartItemManagementService.java
> +        int deletedRowCount = cartItemDao.deleteById(id);
로그인한 회원의 id도 일치해야 삭제하도록 수정하였습니다!!

2023-05-08 03:46 UTC, hectick commented on src/main/java/cart/auth/BasicAuthenticationExtractor.java
> +        return null;
예외를 반환하도록 수정하였습니다!!

2023-05-08 05:30 UTC, hectick commented on src/test/java/cart/controller/CartItemControllerTest.java
> +        void successTest() {
넵 요부분은 아이디어만 메모해두도록 하겠습니다!!

2023-05-08 06:00 UTC, hectick commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
DB에 한번 접근하는 다른 방법을 또 생각해봤어요.

Interceptor에서는 Authorization 헤더가 존재하는지만 검증하고, Resolver에서 사용자 인증을 하고, 컨트롤러에 사용자 id만 담아서 넘겨주는 것이죠. 그런데 이렇게 되면 반드시 Interceptor -> Resolver 이 순서로 넘어오는 관계여야 하기 때문에 찰리가 말씀해주신 `트리거가 달라서` 각각 동작해야 하는 것에 어긋나는 것 같아요. 각각 동작하게 하려고 Resolver에서도 헤더를 검증하고 service를 통해 사용자 인증을 하면 Interceptor는 무의미해지는 것 같아서 결국 Interceptor는 지우고 Resolver만 남게 될 것 같습니다.

결국 Interceptor와 resolver를 둘 다 써보려면 돌고돌아 다시 `Interceptor 에서 사용자 인증을 하고, ArgumentResolver 는 사용자 정보를 Controller 함수의 인자에 매핑해주는 방법`으로 돌아오는 것 같아요.  resolver는 그저 요청에 들어있는 값을 이용해서 컨트롤러에 넘길 객체로 매핑하는 용도로 주로 쓰이는 것인가요? 아니면 제가 깨닫지 못한 다른 유용하게 쓰이는 용도가 있을까요?

2023-05-08 22:30 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationPrincipal.java
> +    boolean required() default true;
required 값이 false 일 때는 Guest 유저를 매핑해준다던지 하는 동작이 가능할 수도요?! ㅎㅎㅎ
그런 의도로 보입니다 :)

2023-05-08 22:33 UTC, Gomding commented on src/main/resources/data.sql
> +    image text               NOT NULL,
잘 이해하고 계시네요 :)
말씀대로 Index 관련한 부분은 나중에 Index 학습할 기회가 오면 그 때 감을 잡아도 될것같습니다~!! 👍

2023-05-08 22:34 UTC, Gomding commented on src/main/resources/static/js/cart.js
> +
좋습니다 !!
학습을 위한 것이니 시적 허용 같은 느낌으로 넘어가도 되겠군요 😄

2023-05-08 23:31 UTC, Gomding requested changes
안녕하세요 이리내!
피드백 반영해주신 부분 확인했습니다 🙏 
추가로 몇 가지 피드백 남겼으니 확인 부탁드려요!!

궁금한 점 있으시면 언제든 편하게 DM 남겨주세요 :)

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
대상 멤버의 장바구니 항목을 모두 가져오는데 흐름이
1. 대상 회원이 가진 cart_id & product_id 모두 가져옴
2. 가져온 장바구니 정보 각각에서 product_id를 기준으로 상품 정보를 가져옴

만약 장바구니 항목이 100개 있다면 Product 정보를 조회하는 횟수가 100번이 될 수 있어요 😭 
이는 DB에게 부하를 줄 수 있어보여요!

이를 해결하기 위해서는 두 가지 방법이 떠오르는데 키워드만 남겨보겠습니다 :)
(둘 다 DB 쿼리 용어 입니다~)
1. join
2. where in

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
사용자의 장바구니 항목인지 확인하기 위해 memberId 를 확인하도록 추가해주셨네요 👍 

권한이 없는 리소스에 접근했을 때 예외 처리에 대해서는 고민이 되는데요
- 어차피 회원의 권한이 없는것은 장바구니에 없는 상품이 맞으니 현재 예외 던지는것을 그대로 사용해도 된다.
- 권한이 없는 리소스에 접근했으니 해당 상황에 맞는 예외를 던져준다. ([status code 403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403))

이리내는 위의 두 처리 방법에 대해 어떻게 생각하시나요?

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationService.java
> +        }
DB에서는 email 로만 회원을 조회해오고
정보 검증은 member 라는 도메인 객체에게 물어보면 어떨까요?

```java
if (member.checkPassword(memberDto.getPassword())) {
    throw new AuthenticationException("사용자 인증이 필요합니다.");
}
```

2023-05-08 23:31 UTC, Gomding commented on src/main/resources/data.sql
> +    email    varchar(255)       NOT NULL UNIQUE,
unique 제약조건 추가 👍

2023-05-08 23:31 UTC, Gomding commented on src/test/resources/testData.sql
> +    email    varchar(255)       NOT NULL UNIQUE,
테스트 테이블 스크립트와 애플리케이션 실행 시 테이블 스크립트를 동시에 관리해줘야 해서
나중에 스크립트가 많아지면 관리가 힘들어질 것 같아요 😢 

테이블 정보는 data.sql 을 사용하면서
테스트 할 때는 더미데이터만 넣는 방법은 없을까요? 🤔 

현재는 각각의 테스트 메서드마다 테이블도 새로 만들어서 테스트 속도도 느려질 것같아요 😞

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/dao/MemberDao.java
> +    Member selectByEmail(final String email);
Optional 타입으로 반환해보는 것은 어떠신가요? 😄 

[http://homoefficio.github.io/2019/10/03/Java-Optional-바르게-쓰기/](http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)

2023-05-08 23:31 UTC, Gomding commented on src/test/java/cart/controller/CartItemControllerTest.java
> +        @Test
로그인 상태까지 검증 💯 💯 💯 💯

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/domain/entity/CartItem.java
> +    private final long productId;
CartItem 은 Member 와 Product 객체를 가져보면 어떨까요? 😄 

```java
public class CartItem {
    private final Long id;
    private final Member member;
    private final Product product;
}
```

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/dao/dummyData/MemberInitializer.java
> +package cart.dao.dummyData;
더미데이터의 경우 dao 패키지보다는 최상단에 있는것이 더 빠르게 발견할 수 있다고 생각해요!

애플리케이션을 개발환경에서 실행했는데 dao 패키지를 열어보기전에는 어디서 더미데이터를 넣어주고 있는지 파악이 어렵다고 생각해요~

2023-05-08 23:31 UTC, Gomding commented on src/main/java/cart/config/WebMvcConfiguration.java
> +                .addPathPatterns("/cart/cart-items/**");
addPathPatterns 에서 와일드카드 `*` 과 `**`은 어떤 차이가 있을까요?

2023-05-10 01:32 UTC, hectick commented on src/main/java/cart/config/WebMvcConfiguration.java
> +                .addPathPatterns("/cart/cart-items/**");
<img width="486" alt="image" src="https://github.com/woowacourse/jwp-shopping-cart/assets/62106852/2bfcd22e-5433-44fa-9fda-4880b83183c0">

2023-05-12 01:40 UTC, hectick commented on src/main/java/cart/auth/AuthenticationService.java
> +        }
오호 도메인에게 검증 책임을 넘기는 것이군요

2023-05-12 06:02 UTC, hectick commented on src/main/java/cart/dao/MemberDao.java
> +    Member selectByEmail(final String email);
반영하였습니다!!

2023-05-12 06:03 UTC, hectick commented on src/main/java/cart/dao/dummyData/MemberInitializer.java
> +package cart.dao.dummyData;
그렇겠네요! 분리하겠습니다!

2023-05-12 07:24 UTC, hectick commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
join 쿼리를 이용하도록 하였습니다!!!

2023-05-12 07:25 UTC, hectick commented on src/main/java/cart/domain/entity/CartItem.java
> +    private final long productId;
[위](https://github.com/woowacourse/jwp-shopping-cart/pull/292#discussion_r1187966378)에서 말씀해주신대로 join 쿼리로 변경하면서 CartItem이 Member와 Product를 갖도록 수정해보았습니다~!

2023-05-12 07:34 UTC, hectick commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
경우를 나누어서 생각해 볼 수 있을 것 같습니다.

1. cartItemId 자체가 존재하지 않는 경우
들어온 요청은 cartItem에 대한 요청이고, carItem의 입장에서는 애초에 존재하지도 않는 리소스이기 때문에 따질 권한이 없다고 생각됩니다. 현재 예외 던지는 것을 그대로 사용해도 될 것 같다고 생각됩니다.

2. cartItemId가 존재하는데, 해당 row의 memberId가 요청과 다를경우
권한이 없는 리소스에 대한 접근으로 403으로 처리할 수 있을 것이라 생각됩니다.

그렇다면 일단 두 경우를 나누어서 예외를 던져보도록 하겠습니다!

2023-05-12 07:42 UTC, hectick commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
그런데 권한이 없다고 알려주는 것이 안전한 일 일까요...?

2023-05-12 08:06 UTC, hectick commented on src/test/resources/testData.sql
> +    email    varchar(255)       NOT NULL UNIQUE,
프로덕션 코드에 있는 테이블 정보를 data.sql -> schema.sql 로 이름을 변경하고,
testData.sql에서는 테스트에 사용할 더미 데이터만 넣어두고,
dropTable.sql에서는 테이블을 drop하는 sql을 넣어주도록 수정해봤습니다!

이로써 테스트를에서는 프로덕션코드의 schema.sql로 테이블을 만들고, testData.sql로 더미 데이터를 넣고, dropTable은 테이블을 drop 할때 사용하도록 수정하였습니다!

그런데 각각의 테스트 메서드가 분리된 환경에서 테스트되려면, 테스트 메서드마다  테이블을 한번씩 초기화해줘야해서 테이블을 새로 만드는 것은 불가피한 일이 아닌가요..??

2023-05-12 08:10 UTC, hectick commented
안녕하세요 찰리 제출이 늦어지게 되어 죄송합니다 ㅜㅜ
찰리가 달아주신 리뷰들 반영해보았으니 확인해주세요..!

2023-05-12 11:53 UTC, Gomding commented on src/main/java/cart/service/CartItemManagementService.java
> +        }
좋은 의견이네요!! 
만약 보안상 민감한 부분이라 `넌 권한이 없어` 라는것 조차 힌트가 될 수 있는 상황이라면 400 status code 정도로 응답해줄 수 있겠어요 😄

2023-05-12 12:00 UTC, Gomding commented on src/test/resources/testData.sql
> +    email    varchar(255)       NOT NULL UNIQUE,
테스트 메서드마다 격리된 환경에서 실행하기 위해 메서드마다 DB 를 초기화 시켜줘야하는 것은 맞습니다 :)
(상황마다 다르겠지만 대부분은 초기화가 필요하겠죠)

이때 몇 가지 방법이 있겠네요
- DB 테이블을 전부 삭제하고 다시 생성
- 테스트 메서드 실행 후 사용한 DB 테이블만 초기화 (방을 사용하고 나갈때 정리하고 나가는 느낌)
- 테스트 메서드 실행 전 자신이 사용할 DB 테이블 초기화 (방을 청소하고 작업을 시작)
- DB Truncate 사용

2023-05-12 12:22 UTC, Gomding commented on src/main/java/cart/auth/AuthenticationArgumentResolver.java
> +    }
>  resolver는 별다른 로직없이 그저 요청에 들어있는 값을 이용해서 컨트롤러에 넘길 객체로 매핑만 해주는 용도로 나타난 건가요?

요청에 들어있는 값에 한정 지을 순 없고 컨트롤러에 어떤 객체를 매핑시켜주기위한 용도는 맞다고 생각합니다 😄 
그 외에 더 많은 책임을 가진다면 한 가지 이상의 책임을 가지게 되겠군요 🤔 
특별한 로직을 넣는것은 가능하지만 지양해야하는 패턴이라 생각됩니다!

2023-05-12 12:24 UTC, Gomding commented on src/main/java/cart/config/WebMvcConfiguration.java
> +                .addPathPatterns("/cart/cart-items/**");
잘 이해하고 사용해주셨군요 👍

2023-05-12 13:03 UTC, Gomding requested changes
안녕하세요 이리내!
피드백 반영해주신 부분 확인했어요 👍 
장바구니 미션 요구사항을 만족해서 이만 종료해도 되겠어요 😄 
변경사항이 많았을텐데 고생많으셨습니다!

추가로 궁금한 점 있으시면 언제든 DM 남겨주세요 🙏 
지하철 미션도 화이팅입니다 🔥 🔥 🔥

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/dao/JdbcMemberDao.java
> +    public Optional<Member> selectByEmail(final String email) {
Optional 타입 반환 👍

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/dao/JdbcMemberDao.java
> +            return Optional.empty();
empty Optional 반환 👍

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/dao/JdbcProductDao.java
> +        return Optional.ofNullable(jdbcTemplate.queryForObject(sql, productEntityRowMapper, id));
여기도 조회된 Product 가 없을 때 `Optional.empty()`를 반환하는 것이 어떨까요? 😄

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/service/CartItemManagementService.java
> +                .orElseThrow(() -> new IllegalArgumentException("사용자를 찾을 수 없습니다."));
Optional 처리 👍

2023-05-12 13:03 UTC, Gomding commented on src/test/java/cart/dao/JdbcMemberDaoTest.java
> +            assertThat(memberDao.selectByEmail(member.getEmail())).isEmpty();
반환되는 Optional 값 검증 좋네요! 💯

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/dao/JdbcCartItemDao.java
> +        );
쉽지 않은 변경이었을텐데 고생하셨습니다 👏 👏 👏

2023-05-12 13:03 UTC, Gomding commented on src/main/java/cart/domain/entity/CartItem.java
> +    private final long productId;
simpleInsert 는 사용하기 힘든 구조가 될 것같네요 ㅠㅠ..

2023-05-12 13:04 UTC, merged