[2단계 - 상품 관리 기능] 비버(전인표) 미션 제출합니다
woowacourse/jwp-shopping-cart pull request #293
Opened 2023-05-04 03:02 UTC by ingpyo

안녕하세요 조앤!
이번에 2단계미션을 하면서 controller에서 service로 넘어갈 때 dto를 만들어서 넘겨주는 방식을했는데
이러한 방식을 사용하면서 더 복잡도가 올라가는 것을 느꼈습니다.
그래서 저는 request를 service에서 넘겨주고 메소드 상단에서 도메인으로 바뀌거나 entity로 바뀌는 로직이있게 스스로 규칙을 정해놓고 구현을했습니다!

2023-05-05 01:04 UTC, seovalue requested changes
안녕하세요 비버~ 조앤이에요ㅎㅎ
기한 안에 빠르게 잘 구현해주시는 것 같아요👍 
몇 가지 리뷰 남겼는데 확인 후 다시 리뷰 요청 주세요~

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/authority/Authority.java
> +package cart.authority;
README에 요구사항 및 API 명세 추가해주세요~

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +        return ResponseEntity.noContent().build();
postMapping에 대한 응답으로 noContent를 선택해주신 이유가 궁금해요.

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +            @PathVariable("id") @NotNull(message = "상품 아이디가 비어있습니다.") final Long productId,
`/cart/{id}` 에서 id가 `productId`를 나타내고 있는 부분이 잘 이해가 안되는데요,

현재 유저의 장바구니에 상품을 추가한다는 의미의 API인 것 같은데, 넘겨주는 productId는 요청 body에 담는 것은 어떨까요?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/entity/CartEntity.java
> +    private final Long memberId;
장바구니가 유저당 한개가 아니라, 유저와 product당 하나로 생성해주시는 이유가 궁금해요.

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +    @DeleteMapping("/{id}")
`DELETE /cart/items/{product_id}`
삭제도 이런 식으로 product_id가 들어갈 수 있게 상위에 아이템이라는 리소스를 명시해주는건 어떨까요?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/ProductController.java
> +    private final AdminService adminService;
이거 지금 UI부터 어색해서 ProductController 안에 AdminService가 위치한 것 같은데요. (관리자 페이지에서 상품을 등록할 수 있기 때문)

서버 구현은 UI와 별개로 가져가야한다고 생각해요. UI는 항상 바뀔 수 있기 때문이에요. 상품 컨트롤러에서는 상품을 CRUD할 수 있고, 상품 CRUD의 역할을 하는 서비스는 adminService가 아닌 productService가 더 적합하다고 생각하는데, 어떻게 생각하시나요?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/dto/ProductResponse.java
> +    public ProductResponse(final Long id, final String name, final String image, final Long price) {
Response와 DTO에 대한 명명을 구분하시는 기준이 무엇인가요?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/controller/dto/MemberResponse.java
> +package cart.controller.dto;
dto 안에서도 response/request 패키지 분리해보는 것은 어떨까요?

2023-05-05 01:04 UTC, seovalue commented on src/test/java/cart/controller/CartControllerTest.java
> +    @DisplayName("/cart/{id} post요청 200을 응답한다.")
noContent는 204아닌가용?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +public class AuthorityMemberArgumentResolver implements HandlerMethodArgumentResolver {
argumentResolver를 사용해주신 이유가 궁금해요! interceptor와는 어떤 차이를 갖나요?

2023-05-05 01:04 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = Long.class.isAssignableFrom(parameter.getParameterType());
parameter의 타입까지 확인해주시는 이유가 궁금해요!

2023-05-05 09:31 UTC, ingpyo commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +public class AuthorityMemberArgumentResolver implements HandlerMethodArgumentResolver {
interceptor는 핸들러 메소드 호출 전후에 요청/응답 객체를 가로채어 처리하는 역할을 하고 argumentResolver는 핸들어 메소드 호출 될 때 컨트롤러의 파라미터로 전달되는 인자 객체를 변환하는 기능을 제공합니다!
빈스코프를 활용하면 interceptor를 사용해서 값을 전달받을수 있지만 argumentResolver는 한번에 처리할 수 있다는 장점이있습니다
제가 내린 결론은 검증만을 처리할때는 interceptor를 검증을하고 객체를 반환할때는 argumentResolver를 사용하자고 정했습니다!

조앤의 생각을 듣고싶습니다!!😀

2023-05-05 09:31 UTC, ingpyo commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = Long.class.isAssignableFrom(parameter.getParameterType());
타입을 검증해주는게 안정성이있는 코드인거같아서 parameter의 타입까지 확인해주는 로직을 넣었습니다!

한개의 파라미터에서는 타입검증을 안해줘도 될까요?... 조앤의 생각이 궁금합니다!

2023-05-05 09:31 UTC, ingpyo commented on src/test/java/cart/controller/CartControllerTest.java
> +    @DisplayName("/cart/{id} post요청 200을 응답한다.")
수정했어야됐는데,,, 수정하겠습니다!

2023-05-05 09:31 UTC, ingpyo commented on src/main/java/cart/controller/dto/MemberResponse.java
> +package cart.controller.dto;
패키지 분리하는게 더 가독성이 좋아보이네요,, 분리하겠습니다!

2023-05-05 09:31 UTC, ingpyo commented on src/main/java/cart/controller/dto/ProductResponse.java
> +    public ProductResponse(final Long id, final String name, final String image, final Long price) {
dto는 서비스에서 컨트롤러로 넘겨줄때 사용하는 용도로 만들었고 Response는 컨드롤러에서 웹으로 넘겨주는 용도로 만들었습니다!

2023-05-05 09:32 UTC, ingpyo commented on src/main/java/cart/controller/ProductController.java
> +    private final AdminService adminService;
adminService보다는 productService가 더 적절한 이름 같습니다.... 수정하겠습니다..🥹

2023-05-05 09:32 UTC, ingpyo commented on src/main/java/cart/controller/CartController.java
> +    @DeleteMapping("/{id}")
 DELETE도 body에 담아서 DELETE /cart/items  이런식으로 관리하겠습니다!

2023-05-05 09:32 UTC, ingpyo commented on src/main/java/cart/entity/CartEntity.java
> +    private final Long memberId;
장바구니라고 테이블을 명명하면 하나를 담을때마다 장바구니가 생긴다고 오해할 수 있군요,,,,🥹
cart_product라고 수정하겠습니다!

2023-05-05 09:32 UTC, ingpyo commented on src/main/java/cart/controller/CartController.java
> +            @PathVariable("id") @NotNull(message = "상품 아이디가 비어있습니다.") final Long productId,
body에 담아서 객체로 관리가는게 더 가독성이 높아보입니다! 
수정하겠습니다!

2023-05-05 09:33 UTC, ingpyo commented on src/main/java/cart/controller/CartController.java
> +        return ResponseEntity.noContent().build();
delete에 붙여야되는데 실수를 했습니다...
delete에다 붙인 이유는 더 이상 자원에 접근할 수 없다라는 뜻으로 사용했습니다!

2023-05-05 09:49 UTC, ingpyo commented on src/main/java/cart/authority/Authority.java
> +package cart.authority;
아이고,,, 추가하겠습니다!!

2023-05-06 09:29 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +    @DeleteMapping("/{id}")
오잉! 삭제에서는 지금처럼 {id}로 명시해주는 게 더 좋아보여요! 대신 `cart/{id}` 라고 하면 장바구니 1번을 삭제하는 느낌이라 `cart/items/{id}` 를 말씀드린거였어요!

2023-05-06 09:32 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +public class AuthorityMemberArgumentResolver implements HandlerMethodArgumentResolver {
저도 동의해요~ 👍  객체까지 반환할 때 resolver를 쓰는게 resolver의 역할에 맞는 것 같아요. 엔드포인트로부터 들어온 파라미터를 가공하여 필요한 데이터를 뽑는 용도!

2023-05-06 09:33 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = Long.class.isAssignableFrom(parameter.getParameterType());
아뇨ㅎㅎ resolver 자체가 파라미터를 가공하여 원하는 타입의 데이터를 resolve 하는 것이니, 타입까지 확인해주는 것도 좋아보여요!

2023-05-06 09:41 UTC, seovalue requested changes
안녕하세요, 비버! 조앤이에요ㅎㅎ
리팩터링 잘 해주셨네요👍 요구사항은 만족해서 머지해도 될 것 같은데, 모든 서비스를 crud로 분리해주신 이유가 넘나 궁금해서..ㅎㅎㅎ 
확인 후 다시 리뷰 요청주세요!!

2023-05-06 09:41 UTC, seovalue commented on README.md
> +### 기능
👍

2023-05-06 09:41 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = MemberIdRequest.class.isAssignableFrom(parameter.getParameterType());
Request라는 명칭을 붙이신 이유가 무엇인가요?! request는 외부로부터 들어오는 요청을 의미한다고 생각하는데, 현재 동작상으로는 애노테이션과 타입이 일치하면 내부적으로 멤버를 resolve 해오는 것 같아서요,

2023-05-06 09:41 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +    private final ProductReadService productReadService;
갑자기 서비스를 전부 CRUD로 분리해주신 이유가 무엇인가요..?

2023-05-06 09:41 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +            @RequestBody @Valid final CartItemCreationRequest productId,
변수명도 바꿔볼까요~

2023-05-06 09:41 UTC, seovalue commented on src/test/java/cart/service/product/ProductDeleteServiceTest.java
> +        final ProductCreationRequest productCreationRequest = new ProductCreationRequest("땡칠", "asdf", 100L);
테스트에서 공통으로 사용되는 테스트용 객체의 경우에는 TestFixture로 분리해볼 수 있어요.

2023-05-06 12:31 UTC, ingpyo commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = MemberIdRequest.class.isAssignableFrom(parameter.getParameterType());
제가 질문을 이해한 내용은 Resolver가 가공을해서 controller에 넘겨주니까 Request라는 네이밍 대신 MemberId를 하는게 더 적절하다.
라고 이해했는데 맞나요 조앤?...🥹🥹🥹🥹🥹🥹🥹

2023-05-06 12:31 UTC, ingpyo commented on src/main/java/cart/controller/CartController.java
> +    private final ProductReadService productReadService;
나중에 특정기능(ex:저장할 때 할인 적용)을 유지보수를 할 때 기능마다 서비스를 나누는게 더 유지보수 측면서에 좋다고 생각해서 분리해주었습니다!

2023-05-06 12:31 UTC, ingpyo commented on src/main/java/cart/controller/CartController.java
> +            @RequestBody @Valid final CartItemCreationRequest productId,
수정하겠습니다!!😀

2023-05-06 12:31 UTC, ingpyo commented on src/test/java/cart/service/product/ProductDeleteServiceTest.java
> +        final ProductCreationRequest productCreationRequest = new ProductCreationRequest("땡칠", "asdf", 100L);
fixture를 한번도 적용안해봤는데 적용해보겠습니다!!

2023-05-06 14:27 UTC, seovalue commented on src/main/java/cart/authority/AuthorityMemberArgumentResolver.java
> +        boolean hasMemberType = MemberIdRequest.class.isAssignableFrom(parameter.getParameterType());
넵 제 의도는 그게 맞아요!

2023-05-06 14:33 UTC, seovalue commented on src/main/java/cart/controller/CartController.java
> +    private final ProductReadService productReadService;
@ingpyo 그럼 만약 findOrCreate를 하게 되는 경우면 어디에 속해야할까요? findOrUpdate라면? ifExistsContinueElseDelete라면?ㅎㅎ 

보통 Write/Read 두가지로 나누는 경우는 있는데요, CQRS라고 하기도 해요. 이렇게 나누는 주된 이유는 대부분의 서비스는 read가 주로 이루어지기 때문에, 읽기용 DB를 분리해두어서 성능 향상을 도모하는 등의 이유가 있어요. 

그리고 또는 말씀해주신 케이스처럼 `저장할 때 할인 적용`과 같은 비즈니스 로직에 따라 유즈케이스를 분리하는 경우도 있어요. 

지금은 사실 비즈니스 로직이 복잡하지 않기 때문에, 굳이 c,r,u,d를 모두 나눌 필요는 없다고 생각해요. 오히려 제가 위에 예시로 들었던 케이스가 요구사항으로 나온다면 어디에 넣어야할지, 상위에 c,d를 갖는 서비스를 하나 더 만들어야할지 등 더 복잡해질 수도 있다는 생각이 듭니다! 컨트롤러 한개당 항상 최소 4개의 서비스를 가지게 될거예요

2023-05-06 14:35 UTC, seovalue approved these changes
안녕하세요 비버ㅎㅎㅎ 조앤이에요
남겨주신 질문에 저도 답변 남겼어요. 다음 미션 하시면서도 고민해보시면 좋을 것 같아요~
고생 많으셨어요!

2023-05-06 14:35 UTC, seovalue commented on src/test/java/cart/fixture/ProductEntityFixture.java
> +    public static final ProductEntity TEST_PRODUCT_BEAVER_ENTITY_ID = new ProductEntity(1L, "비버", "A", 1000L);
오홍 👍  변수명도 반환값과 일치하게 지어주시면 더 좋을 것 같아요!

2023-05-06 14:35 UTC, merged