[2단계 - 상품 관리 기능] 애쉬(정설희) 미션 제출합니다
woowacourse/jwp-shopping-cart pull request #296
Opened 2023-05-04 07:56 UTC by xxeol2

2023-05-06 04:26 UTC, KIMSIYOUNG requested changes
안녕하세요 애쉬
2단계 잘 구현해주셨네요.
리뷰가 늦어 죄송합니다.
몇가지 코멘트 남겼는데 확인 부탁드립니다!

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/test/java/cart/controller/api/CartApiControllerTest.java
> +    void getCartProducts() {
깨지는 테스트가 있네요 확인 부탁드려요!

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +public class LoginArgumentResolver implements HandlerMethodArgumentResolver {
깔끔하게 잘 구현해주셨네요. 로그인 리졸버에서 하는 역할이 많은 것 같아요. 
해당 리졸버는 꺼내온 값을 통해 `Member`만 리졸빙해주고, BasicTokenExtractor, BearerTokenExtractor 와 같은 클래스들이 각 타입에 맞는 추출방법을 제공하는게 어떨까요?

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/WebViewController.java
> +public class WebViewController {
API, WebView 와 같은 네이밍을 작성해주셔서 구분하기가 쉽네요👏

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/service/CartService.java
> +                    throw new IllegalArgumentException("이미 장바구니에 담은 상품입니다.");
이렇게 작성하게 되면, 요청이 동시에 오는 경우 정합성을 지키기 어려울 수도 있어요.

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/service/MemberService.java
> +            throw new UnauthenticatedException();
인증과 회원의 개념이 혼재되어 있는 것 같아요. 

LoginResolver 에서 인증처리를 수행할 때 사용하지만 , `Member`Service 이기때문에 findByEmailAndPassword 정도의 기능을 제공하는게 아닐까요?

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/service/ProductService.java
> +    public void update(final long id, final String name, final int price, final String imageUrl) {
모두 원시형으로 변경해주신 이유가 무엇일까요?

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/service/CartService.java
> +    public List<Product> findCartProducts(final Member member) {
좋은 고민을 하고 계신 것 같습니다. 말씀하신대로 서비스에서 특정 응답값을 한정하게 되면, 요청하나와 1:1 매칭되는 형태가 되는 것 같습니다.
일반적인 답변이란 없겠지만(저도 어떤 `API` 성격을 가지고 있는가에 따라 다르게 구현하고 있습니다.) 현재 구조에서는 서비스가 도메인을 반환하도록 하는게 조금 더 많은 처리가 가능할 것 같아요.
이에 대한 대안으로 컨트롤러와 서비스 사이에 하나의 레이어를 더 둘 수도 있고 말씀하신대로 서비스와 컨트롤러 사이에 DTO를 따로 두고, 실제 응답은 별도 DTO를 두는 방법 등 방법이 많을 것 같아요. 다만 현재는 서비스에서 도메인을 반환하고 컨트롤러에서 이를 변환해주어도 충분할 것 같습니다.

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/test/java/cart/service/CartServiceTest.java
> +        assertThatThrownBy(() -> cartService.delete(member, productId))
이런 테스트는 말씀하신대로 큰 의미를 가지긴 어려운 테스트인 것 같아요. 
다만 구현이 변경되었을 때 이 테스트가 터지면서 테스트를 다시 짜야한다는 걸 인지할 순 있겠죠?
테스트도 결국은 들어간 비용대비 더 많은 것을 뽑을 수 있도록 작성하는게 중요한 것 같아요.
이 테스트도 절대 무의미하다고 볼 순 없지만 저는 시간이 없다면 굳이 작성하지 않을 것 같습니다.

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public Member resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
말씀하신 것은 레벨1에서 학습하셨던 SRP와 연관되는 것 같아요. 
현재 클래스는 아래의 2가지 일을 모두 하고 있는 것이구요. 다만 기능이 복잡하지 않기에 한 곳에서 두가지를 처리해도 충분할 것 같다는 생각이에요.
Base64를 디코딩하는 작업은 1번을 수행한 이후 요청에 담아주면 2번 리졸버에선 그 요청값을 기반으로 바로 MemberService.login을 호출할 수 있을 것 같아 문제일 것 같진 않네요.
역할을 분리해줄 것인지, 굳이 분리할 필요 없다에 따라 결정하면 될 것 같아요.

1. 요청을 추출하여 올바른 토큰인지 확인
2. 요청값을 기반으로 사용자를 리졸빙

2023-05-06 04:26 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public LoginArgumentResolver(final MemberService memberService) {
리졸버에 대한 테스트 코드는 없는 것 같아요!

2023-05-07 14:28 UTC, xxeol2 commented on src/test/java/cart/controller/api/CartApiControllerTest.java
> +    void getCartProducts() {
<img width="748" alt="스크린샷 2023-05-07 오후 11 28 20" src="https://user-images.githubusercontent.com/71129059/236683621-f7143908-0ef4-4800-9652-494b620be89b.png">
제 로컬에서는 깨지는 테스트를 확인할 수 없어서, 혹시 어떤 테스트가 깨졌는지 알려주실 수 있나요 ? 🥺🥲

2023-05-08 03:24 UTC, xxeol2 commented on src/main/java/cart/service/MemberService.java
> +            throw new UnauthenticatedException();
인증 관련 기능은 AuthService로 분리해줬습니다 !!

2023-05-08 03:28 UTC, xxeol2 commented on src/main/java/cart/service/CartService.java
> +                    throw new IllegalArgumentException("이미 장바구니에 담은 상품입니다.");
synchronized 키워드를 활용하도록 수정했습니다 !!
하지만 해당 키워드를 사용하게 된다면, 여러명의 사용자가 동시에 요청을 보냈을 때 대기시간이 걸리고 성능이 저하될 것 같은데 이러한 문제를 어떻게 해결할 수 있을까요?..

2023-05-08 03:29 UTC, xxeol2 commented on src/main/java/cart/service/ProductService.java
> +    public void update(final long id, final String name, final int price, final String imageUrl) {
null인 id가 들어오는 것을 방지하기 위해 원시형으로 변경해주었습니다!

2023-05-08 04:59 UTC, xxeol2 commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +public class LoginArgumentResolver implements HandlerMethodArgumentResolver {
Resolver와 BasicAuthorizationExtractor를 분리해줬습니다!
현재 BasicLogin 방식만 지원하기 때문에, AuthorizationExtractor 인터페이스를 추상화하는 것은 비용이 든다고 판단했습니다.
이 때, BasicAuthorizationExtractor는 단순 디코딩 역할을 담당해 유틸 클래스처럼 느껴져서 static 함수를 활용했는데 이 방식에 대해 어떻게 생각하시는지 궁금합니다!
추가로, BasicAuthorizationExtractor에서 UnauthenticatedException을 throw해주는 방식에 대해서도 괜찮은지 여쭤보고 싶습니다!

2023-05-08 07:11 UTC, xxeol2 commented on src/main/java/cart/service/CartService.java
> +    public List<Product> findCartProducts(final Member member) {
조금 더 복잡해지면 아무래도 서비스와 컨트롤러간 DTO를 도입하는 방법이 가장 적합할 것 같네요 ..!
지금 구조에서는 하나의 응답이 하나의 도메인과 연관되어있기때문에 Domain을 반환하는 구조로 유지하겠습니다 !!
감사합니다 🙇🏻‍♀️

2023-05-08 07:15 UTC, xxeol2 commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public Member resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
Extractor 클래스를 분리해봤습니다.
여전히 Interceptor는 도입하지 않았는데요, Interceptor에서는 리턴값이 boolean/void이기 때문에 디코딩한 후 요청에 담아주는 방법을 활용할 수 없다고 판단했기때문입니다 !
혹시 카일은 1번 과정을 Interceptor에서 진행하시는 편인가요, Resolver에서 (별도의 클래스의 메서드를 활용하는 등의 방식으로)함께 진행하시는 편인가요 ?!

2023-05-08 08:02 UTC, xxeol2 commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public LoginArgumentResolver(final MemberService memberService) {
LoginArgumentResolverTest를 추가해줬습니다!
그런데 이 때, 테스트를 위한 LoginArgumentResolverTestController를 별도로 생성하고 빈 등록을 해줬는데 해당 방법이 적합한 방법인지 궁금합니다..!!

2023-05-09 07:26 UTC, KIMSIYOUNG commented on src/test/java/cart/controller/api/CartApiControllerTest.java
> +    void getCartProducts() {
아 요거 제 로컬 파일때문에 그랬던거였네요..죄송합니다

2023-05-09 07:36 UTC, KIMSIYOUNG approved these changes
안녕하세요 애쉬!
리뷰 잘 반영해주셨네요.
이번 미션은 여기서 머지해도 충분할 것 같습니다.
궁금하신 내용이나 더 이야기 나누고 싶은 내용이 있으시다면 디엠 주세요.
고생하셨습니다

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/extractor/BasicAuthorizationExtractor.java
> +            throw new UnauthenticatedException();
이렇게 예외를 던져도 무관할 것 같습니다. 다만 조금 더 정확하게 하자면 
Extractor는 변환 실패에 대한 예외를 던지는게 맞을 것 같고, 그걸 사용하는 쪽에서 인증실패로 처리하는게 조금 더 정확한 표현일 것 같아요.

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/service/CartService.java
> +                    throw new IllegalArgumentException("이미 장바구니에 담은 상품입니다.");
DB에 유니크 키를 활용해보면 어떨까요?

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/service/ProductService.java
> +    public void update(final long id, final String name, final int price, final String imageUrl) {
null인 경우에 대해서 방어로직을 작성해주는게 좋지 않을까요? null로 들어온 값을 long으로 받으면 0으로 할당되는데 예상치못한 동작이 있을 수도 있을 것 같아요.

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public Member resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
저는 1번으로 진행할 것 같고 아래의 두가지 방법중 첫번째로 진행할 것 같습니다. 

1. 요청값 내부에 임의로 값을 설정해서(request.setAttribute) resolver에서 그 값을 꺼내와서 사용하는 형태로 구현할 수 있을 것 같아요.
2. 또는 중복된 로직을 사용해서 값을 꺼내올 수도 있을 것 같습니다.

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/LoginArgumentResolver.java
> +    public LoginArgumentResolver(final MemberService memberService) {
현재 작성하신 방법으로 해주셔도 충분할 것 같습니다. 다만 구현도 조금 더 공부할겸 LoginArgumentResolver에서 필요한 파라미터를 목으로 설정하고 각 값을 어떻게 넣어줘야 동작하는지 학습해보시는 것도 괜찮을 것 같네요

2023-05-09 07:36 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/extractor/BasicAuthorizationExtractor.java
> +    public static BasicAuthInfo extract(final String header) {
static 하게 구현해도 충분할 것 같습니다. 말씀하신대로 성급한 추상화라고 볼 수도 있겠네요🙂

2023-05-09 07:36 UTC, merged