[2단계 - 상품 관리 기능] 오리(오현서) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #299
Opened 2023-05-04 08:39 UTC by carsago

안녕하세요 빙봉 이번 리뷰도 잘부탁드립니다.

2단계를 진행하면서 아쉬운게 많아졌네요.

돌이켜보면 Spring으로 진행한 Level 2의 모든 미션을 전 ```객체 중심의 설계가 아닌 테이블 중심의 설계를 한 것 같아요.```

구현을 하고 지나서 알게됐지만, DB가 붙어있지 않은 미션이였다면 이런식으로 도메인 객체를 설계하지 않았을텐데.. 라는 생각이 듭니다.

물론 관계형 DB와 객체간의 불일치는 어쩔 수 없는거지만, Level 1에서 계속 학습했던 것이 OOP에 관한 부분이기에 객체 중심으로 접근 하여서 설계를 했으면 더 좋았을 것 같아요. 지금은 사용하고 있지 않지만 ORM과 같이 이런 불일치를 어느정도 해소해주는 기술들이 많으니까요!

PR을 제출하고 난 후 도메인 객체를 먼저 짜고 객체들을 바탕으로 테이블을 설계하는 식으로 고민을 더 해볼 예정입니다.!

2023-05-05 10:08 UTC, aegis1920 requested changes
안녕하세요 오리! 빙봉입니다 🙂 

2단계 구현 잘해주셨어요! 👍 

코멘트와 궁금한 점 남겼으니 확인 부탁드려요!

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/config/LoginArgumentResolver.java
> +            throw new UnauthorizedException("Authorization Header는 'BASIC ****'과 같은 값으로 전달되어야 합니다.");
예외 문구에 `AUTHORIZATION_HEADER_PREFIX`을 그대로 활용해도 될 것 같네요!

2023-05-05 10:08 UTC, aegis1920 commented on src/main/resources/data.sql
> +CREATE TABLE if not exists MEMBER
테이블을 생성하는 건 `schema.sql`에 작성하는 것이 더 적절해보입니다!

2023-05-05 10:08 UTC, aegis1920 commented on src/main/resources/templates/myCart.html
html 파일 명은 어떤 게 좋을 지 고민해보시죠! ([링크](https://www.thoughtco.com/naming-html-files-3466503))

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/dao/CartProductDao.java
제네릭으로 인터페이스를 만들어줘도 좋을 것 같아요! ([링크](https://www.baeldung.com/java-dao-pattern))

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/dao/CartProductDao.java
> +                     Long productId) {
```suggestion
    public Long save(Long memberId, Long productId) {
```

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/domain/CartProduct.java
> +package cart.domain;
> 돌이켜보면 Spring으로 진행한 Level 2의 모든 미션을 전 `객체 중심의 설계가 아닌 테이블 중심의 설계를 한 것 같아요.`

말씀하신대로 테이블 중심의 설계라면 이 부분은 패키지가 domain이 아닌 entity에 더 가깝겠네요 🙂 

> 구현을 하고 지나서 알게됐지만, DB가 붙어있지 않은 미션이였다면 이런식으로 도메인 객체를 설계하지 않았을텐데.. 라는 생각이 듭니다.

DB가 붙어있지 않다는 건 persistent layer가 없다는 의미와 같다고 생각하는데요. DB가 붙어있지 않다는 미션은 자동차 경주 같은 미션(웹X)을 의미하는 걸까요?

만약 DB가 붙어있지 않다고 했을 때 어떤 식으로 도메인 객체를 설계하셨을 지 간단하게나마 설명해주실 수 있을까요?

> PR을 제출하고 난 후 도메인 객체를 먼저 짜고 객체들을 바탕으로 테이블을 설계하는 식으로 고민을 더 해볼 예정입니다.!

기대가 되네요! 👍

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/config/LoginArgumentResolver.java
> +    private final MemberDao memberDao;
LoginArgumentResolver가 MemeberDao와 Member에 의존하고 있는 상황인데요. 어떻게 하면 의존을 줄일 수 있을까요?

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/controller/CartApiController.java
> +    public ResponseEntity<List<CartProductResponse>> findCartProductsByMember(@Login Member member) {
domain이 Controller 레이어까지 올라와있는데요. 더 나은 설계가 있지 않을까 싶어요. 어떤 방법이 있을까요?

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/config/LoginArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
헤더를 가져오고 validation하는 로직을 이쪽에 구현하신 이유가 궁금해요. Filter, ArgumentResovler, Interceptor 등 여러 가지 방법이 있는데요. ArgumentResovler에 구현하신 이유가 있을까요?

2023-05-05 10:08 UTC, aegis1920 commented on src/test/resources/test_data.sql
마찬가지로 schema.sql이 더 나을 것 같아요!

2023-05-05 10:08 UTC, aegis1920 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
👍

2023-05-05 10:08 UTC, aegis1920 commented on src/test/java/cart/dao/CartProductDaoTest.java
> +    private static final String MEMBER_INSERT_SQL = "insert into member(id, email, password) values (?, ?,?)";
Test를 위한 SQL을 따로 작성하신 거 너무 좋네요 👍 SqlTestSupporter 이런 식으로 빼서 따로 만들어줘도 좋을 것 같습니다!

2023-05-05 10:08 UTC, aegis1920 commented on src/test/java/cart/dao/MemberDaoTest.java
> +                .hasMessage("해당하는 email의 member가 존재하지 않습니다.");
hasMessage로 너무 정확하게 판별하면 예외 메시지와 의존도가 너무 강하더라고요ㅎㅎ `hasMessageContaining`으로 작성해주는 것도 좋을 것 같아요 🙂

2023-05-06 13:16 UTC, carsago commented on src/main/resources/data.sql
> +CREATE TABLE if not exists MEMBER
이 부분도 나누는게 더 좋겠네요!

2023-05-06 13:16 UTC, carsago commented on src/main/resources/templates/myCart.html
이건 너무 후다닥 치우고 넘어 가버렸었네요 ㅎㅎㅠ

2023-05-06 13:18 UTC, carsago commented on src/test/java/cart/dao/MemberDaoTest.java
> +                .hasMessage("해당하는 email의 member가 존재하지 않습니다.");
이 부분도 지금은 단순하게 메시지를 던져줘서 티가 안나지만, ```클라이언트의 입력값을 전달해줘!`` 와 같이 더 디테일한 메시지를 주는 식으로 바뀐다면 변경에 어려움이 있을 것 같네요!

2023-05-06 18:29 UTC, carsago commented on src/main/java/cart/config/LoginArgumentResolver.java
> +    private final MemberDao memberDao;
AuthService라는 부분을 만들어봤어요! 추가 푸쉬한 코드에 자세한 제 생각, 고민을 달아놓을게요!

2023-05-06 18:29 UTC, carsago commented on src/main/java/cart/controller/CartApiController.java
> +    public ResponseEntity<List<CartProductResponse>> findCartProductsByMember(@Login Member member) {
이 부분도 별도의 객체가 있으면 괜찮을 것 같아요

2023-05-06 18:29 UTC, carsago commented on src/main/java/cart/config/LoginArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
이 부분도 위의 질문과 함께 추가 코드에, 같은 맥락으로 코멘트를 남길게요!

2023-05-06 19:13 UTC, carsago commented on src/main/java/cart/auth/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
처음에는 가장 단순하게 ArgumentResolver에 인증 관련 모든 로직을 넣어놨었어요. 그게 가장 간단하고, 객체의 책임을 분리하는 건 좋지만 그로인해 과도하게 클래스가 많아지다면, 이번 미션은 정말 단순한 어플리케이션임에도, 로직이 복잡해진다고 느꼈기 때문이에요.

하지만 저도 내심으로 그렇고, 다른 크루들과 이야기하며 내린 결론은 `header를 파싱하고 회원 등록 유무등을 판단하는 건ArgumentResolver의 역할이 아니다.` 라는 것이였어요.

ArgumentResolvers의 역할은 파라미터를 받아서 원하는 객체로 전달해주는 것이고 특히, ArgumentResolver는 이미 스프링에 존재하고, 사용되는 것이기 때문에 제가 마음대로 책임을 확대하거나 축소하는 것은 안된다고 판단했어요.

그래서 파싱과 검증 부분을 Interceptor 분리하고, ArgumentResolver는 단순히 원하는 객체를 뱉어주는 역할만 하게 전환했습니다.

`여기서 Interceptor를 사용하냐, Filter를 사용하냐를 고민했는데요. 저는 Interceptor를 활용하기로 했어요.`

현재 인증을 진행하기 위해선 Parse하는 작업도 있지만, email에 해당하는 회원의 존재 여부, 패스워드의 일치여부를 판단해야하는데, 이를 결국 특정한 Service나 Dao등 스프링 빈에 의존해야하기 때문에 Filter 보다는 Interceptor를 활용하는게 더 좋다고 고려했습니다. 예외 핸들링 같은 부분도 있고요.

다만 이런 부분이 명확하다고는 느끼지 않아요. 사실 블로그나 스택오버플로우등의 포스팅을 보면서, `Filter는 어떤 경우에.. Interceptor는 어떤 경우에..` 관련된 내용을 읽고 추상적인 수준의 느낌은 알았으나, 어떤 부분에 필터를 활용할지, 인터셉터를 활용할 지는 제가 이후에 더 복잡하고, 많은 로직이 들어가는 어플리케이션을 다루면서, 실제로 경험을 하고 스스로 선택을 해야 조금씩 감을 잡을 수 있을 것 같아요!

2023-05-06 19:13 UTC, carsago commented on src/main/java/cart/auth/AuthInterceptor.java
> +    private final CredentialThreadLocal credentialThreadLocal;
# 

Interceptor가 ArgumentResolver에 어떻게 값을 넘겨주지? 라는 고민이 있었는데 제가 알게 된 방법은 3가지입니다.

1. request에 필요한 값을 넣기
2. ThreadLocal 활용하기(택한 방법)
3. RequestScope와 같은 web Scope 활용

우선 1번 방법은 가장 먼저 제외하였어요.

첫번째 이유는 HTTP Request 라는 것은 하나의 규약인데 여기에 내가 편하자고 마음대로 값을 추가(변경) 해도 될까? 라는 점

두번째는 클라이언트가 넘겨준 값을 마음대로 수정해도 될까? 라는 점 때문에 택하지 않았어요.

여기서 저는 ThreadLocal 방식을 택했는데요.

이는 ThreadLocal은 사용한적은 없지만 그래도 알고 있었던 개념이고, web scope는 2단계를 수행하면서 처음으로 접한 개념이였기에 그나마 조금이라도 알던 것을 활용하면서 더 학습하자!! 라는 느낌으로 마음이 더 간 부분이 있었습니다.

다만 이런 방법을 사용할 때 제가 파악한 문제점은 ThreadLocal은 스레드풀에 반납해서 다시 사용되기 때문에 사용하기 값을 지워주지 않으면 위험하다. 하나의 request가 단일 스레드를 보장할 수 있는가? 라는 부분인데요.

이러한 부분과 Request Scope에 대한 추가적인 학습은 다음주가 오면 크루들과 이야기 하면서 수행하면 좋을것 같아요.

특히 Request Scope를 택한 크루들에게 이 기능을 구현하기 위해 왜 그런 방법을 사용했는지, 현재 로직에서 어떤 장점이 있는지, 그렇다면 단점은 없는지 물어보면서요!

2023-05-06 19:14 UTC, carsago commented on src/main/java/cart/auth/BasicAuthParser.java
> +public class BasicAuthParser {
가능하다면 수월한 단위 테스트를 위해 HTTP 요청에 의존하지않도록 분리하는 것이 좋다고 느꼈어요!

이후의 미션에서도 과한 의존을 벗어내서 테스트를 쉽게 할 수 있는 방법이 있다면, 최대한 나누는 방법을 찾아 볼 것 같네요

2023-05-06 19:27 UTC, carsago commented on src/main/java/cart/domain/CartProduct.java
> +package cart.domain;
제가 만약 콘솔 게임을 짜듯이 이번 미션을 설계 했다면
Cart라는 객체를 만들고 이 객체가 List로 Product (혹은 일급컬렉션)를 가지게 만들었을 것 같아요.

그렇게 된다면 이후에 요구사항이 추가되었을 때, (예를 들어 장바구니에 담은 상품들의 가격의 합을 계산하라)
적합한 책임을 가진 도메인 객체가 이를 수행할하여 변경에 있어서 상대적으로 어려움이 없을테니까요.

다만 지금 제가 설계한 도메인 객체들은 테이블의 설계에 맞춰 단순히 값을 찍어주기 위한 목적이다 보니, 이러한 역할을 수행하기 어렵다고 보입니다. 그래서 도메인 객체를 먼저 짜고 테이블을 설계하는 방식을 생각해보았는데요..

지금 상황에서 너무너무 어렵게 느껴지네요... 조금 코드를 수정하다가 `이건 아니다`라고 느껴서 원상복구 시켰습니다.
dao에서 join을 해주는 것도 그렇고, 도메인 객체로 매핑하기 위해 여러개의 dao에 의존하는 repository도 필요할 것 같고.. 코드 구조 자체가 필요 이상으로 복잡해질 것이라 느껴졌어요.

그렇게 복잡하게 수정을 하더라도 테이블의 변경에 따라 도메인 객체가 변경된다는 문제점도 발생하고요. 그렇게 하면 또 entity와 domain 객체를 분리하고 싶다는 욕구가 생길 것 같네요.

2023-05-06 19:32 UTC, carsago commented
안녕하세요 빙봉! 리뷰 잘부탁드립니다.

추가 변경사항은 리뷰에서 짚어주신 부분 위주로 수행하게 됐어요. 
디테일한 내용은 코멘트를 남겼습니다!!

2023-05-06 19:37 UTC, carsago commented on src/main/java/cart/service/AuthService.java
> +public class AuthService {
전반적인 Auth 클래스들의 패키지가 고민이네요
이 서비스는 MemberDao에 의존하기 때문에 Service로 갔지만, 맞나 싶기도하고, 다른 클래스들도 고민이 듭니다!

2023-05-06 21:11 UTC, carsago commented on src/main/java/cart/dao/CartProductDao.java
이 부분은 현재 모든 DAO가 CRUD 쿼리가 존재하는것이 아니라서 적용 하진 않았는데 되게 좋은 방식 같네요!!

2023-05-07 14:31 UTC, aegis1920 requested changes
안녕하세요 오리! 빙봉입니다 🙂 

구현 정말 잘해주셨습니다! 👍 질문에 대한 답변 및 간단한 코멘트 남겼는데요. 이미 요구사항을 충분히 만족했지만 반영하시면 오리에게도 좋을 것 같아서요! 다시 리뷰요청 보내주시면 머지할테니 부담 갖지 않으셨으면 합니다ㅎㅎ

궁금한 점이 있다면 언제든 편하게 DM 주세요!

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +    private ThreadLocal<Credential> local = new ThreadLocal<>();
- local이라는 변수명 말고 Credential이 들어간 변수명이 좋을 것 같아요!
- `@Component`가 아닌 static으로 만들어도 되지 않을까요?

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/dto/response/CartProductResponse.java
> +    private final Long Id;
여기만 Id로 되어있네요?

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/persistnece/dao/CartProductDao.java
> +    private RowMapper<CartProduct> rowMapper = (resultSet, rowNum) -> new CartProduct(
여기만 final이 안 붙어있군요ㅎㅎ

2023-05-07 14:31 UTC, aegis1920 commented on README.md
> +#### 상품 API
README 정리가 한 번 필요하겠네요 🙂

2023-05-07 14:31 UTC, aegis1920 commented on src/main/resources/schema.sql
> +    FOREIGN KEY (member_id) REFERENCES MEMBER (id) on delete CASCADE,
외래키를 사용하신 이유가 있을까요?

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/auth/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
> 현재 인증을 진행하기 위해선 Parse하는 작업도 있지만, email에 해당하는 회원의 존재 여부, 패스워드의 일치여부를 판단해야하는데, 이를 결국 특정한 Service나 Dao등 스프링 빈에 의존해야하기 때문에 Filter 보다는 Interceptor를 활용하는게 더 좋다고 고려했습니다. 예외 핸들링 같은 부분도 있고요.

👍 👍 

> 다만 이런 부분이 명확하다고는 느끼지 않아요. 사실 블로그나 스택오버플로우등의 포스팅을 보면서, Filter는 어떤 경우에.. Interceptor는 어떤 경우에.. 관련된 내용을 읽고 추상적인 수준의 느낌은 알았으나, 어떤 부분에 필터를 활용할지, 인터셉터를 활용할 지는 제가 이후에 더 복잡하고, 많은 로직이 들어가는 어플리케이션을 다루면서, 실제로 경험을 하고 스스로 선택을 해야 조금씩 감을 잡을 수 있을 것 같아요!

맞습니다! 이 부분은 실제로 경험을 해봐야 어떤 것을 사용할 지 아실거예요. 실무에서도 Filter와 Interceptor, ArgumentResolver 모두 스프링에서 지원해주는 게 있기 때문에 필요한 부분에 한해서 상속한 후 구현해서 사용하는 게 대부분입니다 🙂

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/auth/AuthInterceptor.java
> +    private final CredentialThreadLocal credentialThreadLocal;
👍 👍 request에 특정 값을 간편하게 추가하기 위해서는 저는 1번 방법도 괜찮다고 생각하지만 request에 있는 값을 계속해서 옮겨가야한다는 부분에서 실용적이지 않을 것 같아요. 3번은 제가 사용해본 적이 없어서 잘 모르겠네요 😅

> 다만 이런 방법을 사용할 때 제가 파악한 문제점은 ThreadLocal은 스레드풀에 반납해서 다시 사용되기 때문에 사용하기 값을 지워주지 않으면 위험하다. 하나의 request가 단일 스레드를 보장할 수 있는가? 라는 부분인데요.

Interceptor에서 set하셨다면 HandlerInterceptor.afterCompletion()를 overrride해서 ThreadLocal.remove()를 실행해주면 좋을 것 같아요! 그러면 문제가 해결되지 않을까요?

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/service/AuthService.java
> +public class AuthService {
Auth는 도메인 자체가 분리되어야할 것 같아요. 인증도 여러 가지 방법으로 가능하기 때문에 모듈 자체가 분리되어야된다고 생각합니다 🙂 (지금 단계에서는 그대로 두셔도 됩니다! 추후 프로젝트 진행하실 때 한 번 해보세요!)

2023-05-07 14:31 UTC, aegis1920 commented on src/test/java/cart/auth/BasicAuthParserTest.java
테스트 대단합니다 👍 👍 고생 많으셨어요!

2023-05-07 14:31 UTC, aegis1920 commented on src/main/java/cart/domain/CartProduct.java
> +package cart.domain;
정말 잘 파악하셨네요! 👍 ORM을 쓰더라도 entity와 domain 객체간의 불일치를 완벽하게 해결해주지 못합니다. 이런 이유로 entity와 domain을 분리하는 팀도 있고 한 곳에 두는 팀도 있고요ㅎㅎ 미션 진행하시면서 지속적으로 고민이 필요한 주제라고 생각해요 🙂

2023-05-08 07:46 UTC, carsago commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +    private ThreadLocal<Credential> local = new ThreadLocal<>();
굳이 Bean일 필요가 없는 클래스를 Bean으로 관리할 필요는 없을 것 같네요
사실 대부분의 utils에 가까운 클래스들은 빈이 아니라 static하게 활용해도  별 차이가 없을 것 같아요.
다만 이들을 static 하게 했을때, 이후에 테스트라던가 Mocking 하는데 어려움이 있을 수도 있지 않을까요? 
(물론 지금 이 클래스는 당장 모킹할 이유가 없긴 합니다.)

빙봉은 특정한 클래스는 static 하게, 특정한 클래스는 빈으로.. 이를 선택하는 기준등이 있으신가요?

2023-05-08 08:00 UTC, carsago commented on src/main/resources/schema.sql
> +    FOREIGN KEY (member_id) REFERENCES MEMBER (id) on delete CASCADE,
우선 일반적으로 알려진 방법이라 FK를 사용했습니다. 다만 FK를 설정한다면 분명히 단점이 있을 것 같아요. 저도 확실히 테스트 하기 어렵다는 것을 느꼈구요. 다만 ```실무에서는 어떻게 할까?, 굳이 설정하지 않아도 될까?``` 라는 부분에 확신이 없었어요.

물론 지금도 확신이 있는 건 아니지만, 다른 크루들의 리뷰를 보니, 설정하지 않는 경우도 많다고 해서, 다음 미션(지하철)에서는 FK를 설정하지 않는 것을 고려할 것 같아요. 아무래도 도메인의 특성상 너무 많은 FK가 엮여 있어서 테스트하기가 너무 어려울 것이다 라는게 느껴지거든요.

물론 정합성 같은 부분에서 위험성이 없는건 아니지만, 프레임워크등을 활용해 자바 코드의 영역에서 충분히 체크해줄수 있지 않을까? 라는 생각도 듭니다.

2023-05-08 08:01 UTC, carsago commented
안녕하세요 빙봉! 이번에도 남겨주신 코멘트 위주로 수정을 하였고, 답변에 대해 생각하는 식으로 학습을 하였습니다.
리뷰 잘 부탁드려요!!

2023-05-08 15:04 UTC, aegis1920 commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +    private ThreadLocal<Credential> local = new ThreadLocal<>();
음.. 딱히 선택하는 기준은 없고 스프링 컨테이너에 관리되도록 해서 하나의 빈으로 생명주기를 가지고 가고 싶으면 빈으로 만드는 것 같네요. 다만 가급적이면 빈으로 만들지 않으려고 합니다. 빈이 많아지면 빈 초기화 시간이 늘어나서 빌드가 길어질테고 통합테스트 시 테스트도 느려지게 됩니다. 더불어 빈이 늘어나면 스프링 컨테이너가 관리할 일이 더 많아진다는 것이고 또 의존성이 복잡해질텐데 그러면 유지보수에 어려움을 겪을 일 또한 많아질 수 있다는 걸 의미할테니까요.

static을 Mocking하는 MockedStatic이라는 것도 있으니 한 번 보시면 좋을 것 같네요!

2023-05-08 15:06 UTC, aegis1920 commented on src/main/resources/schema.sql
> +    FOREIGN KEY (member_id) REFERENCES MEMBER (id) on delete CASCADE,
- 외래키를 적용하면 성능 저하 및 여러 작업(마이그레이션 혹은 삽입, 삭제 등등..) 시 고려해야할 점들이 늘어나게 됩니다. 이런 불편으로 실무에서도 외래키는 가급적 사용하지 않습니다.
- [github이 외래키를 쓰지 않는 이유](https://github.com/github/gh-ost/issues/331)도 읽어보시면 좋을 것 같아요!

2023-05-08 15:22 UTC, aegis1920 approved these changes
안녕하세요 오리! 빙봉입니다 🙂 

끝까지 피드백 반영해주셔서 감사합니다ㅎㅎ 고생 많으셨어요! 
다시 봐도 꼼꼼한 테스트코드에 놀라게 되네요 💯 💯 

이번 미션은 여기서 머지하겠습니다!

2023-05-08 15:22 UTC, aegis1920 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +
공백이 있네요!

2023-05-08 15:22 UTC, aegis1920 commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +    private static ThreadLocal<Credential> credentialHolder = new ThreadLocal<>();
final을 붙였어도 됐겠네요 🙂

2023-05-08 15:22 UTC, aegis1920 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +        return credential;
inline return도 가능하겠네요!

2023-05-08 15:22 UTC, merged