[2단계 - 장바구니 기능] 테오(최우성) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #306
Opened 2023-05-04 13:57 UTC by woosung1223

안녕하세요 카프카 ㅎㅎ 
좋은 리뷰도 많이 해주시고 조언도 많이 해주셔서 빠르게 성장하고 있습니다.

step2를 진행하면서 새로운 개념도 많이 배우고, 고민도 굉장히 많이 했는데요.
카프카에게 직접 여쭤보고 싶은 질문들은 아래에 나열해보려고 해요! 편하게 읽어봐주시면 감사하겠습니다 😊

---
### DIP 관련
 step2에서도 step1과 마찬가지로 Businiess Layer - Persistence Layer 사이에 DIP를 적용했는데요. Service, Domain, Repository Interface가 모두 완성되고 나서야 Repository의 구현체를 만들고, DB 설계를 진행했어요. 이 과정을 통해 영속성의 개념이 도메인에 전파되지 않게 할 수 있었습니다. 또한 도메인에서 외부로 흐르는 의존성은 더 이상 존재하지 않게 되었는데요..! **1. DIP를 통해 도메인을 먼저 구현하고,** **2. 영속성 및 테이블을 구현하는 방식**이 실무에서도 자주 사용되는지 궁금합니다. 실제로 이런 방식으로 개발을 진행해보니 비즈니스 로직을 정말 순수하게 가져갈 수 있다는 장점이 있는 것 같은데.. 카프카는 어떻게 생각하시는지 궁금하네요.

### 계층 및 구조 관련
 Spring으로 웹 서비스를 구성해본 적이 없기에 현재 제가 설계한 패키지 구조, 계층 구조, 객체 관계가 올바르다는 확신을 쉽게 할 수가 없는 것 같아요. 이런 구조를 앞으로의 미션에서도 유지해도 좋을지, 아니면 개선해야 할 부분이 있는지.. 객체 및 계층의 책임이 제대로 분리되었는지에 대해서도 조언 주실 수 있을까요? 

 
---

그리고 저번 리뷰 때 말씀해주셨던 내용은 대부분 다 적용을 완료했어요! .http를 이용한 테스트까지 진행해보았습니다.  ㅎㅎ

아직 스프링에 대한 기본기가 많이 부족한 것 같아요..! 이번 리뷰도 잘 부탁드립니다 감사합니다!! 🙇‍♂️

2023-05-04 16:55 UTC, include42 commented
안녕하세요 테오! 리뷰어 카프카입니다.
근래에 좋은 질문을 많이 주셔서, 저도 자극을 받고 더 고민하고 성장하는 시간들이었네요 😄 

이번 step2에서 새로운 내용을 많이 배웠다니 기대가 많이 됩니다!
저번에 논의했던 내용들이 잘 적용되었는지, 새로운 기능 구현은 잘 되었는지도 궁금하네요.
안그래도 이전에 서비스의 구성에 관해 테오와 논의한 뒤 좋은 레퍼런스를 찾기도 했는데,
리뷰 진행하면서 이 내용도 함께 공유드려 보고자 합니다.

리뷰는 내일 저녁 10시 전후로 가능할 것으로 생각됩니다.
내일 개인 일정이 있어서 좀 빠듯하게 이루어지게 되었네요. 혹시 더 늦어지게 되면 별도로 dm 드리겠습니다.

지금 잠시 여유가 나서, 질문에 대해서는 아래에 추가로 코멘트 남기겠습니다.

2023-05-04 17:05 UTC, include42 commented
### DIP 관련
우선 영속성과 도메인은 어느정도 함께 가게 되는 구성이라 분리하기가 쉽지 않았을텐데, 저번 레벨1때부터 신경써서 잘 해주셨습니다. 이러한 방식의 개발은 매우 좋은 방법이라고 생각합니다.
다만 저의 경우 실무에서는 이렇게 엄격히 구분해서 개발을 진행하지는 못하는 경우가 많아요.
실무에서는 개발의 기한이 명확하고 이미 기획이 진행된 내용을 진행하기 때문에, 명세에 맞게 엔티티+도메인 작업을 빠르게 수행하는 상황이 많습니다. 대신 기획한 내용에 대해 기획자(PO 프로젝트 오너 라고 하기도 합니다)를 통해 충분히 리뷰를 받고, 개발을 진행하기 전에 팀 내에서 검토를 수행하면서 방향을 명확히 잡으며, 이후 개발한 내용을 리뷰하며 도메인이 적절히 설계되었는지, 테이블 구조가 적절한지 등을 종합적으로 검토하는 프로세스를 밟게 되거든요.
다만 그렇다고 해서 제 방식이 정답이라고 생각하지는 않습니다. 상대적으로 검토할 환경이 부족한 테오의 상황에서라면, 이번에 진행한 과정대로 수행하는 것이 더 안전하다고 생각해요. 그리고 TDD를 통해 계층별로 개발을 진행하게 된다면, 자연스럽게 그러한 방향으로 진행되겠다는 생각도 들고요.
프로젝트를 진행할 경우 어느정도 코드 퀄리티나 도메인의 의존성 문제 등을 타협하는 대신 빠른 기능구현을 요구받는 경우가 많아서, 앞으로 레벨3,4를 진행할 때에는 테오가 생각하는 철학을 100% 관철하지 못하는 상황도 종종 생길 수 있다고 생각합니다. 이번 레벨2 과정동안 철학을 쌓아가면서, 동시에 절대 타협할 수 없는 지점과 타협 가능한 지점을 저울질해보는 것도 강하게 권합니다.

### 계층 및 구조 관련
이부분은 리뷰 진행하면서 다시 꼼꼼히 확인해 보겠습니다. 우선 1단계 리뷰 기준에서는 계층/패키지 구조상으로 걸리는 부분은 없었습니다.
이번 2단계 요구사항에서 엔티티 간 연관관계 구현이 있어서, 그 부분이 잘 되었는지를 우선 살펴봐야겠네요. 추가로 서비스 레이어는 제가 조언드린 방향대로 어느정도 타협한 것으로 보이는데, 이부분도 적절할지 검토해 보겠습니다.

2023-05-05 13:03 UTC, include42 requested changes
안녕하세요 테오, 리뷰어 카프카입니다.
작업하신 내용 잘 보았습니다. 1단계때에도 충분히 좋은 퀄리티의 코드를 보여주셨는데,
이번 단계에서 전반적으로 더 좋아져서 리뷰하는 즐거움이 있었습니다. 😄 

큰 개선사항은 없으나, 서비스 테스트의 정상 케이스 추가 및 컨트롤러 테스트의 세부사항 구현을 추가로 요청드리고자 합니다. 이외에는 코멘트 확인해주시고 논의를 해보면 좋을 것으로 생각됩니다. 💯 

작업하시느라 고생 많으셨습니다 👍

2023-05-05 13:03 UTC, include42 commented on docs/README.md
> +    - [x] 이것이 좋은 방향인지는 카프카와 논의해봐야 할 듯!
이 부분은 좋은 방향이라고 생각합니다.
컨트롤러와 도메인간 결합도를 낮추려면 서비스에서 도메인을 인자로 받고 반환하거나, 혹은 서비스<->컨트롤러간 DTO를 사용하거나의 크게 두 가지가 가능하다고 생각합니다.
저는 이러한 방식의 절충안으로 컨버터를 두는 것에 찬성합니다. 여기 써놓은 것과는 달리 어댑터 패키지 내에 컨버터를 두는 정도로 반영을 해둔듯한데, 이정도가 새로 시도해보기 적절한 수준이었다는 생각이 드네요.

만약 여기서 더 개선해본다면, 저는 컨버터를 도메인/컨트롤러별로 좀 더 나누거나, 공통 내용을 상위객체로 빼거나 할수도 있을듯하긴 합니다. 다만 현재도 충분히 좋아서, 선택적으로 개선해보면 좋을듯하네요. 💯

2023-05-05 13:03 UTC, include42 commented on docs/README.md
> +    - [x] Repository에 이런 기능이 들어가는 것을 두려워하지 말자! 성능 최적화를 위해. Repo에는 보편적인 기능만 들어갈 필요는 없다.
아직 DB 관련 내용이 낯설수도 있는데, 학습 속도도 좋고 방향도 좋습니다.
그리고 이후 개발을 하다 보면, jpa나 querydsl 등을 이용해 커스텀한 쿼리를 바탕으로 복잡한 메소드를 만들기도 합니다.
적어주신대로 최적화의 목표가 크고(쿼리 속도가 지연되면 효율에 치명적...), 이외에도 해당 도메인에 특화된 내용이라면 충분히 가능한 선택이라는 이유도 있겠지요.

2023-05-05 13:03 UTC, include42 commented on docs/README.md
> +    - [x] 따라서 이런 철학은 유지하되, 상황에 따라 trade-off를 계산해 자원 중심으로도 service를 만들 수 있어야 할듯.
이부분은 저번에 미션 진행해주신 후 저도 고민을 많이 했습니다.
일단 저는 어느정도의 trade-off를 한 결과가 좋았다고 느꼈습니다. 
다만 관련해서 테오가 생각하는 철학을 발전시킨 구조도 있어서, 참고할 수 있도록 자료 남겨두고자 합니다.

2023-05-05 13:03 UTC, include42 commented on docs/README.md
> +    - [x] 따라서 이런 철학은 유지하되, 상황에 따라 trade-off를 계산해 자원 중심으로도 service를 만들 수 있어야 할듯.
저희 사내에서 테오에게 추천했던 [만들면서 배우는 클린 아키텍처](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=283437942)를 바탕으로, 새 프로젝트에 헥사고날 아키텍처를 적용한 경우가 있었는데요,
이때 서비스 구성이 인상적이라 아래에 대략적으로 전달드리고자 합니다. (원본 코드는 보안상의 이유로 공유 불가합니다.)
```
// domain이 Cart라고 가정
class CartService implements CreateCartUseCase, DeleteCartUseCase {
    private final PersistCartPort creator;
    private final LoadCartPort selector;
}
```
이때 위에서 참조한 유즈케이스 인터페이스에는, 각각 create 메소드와 get/search 메소드가 들어가 있습니다.
그리고 port들의 경우, 해당 기능을 구현한 repository 컴포넌트에 연결됩니다.
이 구조가 이해가 잘 가시나요? 이렇게 할 경우 유즈케이스를 모아 서비스를 구축해주고,
서비스에서는 repository를 비롯한 외부 통신을 포트별로 정리해 인자로 받게 되는 것입니다.

일단 이 구조를 곰곰히 생각해보는 것이 이번 미션 수준에서의 목표라고 생각됩니다.
이 구조 그대로 현재 프로젝트에 적용하려면 필요한 리소스가 너무 크니까요.
다만 해당 구조가 테오가 고민하던, 비즈니스 중심의 유즈케이스 구성과 자원 중심의 서비스 구성의 괴리를 연결해줄 힌트가 되리라고 생각됩니다.

2023-05-05 13:03 UTC, include42 commented on src/main/java/cart/business/service/ProductService.java
> +public class ProductService {
전반적으로 서비스 및 repository 구성을 보면서, 적절히 잘 구현되었다고 생각되어 추가적인 코멘트를 달 부분이 없었습니다.
검증도 잘 해주고 있네요. 이정도라면 현재 미션 수준을 충족하고 있다고 생각됩니다. 💯

2023-05-05 13:03 UTC, include42 commented on src/main/java/cart/config/ResolvedMember.java
> +}
어노테이션을 직접 만들어 활용하는 것 좋습니다.
어떤 식으로 만들고 어떻게 동작하는지, 이번 작업을 계기로 학습해두면 도움이 될 것입니다. 😄

2023-05-05 13:03 UTC, include42 commented on src/main/java/cart/presentation/adapter/DomainConverter.java
> +public class DomainConverter {
도메인컨버터를 만들어주신 부분은 위에서 코멘트했듯 매우 좋습니다!
내용도 적절하게 잘 구현해주셔서 좋았습니다.

다만 DomainConverter가 세부적인 도메인별 컨버터로 쪼개지면 어떨까 싶은데, 어떻게 생각하시나요?

2023-05-05 13:03 UTC, include42 commented on src/main/java/cart/presentation/adapter/LoggerInterceptor.java
> +public class LoggerInterceptor implements HandlerInterceptor {
오 로그를 위한 Interceptor라니 넘넘 좋습니다 💯 💯 
실행했을 때 로그 기록되는 것도 잘 확인할 수 있었습니다.

개발하면서 이렇게 로그를 잘 관리해주는 것도 매우! 중요한 역량입니다.
해당 인터셉터는 다음 미션에서도 가능하다면 적용해보기를 권합니다. 👍

2023-05-05 13:03 UTC, include42 commented on src/test/java/cart/business/service/MemberServiceTest.java
> +class MemberServiceTest {
serviceTest에도 mockito를 적용해 주셨네요!! 이렇게 단위 테스트를 구성해보니 어떠셨나요? 😄 
다만 본 테스트의 경우 정상동작 테스트 없이 예외에 대한 테스트만 존재하는 것으로 보이는데요,
추후 정상동작에 대해서도 로직 추가 등이 있을 수 있으므로, 테스트를 추가로 만들어두면 좋을듯합니다.

2023-05-05 13:03 UTC, include42 commented on src/test/java/cart/presentation/controller/CartControllerTest.java
> +class CartControllerTest {
WebMvcTest도 사용해보니 단위테스트에 효과적이었지요? 해당 컨트롤러만 올라가도록 설정도 잘 해주셨네요.
테스트 구성도 잘 해주셨습니다 💯

2023-05-05 13:03 UTC, include42 commented on src/test/java/cart/presentation/controller/CartControllerTest.java
> +                .andExpect(status().isOk());
다만 여기서 더 테스트를 진행해 볼 수는 없을까요?
webMvcTest jsonpath 라는 검색어로 구글링해보면 몇몇 블로그 자료가 나올텐데,
이를 확인해본 뒤 이 부분을 개선해보기를 요청드립니다. (조회한 값 정보까지 확인)

2023-05-05 14:43 UTC, woosung1223 commented on docs/README.md
> +    - [x] 따라서 이런 철학은 유지하되, 상황에 따라 trade-off를 계산해 자원 중심으로도 service를 만들 수 있어야 할듯.
좋은 예시 공유 감사드립니다 ㅎㅎ

요즘 해당 책을 열심히 읽고 있기에, 예시 코드를 이해하는 데에는 큰 어려움은 없어서 다행입니다.
그리고 공유해주신 자료, 설명해주신 내용을 토대로 이해한 바는 다음과 같은데, 한 번 가볍게 봐주시면 감사하겠습니다.

위처럼 구성하는 경우 클라이언트(인커밍 어댑터, Ex. 웹 컨트롤러) 입장에서는 단일 유즈케이스를 사용하는 것이 됩니다.
즉, 해당 기능에 대해서만 알고 있으며 그 기능을 수행할 객체에 대해서는 전혀 모르죠.

따라서 이 경우는 **기능 중심으로 응집된 유스케이스**를 사용하는 것처럼 보입니다.
반면 서비스를 보았을 때는 **공통 자원을 사용하는 여러 유스케이스**를 모아 구현되는 것처럼 보이네요.

하나의 자원으로 서비스가 묶이는 경우, 비즈니스 흐름을 담지 못한다는 단점이 있었는데요.
위 코드처럼 구성하면 비즈니스 흐름을 담으면서 자원 단위로 관리할 수 있다는 장점이 있을 것 같습니다.

만약 기능을 수정하고 싶다면 빠르게 해당 이름을 가진 유스케이스를 찾아 수정하면 되고, 자연스레 수정 여파가 유스케이스를 implements하는 서비스에게 전해지기 때문에 문제가 없을 듯 보입니다..! 그리고 자원 단위로 묶였기 때문에 자원에 대한 응집도도 높구요. 

아직 이런 구조를 언제 효율적으로 사용할 수 있는지는 감이 안오지만.. ㅎㅎ 제가 잘 이해한 것이 맞을까요? 😅

2023-05-05 14:46 UTC, woosung1223 commented on src/main/java/cart/presentation/adapter/DomainConverter.java
> +public class DomainConverter {
저도 동의합니다!

다만 도메인 컨버터를 분리해야 하는 시점이라면, 컨버팅 기능을 담는 객체로써의 메리트는 크게 없을 것 같아서 저번에 카프카가 말씀해주신 Controller - Service 간의 DTO 사용을 고려해봐도 좋을 것 같네요..!

한번 고민해보고 두 방향 중 하나를 골라 리팩토링 해보도록 하겠습니다 😄

2023-05-05 14:51 UTC, woosung1223 commented on src/test/java/cart/business/service/MemberServiceTest.java
> +class MemberServiceTest {
정말 Service에서 테스트해야 하는 부분만 진행할 수 있어 좋았던 것 같아요!
따라서 Mockito 심화 학습 필요성도 많이 느끼고 있습니다 ㅎㅎ

그리고 말씀하신대로 정상 동작 테스트도 한번 구성해보겠습니다!

2023-05-05 14:52 UTC, woosung1223 commented on src/test/java/cart/presentation/controller/CartControllerTest.java
> +                .andExpect(status().isOk());
저도 테스트가 빈약하지는 않은가 걱정이 되었는데, 짚어주셔서 감사하네요 ㅎㅎ

한번 진행해보겠습니다!

2023-05-05 15:19 UTC, include42 commented on docs/README.md
> +    - [x] 따라서 이런 철학은 유지하되, 상황에 따라 trade-off를 계산해 자원 중심으로도 service를 만들 수 있어야 할듯.
네 저도 동일하게 이해하고 있습니다.
컨트롤러 등에서 특정 기능을 사용할 때에는 관련된 유즈케이스를 주입받아 사용하는데, 이때 해당 서비스가 주입되어 기능을 수행하게 됩니다. 그렇기 때문에 테오가 말한대로 사용하는 쪽에서는 해당 기능만 알 뿐 객체에 대해 몰라도 되고, 전반적인 사용에 있어서도 기능 중심으로 구성할 수 있게 됩니다.
그러나 구현체는 공통 자원을 기반으로 한 서비스 클래스이므로, 이후의 유지보수가 용이하고 코드 확인의 편의성도 강하게 됩니다. 이 부분 역시 테오가 말해준 부분과 같습니다.

이러한 구조가 효율적이냐? 라고 묻는다면...저는 어느정도 타협된 코드를 사용하다 보니 조금 과하게 느껴지는 점도 있었습니다. 아무래도 코드 로직을 확인하다 보면 전체 구성의 확인을 위해 레퍼런스를 타고 들어가면서 구현체 코드를 봐야 하는데, 그 과정까지 여러 인터페이스가 걸쳐 있어서 종합적인 가독성에선 조금 아쉬운 면이 있었거든요.
다만 확실한 것은, 단순히 컨트롤러 코드만 봤을때, 혹은 사용되는 다른 클래스의 코드를 봤을 때 해당 단위에서의 가독성이 압도적으로 좋아진다는 점이었습니다. 그래서 저는 기존 프로젝트에 이 구조를 바로 적용하지는 못하더라도, 만약 신규 프로젝트를 하게 된다면 한번 도입해봐야겠다 라는 욕심은 들더라고요.

결론적으로, 테오가 잘 이해한 것이 맞습니다.
그사이 학습을 꾸준히 해주셔서, 이러한 구조를 직관적으로 이해할 수 있는 것으로 보이네요. 참 잘해주셨습니다 💯

2023-05-06 03:57 UTC, woosung1223 commented on docs/README.md
> +    - [x] 따라서 이런 철학은 유지하되, 상황에 따라 trade-off를 계산해 자원 중심으로도 service를 만들 수 있어야 할듯.
감사합니다 😄
이 주제로 굉장히 오랫동안 고민을 했는데 카프카가 좋은 방향으로 이끌어주신 것 같아요

이 구조를 남은 미션 기간동안 조금 더 고민해보고, 누군가를 설득할 수 있는 단계가 된다면 다음 페어프로그래밍 때 페어를 설득해보고 싶군요 ㅎㅎ 무언가 미션 초반부터 고민했던 서비스 관련 문제가 조금씩 실마리가 풀리는 느낌입니다. 감사합니다!!

2023-05-07 04:19 UTC, include42 approved these changes
안녕하세요 테오, 리뷰어 카프카입니다.

저번 수정 요청에 대해 적절히 잘 반영해 주셨습니다.
테스트도 많이 보강이 되었고, 전반적인 구조도 잘 잡혀 좋네요 💯 
이미 프로젝트가 미션의 요구사항을 충족하고 있고,
논의하는 과정에서 필요한만큼 학습하시고 성장하셨다고 생각되기에 이번 미션은 여기서 approve 하겠습니다.

그간 미션 진행하시면서 고생 많으셨습니다! 👍 👍

2023-05-07 04:19 UTC, include42 commented on docs/README.md
> +    - [x] 도메인 엔티티를 presentation Layer로 반환했을 때의 문제점은 뭘까? 추후 고민해보기.
이번 미션 진행하면서, 이 내용에 대해서는 테오만의 주관이 점점 명확해지고 있네요 💯 
리뷰 받으면서 해당 내용에 대해 적극적으로 질문하고 논의해줘서 고마웠습니다 👍 

추가로, 마지막에 적어준 내용은 꼭 고민해보면 좋겠습니다.
의외로 저런 경우가 꽤 많아서, 저도 레거시 코드를 보다보면 많이 보긴 하는데
저렇게 하면 안된다고 상대를 설득할 만큼의 근거와 철학을 가지고 있나? 하면 저도 아직 부족한 느낌이라서요 😓

2023-05-07 04:19 UTC, include42 commented on src/test/java/cart/business/service/MemberServiceTest.java
> +        memberFixture = new Member(new MemberId(1), new MemberEmail("a@a.com"), new MemberPassword("1234"));
fixture를 만들어준 부분 좋습니다! 정상 케이스도 테스트에 잘 구현해 주셨네요. 💯 

다만 유의할 점! 보통 공통으로 돌려쓰는 값은 setup 메소드에 올려두는 편인데요,
이러한 방식은 아래의 두 가지로 분류할 수 있습니다.
- 상태 공유: `@BeforeAll` 설정시 발생. 특정한 상태가 모든 테스트 케이스에서 공유됨
- 설정 공유: `@BeforeEach` 설정시 발생. 모든 테스트 케이스가 해당 메소드의 설정을 공유함

상태 공유나 설정 공유는 테스트에 안좋은 영향을 줄 수 있습니다.
 - 상태 공유의 경우, 공유된 값(위의 픽스처)을 수정하거나, 공유된 상태(DB를 올려둔다던가)을 수정해서 테스트를 실패하도록 할 수 있습니다. 순서에 의존하는 테스트가 되어서 간헐적으로 실패하면 최악의 경우이고요.
 - 설정 공유는 이보다는 낫지만, 종종 아래와 같은 경우가 발생합니다.
   - 도메인의 명세 등이 변경되어, 공유된 설정을 변경
   - 이 과정에서 해당 설정을 쓰는 다른 테스트가 목적과 다르게 작동
   - 이로 인해 테스트의 목적을 수행하지 못하고, 이후 오류가 발생해도 테스트는 성공하는 상황 발생

그렇기 때문에, 저는 아래의 방향을 추천드립니다.
- 테스트 픽스처 구성에 필요한 메타데이터(memberId, MemberEmail 같은 클래스)는 크게 문제가 없을듯합니다.
- 그러나 테스트용 픽스처를 전역으로 상태 공유하거나 테스트별로 설정 공유할 경우, 이후에 수정에 따라 문제가 발생할 수 있습니다.
- 가능하다면, 각 테스트 메소드 내에서 픽스처를 만들어주는 것이 바람직합니다.

위 내용은 제가 [좋은 코드, 나쁜 코드](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=294649282) 369 - 379 pp 를 인용한 내용입니다. 
해당 책이 있거나, 혹시 루터 등에 배치되어 있다면 꼭 chapter 10~11 을 읽어보세요! (물론 다른 내용도 모두 좋은 책입니다)
단위 테스트에 대한 중요한 개념은 다 들어있습니다.

2023-05-07 04:19 UTC, include42 commented on src/test/java/cart/presentation/controller/CartControllerTest.java
> +    }
이부분도 요구사항에 맞춰 잘 반영해 주셨습니다 👍 
직접 해보니 생각만큼 어렵지는 않았지요? 그에 비해, 해당 테스트를 통해 확인할 수 있는 범위가 매우 넓어졌습니다.
이후 미션에서도 컨트롤러와 서비스의 단위 테스트를 잘 구축하시기를 바랍니다. 💯

2023-05-07 04:20 UTC, merged

2023-05-07 05:43 UTC, woosung1223 commented on src/test/java/cart/business/service/MemberServiceTest.java
> +        memberFixture = new Member(new MemberId(1), new MemberEmail("a@a.com"), new MemberPassword("1234"));
감사합니다!! fixture를 공유하는 것이 문제가 될 수 있다는 건 처음 알았네요.. 

안그래도 테스트와 모킹에 관심이 많아져서 공부중이었는데, 해당 책을 내일 캠퍼스에 가자마자 읽어봐야겠군요 😄
]

2023-05-07 05:44 UTC, woosung1223 commented on src/test/java/cart/presentation/controller/CartControllerTest.java
> +    }
넵 생각보다 어렵지 않았고 테스트의 유연성이 빠르게 증가하는 것을 느꼈습니다! ㅎㅎ
이제 컨트롤러에서 검증하고자 하는 건 대부분 검증이 되었다고 생각해요(요청에 대한 응답, 응답 포맷)

다음 미션부터도 꼭 적용하도록 하겠습니다!! 👍