[2단계 - 장바구니 기능] 오도(문민혁) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #319
Opened 2023-05-05 02:23 UTC by odo27

안녕하세요 토니 🙂
2단계 구현하는데 시간이 오래 걸려 이제야 리뷰 요청 보냅니다 🥹
2단계도 잘 부탁드립니다 ㅎㅎ

2023-05-06 07:03 UTC, toneyparky requested changes
안녕하세요 오도~! 
이번 미션도 잘 구현해주셨네요! 기능 요구사항을 잘 만족해주셨어요! 
스프링에서 제공하는 기술을 적용하면 코드가 더 깔끔해질 수 있을 것 같아서 코멘트 남겼으니 확인 부탁드려요. 
궁금한점은 편하게 DM 주시고 남은 주말 즐겁게 보내세요 :)

2023-05-06 07:03 UTC, toneyparky commented on README.md
> +- [x] 사용자 기능 구현
요구사항을 잘 정리해주셨네요 굳굳~!

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/controller/CartCreateController.java
> +package cart.controller;
이제는 컨트롤러가 더 많아졌네요~!
API 컨트롤러와 뷰 컨트롤러를 패키지로 명확하게 구분하는건 어때요?

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/controller/CartDeleteController.java
> +    @DeleteMapping("carts/{id}")
```suggestion
    @DeleteMapping("/carts/{id}")
```

다른 엔드포인트와 동일하게 컨벤션을 맞춰주면 어떨까요?

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +
새로 추가된 예외도 꼼꼼하게 처리해주셨네요~!

다만 `LoginFailException`의 예외 메시지가 적절한지는 조금 더 고민해보면 좋겠어요. 예외가 발생했을 때에 `email과 password가 일치하지 않습니다` 가 맞을지 말이죠~!

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/domain/user/Email.java
> +public final class Email {
객체를 만들어 적절하게 비즈니스 요구사항을 담아주신 점 좋네요~! 이메일과 관련된 로직은 이 클래스만 보면 이해할 수 있겠어요!

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
이번 미션에서 추가로 학습하면 좋을 스프링의 기술이 있어요. 바로 `argument resolver`와 `interceptor`에요. 
지금처럼 `BasicAuthorizationExtractor`를 만들어  `AuthService`에서 이를 사용하고 컨트롤러에서 처리해도 좋지만 위의 두 기술을 사용하여 리팩터링해보시고 기존 방법과 어떤 부분이 다르다 느끼셨는지 댓글로 남겨주세요 😀

[도움이 될만한 글](https://tecoble.techcourse.co.kr/post/2021-05-24-spring-interceptor/)

2023-05-06 07:03 UTC, toneyparky commented on src/main/resources/schema.sql
> +);
MEMBER 테이블은 email을 PK로 처리해주신 이유가 궁금해요. 별도의 AUTO Incrementation 을 이용한 Long 타입의 컬럼을 이용하는 것과는 어떤 차이가 있을까요?

2023-05-06 07:03 UTC, toneyparky commented on src/main/java/cart/dto/ProductResponse.java
>      public static ProductResponse from(final Product product) {
DTO가 더 많이 생겼네요..! 이런 상황에서는 더 명확하게 객체의 용도를 표현해주면 좋겠어요.
지금 모든 DTO는 컨트롤러에 의존성을 가지고 있죠. 그러므로 컨트롤러 패키지 하위에 dto 패키지를 두는건 어떨까요?

2023-05-06 07:03 UTC, toneyparky commented on src/test/java/cart/dao/CartDaoTest.java
> +class CartDaoTest {
삭제에 대한 테스트는 없어도 될까요? 이외 별개로 누락된 메서드에 대해서도 테스트를 추가하면 좋겠어요.
인텔리제이에서는 아래의 캡쳐처럼 테스트 커버리지를 확인할 수 있으니 참고하셔도 좋겠네요!

<img width="830" alt="image" src="https://user-images.githubusercontent.com/37579660/236608560-f091ec8a-8c71-490d-a4e8-66ef2a9ac974.png">

2023-05-06 07:03 UTC, toneyparky commented on src/test/java/cart/ProductIntegrationTest.java
> +@ActiveProfiles("test")
이렇게 테스트 클래스 하나에만 프로파일이 설정되어 있다면 코드를 파악하는 데에 힘들 것 같아요. `application.yml` 파일을 만들어서 더 명시적으로 표현할 수 있을까요?

2023-05-06 10:32 UTC, odo27 commented on src/main/java/cart/controller/CartCreateController.java
> +package cart.controller;
너무 좋은 것 같습니다! 두 개의 패키지를 만들어 분리했습니다~ ☺️

2023-05-06 10:41 UTC, odo27 commented on src/main/java/cart/controller/CartDeleteController.java
> +    @DeleteMapping("carts/{id}")
반영했습니다! 앞으로 더 신경쓰도록 하겠습니다 🥹

2023-05-06 11:24 UTC, odo27 commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +
해당 email이 존재하지 않는 경우의 예외와 패스워드가 일치하지 않을 때의 예외를 분리했습니다 😊

2023-05-08 07:07 UTC, odo27 commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
`argument resolver`와 `interceptor`를 적용해 리팩터링 했습니다 😀

`Controller`에 `AuthService`를 사용해 `HttpServletRequest`의 인증 헤더를 검증하는 로직이 중복되어 존재했었는데 이를 `Argument Resolver`에서 처리하게 구성할 수 있었습니다. 컨트롤러에 인증에 관련된 로직이 포함되지 않아 가독성이 좋아졌고 인증이 필요한 컨트롤러가 늘어날 때마다 계속해서 같은 코드를 추가해야했는데 리팩터링 후에는 인증이 필요한 파라미터 앞에 어노테이션만 붙여 사용할 수 있어 편리해졌습니다.

`Interceptor`를 사용해 헤더가 존재하는지 검증하는 기능을 추가했습니다. 인터셉터를 사용하고 싶은 부분은 `addInterceptors`를 오버라이딩해 `Registry`에 `Interceptor`와 적용할 경로를 추가하는 방식으로 해결할 수 있었습니다 ☺️

2023-05-08 07:46 UTC, odo27 commented on src/main/resources/schema.sql
> +);
`email`을 PK로 사용한 이유는 크게 2가지입니다.

1. 이메일 주소를 제공하는 서비스에서 중복된 이메일을 허용하지 않습니다. 중복된 이메일은 존재할 수 없기에 PK로 사용했습니다.
2. `member_id`를 사용한다면 DB에 중복된 이메일이 존재할 수 있는데 패스워드로 검증할 때 어떤 이메일의 비밀번호로 검증할지 특정할 수 없기에 PK로 두었습니다.

`PRODUCT` table의 경우 name이 중복될 수 있어 `product_id`를 두었고 `CART` 테이블의 경우 같은 사용자가 같은 제품을 여러 개 담은 경우에 제품을 삭제하기 위해 `cart_id`를 두었는데 `MEMBER` 테이블은 email 자체가 너무 명확하게 유일성을 보장해 준다고 생각해 `member_id`를 만드는 것은 불필요한 컬럼을 생성하는 것이라고 생각했습니다.

`별도의 AUTO Incrementation 을 이용한 Long 타입의 컬럼` 을 이용하는 방식의 장점에 대해 공부해봤습니다.

1. 정수형을 사용함으로써 문자열에 비해 인덱스 성능이 좋다 → 빠른 조회가 가능하다
2. 사용자가 사용하는 이메일을 변경하고 싶을 수 있다 → `member_id`는 동일하게 유지하며 변경을 쉽게 할 수 있다
3. 문자열을 다른 테이블의 외래키로 사용하면 대소문자 구분이나 공백 처리 등에 주의해야 하는데 정수형 식별자를 사용하면 간단하고 명확하게 테이블을 연결할 수 있다

`email을 pk로 사용한 이유` 2번에 적었던 email의 중복문제는 아래와 같이 UNIQUE 키워드를 사용해 해결할 수 있을 것 같습니다

```sql
CREATE TABLE IF NOT EXISTS MEMBER
(
    member_id BIGINT       NOT NULL AUTO_INCREMENT,
    email     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    UNIQUE (email),
    PRIMARY KEY (member_id)
);
```

2023-05-08 09:52 UTC, toneyparky commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +
요 부분은 아직 커밋이 안되어 확인하지 못했어요. 

다만 적어주신 코멘트로 비추어보아 이메일과 패스워드 케이스를 분리해서 적어주셨다고 생각되네요. 이럴 경우에는 각 상황에 따라 예외 메시지가 고객에게 노출될거에요. 일반적으로는 이게 좋은 방향성이지만 회원 정보는 다르답니다. 왜냐하면 악의를 가진 사람이 해킹을 위해 고객의 정보를 마구마구 입력해볼 수 있기 때문이에요. 이런 상황에서는 상세한 정보가 오히려 해커에게 힌트를 줄 수 있겠죠. 

요 부분을 고려하여 상황에 맞는 예외 메시지를 작성하시도록 수정해보셔도 좋겠어요..!

2023-05-08 10:04 UTC, odo27 commented on src/main/java/cart/dto/ProductResponse.java
>      public static ProductResponse from(final Product product) {
dto 패키지를 컨트롤러 패키지의 하위로 이동했습니다 😊

2023-05-08 10:06 UTC, odo27 commented on src/test/java/cart/dao/CartDaoTest.java
> +class CartDaoTest {
삭제에 대한 테스트와 작성하지 못한 테스트들 추가했습니다!

2023-05-08 10:21 UTC, odo27 commented on src/test/java/cart/ProductIntegrationTest.java
> +@ActiveProfiles("test")
test 패키지에 application.yml을 만들어 spring.profiles.active 설정을 추가했습니다!

2023-05-08 10:34 UTC, toneyparky commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
컨트롤러와 서비스를 통해 진행하던 로직을 `Argument Resolver `를 통해 명확하게 처리할 수 있게 되었죠..! 또한 `Interceptor`를 이용하여 경로도 명확하게 지정할 수 있구요. 

이번에 오도가 리팩터링하셨듯 스프링이 제공하는 적절한 기능을 사용하면 이해하기도, 추후에 유지보수하기에도 좋은 코드가 탄생한답니다..!

잘 구현해주셨습니다. 고생 많으셨어요. 조금 더 나아간다면 필터의 개념에 대해서 학습해보면 좋겠네요. 인터셉터와는 어떤 부분이 다른지, 각 기술은 어떤 경우에 사용하면 좋을지와 같이요..!

2023-05-08 10:34 UTC, toneyparky commented on src/main/resources/schema.sql
> +);
오도가 email을 PK로 사용하신 근거와 정수형 PK 를 사용할 때의 장점을 잘 적어주셨네요. 감사해요!

적어주신 근거는 충분히 납득이 가네요..! 다만 적어주신 내용 중 `사용자가 사용하는 이메일을 변경하고 싶을 수 있다 → member_id는 동일하게 유지하며 변경을 쉽게 할 수 있다` 와 같은 부분을 고려하면 추후에는 정수형 PK를 우선적으로 고려하셔도 좋겠다 싶어요. 개발을 하다보면 요구사항은 바뀌기 마련이고 절대 변하지 않을 것 같은 규칙도 변할 수 있기 때문이에요. 그렇기에 유연한 설계를 가져간다면 추후에 들 비용을 줄일 수 있겠죠?

`UNIQUE` 키워드도 실제로 현업에서 사용해요. 잘 적어주셨습니다 👍  
다만 해당 제약사항은 DB단의 제약 사항이에요. 이 제약을 무시하고 생성을 요청할 경우에는 DB 관련된 예외가 발생해요. 그리고 이 예외는 raw하게 클라이언트에게까지 전달될 수 있구요. 이 부분을 고려하여 캐치하여 이해하기 쉬운 예외로 바꿔서 던진다던가, 애플리케이션에서 방어 로직을 추가한다던가 하면 보다 탄탄한 프로그램이 될거에요. 

레벨 3에서 프로젝트를 하며 회원 기능을 또 다룰텐데 이번 미션에서 학습한 내용을 잘 적용하시면 좋겠네요 🙂

2023-05-08 10:34 UTC, toneyparky commented on src/main/java/cart/dto/ProductResponse.java
>      public static ProductResponse from(final Product product) {
네 이러면 DTO가 어디에 속해있는지를 명확하게 파악할 수 있죠! 만일 API 내에서만 사용된다면 `controller.api.dto`로 스콥을 더 좁혀도 좋겠어요. 패키지를 통해 더 명확히 드러내는거죠. 

지금도 충분히 좋습니다. 고생하셨어요~!

2023-05-08 10:35 UTC, toneyparky commented on src/test/java/cart/dao/CartDaoTest.java
> +class CartDaoTest {
크.. 확인확인 

`@Nested` 내부에 `@BeforeEach`를 통해 중첩을 제거하는 부분도 잘 해주셨구요..! 뷰 테스트는 꼼꼼하게 처리해주셔서 크게 손볼 부분이 없네요.

2023-05-08 10:36 UTC, toneyparky commented on src/test/java/cart/ProductIntegrationTest.java
> +@ActiveProfiles("test")
요거까지..! 잘 챙겨주셨군요.

파일로 관리하는편이 유지보수에 더 효과적이라 생각해요. 설정이 분산되지도 않구요. 추후에 프로젝트를 진행할 때에는 로컬 환경, 개발 환경, 운영 환경과 같이 각 상황에 맞는 설정 정보를 다뤄야할텐데 미리 학습해보셨다 생각해주시면 좋겠네요..!

2023-05-08 11:02 UTC, toneyparky approved these changes
안녕하세요 오도~!

이번 미션 충분히 잘 마무리해주셨네요..! 조금 더 이야기 나누면 좋을 부분은 추가로 코멘트를 남겼어요. 다만 코드상으로는 크게 변경할 내용이 없기에 다음 미션을 위하여 머지하도록 할게요. 질문에 대해 답변은 남겨주세요~!

궁금한 사항이 있다면 지금처럼 언제든 DM 주세요 🙂
고생 많으셨습니다!

2023-05-08 11:02 UTC, toneyparky commented on src/main/java/cart/service/CartSearchService.java
> +public class CartSearchService {
이제는 객체가 더 늘어났군요..!

<img width="296" alt="image" src="https://user-images.githubusercontent.com/37579660/236806357-51c4f173-7f90-41dc-a649-475147152c56.png">

이름으로 구분하지만 원하는 객체를 찾기 어려울 수 있겠다는 생각이 드네요. 만일 여기에서 도메인이 하나 더 추가될 경우에는... 😀

현재는 레이어별로 패키지가 구성되어 있지만 이를 도메인 별로 나눠보면 또 다른 시야가 열릴거에요. ([참고 글](https://hyeran-story.tistory.com/160)) 각 도메인에 해당하는 패키지 하위에 컨트롤러, 서비스, 레포지토리, 도메인 등의 패키지가 있고 객체도 있는거죠. 시간적인 여유가 있다면 이 부분도 가볍게 적용해보시고 지금의 구조와 어떤 차이가 있는지 비교해봐도 좋겠네요.

2023-05-08 11:02 UTC, toneyparky commented on src/main/java/cart/domain/user/User.java
> +public class User {
DB에 저장되는 사용자와 실제 로그인이 완료된 인증된 사용자는 같은 개념일지에 대해서도 고민해봐도 좋겠네요...!
이렇게 별도의 개념이 도출된다는건 그에 맞는 유즈케이스가 있음을 의미하기에, 필요하다면 도출해볼 수 있어요.

2023-05-08 11:02 UTC, toneyparky commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +package cart.infrastructure;
`infrastructure`라는 패키지가 어떤 의미인지 궁금하군요..!

2023-05-08 11:02 UTC, toneyparky commented on src/main/java/cart/service/CartOwnerMismatchException.java
> +public class CartOwnerMismatchException extends IllegalArgumentException {
예외도 서비스 파일들과 함께 혼재되어 있어서 파악하기 힘들어지는군요..! 별도의 패키지로 분리할 수 있겠어요. 

개발을 하다보면 객체간의 관계도 중요하지만 패키지나 모듈의 구조도 중요해요. 프로젝트를 이해하는 첫걸음이기 때문이에요. 보통 새로운 프로젝트를 켜보면 리드미를 읽고 구조를 파악하니까요.

다음 미션에서는 주기적으로 의심하고 최적의 구조를 가지도록 개선해보죠. 다만 정답은 없기에 페어, 팀원과 열심히 대화를 나누시길..!

2023-05-08 11:02 UTC, merged

2023-05-08 12:13 UTC, odo27 commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +
그 부분까지는 생각하지 못했습니다! 오히려 아이디가 존재하지 않는지, 비밀번호가 일치하지 않는지 등을 알려주는 것이 해킹을 도와주는 꼴이 될 수 있었군요 😅 정리해주신 `상황에 맞는 예외 처리`에 대해 늘 고민하며 개발하겠습니다!

2023-05-08 12:18 UTC, odo27 commented on src/main/java/cart/service/CartSearchService.java
> +public class CartSearchService {
도메인형 패키지 구조! 적용해보겠습니다~ 😆

2023-05-08 12:22 UTC, odo27 commented on src/main/resources/schema.sql
> +);
`다만 해당 제약사항은 DB단의 제약 사항이에요. 이 제약을 무시하고 생성을 요청할 경우에는 DB 관련된 예외가 발생해요.`
이 부분은 이번 미션에서 `UNIQUE`를 적용했다면 놓쳤을 것 같아요! 짚어주신만큼 다음번에 사용할 때 꼭 체크하도록 하겠습니다~ 😊

2023-05-08 12:28 UTC, odo27 commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +package cart.infrastructure;
이번에 처음 Basic 인증을 구현하며 `스프링 학습 테스트` 교육자료에 있는 부분을 옮겨왔었는데 현재는 해당 클래스를 사용하고 있는 `/controller/auth` 패키지로 이동해야할 것 같습니다!

2023-05-08 12:32 UTC, odo27 commented on src/main/java/cart/service/CartOwnerMismatchException.java
> +public class CartOwnerMismatchException extends IllegalArgumentException {
좋습니다~ 참고자료로 남겨주신 `스프링 패키지 구조` 관련해서 더 알아보다 보니 어떤 식으로 패키지를 나눠야 하는지 감이 조금 잡히는 거 같습니다! 앞으로 말씀해주신 `패키지나 모듈의 구조`에 대해 자주 고민하고 많은 대화를 나누며 개발해보겠습니다 ㅎㅎ

2023-05-08 20:13 UTC, toneyparky commented on src/main/java/cart/infrastructure/BasicAuthorizationExtractor.java
> +package cart.infrastructure;
네..! 기존의 코드에서 만족하지 않고 더 나은 방향을 항상 고민해봅시다!