[2단계 - 장바구니 기능] 제리(권현재) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #320
Opened 2023-05-05 06:03 UTC by Hyeonjae-K

현구막 안녕하세요.
열심히 했지만 2단계 미션이 생각보다 오래 걸렸습니다😭

미션을 진행하면서 고민했던 점들 함께 남겨두겠습니다.
즐거운 주말 보내세요🔥

---

### 데이터 검증은 어디서 해야 하는가?
1. 컨트롤러에서 `@Valid`를 통해 검증했지만 현구막의 리뷰대로 비즈니스 로직이 바뀔 경우 비즈니스 규칙이 드러난 RequestDTO들을 모두 바꿔야 하므로 도메인에서 모든 검증을 처리하도록 했습니다.
2. 모든 요청은 결과적으로 도메인을 거쳐야 하므로 컨트롤러를 통하지 않는 요청에 대해서도 검증이 이뤄질 수 있다는 장점이 있으나 간단한 검증까지 도메인에서 하므로 컨트롤러에서 검증하는 것 대비 불필요한 리소스를 사용한다는 단점이 있었습니다.
3. 결과적으로 당연한(?) 검증은 컨트롤러에서 하고 비즈니스 룰과 관련된(글자수, 가격 범위 등)은 도메인에서 하도록 했습니다.
하지만, 당연한 검증과 비즈니스 룰 사이의 기준을 정하는게 힘든것 같습니다. (예를 들어 사용자명의 형식을 이메일 형식으로 받는다면 우리 서비스에선 당연한 거지만 비즈니스 규칙이기도 해서 어디서 검증을 해야 할지 모르겠습니다)

이러한 경우 현구막은 어떻게 하실 것 같나요?

### Interceptor와 ArgumentResolver를 통한 인증
저는 인증 값을 처리하여 객체로 반환해주기 위해 ArgumentResolver를 사용했습니다.
하지만 Interceptor를 사용할 경우 `addPathPatterns()`를 통해 특정 경로로 들어오는 모든 요청에 대해 검증을 수행하므로 컨트롤러 단위로 설정해줄 필요가 없어 중복이 제거되고 개발자의 실수로 인해 특정 컨트롤러에 인증이  빠지는 실수를 방지할 수 있을 것 같습니다.
또한, 현재는 ArgumentResolver에 의해 반환된 객체를 모든 컨트롤러가  사용하고  있지만 반환 객체가 불필요한 경우에도 ArgumentResolver를 사용해야  한다는 단점이 있는 것 같습니다.
현구막은 ArgumentResolver를 통해 인증하는 것을 어떻게 생각하시나요?

2023-05-07 01:27 UTC, Hyeon9mak requested changes
안녕하세요 제리! 2단계 진행 고생 많으셨어요.
엔티티 관련된 부분이 크게 리팩터링되어 오래걸리 실 수 밖에 없었겠다 생각이 듭니다 👍 👍 
덕분에 즐겁게 코드 구경했어요!

> 데이터 검증은 어디서 해야 하는가?

저도 제리와 같은 결정을 내릴 것 같은데요, 
너무 당연한 값(`가격은 음수일 수 없다.`)에 대해선 request 레벨에서 검증을 진행해 줄 수 있겠고, 
값에 대한 우리 비즈니스만의 정책(`가격은 최소 1,000원 부터 100원 단위로만 등록 가능하다.`)은
domain 계층에서 검증을 진행할 것 같아요.

말씀해주신 이메일과 같이 애매한 경우 2가지 선택이 있을 것 같은데요,
`@Email` 과 같은 잘 만들어진 어노테이션을 그냥 믿고 사용하는 것과,
`@Email` 도 쓰고 domain 게층에서도 한번 더 검증하는 것이 있겠네요.
저는... 귀찮더라도 사실 VO 는 한번 만들어두면 크게 변화가 생기지 않는 부분이라 후자를 택할 것 같아요.
(성능상 문제가 되지 않는 선에서) 검증을 여러번 진행해서 품질을 높이는 건 어쨌든 좋은 방향이니까요.

> Interceptor와 ArgumentResolver를 통한 인증

저는 최대한 간단한 방법으로 잘 구현해주셨다는 느낌을 받았고,
ArgumentResolver를 이용해주신 덕분에 member 정보를 바로 활용할 수 있는 점도 좋았어요.

interceptor 를 이용하면 path pattern 을 이용해서 개발자가 꼭 인지하지 않아도 
컨트롤러 동작 전후로 무언가를 해줄 수 있다는 장점이 있겠지만,
반대로 말하면 path pattern 을 깜빡하면 전후 동작을 빠뜨릴 수 있고,
path pattern 을 확인하지 않으면 의도치 않게 불필요한 전후 동작이 들어간다는 단점도 있는 것 같아요.
그래서 이러나 저러나 비슷하고, 결국 개발자가 긴장하고 개발해야한다는 느낌이네요 😄 

제가 잘못 알고 있는 걸수도 있는데, ArgumentResolver 는 컨트롤러의 파라미터 중 
supportsParameter 를 명시해둔 파라미터랑 일치하는게 있다면 동적으로 바인딩해주는 걸로 알고 있어요.
그래서 `MemberRequest` 를 명시하지 않은 컨트롤러에서는 ArgumentResolver 가 동작하지 않을 것 같은데...
제리의 고민이 해결되었을까요?

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/auth/AuthenticationPrincipalArgumentResolver.java
> +    }
argument resolver 를 이용한 사용자 정보 반환 👍

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/auth/exception/AuthorizationException.java
> +}
`@ResponseStatus` 어노테이션을 이렇게 사용할 수도 있군요..?
고민이 되는 부분은 예외는 제리가 만들어주신 프로그램 내부에서 언제든지 발생할 수 있는 것이고,
HttpStatus 는 Http 통신을 하도록 했을 때만 유의미한 내용 같아요.
Http 통신과 관련된 부분을 유지보수 하고 싶을 때 `AuthorizationException` 클래스 파일도 열어봐야하는데, 책임이 잘 나눠진걸까요?

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/config/WebMvcConfiguration.java
> +    }
다른 view controller 들도 한꺼번에 관리해주면 유지보수가 편해지겠네요 😄 👍 
view controller 를 잘 분리해두셨기 때문에, 이 피드백을 반영할 때 아마 큰 변화가 없겠네요.

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/controller/CartResourceController.java
> +    }
`productId` 와 `itemId` 가 혼용되는 것 같아요. 이를 통일해보면 어떨까요?

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/controller/exceptionHandler/GlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
👍 👍 비즈니스 예외 잘 핸들링해주셨어요.
한가지 고민해볼 포인트는 개발자가 예측하지 못한 예외 상황도 언제든지 발생할 수 있다는 점인데요, 
가령 제가 요청을 넣을 때 헤더에 content-type 을 명시하지 않은 경우에요.

```
{
    "timestamp": "2023-04-19T10:56:35.995+00:00",
    "status": 415,
    "error": "Unsupported Media Type",
    "path": "/products"
}
```

그럼 위와 같은 메세지를 볼 수 있는데, 사용자가 굳이 알 필요 없는 정보죠?
이처럼 예측하지 못한 예외에 대해서도 포괄적으로 관리할 수 있도록 
`Exception.class` 에 대한 핸들러도 명시해주면 더 좋습니다 👍

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/domain/cart/CartId.java
> +    }
id 포장 👍 
VO 니까 동등성 부여를 해줄 수도 있겠네요.

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/domain/cart/Item.java
> +        this.memberId = new MemberId(memberId);
역시나 "member id 와 product id 가 모두 일치하면 같은 아이템이다." 라는 의미로 동등성 부여가 가능하겠네요!

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/domain/cart/ItemEntity.java
> +    }
그러나 엔티티의 경우 식별자를 통해 상태변화를 추적하는 객체이므로, 엔티티에서는 id 에 대해서만 동등성 부여를 해주면 되겠네요 😄

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/domain/member/MemberPassword.java
> +    }
오, 꼼꼼한 검증 😄 👍

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/dto/request/ProductRequest.java
> +    private final int price;
오~ 맞아요. '가격정보' 라는 것에서 이정도 검증은 해줄 수 있죠 👍

2023-05-07 01:27 UTC, Hyeon9mak commented on src/main/java/cart/service/MemberService.java
> +    }
현재는 http 통신 과정에서도, db 에 저장할 때도 사용자 비밀번호를 암호화하지 않기 때문에 이 방식이 유효하지만,
실제로 http 통신 과정에서의 암호화, db 저장시 암호화가 진행되면 문제가 생길 수 있어 보여요.
사용자 id(email) 를 통해 엔티티 (혹은 도메인) 객체를 조회해온다음, 별개 로그인 로직(비밀번호 대조)을 만들어보면 어떨까요?

2023-05-07 01:27 UTC, Hyeon9mak commented on src/test/java/cart/service/ProductServiceTest.java
>      private ProductService productService;
ProductServiceTest 클래스가 길고 테스트 작성이 답답하지 않으셨나요?
ProductService 도 어느덧 100라인 가까이 작성되고 있어요.
현재 ProductService 가 상품이라는 데이터를 중심으로 넓은 의미의 클래스가 되어서인 것 같아요.

상품 생성 로직을 유지보수하고 싶을 때도 ProductService,
상품 조회 로직을 유지보수하고 싶을 때도 ProductService,
상품 수정 로직을 유지보수하고 싶을 때도 ProductService,
상품 삭제 로직을 유지보수하고 싶을 때도 ProductService
상품과 관련된 로직을 확인하려면 무조건 ProductService를 열어봐야하고, 유지보수 포인트를 찾기 어려워요.
그리고 병렬로 작업이 진행되면 merge conflict 가 발생할 확률도 높아보여요.

데이터가 아닌 요청(usecase)를 중심으로 클래스를 나눠보면 어떨까요?
각 요청에 알맞는 서비스 클래스를 만들어 나누면 패키지 트리에서 보여지는 클래스 파일의 개수는 많아지겠지만,
상품 생성 로직을 유지보수하고 싶을 때도 ProductEnrollService,
상품 조회 로직을 유지보수하고 싶을 때도 ProductFindService,
상품 수정 로직을 유지보수하고 싶을 때도 ProductUpdateService,
상품 삭제 로직을 유지보수하고 싶을 때도 ProductDeleteService
패키지 트리에서 한 눈에 유지보수할 포인트를 찾아볼 수 있고,
merge conflict 의 위험도 없으며, 테스트 코드도 한결 가볍게 보이겠죠.

2023-05-07 03:32 UTC, Hyeonjae-K commented on src/main/java/cart/controller/CartResourceController.java
> +    }
`productId`는 카트에 추가할 상품의 id를 의미하고 `itemId`는 카트에 들어있는 상품을 의미합니다. 확실히 내부 동작을 보지 않으면 `productId`와 `itemId`가 뭐가 다른지 알기 힘드네요😭
개발 편의를 위해 상품을 카트에 추가할 때 추가할 상품의 id를 `PathVariable`로 받도록 했습니다. post 메서드에서  body가 아닌 이러한 방식으로 등록할 상품의 정보를 함께 전달하는게 일반적으로 사용되는 개발 방식이 아닌건지 궁금합니다.

2023-05-09 16:47 UTC, Hyeon9mak approved these changes
안녕하세요 제리, 장바구니 미션 마지막까지 고생 많으셨어요.
요구사항도 모두 충족되었고, 피드백도 잘 반영해주셨습니다.
조금이라도 더 도움을 드리고 싶은데, 워낙 빠르게 잘 리팩터링해주셔서 어렵네요 ㅎ_ㅎ;;
가벼운 코멘트만 조금 남겼으니 가벼운 마음으로 확인 해주세요.

앞으로도 여러가지 시도를 해보시면서 제리만의 설계기준을 확보해나가시면 좋겠습니다!
궁금하신 점 DM, 코멘트 남겨주세요 🙇‍♂️ 
다음 미션도 화이팅입니다 💪

2023-05-09 16:47 UTC, Hyeon9mak commented on src/main/java/cart/service/product/ProductDeleteService.java
> +    @Transactional
서비스를 잘 분리해주신 덕분에 가독성이 엄청 높아졌네요!
`@Transactional` 어노테이션도 클래스 레벨에 붙여서 더욱 눈에 잘 띄게 할 수 있을 것 같아요.
신규 기능을 개발하는 개발자도 `@Transactional` 어노테이션을 깜빡하는 실수가 줄어들겠네요 😄

2023-05-09 16:47 UTC, Hyeon9mak commented on src/test/java/cart/service/product/ProductFindServiceTest.java
> +        assertThat(products.size()).isEqualTo(3);
`XXXXService` 테스트 코드도 가독성이 엄청 높아졌음이 체감되셨을까요? 😄 👍

2023-05-09 16:47 UTC, Hyeon9mak commented on src/main/java/cart/domain/member/Member.java
> +    }
아! 사실 멤버 비밀번호 관련 코멘트의 의도는 이런 느낌이었어요.

```java
public class Member {

    public void login(String password) {
        if (this.password.compareWithRawPassword(password) == false) {
            throw new 인증관련예외(...);
        }
    }
}

public class MemberPassword {

    public boolean compareWithRawPassword(String password) {
        return this.password == somethingEncryptLibrary(password))        
    }
}
```
```java
Member member = memberDao.findMemberByUsername(username);
member.login(password);
```

제가 너무 두리뭉술하게 코멘트를 남겼던거 같네요 😅

2023-05-09 16:47 UTC, merged