[2단계 - 장바구니 기능] 루카(백경환) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #322
Opened 2023-05-05 08:06 UTC by dooboocookie

안녕하세요 카일!! 😸
1단계 리뷰에서 해주신 조언을 토대로 최대한 2단계 잘 작성해보았습니다.

---

# 중요하게 생각한 부분
## 인증, 인가에 대한 `Interceptor`와 `ArgumentResolver`
- `AuthInterceptor`의 역할을 다음과 같이 정하였습니다.
  - 인증 정보가 필요한 `URL`에 대해서 요청에서 인증 정보를 확인한다.
    - `Authorization`헤더가 있는지 확인 (없으면, 401 응답)
    - `Basic`인코딩된 값인지 확인 (아니면, 401 응답)
  - `email`과 `password`가 맞는지 확인 (아니면, 401응답)
- `BasicAuthorizationArgumentResolver`의 역할은 다음과 같이 정하였습니다.
  - `@BasicAuthorization` 어노테이션을 아규먼트로 가지고 있는 핸들러를 호출할 때 파라미터를 넘겨준다.
    - `Authorization`헤더가 있는지 확인 (없으면, 401 응답)
    - `Basic`인코딩된 값인지 확인 (아니면, 401 응답)
  - `LoginUser` 타입으로 변환하여 파라미터로 넘겨준다.

## 도메인(엔티티)에 필드로 `FK ❌` &rarr; `도메인 객체 참조 👌`
### ERD
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/79090478/236401083-da5e1add-b770-4148-9d3f-e314f96267bf.png">

### 도메인(엔티티)의 클래스 다이어그램

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/79090478/236402090-47126938-876a-4c49-9faf-9c46d30c1f5a.png">

- 처음에는 CartDao에서 `JOIN을 사용하지 않고` Cart 테이블에 대한 정보만 가져왔습니다.
  - 그렇다 보니, user_id나 item_id로 user나 item을 조회해야되는 상황이 발생되었습니다.
- 그래서 `JOIN`을 사용해서 User와 Item를 Cart의 필드로 갖도록 하였습니다.
- 엔티티와 도메인을 동일하게 보기 때문에, 추후에 Cart에 도메인 로직이 추가된다 하더라도 User와 Item이 도메인 객체로 존재해야 더 적절할 것 같아서 이렇게 진행하였습니다. 

---

# 질문 사항
## 1. Basic 인증과 Interceptor 관련
- Basic인증을 사용하라는 요구조건이 있습니다.
- 인증 처리된 정보가 서버에 저장되어있지 않아, 매번 Base64로 인코딩된 정보를 디코딩하여  맞는 회원인지 확인합니다.
- Basic인증의 보안의 약점은 둘째 치고, 코드상으로 몇가지 문제가 보이는데요.
  1. Interceptor에서 매번 인증처리를 위해 Service를 호출해야한다.
    -> 핸들러보다 앞단?에서 실행되는 인터셉터에서 서비스를 호출하는 것이 괜찮을지 궁금합니다.
  2. Interceptor에서는 인증을 위해, ArgumentResolver에서는 객체로 변환을 위해 해더를 뜯어서 확인하는 동일한 과정이 일어난다. 
    -> 이 중복은 Basic인증이여서 어쩔 수 없이 일어나는 문제라 생각하지만, 이에 대해서 어떻게 생각시는지 궁금합니다.
    -> 처음에는 둘 중 하나만 사용해야 하나 싶었지만, 인터셉터와 아규먼트리졸버의 역할이 확실히 다르다고 생각하였습니다.

## 2. CartDao에서 JOIN 사용
- 저는 위에서 얘기했던 이유로 Join을 사용하는데요.
- 전반적인 Cart 도메인 객체에 대한 의견이 궁금합니다.
- 만약에, Cart가 참조하고 있는 테이블이 많아지면, 그 테이블을 전부 조인하여, 전부 참조 주소를 객체로 갖고 있는 상황을 상상했을 때,
  - 하나의 조회 때문에 너무 큰일을 한다는 생각이 들었습니다.

## 3. CartService에서 401 응답을 위한 에러
- `UnauthorizedException`에러 발생 시, `401 응답`을 주도록 하였습니다.
- 대부분의 경우 Interceptor에서 에러 발생으로 401 응답이 나갑니다.
- 하지만, 삭제하려는 장바구니가 다른 회원의 장바구니 인 경우
  - 이 상황에서는 Service에서 그를 비교하고  `UnauthorizedException`가 발생합니다.
- 애초에 권한이 없어야 하는 요청을 service까지 끌고 들어온 느낌이 있습니다.
- 이에 대해 어떻게 생각하시는지 궁금합니다. 
---
저번에 리뷰 정말 꼼꼼히 해주셔서 많이 배울 수 있었습니다.
이번에도 리뷰 잘 부탁드리겠습니다!!

글 읽어주셔서 감사합니다!!🙇‍♂️🙇‍♂️🙇‍♂️

2023-05-06 17:15 UTC, KIMSIYOUNG requested changes
안녕하세요 루카
리뷰가 늦어 죄송합니다.
이미 잘 구현해주셔서 질문 남기신 부분에 대한 답변위주로 남겼어요.
확인해주시고 루카 의견도 조금 더 구체적으로 남겨주시면 이해하는데 더 도움이 될 것 같습니다.

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/main/java/cart/service/CartService.java
> +        if (!Objects.equals(user.getId(), cart.getUser().getId())) {
요 부분에 대해서 조금 애매하다고 생각하시는 것 같아요. 일단 이 로직이 있어야하는 이유는 무엇인가요?
말씀하신대로 이미 앞단에서 요청자가 누구인지 특정해주고 있으니까요.

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorizationArgumentResolver.java
> +public class BasicAuthorizationArgumentResolver implements HandlerMethodArgumentResolver {
Resolver 와 인터셉터의 차이는 무엇인가요? 
둘의 역할 경계가 명확해야 이 둘의 중복된 기능도 사라지고 각자의 역할에 충실할 것 같아요.

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/main/java/cart/dao/CartDao.java
> +public class CartDao {
`Join` 에 대해서 함께 조회하여 결과를 전달하는 것은 크게 문제되지 않는 것 같아요.
다만 말씀하신대로 어디까지를 한 `묶음`으로 간주할 것인지는 중요할 것 같아요. 
데이터의 생명주기 /  사용되는 패턴 / 여러 데이터를 하나의 그룹으로 만들 수 있는 개념 등이 존재하는 경우 이들을 묶어서 관리하는 것도 방법일 것 같아요. 어떠한 정답은 없는 것 같아요. 다만 위에서 말한 것들을 생각해서 설계하는 것 같습니다.

또한 이런게 DB를 다루는 엔티티와 도메인이 달라질 수 있는 포인트가 될 수도 있을 것 같아요.

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/interceptor/AuthInterceptor.java
> +    private final UserService userService;
서비스를 호출하는 것 자체는 크게 문제되진 않을 것 같아요. 
물론 레이어아키텍쳐에서 바로 자신의 다음 계층에 의존해야하는 법칙을 지킨다면 적절하지 않다고 볼 수도 있을 것 같아요.
다만 이 정도는 크게 문제되지 않는 선인 것 같아요. 고민이 된다면 (인터셉터에서 사용할 Component를 정의하고 같은 패키지에 두어도 괜찮을 것 같아요.)

+ 서비스를 사용하는 것은 괜찮지만 `인증 `을 위한 것과 `회원`에 관한 것 두가지는 혼용되지 않도록 조심하면 좋을 것 같아요.

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/util/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
테스트가 없는 것 같아요.🙂

2023-05-06 17:15 UTC, KIMSIYOUNG commented on src/test/java/cart/controller/CartControllerTest.java
> +        Mockito.verify(cartController, Mockito.times(1)).createCart(Mockito.any(), Mockito.anyLong());
깨지는 테스트가 꽤 많네요. 확인해주시면 좋을 것 같아요.

2023-05-07 03:22 UTC, dooboocookie commented on src/test/java/cart/controller/CartControllerTest.java
> +        Mockito.verify(cartController, Mockito.times(1)).createCart(Mockito.any(), Mockito.anyLong());
<img width="296" alt="image" src="https://user-images.githubusercontent.com/79090478/236655923-241bab54-1604-42e8-9b77-d74c9b875b9b.png">

제가 했을 땐 안깨지는데, 혹시 어떻게 깨지는지 알 수 있을까요?? 어디가 문제일지 잘 예상이 안됩니다 😭

2023-05-07 07:35 UTC, dooboocookie commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorizationArgumentResolver.java
> +public class BasicAuthorizationArgumentResolver implements HandlerMethodArgumentResolver {
# AuthInterceptor
### Interceptor의 역할
- handler 호출 전과 후에 처리해 줘야할 공통작업을 수행하는 역할
- 특정 URL패턴을 제외하거나 추가하여 그 요청이 있을 때에 공통작업을 수행한다.
### AuthInterceptor의 역할
- `인증`이 필요한 요청(/carts/**)이 오면 인증 처리
- `authorization`헤더 값으로 회원이 맞는지 판단 (없으면 401 응답)
    - Basic 인증인지 확인 (아니면 401 응답)
    - Base64로 디코딩
    - email가 존재하고, password가 일치하는지 확인 (틀리면 401 응답)
      - `어떤 회원인지`는 중요하지 않음  

# BasicAuthorizationArgumentResolver
### ArgumentResolver의 역할
- handler의 argument 타입에 따라 request의 값을 argument 타입에 바인딩해서 넘겨주는 역할
###  BasicAuthorizationArgumentResolver의 역할
- `@BasicAuthorization` 어노테이션이 있는 argument 에서 사용하는 Resolver
- `authorization`헤더 값을 파라미터로 바인딩 (없으면 401 응답)
    - Basic 인증인지 확인 (아니면 401 응답)
    - Base64로 디코딩
    - `LoginUser` 객체에 email, password 바인딩

# 차이점
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/79090478/236664205-9c9cbd11-fe6b-4b78-be20-bbd0273d5ee1.png">

(시퀀스 다이어그램을 처음 그려봐서... 적절히 그린 것인지는 잘 모르겠습니다...)

- `AuthInterceptor`는 `/carts/**`관련 요청이 왔을 때, 회원인지 맞는지 확인하는 역할
  - 인증, 인가의 역할  
- `BasicAuthorizationArgumentResolver`는 `@BasicAuthorization`인 아규먼트에 객체를 넘겨주는 역할
  - LoginUser 객체에 헤더 정보를 바인딩하는 역할

# 중복 코드
-  `Authorization` 해더를 디코딩해서 email과 password를 추출해내는 작업
- 위 작업이 한쪽에서는 `인증을 위해서` 하고, 한쪽에서는 `LoginUser에 바인딩`하기 위해서 합니다.
- 중복 기능이여도, 각자 꼭 필요한 일을 하는 것이라는 생각이 들어서 일단은 필요한 중복으로 생각하고 있습니다.

2023-05-07 08:29 UTC, dooboocookie commented on src/main/java/cart/service/CartService.java
> +        if (!Objects.equals(user.getId(), cart.getUser().getId())) {
저는 이게 지금 구조에서 제일 의아한 부분입니다.
현재`AuthInterceptor`에서는 `통과할 수 있는지(인가)`를 따져보는 것이 아니라,
매 요청마다 `회원인지(인증)`만 따져보는 상황입니다.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/79090478/236666408-8dbbbc88-678d-441a-a395-28650ae2f87c.png">

(시퀀스 다이어그램을 처음 그려봐서... 적절히 그린 것인지는 잘 모르겠습니다...)

어떤 사용자가 `DELETE /carts/1`과 같이 1번 장바구니 내역을 삭제를 요청했을 때,
1. `AuthInterceptor`에서 user(어떤 회원이든)인지 확인한다.
2. `CartService`에서 `지우고자 하는 Cart`와 `같은 User`인지 판별하고 아니면 401 응답

이러한 구조입니다.

`1번 회원의 정보에 접근하려할 때 이 회원이 1번인지`를 확인해야될 것 같은데,
현재 `/carts/**`요청들은 어떤 카트에 접근하는지 Interceptor에서 확인할 방법은 없고
인증이 성공한 회원의 정보만을 제공하고 있습니다.
일단 현재 미션 요구사항에 맞춰 구현해본 것인데, 
구조적으로 이상한 부분이 있거나, 개선할 부분이 있는지 궁금합니다.

2023-05-07 08:40 UTC, dooboocookie commented on src/main/java/cart/dao/CartDao.java
> +public class CartDao {
현재로서는 Cart라는 도메인이 적절하고 엔티티와 도메인을 분리해야할 필요성을 느끼지 못하여, 일단 이대로 가겠습니다!!

말씀해주신 내용을 토대로 설계에 대한 기준을 잡아갈 수 있도록 하겠습니다!! 좋은 말씀 감사합니다.

2023-05-07 08:58 UTC, dooboocookie commented on src/main/java/cart/controller/auth/interceptor/AuthInterceptor.java
> +    private final UserService userService;
현재는 `User의 목록을 불러오는` 로직과 `인증하는`로직이 같은 `UserSevice`로 묶여 있었는데,
두 가지 기능을 아무 곳에서나 사용하는 것을 방지하는 차원에서,
`auth`패키지로 분리하여, 인증을 위해서 쓰는 Component를 패키지로 분리하였습니다!!

2023-05-07 09:38 UTC, dooboocookie commented on src/main/java/cart/controller/auth/util/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
앗 테스트 추가하겠습니다!!

2023-05-07 10:53 UTC, dooboocookie commented
안녕하세요 카일!!
리뷰 감사합니다!!

인증하는 부분에 대해 집중적으로 답 남겨보았습니다!!

2023-05-08 02:58 UTC, KIMSIYOUNG commented on src/main/java/cart/service/CartService.java
> +        if (!Objects.equals(user.getId(), cart.getUser().getId())) {
아하 제가 이해를 잘못한 것 같아요. 
말씀하신대로 현재의 상황에서는 `401`또는 `404`, `400`을 검증하고 내려주는게 옳은 행위인 것 같아요.
앞단에서는 이를 알 수 없고 비즈니스 로직에서 `자신이 가지고 있는 목록이 맞는지`를 확인하고 이를 판단하여 결과를 전달하는게 자연스러운 것 같습니다.
응답코드는 루카의 생각에 따라 다르겠지만 `검증` 자체는 당연한 것 같아요.

401 : 비인가 요청
400 404 : 요청한 사용자가 가지고 있으면서, 카트번호는 1번인 카트는 없음

2023-05-08 03:02 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorizationArgumentResolver.java
> +public class BasicAuthorizationArgumentResolver implements HandlerMethodArgumentResolver {
말씀하신대로 `각자 꼭 필요한 일을 하는 것` 이라고 생각이 되신다면 현재 코드를 유지해도 좋을 것 같습니다. 또한 기능에 대해서도 잘 인지하고 계신 것 같아요.
다만 인터셉터에서 이미 정확한 인증수단과 인증수단에 해당하는 값이 있는지를 검증한다면, 이 값을 다음으로 넘겨주는 것까지 수행해도 역할을 과하게 가지고 있는 형태는 아닌 것 같아요. 
리졸버는 전달받은 값을 통해 Email, Password를 리졸빙할 수도 있지만, 어떤 값을 조회해서 다른 것을 리졸빙해줄 수도 있을테니까요.

2023-05-08 03:04 UTC, KIMSIYOUNG commented on src/main/java/cart/dao/CartDao.java
> +public class CartDao {
도메인이 없다면 데이터관점에서만 고민하면 될 것이고, 있다면 도메인 데이터 각각의 관점에서 어떠한 단위로 도메인묶음, 데이터묶음을 만들고 다른 도메인 묶음과는 어떻게 소통할 것인지에 대해서도 추후에 다른 미션들에서 고민해보시면 좋을 것 같습니다.

2023-05-08 03:04 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/interceptor/AuthInterceptor.java
> +    private final UserService userService;
넵넵! 잘 이해하고 반영해주신 것 같습니다.

2023-05-08 03:04 UTC, KIMSIYOUNG commented on src/test/java/cart/controller/CartControllerTest.java
> +        Mockito.verify(cartController, Mockito.times(1)).createCart(Mockito.any(), Mockito.anyLong());
앗 제 로컬파일이 문제였던 것 같아요. 죄송합니다 안 꺠지는 것 확인했습니다!

2023-05-08 03:14 UTC, KIMSIYOUNG requested changes
안녕하세요 루카
리뷰 반영 잘 해주셨네요!
몇가지 코멘트 남겼는데 확인 부탁드립니다. 
말씀하신 기능 구현이 되면 PR주세요!

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS CARTS
특정 사용자의 장바구니에 동일한 아이템을 담을 수 없다는 것을 제약조건으로 표현해보면 어떨까요? 

어플리케이션에서는 정합성을 완벽하게 보장하기 어렵지만 `RDB`의 제약조건을 사용한다면 효과적으로 이를 보장할 수 있어요.

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorization.java
> +public @interface BasicAuthorization {
현재는 `Basic`만 사용되지만 `Bearer`를 사용하는 곳도 생길 수 있을 것 같아요.
추상화해보면 좋을 것 같습니다.

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CartController.java
> +    @PostMapping("/{itemId}")
`carts`라는 자원에 접근하는 URL 이지만 itemId를 넣어주어야하네요. 부자연스러운 것 같아요.

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/Authorization.java
> +        Optional<User> findUserByEmail = userDao.findBy(email);
비밀번호를 함께 넣어 조회하는 것이 보다 정확하지 않을까요?

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/Authorization.java
> +public class Authorization {
네이밍이 너무 추상적인 것 같아요. 조금만 더 구체적으로 지어주면 좋을 것 같습니다.

2023-05-08 03:14 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/util/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
보통 이러한 파일에는 주석으로 어떠한 포맷을 어떻게 변환한다는 것을 명시해주는게 같이 작업하는 분들에게 더 도움이 될 것 같아요🙂

2023-05-08 12:12 UTC, dooboocookie commented on src/main/java/cart/service/CartService.java
> +        if (!Objects.equals(user.getId(), cart.getUser().getId())) {
아 생각이 정리되었습니다!!
현재로선 인증, 인가를 Interceptor에서 넘어가고 여기서 거절된다면, 401응답이 맞겠지만,

지금 같이 `1번 사용자`의 cart에서 `1번 상품이 없다`라고 판단하여 400 응답을 내주는게 맞을 것 같습니다!!

2023-05-08 12:15 UTC, dooboocookie commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorizationArgumentResolver.java
> +public class BasicAuthorizationArgumentResolver implements HandlerMethodArgumentResolver {
리졸버가 인터셉터에서 `request`나 어딘가에 캐싱(?)된 값을 꺼내서 다른 객체로 리졸빙 해주는 것도 방법이겠군요!!

근데 그럼 `그 리졸버가 꼭 해당 인터셉터 이후에 일어나야 한다`는 점이 두 개가 의존도가 너무 강하다는 생각이 듭니다!!
그래서 일단 현재로서는 이대로 유지해보려고 합니다!

2023-05-08 12:22 UTC, dooboocookie commented on src/main/java/cart/controller/auth/util/BasicAuthorizationExtractor.java
> +public class BasicAuthorizationExtractor {
넵! 주석으로 조금 더 의미를 분명히 나타내도록 하겠습니다!!

2023-05-08 12:38 UTC, dooboocookie commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS CARTS
RDB의 제약조건 추가하였습니다!
그리고 또한 RDB에서 제약조건으로 인한 에러를 던지면, SQLExcetpion을 컨트롤하기가 힘들 것 같아서 저장하기 전에 한번 조회해보는 방식으로 예외 핸들링하였습니다. (400 응답 주도록)

2023-05-08 12:44 UTC, dooboocookie commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorization.java
> +public @interface BasicAuthorization {
일단은 어노테이션 네이밍 변경하였습니다!

근데 어노테이션을 추상화한다는게 어떤 의미인지 모르겠습니다

`@Authorization` 어노테이션을 포함하는 `@BasicAuthorizaion`과 `@BearerAuthorizaion`이 있는 형태일까요?

그래도 제 생각엔 리졸버가 `supportsParameter(final MethodParameter parameter)`로 판단할 때`@BasicAuthorizaion`를 보고 판단할 것 같은데, 어떤 장점이 있는지 모르겠습니다.

2023-05-08 12:45 UTC, dooboocookie commented on src/main/java/cart/controller/auth/Authorization.java
> +        Optional<User> findUserByEmail = userDao.findBy(email);
앗! 그렇겠네요. 인증 처리가 된 사용자라고 가정하고 좀 나이브하게 생각했던 것 같습니다.

2023-05-08 12:48 UTC, dooboocookie commented on src/main/java/cart/controller/CartController.java
> +    @PostMapping("/{itemId}")
그렇네요...

심지어 밑에서는 @DeleteMapping("/{cartId}")로 사용하고 있네요..

POST하는 경우에는 cartId는 아직 없는 상태이고 아이템 정보와 인증 처리된 정보가 필요한 상황이니 요청 파라미터로 받도록 하겠습니다.

2023-05-08 13:00 UTC, dooboocookie commented on src/main/java/cart/controller/auth/Authorization.java
> +public class Authorization {
적절한 네이밍이 생각이 안나서, 일단 AuthorizationService라는 이름으로 변경하였습니다.

2023-05-08 13:01 UTC, dooboocookie commented
추가 구현하기로 한 부분은 시간이 부족할 것 같습니다.
이 부분은 제가 스스로 한번 해보겠습니다

일단은 리뷰주신 내용만 수정하여 보내겠습니다!!

2023-05-09 07:38 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorizationArgumentResolver.java
> +public class BasicAuthorizationArgumentResolver implements HandlerMethodArgumentResolver {
네네🙂말씀하신대로 두가지의 의존이 생기기마련인 것 같습니다. (둘다 인증 및 인증의 결과처리를 분리한 것 뿐이니까요).

2023-05-09 07:40 UTC, KIMSIYOUNG commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS CARTS
넵넵
`@Repository`를 달고 있으면 로우한 예외를 스프링 예외로 포장하여 전달해주고 있습니다. 그렇기에 `컨트롤하기가 힘들 것 같아서`는 맞지만 try-catch 로 잡아서 처리하는 것이 조회하는 것보다 더 정확한 방식이 될 것 같아요.

2023-05-09 07:42 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/argumentresolver/BasicAuthorization.java
> +public @interface BasicAuthorization {
`Authorization` 정도의 어노테이션을 만들고 요청을 파싱해서 Beaer, Basic 타입을 구분하여 각각 처리하는 핸들러를 만들면 어떨까 라는 생각이었는데요.
굳이 하지 않아도 되는 추상화인 것 같습니다!

2023-05-09 07:42 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/auth/Authorization.java
> +public class Authorization {
넵넵🙂

2023-05-09 07:44 UTC, KIMSIYOUNG approved these changes
안녕하세요 루카
리뷰 잘 반영해주셨네요.
잘 구현해주셔서 머지하면 좋을 것 같아요.
궁금하신 내용이나 더 이야기 나누고 싶은 내용이 있으시다면 디엠 주세요.
고생하셨습니다.

2023-05-09 07:44 UTC, merged