[2단계 - 장바구니 기능] 라온(문채원) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #324
Opened 2023-05-05 11:47 UTC by mcodnjs

안녕하세요, 제이미! 라온입니다 😊

2단계 구현 마치고 리뷰 요청 드립니다!
예상했던 시간보다 조금 더 오래 걸렸네요 ㅎㅎ .. 

이번에도 최대한 간단하게 필요한 역할들만 구현해보았고, 
리팩토링+공부하면서 조금 더 기능을 추가하며 학습해보고자 합니다!

궁금했던 점 커멘트로 남겨놓았습니다! 리뷰하실 때 참고 부탁드리겠습니다!
휴일 잘 보내세요 :) 감사합니다 🙇‍♂️🙇‍♂️

2023-05-05 11:55 UTC, mcodnjs commented on src/main/java/cart/dao/CartDao.java
> +        String sql = "SELECT product.id, name, image_url, price FROM cart JOIN product ON cart.product_id = product.id WHERE member_id = (SELECT id FROM member WHERE email LIKE ?)";
사용자 이메일을 통하여 사용자가 장바구니에 담은 product를 가져오는 기능 구현 시, 위와 같은 쿼리문을 작성하게 되었습니다.
cartDao이지만 다른 많은 테이블을 참조하여 쿼리를 날리고 있는건 아닌지 의문이 듭니다 🧐

cartDao를 cart 테이블에만 국한시키고 싶다면, **여러 개의 쿼리를 날리는 방법**으로 해결될 수 있을 것 같은데
쿼리 실행 1번이 DB에 많은 부하를 불러올 수 있다고 알고 있어, 해당 방법을 어떻게 해결할 수 있을지 잘 모르겠습니다

member와 product를 참조하는 cart처럼, 다른 테이블을 참조하는 형태가 많아질수록 이런 문제가 더 많이 발생할 것 같습니다 ..!

2023-05-05 12:18 UTC, mcodnjs commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
Interceptor와 ArgumentResolver를 통해 사용자 인증 정보를 검사하는데요,
현재는 단순히 1) request header에 Basic 인코딩 값이 있으면 컨트롤러로 넘어가고, 
2) 컨트롤러에서 해당하는 이메일 값이 DB에 실제 존재하는지 확인하는 작업을 거칩니다.

이메일 값이 DB에 실제 존재하는지 확인하는 과정을 memberService와 같은 서비스를 통하여 이메일을 먼저 검증하는게 좋을까요? 
하지만, 컨트롤러 앞단에서 외부 DB에 접근하여 검사한다는 것이 불편하여 실제 이메일 검증은 하지 않았습니다

그럼에도 고려하게 되는 이유는 아래와 같습니다!

- 컨트롤러마다 매번 검증 로직 필요
- 단순히 authorization 헤더에 `Basic {email:password}` 형태의 유효하지 않는 값을 넣을 수 있음
- 실제 유효한 이메일인지 검증하는 것이 인가된 사용자이며 의미있는 인증 형태라 생각

2023-05-05 18:29 UTC, jamie9504 requested changes
라온, 안녕하세요. 리뷰어 제이미입니다. 😄 

미션 구현 잘 해주셨네요! 👍 
이번 리뷰는 대부분 코드에 대한 의견을 물어보는 부분이라 편하게 의견 달아주세요.

확인되면 다음번엔 테스트 위주의 코멘트들을 남겨보도록 할게요. 😉

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/dao/CartDao.java
> +        String sql = "SELECT product.id, name, image_url, price FROM cart JOIN product ON cart.product_id = product.id WHERE member_id = (SELECT id FROM member WHERE email LIKE ?)";
필요하면 조인을 하는 것도 좋다고 생각합니다.
Dao와 Repository라는 개념을 가볍게 훑어보는 것도 좋을 것 같아요!
장/단점을 분석해보고 상황에 따라서 적합한 방법을 선택해야 하는데요!

다음에 대해 간략히 의견을 적어주세요!
1. 조인을 사용했을 때의 장/단점
2. 조인을 사용하지 않았을 때의 장/단점
3. Dao와 Repository는 어떤 차이가 있는지

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
관련해서 이야기 하기 전에 라온이 알고 있는 것과 의견에 대해 간략히 서술해주세요!

1. Interceptor가 무엇이고, 사용한 이유는 무엇인가요?
2. ArgumentResolver는 무엇이고, 사용한 이유는 무엇인가요?
3. Interceptor에서 다음과 같이 사용하는 것은 어떠한 장/단점이 있나요?
    1. memberDao 사용
    2. memberService 사용
    3. 아무것도 사용하지 않음(현재)

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +        return new AuthInfo(auth[0], auth[1]);
1. 다음과 같은 상황에서 정상 동작을 하는데 이는 의도된 동작일까요? 
   ``` bash
    $ curl -i -X DELETE \
    -H "Authorization: jamie YkBiLmNvbTpwYXNzd29yZDI=" \        
    http://localhost:8085/cart/products/2
    // 결과
    HTTP/1.1 204 
    Date: Fri, 05 May 2023 17:57:17 GMT
   ```
2. 다음과 같이 잘못된 헤더를 입력하더라도 HTTP StatusCode 500을 반환하는데 이는 의도된 것일까요?
   ``` bash
   curl -i -X DELETE \
   -H "Authorization: basic amFtaWU=" \   // jamie             
   http://localhost:8085/cart/products/2
   // 결과
   HTTP/1.1 500 
   Content-Type: application/json
   Transfer-Encoding: chunked
   Date: Fri, 05 May 2023 17:59:35 GMT
   Connection: close
   
   {"timestamp":"2023-05-06T02:59:35.325969","errorMessage":"알 수 없는 서버 에러가 발생헀습니다."}%   
   ```
3. `BasicAuthException`이 발생했을 때, `handleCommonException`에서 핸들링되어 500 예외가 발생하네요!
HTTP StatusCode 400대를 공부해보고 적절한 응답을 내려줘볼까요?
4. 매직넘버는 상수화해볼까요?
5. 아래 부분은 Interceptor에도 있는데 의도된 중복일까요? 의도한 부분이라면 그 이유는 무엇인가요?
    ``` java
    String header = request.getHeader("Authorization");
    if (header == null) {
        throw new BasicAuthException("사용자 인증 정보가 존재하지 않습니다.");
    }
    ```

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/controller/CartController.java
>  }
1. 아래 중 (1)로 개행중인데, 그 이유는 무엇인가요?
    ``` java
    // (1) . 전부 개행
    return ResponseEntity
            .ok()
            .body(productByEmail);
    // (2) 한 줄에 . 하나
    return ResponseEntity.ok()
            .body(productByEmail);
    ```

2. `List<ProductResponse> productByEmail` -> 복수형으로 변수명을 선언하는 게 좋지 않을까요?

3. AuthInfo - `Info`는 불용어라 피해야한다. 라는 의견이 있는데, 라온의 의견은 어떠한가요?
    > 불용어(Noise word) - 큰 의미를 가지지 않아 검색엔진 색인에서 제외되는 단어

4. 라온이 URL을 선언할 때 사용하는 기준은 무엇인가요?
cart는 단수이고, products는 복수인데 id가 다음 depth로 들어오고 있어서 기준이 무엇인지 궁금합니다.

5. DELETE할 때, `productId`를 이용하고 있는데,
`cartId`, `memberId`, `productId` 중 어떤 것을 어떻게 이용하는 것이 좋을까요?

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/controller/ViewController.java
> +public class ViewController {
1. `ViewController`라는 클래스명을 가지도록 네이밍 기준을 잡으면, 반대는 `ApiController`가 될 것 같은데요.
이 부분은 어떻게 생각하시나요?

2. 도메인이 계속 늘어나면, 이 컨트롤러는 어떻게 될까요?

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/domain/Member.java
> +        Pattern pattern = Pattern.compile(EMAIL_REGEX);
Pattern 객체는 생성 비용이 큰 객체라서, 상수화 시키는 것이 어떨까요?

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleInvalidDomainException(Exception exception) {
1. `GlobalExceptionHandler`가 이 패키지에 위치하는 것이 좋을까요?
2. `ResponseEntityExceptionHandler`에 대해 알아볼까요?
    - 현재는 Http Method를 일치하지 않게 요청하면, 500 예외를 리턴하는데 이를 어떻게 처리해야 좋을까요?
    ``` bash
    $ curl -i -X POST \
    http://localhost:8085/cart/products/2    
    // 결과
    HTTP/1.1 500 
    Content-Type: application/json
    Transfer-Encoding: chunked
    Date: Fri, 05 May 2023 16:21:27 GMT
    Connection: close

    {"timestamp":"2023-05-06T01:21:27.783091","errorMessage":"알 수 없는 서버 에러가 발생헀습니다."}%      
    ```
3. `handleInvalidDomainException`으로 두 예외를 핸들링하고 있는데, 두 예외는 `RuntimeException`을 상속하고 있네요. 다음과 같은 상황에서의 장/단점은 무엇이 있는지 생각해볼까요?
    1. 현재와 같이 커스텀 예외 사용
    2. 위의 두 예외의 경우 `InvalidDomainException`라는 부모 예외를 만들어서 상속 후 부모 예외로 핸들링
    3. IAE 등 표준 예외 사용

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/service/CartService.java
> +@Service
`@Transactional`에 대해 알아볼까요?, readOnly 속성에 대해서도 알아보면 좋을 것 같아요!

2023-05-05 18:29 UTC, jamie9504 commented on src/main/java/cart/service/CartService.java
> +        }
`Optional`의 `ifPresent`에 대해서 알아볼까요?

2023-05-05 18:29 UTC, jamie9504 commented on src/main/resources/static/js/cart.js
>      axios.request({
1. axios에는 `axios.request()` 함수처럼 `axios.get()`, `axios.post()`와 같이 HTTP Method로 된 함수도 있어요!
이것을 사용해보는 건 어떨까요?
2.불필요한 주석은 지워주세요!

2023-05-07 14:59 UTC, mcodnjs reviewed
안녕하세요, 제이미! 라온입니다 😊

말씀 주신 부분 모두 반영하여 다시 리뷰 요청 드립니다 ㅎㅎ 
다시 리뷰 요청드릴 때 테스트 코드 조금 더 보완하여 리뷰 요청 드리고 싶었는데 
너무 리팩토링 기간이 길어지는 것 같아 그러지 못했네요 🥲

리팩토링 반영된 부분에 대해서도 더 보완할 점 있으면 말씀 부탁드립니다!
테스트 코드 리뷰도 잘 부탁 드리겠습니다! 
감사합니다 🙇‍♂️

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/controller/ViewController.java
> +public class ViewController {
각 URI와 서비스에 맞는 컨트롤러 클래스를 만들어주는 것이 명확하다고 생각하나, 
현재 구조에서는 각 Template마다 클래스를 만들어주는 것이 불필요하고 알아보기 어렵다고 느껴졌습니다 .. ! 

ViewController로 기준을 잡으니, 다른 컨트롤러에는 api가 붙어야할 것 같아서 아래와 같이 패키지 구성을 변경해보았습니다! view 패키지 내부에서 각 URI마다 클래스를 더 분리를 하는 것은 아직 불필요하다고 생각하여 분리하지 않았습니다!

```
controller
⎿ view
   ⎿ viewController
   ⎿ Admin(Template? View?)Controller (서비스가 더 커진다면 분리)
⎿ api
   ⎿ ProductController
```

기본적으로 View와 API 패키지(또는 클래스)가 나눠지고 -> 그 뒤에 관련 서비스에 맞춰 클래스를 분리할 것 같습니다!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/service/CartService.java
> +        }
`ifPresent`을 사용하면 if문을 따로 사용하지 않고도 예외처리를 할 수 있네요👍!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/resources/static/js/cart.js
>      axios.request({
모두 반영하였습니다!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +        return new AuthInfo(auth[0], auth[1]);
1. 조금 더 정확하게 토큰 검증을 하였습니다!
2. 조금 더 정확한 검증 후 401 상태코드를 내려주었습니다.
3. 권한 없는 사용자임을 나타내는 상태코드로 401 Unauthorized을 반환하였습니다.
401은 인증 되지 않은 사용자, 403은 인증된 사용자가 권한이 없는 요청을 하였을 때 사용하는 것으로 이해하였습니다!
4. 상수화하였습니다 👍
5. Interceptor와 ArgumentResolver를 통한 검증 및 객체 반환
    1. Interceptor에서 검증을 하지만, ArgumentResolver에서도 Authorization 헤더 값을 가져오려면 `request.getHeader()`를 이용해야하므로 ArgumentResolver에서도 동일한 코드를 사용하였습니다. 
    2. 검증 로직을 추가하면서 어디까지가 Interceptor의 역할인지 고민하였고, 디코딩한 토큰값이 {email}:{password} 의 형태인지까지 검증하는 것까지 Interceptor의 역할이라고 생각하였습니다. 
    3. 그 후 Interceptor에서 검증하고 파싱한 인증 정보를 ArgumentResolver에 전달하는 방법에 있어서 HttpServletRequest 객체를 사용하였습니다. 이 방법 외에도 ThreadLocal 혹은 RequestScope 등을 사용하는 방법이 있다고 하는데, 잘 모르는 개념이라 우선 간단하게 HttpServletRequest객체에 전달하였습니다!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
1. **Interceptor**는 요청 URI에 매핑된 controller 메서드를 호출하기 전후에 실행되며, 요청 및 응답에 필요한 인증, 전처리, 후처리 등을 위해 사용하는 인터페이스입니다. 이번 미션에서 사용한 이유는, 요청 보낸 사용자가 인증된 사용자인지(Basic 토큰을 가졌는지) 실제 컨트롤러 메서드 실행 전에 확인하기 위해 사용하였습니다. + 중복제거
2. **ArgumentResolver**는 Interceptor를 거친 후 컨트롤러 호출 직전 실행되며, 요청값으로부터 핸들러 메서드의 필요한 객체(파라미터)를 만들기 위해 사용하는 인터페이스입니다. 이번 미션에서 사용한 이유는, Authorization 헤더로 전달된 토큰값에서 이메일을 추출하고 AuthInfo의 객체 형태로 컨트롤러 메서드에 넘겨주기 위하여 사용하였습니다. + 중복제거
3. 장/단점
   1. memberDao 사용
      - 장점: 인증된 이메일인지 검증 로직 중복 제거 가능, 보안 수준 높음
      - 단점: 계층형 아키텍처 깨짐 
   2. memberService 사용
      - 장점: 인증된 이메일인지 검증 로직 중복 제거 가능, 보안 수준 높음
      - 단점: 계층형 아키텍처 깨짐, memberService 주입 필요
   3. 아무것도 사용하지 않음(현재)
      - 장점: 인터셉터 로직 단순 ..
      - 단점: 인증된 이메일인지 검증 로직 중복, 보안 수준 낮음

계층형 아키텍처를 꼭 지켜야 하는건 아니지만, 해당 구조를 유지하고 싶다면 파싱 가능한 토큰인지만 확인하는 검증 로직만 갖고, 조금 더 유의미한 검증을 하고 싶다면 dao를 통하여 이메일 확인까지 이뤄지는게 좋을 것 같아요 ! 
추가적인 코멘트 있으시면 남겨주시면 감사하겠습니다 🙇‍♂️

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/controller/CartController.java
>  }
1. 해당 방법이 가독성이 좋아 보여서 사용하였습니다 .. !
2. 넵! `productResponses`로 수정하였습니다
3. Info가 불용어였군요 .. 🫢 전 인증 정보라는 명확한 의미를 갖고 있는 것 같다고 생각이 들지만, 여기 세계에서는 불용어로 다루어 지는 것 같아 다른 많은 사람들이 그렇게 생각할 수 있다고 생각합니다 ㅎㅎ `AuthMemberDetails`로 바꾸어 보았습니다! 
4. `/cart/products/{productId}` 로 선언한 이유는 장바구니 하나에 여러 개의 상품이 들어갈 수 있다고 생각하였습니다. 클라이언트에서 직접적으로 cartId로 api를 요청할 일은 장바구니 기능 상 없을 것이라고 생각하였습니다. 다만 5번 질문에서 말씀 주신 것처럼 cartId를 이용하여 삭제할 수 있다고 생각하고, cartId가 활용될 다른 기능들이 있을까 하여 조금 고민이 되네요 .. 이 부분은 조금 더 고민해보겠습니다!
5. cartId를 이용하여 삭제할 생각은 못했는데요, 왜 못했나 생각해보니, 프론트에서 cartId 값을 가지지 않았기 때문이고, 가지지 않았던 이유는 프론트에서 알 필요가 없는 정보였기 때문이었습니다. cartId의 활용성에 대해 조금 더 생각해보게 되네요! 4번 질문과 같이 조금 더 고민해보겠습니다 ㅎㅎ

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleInvalidDomainException(Exception exception) {
1. controller의 전역 예외를 담당하는 클래스로서, 저는 exception 패키지에 위치하는 것이 적절하다고 생각되는데 제이미 생각은 어떤가요 ?! controller 패키지의 exception 패키지도 생각해보았지만, 컨트롤러 클래스 별로 핸들링하고 있는 것이 아니라서 exception 패키지에 두어도 무방하다고 생각하였습니다!
2. `ResponseEntityExceptionHandler`를 상속받지 않으면 사용자가 직접 정의한 핸들러로 처리하게 됩니다. 따라서, 위와 같이 클라이언트의 에러라도 서버의 에러라고 반환하는 결과가 나타납니다. Spring MVC Exception을 명확하게 핸들링하기 위해선 `ResponseEntityExceptionHandler`을 상속받아 ControllerAdvice를 구현하는 것이 좋을 것 같습니다! 해당 방법으로 리팩토링 하였습니다 ~! 
3. 핸들링할 도메인이 많아지면 ii번 방법으로 하는 것이 확장성 측면에서 좋을 것 같습니다. 또한, 계층 구조를 명확히 할 수 있을 것 같아요. 표준 예외를 사용하면 다른 표준 예외를 던지는 에러들과 함께 처리되므로, ii번 보다 추상적인 에러 핸들링이 될 것 같습니다. 현재 구조보단 ii번 방법을 사용하는 것이 더 좋을 것 같아요!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/service/CartService.java
> +@Service
@Transactional 어노테이션을 통해 프록시 객체가 생성되어 자동으로 커밋 혹은 롤백이 가능합니다. 이를 통해 예외 발생 시 롤백 처리를 자동으로 받아 데이터 무결성과 일관성을 유지할 수 있을 것 같습니다. 또한 readOnly 속성을 통하여 성능적 최적화를 기대할 수도 있고, 쓰기 작업을 방지할 수도 있습니다!

2023-05-07 14:59 UTC, mcodnjs commented on src/main/java/cart/dao/CartDao.java
> +        String sql = "SELECT product.id, name, image_url, price FROM cart JOIN product ON cart.product_id = product.id WHERE member_id = (SELECT id FROM member WHERE email LIKE ?)";
1. Join 사용
   - 장점: JPA의 N+1 문제 방지, 적은 수의 쿼리로 외부 리소스 요청 줄임, 데이터 중복 줄임
   - 단점: 참조된 많은 테이블에 의존성 증가, 복잡한 쿼리문, join으로 인한 속도 저하 발생 가능(그럼에도 2번의 쿼리보단 낫을 것 같습니다. 현재 이 작은 데이터만으로는 전혀 상관없을 것 같구요!)
2. Join 사용 X
   - 장점: Dao 클래스 자체에서 테이블 간의 의존성 감소시킬 수 있음, 직관적인 쿼리
   - 단점: JPA의 N+1 문제 발생, 여러 번의 쿼리 요청 필요, 데이터의 중복
(JPA의 N+1 문제에 대해서는 아직 잘 모르는데, 카더라로 알고 있습니다. 중요한 문제라고 알고 있어서요!)
3. DAO와 Repo는 DB 테이블 중심 vs. 도메인 중심 정도로 이해했습니다. 제이미가 해당 키워드를 던져주신 것은 Repo에서 여러 DAO를 사용하여 접근할 수 있어서 라고 생각이 드는데 맞을까요 ?!

2023-05-07 19:07 UTC, jamie9504 requested changes
라온, 안녕하세요. 리뷰어 제이미입니다 😄 

코멘트 조금 더 남겼습니다. 💪 

금일 18시 전으로 리뷰요청 주시면, 리뷰를 한 번 더 드릴 수 있으니 최대한 의견을 남겨주시고 or 반영해주시고
마지막 요청 기준 시간 전에 리뷰요청 주시면 좋을 것 같아요.
18시 이후로 리뷰요청이 온다면, 별도의 코멘트 없이 머지할 예정입니다. 😉

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/dao/CartDao.java
> +        String sql = "SELECT product.id, name, image_url, price FROM cart JOIN product ON cart.product_id = product.id WHERE member_id = (SELECT id FROM member WHERE email LIKE ?)";
1. 라온이 더 장점이 크다고 생각하는 방법으로 결정해보면 좋을 것 같아요!
2. n+1 문제에 대해서 가볍게 어떤 문제인지 알아보는 것도 좋을 것 같네요 😄 
3. dao와 repository는 약간의 차이가 있는데요! 조인을 사용하는 현재의 로직은 dao에 가까울까 repository에 가까울까 한 번쯤 생각해봐도 좋을 것 같아서 코멘트 남겨놨었습니다.
또한 Cart Table을 중심으로 조회하지만, Product를 반환하므로 이 부분도 생각해보면 좋을 것 같았습니다.

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
1. Interceptor는 어떠한 계층일까요?
2. Crosscutting Concerns에 대해 알아볼까요?

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/controller/CartController.java
>  }
1. 그렇군요! 저는 뭔가 첫 줄에 `ResponseEntity`라는 클래스명만 표시되다보니, 한 눈에 가장 중요한 부분이 보이지 않는다고 생각했습니다. 아래처럼 사용하는 것이라고 느껴졌거든요! 그래서 코멘트 남겨보았습니다 😄 
    ``` java
    authMemberDetails
        .getEmail()
    ```

2. 👍 
3. 불용어이지만, 라온이 충분히 의미를 담은 부분이라고 생각하고 직관적인 부분이라면 사용해도 되긴 하겠죠 😉 그렇지만, 인증정보라는 것은 말 그대로 인증에 대한 정보를 줄 것 같긴 하지만 그게 Member에 대한 정보인지 어떠한 정보인지 추측이 어렵다고 생각했습니다.
4. 👍 
추가적으로 장바구니에 상품을 추가 성공하면 `URI.create("/cart/products")` 값을 내려주는데요. POST API 등록 성공시 내려주게되는 URL은 어떠한 URL이어야 할까요?
5. `프론트에서 알아야 하는 정보 >= 사용자에게 노출해야만 하는 정보` 라고 생각해요.
왜냐하면, 예를 들자면 BE에서 cartId로 무언가를 조작한다면 사용자에게 노출하진 않지만 프론트에서는 그 정보를 알아야 BE에게 요청할 수 있기 때문에 알고는 있어야 한다고 생각하기 때문이에요! 😃 
즉 BE에 요청을 하기 때문에, FE가 알아야 하는 정보가 있기도 하고, FE에서 보여줘야 하기 때문에 BE에서 보내줘야 하는 정보도 있는거죠!

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleInvalidDomainException(Exception exception) {
1. `GlobalExceptionHandler`는 예외가 발생했을 때, Controller 대신 응답을 내려주므로 controller쪽 패키지에 위치하는 것이 어떤가 생각했습니다. 뭔가 exception 패키지는 custom exception들만 정의되어있을 것 같아서요!
2. 👍 
3. 👍

2023-05-07 19:07 UTC, jamie9504 commented on README.md
> +    - 장바구니 상품 삭제: `DELETE /cart/products/:productId`
URL에 대해서 고민해봐도 좋을 것 같아요!
1. 라온은 URL을 어떤 기준으로 설계하시나요?
2. URL만 보았을 때, 이것이 "로그인한 사용자의 장바구니"라는 것을 알 수 있을까요?
3. 현재는 장바구니에 같은 상품을 1번만 담을 수 있는데, 만약 n번 담을 수 있도록 변경되면 어떻게 될까요?
4. `장바구니 하나에 여러 개의 상품이 들어갈 수 있다고 생각`이라면 구조가 `/carts/{cartId}/products/{productId}` 이런 구조가 예상되기도 하지만 실제 cartId는 장바구니에 대한 식별자는 아니긴 하네요 😄 
---

장바구니 화면은 어떠한 차이가 있을까요? 

#### 현재 화면
<img width="355" alt="image" src="https://user-images.githubusercontent.com/59511689/236696925-b5c05602-45a7-4e86-bcd6-c47b4a30aebe.png">

#### 요구사항
<img width="355" alt="image" src="https://user-images.githubusercontent.com/59511689/236696914-b8056119-255c-4811-aa32-0685d1ec1595.png">

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/auth/AuthInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
1. 아래 로직의 책임은 `Interceptor`에 있을까요? `AuthorizationExtractor`에 있을까요?
    ``` java
        if (credentials.size() != 2) {
            throw new InvalidBasicAuthException("유효한 Basic Token 값이 아닙니다.");
        }
    ```
2. 아래 부분을 보았을 때, credentials를 클래스로 만들어줄 수도 있겠네요 😄 
    ``` java
        List<String> credentials = basicAuthorizationExtractor.extract(request);
        // 생략
        request.setAttribute("email", credentials.get(0));
        request.setAttribute("password", credentials.get(1));
    ```

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleCommonException(final Exception exception) {
method에 모두 접미사인 `Exception`을 제거한 것 같은데, 해당 메서드는 제거하지 않은 이유가 있을까요?

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/auth/AuthMemberDetails.java
> +public class AuthMemberDetails {
`Details`는 빼도 좋을 것 같은데 라온의 취향대로 가시죠!
(s는 복수형일 것 같긴 하네요)

2023-05-07 19:07 UTC, jamie9504 commented on src/main/java/cart/dao/MemberDao.java
> +    public Long findByEmail(final String email) {
Member를 찾는 메서드가 아닌데, 메서드명을 어떻게 바꿔주는 것이 좋을까요?

2023-05-07 19:07 UTC, jamie9504 commented on src/test/java/cart/controller/CartControllerTest.java
> +import cart.controller.api.CartController;
1. 일부 파일 EOL이 없네요! <img width="33" alt="image" src="https://user-images.githubusercontent.com/59511689/236696986-69289ef9-1e9f-49ac-a275-dc29d2264eaa.png">

2. `Authorization` 헤더 관련 많은 검증이 추가되었는데, 검증에서 예외가 발생하는 경우에 대한 테스트가 일부 없는 것 같네요 😄 
3. `GlobalExceptionHandler`에 대한 테스트도 진행해볼까요?
4. `@Valid`에 대한 테스트가 대다수 진행되었는데, 일부의 경우에도 추가해주면 좋을 것 같습니다. (ex. `@url`)
5. 현재 통합테스트는 `ProductIntegrationTest`만 있는데, 전반적으로 통합테스트를 추가해볼까요?
6. 통합테스트(`@SpringBootTest`)를 사용하는 것과, 단위테스트(`@WebMvcTest`)를 사용하는 것은 어떠한 차이가 있었나요?
7. 라온은 6번 중 어떤 방식의 테스트를 선호하고, 그 이유는 무엇일까요?
8. `MemberDao`에서 보면, `/data-test.sql`를 통해 데이터를 먼저 넣고 아래 테스트를 할 때 이용하고 있는데요. `@BeforeEach`, `@BeforeAll`로 선언해주는 것과는 어떤 차이(장/단점)가 있을까요?

2023-05-08 08:03 UTC, mcodnjs reviewed
안녕하세요, 제이미! 12시간 만에 또 뵙네요 ㅎㅎ ..

제이미에게 한번 더 리뷰 받고자 빠르게 반영하여 리뷰 요청 드립니다!
이번엔 주신 코멘트에 깊게 생각할 시간이 충분치 않아 생각나는대로 코멘트를 적었는대요,
답변하지 못한 부분도 있습니다 ㅠㅠ 감안해서 봐주시면 감사하겠습니다 🙇‍♂️🙇‍♂️
요청 보낸 뒤에도 조금 더 생각해보겠습니다!  (새벽 4시 빠른 리뷰 감사드립니다 ㅠㅠ )

URL에 대해 조금 고민해보았는데, 이후에 리팩토링한다면 코멘트에 남긴대로 `/cart-products/{cartId}` 혹은 `/cart/{cartId}의 형태를 가지갈 것 같아요! (productId로 컨트롤해야하는 이유가 있을까? 하는 생각이 들더라구요!) 조금 더 고민해보겠습니다 😅

2023-05-08 08:03 UTC, mcodnjs commented on src/main/java/cart/auth/AuthInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
1. Extractor의 역할은 정말 auth 추출의 역할 정도만이라고 생각하여 의미있는 코드라고 생각했는데, 다시 고민해보게 되네요 .. 추출 과정에서 password가 없다면 추출이 안된거라고 볼 수도 있겠네요 🫢 (Basic 토큰에 대한 유효한 추출을 실패한거죠) Extractor로 책임을 넘겨주었습니다! 정말 한끝 차이인 것 같아요 🤯
2. 오 그렇네요! 이 부분에 동의하고 수정하려 하였는데, 그렇게 되면 `AuthMember`와 동일한 클래스가 되는 것 같아요 ..! 의도하신 바가 맞을까요 ?! DAO를 사용한 검증을 추가한다면, ArgumentResolver에서 DB에 있는 이메일인지 검증하고 검증된 `AuthMember` 자체를 객체로 반환해주는 방법도 있을 것 같아요! (이 경우`AuthMember`와 `Credentials`은 같은 필드를 가지고 있을수도 있고, `AuthMember`는 Member와 관련된 추가적인 필드(ex. 나이, 성별 등)를 가질 수도 있을 것 같아요. 그럼 이 경우에 새로운 AuthMember를 반환하는 것이 아니라 Member 를 반환해줘도 괜찮을까요 .. ? )

2023-05-08 08:03 UTC, mcodnjs commented on src/main/java/cart/dao/MemberDao.java
> +    public Long findByEmail(final String email) {
`findIdByEmail` 로 변경해주었습니다!

2023-05-08 08:03 UTC, mcodnjs commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleCommonException(final Exception exception) {
method에 `Exception` 접미사를 모두 제거한 이유는 `ResponseEntityExceptionHandler` 클래스의 메서드를 오버라이드 하면서 메서드 네이밍이 모두 달라 통일성을 지키고자 제거하였는데, 해당 부분은 남겨두는게 명확해보여서 제거하지 않았습니다 😅 말이 앞뒤가 안맞는 것 같네요 .. `handleCommon` 으로만 메서드 네이밍을 짓기엔 부족해보였습니다 ㅠㅠ

2023-05-08 08:03 UTC, mcodnjs commented on src/test/java/cart/controller/CartControllerTest.java
> +import cart.controller.api.CartController;
1, 2, 4. 추가하였습니다!

3번과 5번은 시간관계 상 추가하지 못하였는데, 궁금한 점이 있습니다 ..!
3. `GlobalExceptionHandler` 이 부분은 어떤 식으로 테스트 하면 좋을까요 ..? 특정 에러를 던지는 케이스를 given으로 주고 해당 에러를 ResponseEntity 형태로 던지는지 검증하는 방식이 될까요 ?!
5. 통합테스트가 컨트롤러 테스트와 다른 점은 각각의 빈들을 주입받을 수 있으니, mock으로 스터빙하는 것이 아니라 직접 각 빈들의 동작을 확인할 수 있다는 점이 될까요 ?!

2023-05-08 08:03 UTC, mcodnjs commented on src/main/java/cart/auth/AuthMemberDetails.java
> +public class AuthMemberDetails {
AuthMember로 변경하였습니다 ㅎㅎ

2023-05-08 08:03 UTC, mcodnjs commented on src/main/java/cart/controller/CartController.java
>  }
1. `한 눈에 가장 중요한 부분이 보이지 않는다`에 설득되었습니다 ㅎㅎ 
3. `Member에 대한 정보인지 어떠한 정보인지 추측이 어렵다` 이 말도 동의가 되네요 👍
4. 장바구니에 상품을 추가하는 POST API 시 기대하는 URL은`/carts/{cartId}` 정도가 될 것 같아요
5. `프론트에서 알아야 하는 정보 >= 사용자에게 노출해야만 하는 정보` 저도 동의합니다 👍!

2023-05-08 08:03 UTC, mcodnjs commented on README.md
> +    - 장바구니 상품 삭제: `DELETE /cart/products/:productId`
제가 URL을 설계할 때는, 프론트와 백엔드 사이에서 주고받아야할 리소스들을 생각하고 설계하는 것 같습니다. `cartId 자체가 장바구니 하나의 식별자로서 역할하지 않는다` 이 말에 집중해서 보니 cart와 products를 URL에 합쳐 보아도 좋을 것 같습니다 ㅎㅎ 

장바구니 상품 추가: POST `/cart/products/{productId}` -> `/cart-products/{cartId}`
장바구니 목록 조회: GET `/cart/products` -> `/cart-products`
장바구니 상품 제거: DELETE `/cart/products/{productId}` -> `/cart-products/{cartId}`

2023-05-08 08:03 UTC, mcodnjs commented on README.md
> +    - 장바구니 상품 삭제: `DELETE /cart/products/:productId`
2. 아니요! 현재 URL로는 로그인한 사용자의 장바구니 라는 것은 모를 것 같습니다. 
다만, URL에 로그인한 사용자의 의미가 담겨야할 필요가 있는지는 잘 모르겠습니다 ..! 
3. 같은 상품을 N번 담는 경우의 URL을 말씀하시는 거겠죠 ?! 흠 .. 아직 잘 모르겠습니다 🥲

장바구니 화면은 변경하였습니다 ~!

2023-05-08 08:03 UTC, mcodnjs commented on src/test/java/cart/controller/CartControllerTest.java
> +import cart.controller.api.CartController;
6. @SpringBootTest vs. @WebMvcTest
`@SpringBootTest`의 경우 프로젝트에 있는 모든 스프링 빈을 등록하지만, MockMvc 객체를 빈으로 등록하지 않기 떄문에 `@AutoConfigureMockMvc`를 사용하여 빈으로 등록해줘야 합니다. 다만, 모든 빈을 등록하므로, 속도가 느릴 수 있습니다. 모든 빈을 다 등록하는 테스트이므로 통합테스트에 주로 사용됩니다.
`@WebMvcTest`의 경우 Web Layer 관련 빈(Security, Filter, Interceptor, Controller 등)만 로드하기 때문에 @SpringBootTest보다 빠르며, 작은 단위테스트에 주로 사용합니다.
7. 컨트롤러 테스트까지는 단위 테스트로 진행하여 @WebMvcTest를 사용하고, 현재 있는`ProductIntegrationTest`의 경우에 `@SpringBootTest`를 사용할 것 같습니다.
8. 1) data-test.sql을 사용하면, SQL 파일을 통해 별도로 유지보수 할 수 있고, 코드 가독성이 더 좋다고 생각합니다. 하지만, DB 관련 테스트 케이스들이 독립적이지 않을 수 있을 것 같습니다. 2) `@BeforeEach`, `@BeforeAll`을 사용한다면, 테스트 데이터를 실행할 때마다 데이터를 생성해야하므로 시간이 오래 걸리지만, 실행 시마다 데이터가 초기화되므로 독립적으로 실행될 수 있을 것 같습니다!

2023-05-08 18:00 UTC, jamie9504 requested changes
라온, 안녕하세요. 리뷰어 제이미입니다 😄 

빠르게 반영 or 의견 주셨네요! 이번에도 코멘트를 조금 달아두었습니다.
URL에 대한 고민은 코멘트에 달아둔 내용이 참고가 되면 좋겠네요.

수정하고 싶으신 부분까지 수정하신 후 리뷰 요청 주세요. 수정하지 않으셔도 상관 없습니다!
다음 요청은 별도의 코멘트 없이 Approve & Merge 될 예정입니다.

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/controller/CartController.java
>  }
1. 그렇다면, Post API에서 내려주는 URL도 바꿔줘볼까요? 
2. 위와 같이 (`/carts/{cartId}`)로 내려주면
POST `/cart/products`와 DELETE `/cart/products/{productId}` URL은 지금대로 유지하는 방향이 좋을까요?

2023-05-08 18:00 UTC, jamie9504 commented on README.md
> +    - 장바구니 상품 삭제: `DELETE /cart/products/:productId`
1. 👍 URL을 어떻게 설계할지도 마치 메서드 시그니처를 설계하듯 고민을 해두면 좋은 부분인 것 같아요! 2번 코멘트를 참고해주세요!
2. URL도 메서드명처럼 결국 어떠한 의미를 가지고 있는데, 그 부분이 의도가 명확하다면 FE와 BE가 따로 명세를 확인하지 않아도 이해하기가 용이하니까요!
예를 들어보자면, `public String getName()`이라는 메서드는 name이라는 String 값을 주는 메서드구나, 싶듯이 `GET /products/{productId}`은 productId에 해당하는 products를 응답해주겠구나!라는 것을 가늠해볼 수 있겠죠?
그런 측면에서 현재의 URL이 직관적인가를 고민해보면 좋을 것 같고, Restful API에 대해서 조금 더 알아봐도 좋을 것 같아요.
3. 2번 관련되서 학습해보고, 이 부분도 고민해보면 좋을 것 같아요! 정답은 없고 고민해보면 좋지 않을까 해서 적어둔 코멘트입니다 😉

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/auth/AuthInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
1. 👍 맞아요! 분리한 객체가 어디까지 책임을 가져가야 할지는 항상 고민이 되는 것 같아요 😢 
2. 그렇죠! 그렇게 된다면 `AuthMember`와 `Credentials`을 한 객체로 통일할지, 분리할지도 고민해보아야 해요. 
또한 Dao를 거친다면 `AuthMember`를 반환할지 `Member`를 반환할지도 고민해보아야겠죠?
위의 `Crosscutting Concerns` 관련된 코멘트를 고민하면서 이 부분도 같이 고민해보세요!

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleCommonException(final Exception exception) {
그렇군요 😄 
`ResponseEntityExceptionHandler` 클래스에서 오버라이딩한 메서드와 동일하게 메서드 네이밍을 가져갈지,
아니면 따로 가져갈지도 일관성만 있다면, 라온의 취향대로 가면 좋을 것 같네요.
`Exception`을 핸들링하는 부분이라, `handleException` 여도 괜찮을 것 같구요 😉

2023-05-08 18:00 UTC, jamie9504 commented on src/test/java/cart/controller/CartControllerTest.java
> +import cart.controller.api.CartController;
1. 👍 
2. 👍 
3. `GlobalExceptionHandler`에 대한 테스트를 어떻게 하고 싶은지 라온의 기준에 따라 다를 것 같은데요. 예를 들자면 이러한 방법들도 있겠죠? 이 부분은 다양한 방법이 있을 수 있으니, 크루들과 각자 어떻게 하고 있는지 이야기해봐도 좋을 것 같아요 😄 
    1. 기존 컨트롤러 테스트에 given()을 주어 원하는 HttpStatusCode 또는 응답값을 잘 내려주는지 확인
    2. 가짜 컨트롤러(모의 객체)에서 예외를 발생시키게끔 만들어서 확인
4. 👍 
5. 네, 현재 코드 기준으로는 인입되는 Controller부터 Dao까지 전체적으로 잘 동작하고 있는지를 확인하는 부분이 통합테스트인거죠!
6. 👍 
7. 그렇다면 컨트롤러 테스트까지는 단위 테스트를 하고, 별도로 통합 테스트까지 작성하는 것이 라온의 취향일까요?
각자 어디까지 테스트를 진행할지 의견이 다를 수도 있는데요. 예를 들자면 아래와 같은 의견이 있을 수 있겠네요.
라온은 어디까지 테스트를 하면 좋다고 생각할지 궁금하네요!
    1. 통합테스트에서 Happy Case, Bad Case 모두 진행 + 단위 테스트(컨트롤러 단위까지)도 모두 진행
    2. 통합테스트는 Happy Case만 진행 + 단위 테스트(컨트롤러 단위까지)는 Happy Case, Bad Case 모두 진행
    3. 통합테스트에서 Happy Case, Bad Case 모두 진행 + 단위 테스트는 하지 않음
    4. ... etc
8. 👍 이 부분도 라온이 느끼기에 장점이 큰 것을 골라서 일관성있게 작성하면 될 것 같아요.

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +                LocalDateTime.now(),
1. `ExceptionResponse`의 필드(`LocalDateTime timestamp`)로 시간을 내려주고 있지만,
응답시 시간도 내려주는 것을 알고 계신가요?
    ``` bash
    curl -i -X POST 'http://localhost:8085/cart'
    // 응답
    HTTP/1.1 400 
    Content-Type: application/json
    Transfer-Encoding: chunked
    Date: Mon, 08 May 2023 17:28:18 GMT
    Connection: close
    
    {"timestamp":"2023-05-09T02:28:18.448646","errorMessage":"Request method 'POST' not supported"}%    
    ```
2. `timestamp`라는 변수명은 뭔가 조금 덜 직관적인 것 같긴 하네요 😄 
`LocalDateTime` 자료형인데 `Timestamp` 자료형일 것 같은 느낌도 들어요.

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/exception/InvalidBasicAuthException.java
> +    public InvalidBasicAuthException(final String errorMessage) {
BasicAuth 관련된 인증 관련된 예외인데, 이렇게 되면 나중에 다른 인증 방식이 늘어날 때 인증 항목마다 예외가 늘어나겠네요!
Basic 관련된 별도의 처리가 없다면,`InvalidAuthException` 정도로 한 단계 추상화한 예외여도 괜찮지 않을까 싶은데, 라온의 의견은 어떤가요?

2023-05-08 18:00 UTC, jamie9504 commented on src/main/java/cart/exception/InvalidDomainException.java
> +public abstract class InvalidDomainException extends RuntimeException {
실질적으로 `InvalidDomainException` 추상 클래스와 구현된 클래스들이 어떻게 이용되고 있는지 확인해보고,
이걸 그대로 가는 것이 좋을지 합치는 것이 좋을지, IAE같은 클래스로 가도 괜찮을지 다시 한 번 더 고민해봐도 좋을 것 같아요!

커스텀 예외는 생성하게 되면 관리를 지속적으로 해줘야 하므로 필요성이 있을 때만 생성하는 것이 좋다고 생각합니다 😄 
물론 지금 상황에서 생성이 필요하다면 생성하는 게 맞습니다!

2023-05-08 18:00 UTC, jamie9504 commented on src/test/java/cart/auth/BasicAuthorizationExtractorTest.java
> +
1. 불필요한 두 줄 개행이네요!
2. EOL 표시가 아직 남아있는 부분들이 있네요?
3. 테스트 코드 네이밍을 어디까지 하는 게 좋을지도 시간될 때 고민해보면 좋을 것 같아요.
https://dzone.com/articles/7-popular-unit-test-naming
4. 파라미터에 조금 더 의미를 담아주면 좋겠죠? 예를 들자면, 아래의 경우 `invalidEncodedString` 이라던가요!
`void extractTest_parsingFail(String encodedString) {`
5. 의미가 애매한 경우, 변수화해서 이름을 지어줘도 좋겠네요 😉 
`Basic YUBhLmNvbTpwYXNzd29yZDE=`

2023-05-08 18:00 UTC, jamie9504 commented on src/test/java/cart/controller/ViewControllerTest.java
> +    }
개인적으로는 변경할 때 한 번에 변경되는 것을 선호해서 아래와 같이 중복되는 부분은 변수로 추출하는 것을 선호하는데요. 
(실수 방지 목적도 있습니다.)
이 부분은 참고만 해보시고, 라온 취향대로 가면 될 것 같아요.

``` java
@DisplayName("'/'로 GET 요청을 했을 때 index template을 반환한다.")
@Test
void getIndexPage() throws Exception {
    long productId = 1L;
    String name = "치킨";
    String imageUrl = "https://pelicana.co.kr/resources/images/menu/best_menu02_200824.jpg";
    int price = 10_000;
    Product product = new Product(productId, name, imageUrl, price);

    // given
    given(productService.findAll()).willReturn(List.of(ProductResponse.from(product)));

    // when, then
    String products = "products";
    mockMvc.perform(get("/"))
            .andExpect(status().isOk())
            .andExpect(model().attributeExists(products))
            .andExpect(model().attribute(products, hasItem(hasProperty("id", is(productId)))))
            .andExpect(model().attribute(products, hasItem(hasProperty("name", is(name)))))
            .andExpect(model().attribute(products, hasItem(hasProperty("imageUrl", is(imageUrl)))))
            .andExpect(model().attribute(products, hasItem(hasProperty("price", is(price)))))
            .andExpect(view().name("index"));
}
```

2023-05-10 18:26 UTC, mcodnjs reviewed
안녕하세요, 제이미! 라온입니다 😊

현재 진행중인 지하철 미션으로 큰 리팩토링은 하지 못하였습니다 ㅠㅠ
URL은 시간 관계 상 현재 구조를 그대로 사용하였고, 
그 외 남겨주신 코멘트들은 최대한 반영하였습니다! 

얻어간게 정말 많은 미션이었던 것 같습니다! 
2주 동안 꼼꼼하고 빠른 리뷰 감사드립니다 🙇‍♂️👍

2023-05-10 18:26 UTC, mcodnjs commented on src/test/java/cart/auth/BasicAuthorizationExtractorTest.java
> +
1. 삭제하였습니다!
2. 추가하였습니다 😅😅
3. 오 좋은 레퍼런스 감사합니다! 개인적으로 현재는 테스트할 메서드 네임을 테스트명으로 작성하고, 분기문이나 여러 가지 테스트가 필요하다면 StateUnderTest까지 적어주는 것 같습니다! `MethodName(_StateUnderTest)` 해당 방식으로 리팩토링하였습니다!
4. 넵 파라미터에도 구체적인 정보가 들어가면 더 좋겠네요 👍
5. 변수화하였습니다 👍

2023-05-10 18:26 UTC, mcodnjs commented on src/main/java/cart/controller/GlobalExceptionHandler.java
> +                LocalDateTime.now(),
1. 응답 시에도 시간을 내려주긴 하지만, 프론트와 서버에서 소통을 위해서 서버에서 편하게 정제하여 시간을 보내기 위해서 도움이 될 것 같아요! 혹은 에러가 발생한 시간과 응답을 내려주는 시간이 다를 수도 있지 않을까요 ?! 이를 활용하는 경우는 있을 것 같은데, 그런 경우가 없다면 .. 굳이 쓰지 않아도 될 것 같아요! 
2. 그런 것 같아요! localDateTime 으로 변경해주었습니다~!

2023-05-10 18:26 UTC, mcodnjs commented on README.md
> +    - 장바구니 상품 삭제: `DELETE /cart/products/:productId`
URL 설계에 정말 많은 고민과 생각을 담아야겠네요 🧐 
이번 미션 뿐만 아니라 다른 미션에서도, 실제 개발에서도 열심히 고민해보겠습니다 🙇‍♂️

2023-05-10 18:26 UTC, mcodnjs commented on src/main/java/cart/dao/CartDao.java
> +        String sql = "SELECT product.id, name, image_url, price FROM cart JOIN product ON cart.product_id = product.id WHERE member_id = (SELECT id FROM member WHERE email LIKE ?)";
1. 저는 join을 사용했을 때의 장점이 보다 크다고 생각됩니다!
2. 장바구니에 여러 개의 상품을 담을 수 있을 때 (상품은 하나의 장바구니에만 담길 수 있음), 장바구니를 조회(1번)하면 장바구니 개수(N번)만큼 상품에 조회를 날려 발생하는 문제로 이해하였습니다.
3. 해당 부분은 도메인 중심으로 DB에 접근하는 것이 맞는 것 같아 Repository에 조금 더 가까울 것 같아요!

2023-05-10 18:26 UTC, mcodnjs commented on src/main/java/cart/exception/InvalidBasicAuthException.java
> +    public InvalidBasicAuthException(final String errorMessage) {
넵 저도 동의합니다!

2023-05-10 18:26 UTC, mcodnjs commented on src/main/java/cart/exception/InvalidDomainException.java
> +public abstract class InvalidDomainException extends RuntimeException {
저는 개인적으로 생성해주는 것이 좋다고 생각합니다 ㅎㅎ 
구체적인 예외일수록 사용자에게 보여줄 에러 메세지의 정보를 충분히 보여주거나, 혹은 보안 상 감출 수 있다고 생각합니다! 
(예외 클래스를 통해 컨트롤할 수 있는 부분이 증가)

2023-05-10 18:26 UTC, mcodnjs commented on src/test/java/cart/controller/ViewControllerTest.java
> +    }
넵 저도 제이미와 동일한 의견입니다 ㅎㅎ 
중복되는 변수 추출하여 리팩토링 하였습니다 ~!

2023-05-10 18:26 UTC, mcodnjs commented on src/test/java/cart/controller/CartControllerTest.java
> +import cart.controller.api.CartController;
3. 이 부분은 조금 더 고민해보겠습니다!
5. 제대로 테스트 되지 않고 있던 ProductIntegrationTest와 CartIntegrationTest 추가 구현하였습니다! 
7. 넵 저는 2번을 선호하는 것 같아요! 통합테스트에서는 요청이 제대로 전달되고 응답이 반환되기 까지 정상적으로 잘 동작하는지만 확인하면 된다고 생각하고, Bad Case 같은 경우는 단위테스트를 통해 조금 더 빠르고 간편하게 정확한 테스트를 할 수 있다고 생각해요

2023-05-10 18:26 UTC, mcodnjs commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
1. Interceptor는 뷰와 컨트롤러 사이에서 동작하는데, 특정 계층에 속한다고 할 수 있을지 모르겠네요 🥲
2. Crosscutting Concerns는 어플리케이션 전반에 필요한 공통 기능들을 의미합니다. 지금 현재 처리하고 있는 보안도 서비스 전반에 필요한 공통적인 기능이므로 Crosscutting Concerns라고 할 수 있을 것 같아요! 이는 비즈니스 로직과는 구분되는 기능으로, 중복되는 공통적인 기능을 OOP를 하면서 적용하기에는 한계가 있어 AOP라는 기법을 사용한다고 하네요. AOP를 이용한다면 제가 고민한 문제들이 어느정도 해결될 것 같습니다 ㅎㅎ

2023-05-11 00:03 UTC, jamie9504 approved these changes
라온, 안녕하세요. 리뷰어 제이미입니다 😄 

지난번 코멘트에 남겼던 것과 같이 월요일 18시 이후에 온 리뷰 요청이라
별도의 코멘트는 남기지 않겠습니다.

장바구니 미션 고생 많으셨습니다. 👏 
현재 진행중인 지하철 미션도 화이팅입니다 💪 

Approve & Merge 합니다!

2023-05-11 00:04 UTC, merged