[2단계 - 장바구니 기능] 스플릿(박상현) 미션 제출합니다
woowacourse/jwp-shopping-cart pull request #331
Opened 2023-05-05 13:44 UTC by splitCoding

안녕하세요 또링!!👀😊

- Basic Authorization
- Interception
- ArgumentResolver
- ViewController 
- Mock, Stub, MockInjection

등을 이번에 학습하고 적용해보느라 좀 걸렸습니다 😭

1단계 PR의 코멘트에도 댓글 달았으니 그 부분도 같이 봐주시면 너무나 감사하겠습니다 👍

2023-05-07 09:33 UTC, jnsorn requested changes
안녕하세요 스플릿! 2단계 잘 구현해주셨어요 👏
조금 더 고민해보면 좋을 부분에 코멘트 남겨두었으니
확인해보시고 다시 리뷰 요청 주세요!

2023-05-07 09:33 UTC, jnsorn commented on src/test/java/cart/controller/api/ProductApiControllerTest.java
> +        final ProductCategoryDto updatedProduct = productService.findAll().get(0);
https://github.com/woowacourse/jwp-shopping-cart/pull/240#discussion_r1186011962

> 업데이트 이후에 업데이트 성공여부를 검증하는 부분에 대해서 고민이 굉장히 많아요 또링ㅠㅠ🥲
> 
> 1. 업데이트 쿼리가 반환하는 affected row count를 체크해서 검증
> 생각하는 문제점 : 다중 트랜잭션 비동기 처리 과정에서 afftected row count가 제대로 전달되지 않을 수 있는 가능성이 존재
> 결국 트랜잭션 격리 수준과 다중 트랜잭션 비동기 처리 여부에 의존하는 검증 방법인 것 같아요
> 2. 업데이트된 상품을 조회하여 요청된 값과 동일한지 검증
> 생각하는 문제점 : 업데이트 쿼리가 하나로 가능했던 기능에 조회쿼리가 추가되면서 1개 -> 2개 의 쿼리로 늘어나면 DB와의 통신이 2배가 되는 것 같다고 생각합니다.
> 우선은 이렇게 2가지의 방법이 생각나는데 혹시 또링은 update의 경우 update 성공 여부를 따로 검증하시는지 궁금합니다😃
> 
> 그리고 하신다면 어떤 방법으로 하고 계신지도 궁금해요😊

저도 현재 스플릿이 구현해주신 것처럼 직접 조회하여 update가 잘 반영되었는지 확인하는 방식을 선호하는 편인데요, 스플릿이 2번으로 선택하신 이유가 또 있는지 궁금하네요! 😉

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/exception/ExceptionAdvice.java
> +
https://github.com/woowacourse/jwp-shopping-cart/pull/240#discussion_r1185828333

> 해당 ExceptionHandler 메서드를 사용하여 예기치 못한 예외의 경우 특정 타입을 예측할 수 없기 Exception 타입을 모두 핸들링 해주었습니다!!😄
> 
> 혹시 해당 메서드가 다른 ExceptionHandler 메서드 보다 먼저 작동하기 않을까 걱정되어 테스트 해보고 검색해보니 구체적인 타입을 핸들링하는 메서드가 우선적으로 작동하게 되어 MethodArgumentNotValidException, IllegalArgumentException의 경우 적절한 메서드가 처리하는 것 또한 확인했습니다!!😊

👍

> 하지만 뭔가 Exception 전체를 모두 같은 방법으로 처리해주는 부분이 조금 맘에 들지 않더라구요 🤨
> 
> 물론 현재 예기치 못한 예외이기 때문에 전체를 핸들링 할 수 있는 타입을 명시하는 것이 맞는 것 같긴하지만 혹시 또링은 예기치 못하게 발생할 수 있는 예외중에도 따로 처리해주는 예외타입이 있는지 궁금해요~😀

예측할 수 있는 validation 오류나 비즈니스 오류 등은 스플릿이 작성해주신 것처럼 별도로 처리하고 있어요. 그 외에 예측할 수 없는 예외에 대해서는 어떤 예외가 발생할지 모르기때문에 상위타입으로 캐치하여 500 error로 내려주고 있구요. 😃
스플릿은 400 에러로 처리해주셨는데, 혹시 400으로 처리해주신 이유가 따로 있는지도 궁금하네요~
또 에러 메세지를 그대로 내려줘도 괜찮을지도 같이 고민해보면 좋을 것 같아요!

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/controller/api/CartApiController.java
> +        final List<ProductEntity> products = cartService.findAllProductsByCustomerId(customerId);
인증 정보를 통해 사용자를 조회하는 로직이 모든 인증이 필요한 API마다 반복되고 있는데요 개선할 수 있는 방법이 없을까요?

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/annotation/BasicAuthorization.java
> +public @interface BasicAuthorization {
어노테이션에 구체적인 인증방식이 표현될 필요가 있을까요? 
인증방식이 변경되면 어노테이션을 사용하는 모든 곳이 변경되지 않을까요?

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/argumentresolver/basicauthorization/BasicAuthInfo.java
> +public final class BasicAuthInfo {
Info라는 명칭은 추상적이에요. 👀

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +    ) throws Exception {
컨벤션이 맞나요 👀? 개인적으로 가독성이 떨어지는 느낌이네요..!

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
interceptor를 사용하여 토큰을 decode 한 후 다시 헤더 정보에 넣어 반환하고 있네요! 스플릿이 생각하는 Interceptor의 역할은 무엇이고, 현재 구조에서는 어떤 목적을 위해 사용하셨는지 궁금해요 :)

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/argumentresolver/basicauthorization/BasicAuthorizationExtractor.java
> +            throw new IllegalArgumentException("잘못된 형식의 인증 정보 입니다.");
`IllegalArgumentException` 적절한 예외가 맞을까요? 
또, IllegalArgumentException이 현재 400 에러코드로 내려가고 있는데 인증과 관련된 적절한 응답코드에 대해 학습해볼까요~?

2023-05-07 09:33 UTC, jnsorn commented on src/main/java/cart/service/CustomerService.java
> +@Transactional(readOnly = true)
@transactional(readOnly = true)의 readOnly 속성은 어떤 역할을 할까요?

2023-05-08 14:35 UTC, splitCoding commented on src/main/java/cart/controller/api/CartApiController.java
> +        final List<ProductEntity> products = cartService.findAllProductsByCustomerId(customerId);
이 부분을 왜 생각을 못했을까요!!ㅜ😅

해당 조회 로직을 Interceptor에게 위임하는 방식으로 바꾸어 보았습니다!!😊

2023-05-08 15:08 UTC, splitCoding commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +    ) throws Exception {
throws 가 추가되다 보니 확실히 가독성이 떨어지는 느낌이 드는 것 같아요 😭

우선 
```java
@Override
    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response,
        final Object handler) throws Exception {
        saveCertifiedCustomerInThreadLocal(request);
        return HandlerInterceptor.super.preHandle(request, response, handler);
    }
```
이렇게 바꿧는데 혹시 더 좋은 방법이 있을까요??😄

2023-05-08 15:15 UTC, splitCoding commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
제가 생각한 Interceptor는 여러 Controller의 메서드에서 중복되는 선처리 과정을 미리 해주는 객체라고 생각합니다!!😄

이 때는 ArgumentResolver또한 학습의 개념으로 사용해보고 싶었고 인증 로직의 중복에 대한 생각은 못했어습니다😭

ArgumentResolver에서는 ':' 를 기준으로 Controller에서 사용할 객체로의 역직렬화의 책임만 부여하고 싶어서 Interceptor에서 decode를 한 Authorization 헤더의 내용을 다시 정보에 넣었었습니다!!😁

2023-05-08 15:17 UTC, splitCoding commented on src/main/java/cart/argumentresolver/basicauthorization/BasicAuthorizationExtractor.java
> +            throw new IllegalArgumentException("잘못된 형식의 인증 정보 입니다.");
전혀 적절한 예외가 아닌것 같습니다!!ㅠ😭

UnsupportedAuthenticationException 라는 커스텀 Exception을 사용하였고 해당 Exception을 처리해주는 ExceptionHandler에서는 401 (UNAUTHORIZED) 응답코드를 전달하도록 변경했습니다!! 😊

2023-05-08 15:17 UTC, splitCoding commented on src/main/java/cart/annotation/BasicAuthorization.java
> +public @interface BasicAuthorization {
인증 부분이 api에서 굉장히 중요한 부분이라고 생각했고 지금의 어플리케이션에서 Basic을 사용한다는 것을 명시적으로 표현하고 싶어서 사용한 네이밍이였습니다😄

하지만 또링의 리뷰를 보니 인증방식이 변경시에 해당 어노테이션을 사용하는 모든 곳에서 변경이 일어나야 하는것 같아요😅

인증관련 로직 또한 좀더 유연하게 바꾸어 보았습니다!!

2023-05-08 15:31 UTC, splitCoding commented on src/main/java/cart/service/CustomerService.java
> +@Transactional(readOnly = true)
해당 속성이 true가 될 경우 해당 트랜잭션을 읽기 전용 모드로 실행하게 됩니다!!

- 일반적으로 트랜잭션 처리가 빠르고, 롤백 시간 또한 감소될 수 있어 성능을 최적화 할 수 있습니다.
- 다른 트랜잭션에서도 사용중인 데이터를 읽고 쓸 수 있게 락을 걸지않기 때문에 읽기 작업에만 사용해야 합니다.
  - 데이터가 변경하려고 할 시 예외가 던져집니다.
  - 락을 걸지 않는다면 동시에 여러 트랜잭션이 동시에 같은 데이터에 접근할 수 있기에 의도치 않은 작업결과를 초래할 수 있습니다

2023-05-08 15:35 UTC, splitCoding commented on src/main/java/cart/exception/ExceptionAdvice.java
> +
상태코드에 대한 공부를 덜하여 생긴 실수입니다ㅠㅠ😅

저도 또링처럼 500 error를 내려주는 것이 맞는 것 같습니다!!👍

또한 서버에서 발생한 의도치 않은 에러메시지를 그대로 클라이언트에 전달한다면 서버의 상태나 정보에 대한 노출이 생길 수도 있고 클라이언트에게 전달해야될 적절한 메시지가 아닌 것 같습니다! 우선 "의도치 않은 서버 오류가 발생했습니다." 라는 메시지를 사용했습니다!😊

2023-05-10 00:53 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthInterceptor.java
> +    private void setCertifiedCustomer(final HttpServletRequest request) {
ㅇ

2023-05-10 00:58 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthInterceptor.java
> +    private void setCertifiedCustomer(final HttpServletRequest request) {
ㅇ

2023-05-10 00:58 UTC, jnsorn commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +    ) throws Exception {
이렇게만 해도 좋은 거 같네요~!

2023-05-11 12:36 UTC, jnsorn approved these changes
안녕하세요 스플릿~! 리뷰가 늦었습니다. 🙏 리뷰 반영해주신부분 확인했어요.
조금 더 같이 얘기해보고 싶은 부분에 코멘트 남겨두었는데, 시간 되실때 고민만 한 번 해보세요. 😃
혹시 리뷰 보다 궁금하거나 질문 생기면 편하게 DM주시구요. 다음 미션도 화이팅입니다. 🚇

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthorizationType.java
> +    );
인증 방식에 따라 decode를 지원하고 있네요. 개인적으로 Function을 필드로 갖게 되면 가독성이 떨어지는 경향이 있는데요, 클래스로 추출해보면 어떨까요? 혹은 BasicAuthorizationExtractor에 해당 역할을 위임해도 괜찮을 것 같은데, 스플릿이 의도한 역할이 따로 있을까요~?

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthorizationType.java
> +    public static AuthorizationType findType(final String authorizationContent) {
NPE 발생 가능성이 있는 코드네요 ⚠️

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthorizationType.java
> +        final String searchingType = authorizationContent.split(" ")[0].toUpperCase();
0은 어떤 의미일까요?

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/service/CustomerService.java
> +    }
interceptor가 아닌 다른 곳에서 해당 메서드를 사용했을때 찾는 고객이 없을 경우 UnAuthorizedCustomerException가 발생할텐데 적절할까요~?

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/auth/interceptor/AuthInterceptor.java
> +        final BasicAuthorizationExtractor extractor = new BasicAuthorizationExtractor(decode(authorizationContent));
Extractor도 같이 추상화 되어야 다양한 인증방식이 있을때 OCP를 지킬 수 있지 않을까요~?

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/controller/api/ProductApiController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
produces를 명시적으로 선언해준 이유가 있을까요?

2023-05-11 12:36 UTC, jnsorn commented on src/test/java/cart/controller/api/CartApiControllerTest.java
> +            .auth().preemptive().basic("split@wooteco.com", "dazzle")
인증 요청 테스트도 깔끔하게 구현해주셨네요

2023-05-11 12:36 UTC, jnsorn commented on src/test/java/cart/controller/api/CartApiControllerTest.java
> +    @DisplayName("요청의 Basic 인증 정보에 해당하는 고객이 존재하지 않을 때 오류 메시지를 담아 400 상태코드를 담아 응답한다.")
인증관련된 예외는 401로 구현해주셨는데, 테스트는 반영이 안된 것 같아요~ 확인해주세요!

2023-05-11 12:36 UTC, jnsorn commented on src/main/java/cart/interceptor/AuthInterceptor.java
> +    ) throws Exception {
이렇게만 해도 좋은 거 같아요~ 다른데도 일관성있게 적용되면 좋겠네요!

2023-05-11 12:36 UTC, merged