[2단계 - 장바구니 기능] 하마드(이건회) 미션 제출합니다
woowacourse/jwp-shopping-cart pull request #345
Opened 2023-05-06 16:35 UTC by rawfishthelgh

안녕하세요 검프! 이제야 2단계 pr을 올리게 되었습니다ㅎㅎ
테스트에서 고민되는 지점이 많아 미션 진행이 너무 어려웠네요...아래 궁금했던 내용을 적어 봤습니다!
이번에도 좋은 리뷰 해주시면 감사하겠습니다 👍 

### 테스트의 격리 수준을 어디까지 이끌어야 하는가...?
***
이번 미션에서 저를 가장 괴롭게 하던 것이었습니다...공유 자원에 여러 스레드가 접근을 수행하고 있어 각 메소드가 끊임없이 다른 테스트에 영향을 주고받고...따라서 어느 지점에서 테스트를 돌리냐에 따라서 성공과 실패 결과가 전부 갈리는 것이 문제였습니다.

이걸 반드시 1. run all Tests를 수행했을 때 성공하도록 해야 하는지, 아니면 2. 개별 클래스 단에서 돌렸을때만 성공시켜도 되는지가 고민이었습니다.

일단 1번을 계속 시도하려니 인수 테스트의 비율을 줄일 수 밖에 없었고, 반환 형식을 mocking해서 쓰는 경우도 많아져 이것이 진짜 테스트가 맞는지조차 의문이 들었습니다.

그런데, 결국 프로덕션 코드에 영향이 가지 않는다면, 꼭 Run All Tests가 성공해야 하는가? 결국 내가 만든 코드가 정상 동작함만 확인할 수 있다면, 클래스 단에서 테스트를 돌렸을 때만 성공하면 되는 것 아닌가? 어차피 다른 시나리오에서의 테스트에 영향을 받는 것이 큰 의미가 있는가? 라는 의문이 계속 들었습니다.

그래서 나름의 타협(?)을 하였고 한 클래스 단에서 Run Test를 수행했을 때 성공하는 정도로 테스트 코드를 구성했습니다.

테스트는 꼭 전체 테스트를 모두 돌렸을 때 성공하도록 구성해야 하는 것일까요? 아니면 다른 클래스의 테스트에 영향을 받는 것은 어느 정도 타협이 가능한 것일까요? 

테스트의 격리 및 성공을 위해서 실제 환경과 점점 동떨어진 환경이 구성되는 느낌을 받아 한번 오기(?)를 부려보고 싶었습니다ㅎㅎ...

2023-05-07 16:12 UTC, Livenow14 requested changes
안녕하세요 하마드 :) 구현 잘해주셨어요.

몇가지 간단한 피드백 남겼으니 확인후 반영 부탁드려요. 

질문에 대한 답변 남겨요.
> 테스트의 격리 수준을 어디까지 이끌어야 하는가...?

테스트의 격리는 최소한 도메인 단위별로는 분리되어야 합니다. 
즉, 하나의 도메인 개념안에서는 격리수준을 조금은 유하게 가져가도 되지만(그럼에도 저는 각 테스트별 격리를 이루려고 노력하는 편입니다), 다른 도메인과의 격리는 필수적으로 이루어져야 합니다. 

그 이유로는 순서 종속성, 결합도 등등과 관련이 있는데요. 
격리가 이루어지지 않으면, 각 도메인의 전체 프로세스를 이해해야만 애플리케이션을 개발할 수 있게되는, 살아있는 레거시 제작을 하게 되는 것과 다르지 않게 되거든요. 

현재 작성해주신 애플리케이션의 도메인은 크게 상품, 장바구니, 유저 등등으로 실제로는 별개의 도메인으로 분리되어야 하는 개념이에요. 
각각의 도메인들은 다른 도메인의 영향없이 요구사항을 만족시킬 수 있어야 하며, 테스트 또한 동일하게 영향을 받지 않아야합니다. 

ex) 상품을 장바구니에 등록하기 위해선 유저가 먼저 생성되어야 한다. 
1. 유저도메인에서
   - 유저 생성/삭제/업데이트 겁증
2. 상품 도메인에서 
   - 상품 생성/삭제/업데이트 검증 
3. 장바구니 도메인에선
   - (유저가 생성되었다 가정) -> (상품이 생성되었다 가정) -> 장바구니 생성 

이렇게 도메인을 분리하여 요구사항을 정리하다보면, 어떤것을 stub으로, 어떤것을 mock으로 사용해야할지 어느정도 감을 잡을 수 있으실거라 생각해요 :) 

이번에 피드백 반영하면서 진행하시다가 어려우신 부분이 있다면 언제든 DM 주세요. 화이팅!

2023-05-07 16:12 UTC, Livenow14 commented on README.md
> +| delete      | /cart/{id} | 장바구니 항목 삭제 | 204         |
http client 기능을 사용했으니, docs에서는 f/o 시켜도 괜찮지 않을까요?

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +    private final AuthorizationExtractor<AuthInfo> authorizationExtractor;
"/cart" prefix를 가지는 Handler에 대하여 인가를 공통적으로 수행할 수 있게 Interceptor를 사용해보는건 어떨까요? Controller 파라미터에서 raw한 HattpServletRequest를 의존하고 있다는게 조금 어색해보여서요.

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +@RequestMapping(value = "/cart")
리소스를 표현할 때는 복수형을 사용해주세요.

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +    public ResponseEntity<List<CartResponse>> showCarts(HttpServletRequest request) {
url에 "all"을 표현하는 것은 좋은 방법은 아니라고 봐요. 
url과 httpMethod를 통해서 유추할 수 있도록 해야합니다. 

view와 동일한 컨트롤러에서 표현하기 위해 분리한 것으로 보이는데, 이경우 view용과 리소스 반환용 컨트롤러를 분리해보는건 어떨까요?

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +    public ResponseEntity<List<CartResponse>> showCarts(HttpServletRequest request) {
서비스로 보내는 중복된 파라미터인 "String email, String password"도 줄일 수 있겠네요 :)

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/dto/CartResponse.java
> +    }
사실상 id라는 식별자를 가진다면, id 비교만 해도 괜찮지 않나요? 
dto에 equals & hash코드가 필요한 이유가 무엇일까요?

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/cart/service/CartService.java
> +@Transactional(readOnly = true)
class level의 트랜잭션을 걸 이유가 있었을까요? 
(메서드가 크게 많아보이지 않아서요. )

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/member/entity/Member.java
> +    }
member는 entity가 아닌가요? 
애플리케이션내에서 특별하고, 유일하게 식별되어야 하는 엔티티의 특성에 따라서는 equals 비교시 식별자로만 진행되어야 합니다.

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/member/entity/Member.java
> +    public int hashCode() {
hashCode도 마찬가지입니다.

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/member/entity/Member.java
> +    }
entity는 애플리케이션내에서 구별가능한 유일한 식별자를 가지며, 변경 가능하다는 특성을 가집니다. 
vo와는 다르개 생각해주셔야 해요.

2023-05-07 16:12 UTC, Livenow14 commented on src/main/java/cart/product/dao/ProductDao.java
> +			ps.setLong(2, product.getPrice());
prepareStatement의 parameter 주입시, 왜 0부터가 아닌 1부터 시작할까요...?!?!

2023-05-08 08:03 UTC, rawfishthelgh commented on README.md
> +| delete      | /cart/{id} | 장바구니 항목 삭제 | 204         |
제거했습니다!

2023-05-08 08:05 UTC, rawfishthelgh commented on src/main/java/cart/cart/controller/CartController.java
> +    private final AuthorizationExtractor<AuthInfo> authorizationExtractor;
처음에는 인터셉터를 활용하는 방식을 시도하다가, AuthInfo 객체에 곧바로 바인딩하고 싶어졌기에 ArgumentResolver를 활용했는데요! 이 방식은 어떻게 생각하시나요??

2023-05-08 08:08 UTC, rawfishthelgh commented on src/main/java/cart/cart/controller/CartController.java
> +@RequestMapping(value = "/cart")
"/carts" 형태로 수정했습니다!

2023-05-08 08:12 UTC, rawfishthelgh commented on src/main/java/cart/cart/service/CartService.java
> +@Transactional(readOnly = true)
기본적으로 서비스 클래스 레벨에 @Transactional(readOnly = true) 옵션을 걸어두고, 데이터 CUD 조작이 필요한 경우 메소드 레벨에 @Transactional을 거는 방식을 사용하기에 기계적으로 해당 방법론을 적용했던 것 같습니다! 다만 검프의 의견처럼 클래스 레벨에서 한꺼번에 적용할 메소드가 많지 않으면 그냥 메소드 레벨에서 걸어도 괜찮을 것 같네요!

2023-05-08 08:23 UTC, rawfishthelgh commented on src/main/java/cart/cart/dto/CartResponse.java
> +    }
id를 만들어놓고, 정작 id를 만들어놓은 이유에 대해서는 생각하지 않았던 것 같네요..! 본래 동등성 비교를 위해 equals & hashcode를 사용했지만 그렇다면 식별자인 id의 의미가 퇴색되는 것 같습니다. 삭제하고 id 비교를 수행할 수 있도록 변경했습니다!

2023-05-08 08:25 UTC, rawfishthelgh commented on src/main/java/cart/member/entity/Member.java
> +    }
이 부분은 제가 엔티티에 대한 이해도 부족으로 일어난 참사(?)였던 것 같습니다ㅎㅎ...
역시 동등성 비교를 수행하기 위해서 본 코드를 추가한 것이었지만, 식별자로서 비교를 수행하는 것이 개념적으로 더 알맞다는 생각이 드네요! 이 역시 변경했습니다!

2023-05-08 08:34 UTC, rawfishthelgh commented on src/main/java/cart/product/dao/ProductDao.java
> +			ps.setLong(2, product.getPrice());
preparedStatement의 인덱스 파라미터가 0부터가 아닌 1부터 시작하더라고요! 
혹시 "0부터 주입하는 방식으로 수정해야 한다" 라는 의도로 코멘트를 주신 건지, "1부터 시작하도록 개발자가 설계한 의도가 무엇인지 질문"하는 의도로 코멘트를 주신 것인지 여쭤봐도 될까요??

2023-05-08 08:51 UTC, rawfishthelgh commented on src/main/java/cart/cart/controller/CartController.java
> +    public ResponseEntity<List<CartResponse>> showCarts(HttpServletRequest request) {
자원에 대한 요청을 수행하는 컨트롤러는 CartController로 분류하고,
단순히 뷰만 렌더링하는 컨트롤러는 CartViewController로 분류했는데요!

문제는 후자의 경우 자원에 대한 요청이 아니므로 여전히 /cart로 표현해도 되는 것인지, 아니면 이도 또다른 복수형으로 표현해야 하는지가 고민입니다...

2023-05-10 07:11 UTC, Livenow14 commented on src/main/java/cart/product/dao/ProductDao.java
> +			ps.setLong(2, product.getPrice());
"1부터 시작하도록 개발자가 설계한 의도가 무엇인지 질문"이 의도였습니다 :) 
한번쯤은 생각해봐도 좋은 주제여서요 ㅎㅎ

2023-05-10 07:14 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +    public ResponseEntity<List<CartResponse>> showCarts(HttpServletRequest request) {
하마드 말씀처럼. 후자는 자원에 대한 요청이 아니므로, 편하게 설정해주셔도 돼요 :)

자원에 대한 RestController에서는(이름에서도 Rest잖아요?!) 스펙을 지켜주도록 하고, 뷰에 대한 부분은 자원을 표현하는게 아닌 다른 방법으로 써도 좋을 것 같네요 

ex) /view/cart

2023-05-10 07:15 UTC, Livenow14 commented on src/main/java/cart/cart/controller/CartController.java
> +    private final AuthorizationExtractor<AuthInfo> authorizationExtractor;
Controller가 AuthorizationExtractor를 직접 의존하고 있는것 보다는, Interceptor가 Cotroller의 파라미터를 의존하게 하는 방법이 조금더 변경가능성이 높아질 것 같아서 드린 피드백이였어요 :)

2023-05-10 12:39 UTC, Livenow14 approved these changes
안녕하세요 하마드 구현잘해주셨어요 :) 

몇가지 질문들은 기존 커맨트에 남겼으니, 다음 미션을 진행하며 고려해봤으면 좋겠어요 :) 

수고많으셨습니다!

2023-05-10 12:39 UTC, merged