[2단계 - 장바구니 기능] 베베(최원용) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #350
Opened 2023-05-07 06:52 UTC by wonyongChoi05

안녕하세요 배럴!
1단계 피드백 주신거 잘 보고 일부분 반영했습니다!

2단계를 구현하면서 1단계보다 고려해야할 부분이 많았다는 걸 느꼈어요! 그리고 브라우저 자체에서 캐싱때문에 몇몇 기능이 동작하지 않았는데, 찾느라 많이 당황스러웠던 것 같네요 ㅎㅎ..

이번 리뷰도 잘 부탁드립니다 배럴!

+ 컨플릭트 드디어 해결했네요 ㅠㅠ 항상 감사합니다!

2023-05-07 13:33 UTC, knae11 requested changes
안녕하세요. 베베, 
몇가지 코멘트 남겨보았습니다!

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/controller/api/CartApiController.java
> +    @PostMapping("/product")
url path를 복수 또는 단수로 통일하는건 어떨까요~? 리소스의 개념으로 본다고 하더라도 혼란의 여지가 있기 때문에 복수와 단수를 혼용하여 사용하지는 않아요.

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/dao/CartDao.java
> +@Component
`@Repository` 어노테이션을 사용하는건 어떨까요?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/error/exception/ErrorCode.java
>      private final int status;
응답으로 statusCode가 나갈텐데 따로 명시한 이유가 있을까요? 아래 code 도 마찬가지로요.

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/error/ApiControllerHandler.java
> +        log.error("MESSAGE : {}", errorCode.getMessage());
로그를 남긴다면 하나의 로그에 남기는게 좋을 것 같아요! 여러번의 에러로그로 나누어 남길 필요가 있나요?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/error/ApiControllerHandler.java
>  public class ApiControllerHandler {
클래스명이 예외를 처리하고 있다고 느껴지지 않는 듯 싶은데요. 어떻게 생각하세요?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/error/ExceptionFilter.java
> +            writerErrorCode(response, new ErrorCode(500, "SERVER-500-1", "Internal Server Error"));
Advice 이외에 filter까지 사용하여 처리하는 이유는 무엇을 위함인가요~? authorization header가 올바르게 들어오지 않을 때, HttpMediaTypeNotAcceptableException 가 발생하여 500이 떨어지고 있습니다ㅠ

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/security/CustomHandlerMethodArgumentResolver.java
> +            throw TokenTypeNotMatchException.EXCEPTION;
Basic 인증도 토큰타입인가요?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/controller/api/CartApiController.java
> +    @DeleteMapping("/product/{id}")
중복으로 설정한 경우, 삭제가 되지 않는 듯 싶은데요. API 요청시에는 204로 응답이 오네요?!

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/dao/MemberDao.java
> +    }
EmptyResultDataAsccessException 이 발생하고 있어요. 예외를 잡아 처리해주는건 어떨까요~?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/security/CustomHandlerMethodArgumentResolver.java
> +
QueryForObject에서 먼저 예외가 발생하여 여기까지 오지 않는 듯 싶네요. 500에러가 나가고 있습니다.

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/exception/NegativeQuantityCantSellException.java
> +public class NegativeQuantityCantSellException extends CartException {
`@ResponseStatus`로 statusCode를 명시해주는건 어떨까요?

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/controller/dto/request/ProductRequest.java
> +import cart.exception.NegativeQuantityCantSellException;
아래 코멘트가 안 남겨져서 여기 남겨요! 메세지로 보여주는 내용중에 empty와 null은 다르지 않나 싶어서요!

2023-05-07 13:33 UTC, knae11 commented on src/main/java/cart/error/ExceptionFilter.java
> +            writerErrorCode(response, new ErrorCode(500, "SERVER-500-1", "Internal Server Error"));
![image](https://user-images.githubusercontent.com/66905013/236680430-8bbff30c-4b57-4b0c-8dd5-87ad1e3be43f.png)

2023-05-08 04:11 UTC, wonyongChoi05 commented on src/main/java/cart/error/exception/ErrorCode.java
>      private final int status;
콘솔에 Error관련 정보들이 상세하게 찍히게함이라는 목표도 있고, 예외가 발생하면 왜 발생했는지 더 구체적으로 설명하기 위해 따로 명시해줬습니다!

2023-05-08 05:57 UTC, wonyongChoi05 commented on src/main/java/cart/security/CustomHandlerMethodArgumentResolver.java
> +            throw TokenTypeNotMatchException.EXCEPTION;
토큰 타입이랑은 전혀 다른 인증 방식이지만 credentials가 일종의 토큰타입처럼 보여서 token으로 명시했는데 오해의 소지가 많을 것 같네요 ㅠㅠ

2023-05-08 07:50 UTC, wonyongChoi05 commented on src/main/java/cart/controller/api/CartApiController.java
> +    @DeleteMapping("/product/{id}")
중복으로 설정했다는게 무슨 의미인지 잘 모르겠습니다 ㅠㅠ

2023-05-08 07:59 UTC, wonyongChoi05 commented
안녕하세요 배럴! 이번 미션 리뷰 맡아주셔서 너무 감사했습니다! 그리고 Optional 관련해서 선예외처리를 안해서 다른 에러가 터지는건 생각해보지 못했던 부분이네요 ㅠㅠ 코멘트 달아주셔서 너무 감사합니다!

그리고 Filter관련 부분과 예외처리를 하는 곳에 있어서 고민을 많이했어서 예기치못하게 너무 산발적으로 퍼져있는 부분도 있었던 것 같습니다.

전체적으로 코멘트 보면서 코드를 다듬으니 왜 이렇게 바꿔야하는지, 바꾸면 무엇이 좋고 무엇이 안좋은지 많이 배워갑니다 감사합니다 배럴!

2023-05-09 13:09 UTC, knae11 approved these changes
장바구니 미션 고생하셨습니다! 다음미션도 화이팅이에요 :)

2023-05-09 13:09 UTC, merged