[Spring 장바구니 - 1단계] 알렉스(이영환) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #39
Opened 2022-06-02 04:20 UTC by yxxnghwan

안녕하세요 제이! 레벨1 마지막 미션에서 만났었는데 레벨2 마지막 미션에 다시 만나게 되었네요! 너무 반갑습니다!🤗
이번 미션도 잘 부탁드려요!

2022-06-03 09:00 UTC, JunHoPark93 requested changes
안녕하세요 알렉스!
미션 잘 구현해주셨네요.
전체적으로 잘해주셔서 큰 수정사항은 없을거같아요.
간단히 확인주시고 다시 요청남겨주시면 머지하도록할게요~

2022-06-04 07:28 UTC, yxxnghwan commented on src/main/java/woowacourse/auth/application/AuthService.java
> +        return jwtTokenProvider.createToken(customer.getEmail());
create로 통일하는 게 자연스러운 것 같네요! 변경했습니다!

2022-06-04 07:30 UTC, yxxnghwan commented on src/main/java/woowacourse/auth/dto/TokenResponseDto.java
> +
로그인 요청에 대한 응답의 dto클래스인데요, 팀 협의 하에 저런 응답 형태로 정해졌어요! 다만 TokenResponse라는 이름이 어색하게 느껴질 수 있다고 생각해서 SignInResponseDto로 클래스 이름을 변경했습니다

2022-06-04 07:35 UTC, yxxnghwan commented on src/main/java/woowacourse/shoppingcart/controller/CustomerController.java
> +        checkAuthorization(id, loginCustomer.getEmail());
해당 코멘트에서 언급하신 방법이 혹시 필터나 인터셉터를 활용하는 방법일까요..? 감이 잘 잡히지 않아서 방법을 제시해주시면 공부해보겠습니다!

2022-06-04 07:36 UTC, yxxnghwan commented on src/main/java/woowacourse/shoppingcart/controller/ControllerAdvice.java
> +        e.printStackTrace();
확인했습니다!

2022-06-04 07:38 UTC, yxxnghwan commented on src/main/java/woowacourse/shoppingcart/domain/vo/Email.java
> +    }
값이 빈 객체를 생성하는 부분에서 필요하다고 생각해서 만들었는데(검증을 거치지 않고 그냥 null을 할당하는 생성자) 생각해보니 value를 파라미터로 받는 생성자를 private으로 닫고 밖에서 사용할 정적 팩토리 메서드(검증을 거치는)를 만드는 게 더 자연스러운 것 같네요. 변경했습니다!

2022-06-04 07:41 UTC, yxxnghwan commented
안녕하세요 제이! 피드백 반영해서 다시 리뷰요청 드립니다!
auth체크하는 방법에 대해서 질문 남겼는데, 어떤 방법이 좋을 지 아직 확신이 안서네요 ㅠㅠ
현재는 인터셉터에서 토큰이 있는 지 유효한 토큰인 지 검사하고, 해당 요청에 대한 자격이 있는 지 검사하는 로직은 컨트롤러의 요청 핸들러 메서드 내부에 checkAuthorization() 메서드를 호출해서 검사하고 있는데요, 다른 방법에 대한 키워드를 주시면 공부해볼게요..😅

2022-06-05 15:02 UTC, JunHoPark93 commented on src/main/java/woowacourse/auth/dto/TokenResponseDto.java
> +
넵 많은 정보가 내려간다면 쓰는입장에서 골라쓰면 되긴하지만 꼭 필요한 응답인지 체크하여 필요한 부분만 내리는것을 권고드려요! 
협의한 부분이라고 하시니 잘 해주셨겠죠~

2022-06-05 15:04 UTC, JunHoPark93 commented on src/main/java/woowacourse/shoppingcart/controller/CustomerController.java
> +        checkAuthorization(id, loginCustomer.getEmail());
넵 리플렉션을 통해서 애노테이션을 만들면되는데 추후 레벨에서 하시게될거에요! 제가 너무 미리 말씀을 드린거같아요. 그래도 지금의 불편함을 알고 공부하면 좋을거같네요!

2022-06-05 15:07 UTC, JunHoPark93 approved these changes
안녕하세요 알렉스!
리뷰 잘 반영해주셨어요.
질문주신 부분은 코멘트 남겨두었는데요, 참고만 부탁드려요!
현재 구조도 충분하여 머지하도록 할게요. 다음 step에서 뵈어요~

2022-06-05 15:13 UTC, merged