[Spring 장바구니 - 1단계] 클레이(양동주) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #51
Opened 2022-06-02 06:58 UTC by yangdongjue5510

안녕하세요 코니! 장바구니 1단계 미션 리뷰 부탁드리게 된 클레이 입니다.

이번 미션에서 API를 같이 협의해서 만들고 JWT 토큰과 Interceptor, ArgumentResolver를 활용해봤어요.

아직 부족한 부분이 많지만 리뷰 잘 부탁드립니다!
궁금한 점은 코멘트로 남기도록 할게요!
감사합니다!

2022-06-02 06:59 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/application/AuthService.java
>  public class AuthService {
토큰 발급, 토큰 페이로드 파싱, 토큰 검증을 하는 AuthService에요.

2022-06-02 07:01 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    public String certify(final LoginServiceRequest loginServiceRequest) {
이번 미션에서 페어들과 서비스에서 어떤 매개변수를 받고 어떤 형태로 반환할 것인지를 논의했어요.
결론부터 말하면 서비스는 서비스레이어의 DTO를 받고 반환하도록 했어요.

2022-06-02 07:03 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/support/JwtTokenProvider.java
> +                            @Value("${security.jwt.token.expire-length}") final long validityInMilliseconds) {
생성자로 필드를 주입받도록 해서 JwtTokenProvider를 테스트하기 쉬운 구조로 변경했어요

2022-06-02 07:11 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +        return HttpMethod.POST.name().equals(method);
인터셉터에 걸리는 `/api/customer` 중 POST 메서드를 통한 요청은 회원가입 요청이라 토큰을 검증해선 안됐어요.
그런데 인터셉터를 등록하는 자바 설정 파일에서는 해결 방법이 없었어요.
그래서 인터셉터에서 post 요청인 경우는 토큰 검증을 통과하도록 했어요.
이 방법은 지금은 잘 되는데 인터셉터만 보면 모든 POST요청을 다 통과시켜주는 꼴이 되어버렸어요.

아마 URI 설계가 잘못된 것 같아요. 협의를 통해 수정해야 할 것 같아요.

2022-06-02 07:19 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
지금 생성자를 보면 `Password`와 `Email`을 VO 객체로 인자를 받아 초기화 해주고 있어요.
사실 원래는 다 `String` 객체를 받았었어요. 추후에 VO를 추가해주면서 수정된 부분이죠.

그런데 `String`을 매개변수로 받는 생성자를 나중에 VO로 바꾸려니 수많은 변경이 필요했어요.

바꾸고 나니 한편으로는 다음과 같이 수정하면 어떨까 싶었어요
```java
public Customer(final Long id, final String name, final String email, final String password) {
        this.id = id;
        this.name = name;
        this.email = new Email(email);
        this.password = new Password(password);
}
```
이렇게 안한 이유는 다른 객체와 강하게 결합되는거 같아서 였어요.
그런데 생각해보니 애초에 인스턴스 필드로 Password, Email을 가지니 이미 결합되어있었다고 볼 수 있어요.
그래서 생성자에서 위 방식처럼 결합되도 추가적인 문제가 없지 않나? 라는 생각이 들었어요.

2022-06-02 07:22 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +        return new Password(PasswordEncryptor.encrypt(rawValue));
`PasswordEncryptor`의 정적 메서드를 통해 암호화 해주도록 했어요.

사실 `PasswordEncryptor`를 Bean 등록해서 서비스에 주입하여 서비스에서 암호화 할까 고민했는데
객체가 암호화 하는 역할을 주는 방식이 더 객체지향적이라고 생각해서 이렇게 했어요.

그런데 이런 방식은 도매인이 Util 클래스인 `PasswordEncryptor`에 의존하게 되더라구요.

2022-06-03 15:54 UTC, choihz requested changes
안녕하세요, 클레이! 장바구니 미션을 함께할 리뷰어 코니입니다 👋

이번 미션의 1단계를 잘 구현해 주셨네요 👍 구현 과정에서의 고민을 남겨 주신 것도 다 잘 보았구요. 몇 가지 피드백을 남겨 두었는데 확인 부탁드리고, 궁금한 점이나 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/auth/application/AuthService.java
> +                .orElseThrow(NoSuchEmailException::new);
존재하지 않는 이메일이 입력됐을 때 그 사실을 그대로 알려주는 것이 적절할지 고민해 볼까요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/auth/application/AuthService.java
> +        }
비밀번호가 틀렸을 때도 마찬가지입니다 😉

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/auth/support/JwtTokenProvider.java
> +    private final long validityInMilliseconds;
상수와 인스턴스 변수는 분리해 주세요~

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +    }
비밀번호가 최소 길이를 넘기만 하면 몇 자여도 상관 없나요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
>      }
기존에 존재하던 코드임은 인지하고 있는데요, 여기서 400 응답이 적절한지 고민해 볼까요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
> +            PasswordNotMatchException.class,
여기도 존재하던 코드의 방식을 그대로 이어받은 점은 알고 있으나, 더 나은 방법은 없을지 고민해 보아요. 커스텀 예외를 만들 때마다 여기에 추가해야 한다면, 실수로 빼먹기 너무 쉽지 않을까요? 그렇게 되면 어떤 일이 발생하나요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +@RequestMapping("/api/customer")
여기서 단수 명사를 사용하신 것은 의도하신 부분일까요? 👀

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        final Customer updatedCustomer = customer.updateName(request.getName());
👍

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/dao/CustomerDao.java
> +    }
메서드 이름이 적절한가요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
`profile`이란 어디서 나온 개념일까요? 실제로는 이름만 수정하고 있는 것으로 보이네요.

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
여기서 PUT 메서드를 선택하신 이유를 여쭤보고 싶어요 👀

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
항상 반대로 사용되고 있다면 메서드 자체를 반대로 제공하는 법도 고려해 볼 수 있겠죠? 또한, `Customer`는 `password`**인** 것이 아니라 `password`**를 가지고** 있는 것 아닐까요?

2022-06-03 15:54 UTC, choihz commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +                .extract();
테스트 코드를 읽는 데 본질적이거나 중요하지 않은 부분이 너무 긴데, 별도로 추출하여 이름을 붙여줌으로써 가독성을 향상하고 중복을 제거할 수 있지 않을까요?

2022-06-03 15:54 UTC, choihz commented on src/main/resources/data.sql
> +FROM customer;
이 파일이 여기 위치해도 괜찮을까요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
`Customer` 클래스를 사용하는 클라이언트 입장에서 지금 구현된 방식과 클레이가 제시하신 방식을 비교해 볼까요? 어떤 장단점이 있을까요?

결합이란 무엇일까요? 결합은 항상 나쁜 걸까요?

2022-06-03 15:54 UTC, choihz commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +        return new Password(PasswordEncryptor.encrypt(rawValue));
의존 관계를 느슨하게 하는 방법은 레벨 1에서부터 지금까지 많이 경험해 보았을 것 같아요 😎

2022-06-05 06:24 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/dao/CustomerDao.java
> +    }
`update`로 수정할게요!

2022-06-05 06:39 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
비밀번호와 이메일을 제외한 사용자 정보를 모두 수정하는 API라서 개념에서 `profile` 을 사용했어요.
현재 비밀번호와 이메일을 제외하면 수정할 수 있는 정보는 이름뿐이라 그렇게 보이는 것 같아요.

2022-06-05 07:00 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
모두 수정하는 PUT과 일부를 수정하는 PATCH 중 어떤 것을 사용하는 것이 좋은가를 팀원과 논읜한 적 있어요.
프론트 쪽에서 정보를 업데이트 하는 경우를 PUT으로 통일하자는 의견을 내줬어요.
편의를 위해 PUT으로 통일했어요.

2022-06-05 07:06 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
password의 메서드를 그대로 customer에 사용해버렸네요 😿
사용하는 곳에 맞도록 메서드 명을 수정하도록 할게요!

2022-06-05 07:19 UTC, yangdongjue5510 commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +                .extract();
테스트 코드를 메서드 분리해보도록 할게요!!!

2022-06-05 07:59 UTC, yangdongjue5510 commented on src/main/resources/data.sql
> +FROM customer;
테스트를 위한 sql 파일은 테스트 패키지 내부 resources 디렉토리에 배치할게요!
그리고 테스트 속도를 높이기 위해 인수테스트에서 dirty context 대신 테이블을 리셋시키는 sql 파일을 실행시키도록 해봤어요!

2022-06-05 08:08 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +        return HttpMethod.POST.name().equals(method);
최근 팀회의를 해보고 나서 생각이 바뀌었어요.
API는 외부와 소통하는 일종의 인터페이스인데 내부 구현 때문에 API를 바꾸는게 맞나? 라는 생각을 했어요.
`인터셉터만 보면 모든 POST요청을 다 통과시켜주는 꼴이 되어버렸어요.` 이 문제를 해결하려면 API를 바꾸는게 아니라 인터셉터를 다르게 구현하는걸 고민하는게 더 낫지 않을까? 라고 생각했어요.

그래서 인터셉터를 고쳐서 회원가입 POST 요청만 통과시키도록 해볼게요

2022-06-05 08:19 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +@RequestMapping("/api/customer")
의도한 부분 맞아요.
path variable을 사용해서 회원조회 하는 경우 `GET api/customers/1` 이런 식으로 복수 명사를 쓰는게 더 자연스러워요.
그런데 토큰을 사용하다보니 URI에 path variable로 식별자를 주지 않고 토큰 내부 페이로드로 주기 시작하니까 URI가 다소 어색했어요.
`GET api/customers` 이런 식이 되는데 이런 경우 프론트  분들이 여러 회원을 다 조회하는 건가? 라는 오해를 하셨다고 했어요.
그래서 단일 회원과 관련된 부분은 `customer`로 통일했어요. 코니 생각도 궁금하네요 😸

2022-06-05 11:40 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
>      }
예상하지 못한 예외는 500이 더 자연스러운 것 같아요. 수정하도록 할게요!

2022-06-05 11:55 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/ControllerAdvice.java
> +            PasswordNotMatchException.class,
실수로 빼먹게 되면 제가 의도한 대로 예외처리가 안되서 500으로 응답될 것 같아요.
예외도 상속 구조로 만들어서 같이 처리되어야 할 예외를 묶도록 할게요!

2022-06-05 11:56 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +                .orElseThrow(NoSuchEmailException::new);
사용자 정보가 일치하지 않는다고 추상적으로 말하는게 더 맞겠네요! 수정하도록 할게요!!

2022-06-05 12:04 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +    }
DB에 저장할 수 있는 글자수는 255자리라서 최대 길이도 제한하도록 추가해봤어요.
제가 제대로 이해한 것인지 잘 모르겠네요 😿

2022-06-05 14:21 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +        return new Password(PasswordEncryptor.encrypt(rawValue));
외부 라이브러리에 의존하는 BcryptEncoder를 구현체로 하고,
이를 추상화한 PasswordEncoder 인터페이스를 추가했어요.

그리고 Password가 인터페이스에 의존해서 사용하도록 했어요.
BcryptEncoder를 빈등록해서 서비스에서 호출해서 사용하도록 해봤어요.
코니 의견이 궁금하네용~~

2022-06-06 01:33 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
클라이언트 입장에서 Email은 굳이 VO로 주입할 필요가 없는 것 같아요.
이메일을 VO로 사용한다는 사실을 클라이언트가 굳이 알 필요 없는 것 같아요.
하지만 비밀번호는 VO로 주입받는게 맞는 것 같아요. 문자열만으로는 이 문자열이 해쉬된 값인지 평문인지 알 수 없으므로 Password 객체를 만들 때 암호화 해줘야 하는지 결정할 수 없기 때문이에요.

결합은 두 클래스의 변화가 서로에게 영향을 많이 끼칠 수 있는 관계라고 생각해요. 일반적으로 결합은 항상 안좋지만 사용을 용이하게 하기 위해서는 어느 정도 양보할 수 있는 부분같아요.

생성자로 주입받으면 결합을 낮출 수 있을 거 같아요. 그런데 이는 인터페이스를 매개변수로 받아 인스턴스 변수의 타입도 인터페이스여야 가능한 이야기 같아요. 제가 원래 했던 방식은 구현체를 주입받고 인스턴스 변수도 구현체이니 주입받아도 강하게 결합되고 있는 것 같아요 😿
그렇다고 인터페이스로 추상화해서 주입하기에는 이메일이나 비밀번호 객체가 변경가능성이 높은 것 같지 않고 불필요하게 복잡해질 것 같아요.

생성자로 원시값을 받아 클래스 내부에서 VO 객체를 만드는 건 강한 결합을 갖게 되요. 그런데 이미 인스턴스 변수의 타입이 VO 객체니까 이미 강하게 결합되고 있다고 볼 수 있어요. 다만 원시타입으로 받다보니 클라이언트가 사용하기는 쉬운 것 같아요.

2022-06-06 01:50 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    private final CustomerService customerService;
CustomerDao 대신 CustomerService를 의존하도록 해서 중복 코드를 줄이려고 했어요!
한편으로는 서비스의 기능을 어떤 기준으로 나눠야 되는건지 어려웠어요.

예를 들면 `아이디와 비밀번호를 확인한다`는 Auth와 관련된 기능인 것 같았어요. 그래서 로직을 AuthService에 있었어요.
그런데 실제 구현하다보니 CustomerDao를 사용하게 되서 이게 AuthService의 기능이 맞나? 라는 고민을 했어요.
그래서 CustomerService로 그 기능을 옮겼어요

코니는 서비스의 기능을 어떤 기준으로 나누시나요?

2022-06-06 01:53 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +    }
내부 구현이 때문에 API를 바꾸는게 맞나? 라는 생각을 하다보니 API 변경보다 내부 구현을 더 좋게 만드는 방법을 고민하는게 맞다고 생각했어요. 그래서 API URI는 수정하지 않고 기존에는 HTTP 메서드만 검사했었는데 이제 URI도 같이 체크해서 통과해주도록 했어요.

2022-06-06 08:04 UTC, choihz approved these changes
안녕하세요, 클레이!

수정해 주신 부분을 확인하고, 추가 피드백도 몇 가지 남겨 두었습니다. 그럼, 다음 단계에서 다시 만나요~ 👋

2022-06-06 08:04 UTC, choihz commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    private final CustomerService customerService;
> CustomerDao 대신 CustomerService를 의존하도록 해서 중복 코드를 줄이려고 했어요!
> 한편으로는 서비스의 기능을 어떤 기준으로 나눠야 되는건지 어려웠어요.
> 
> 예를 들면 `아이디와 비밀번호를 확인한다`는 Auth와 관련된 기능인 것 같았어요. 그래서 로직을 AuthService에 있었어요.
> 그런데 실제 구현하다보니 CustomerDao를 사용하게 되서 이게 AuthService의 기능이 맞나? 라는 고민을 했어요.
> 그래서 CustomerService로 그 기능을 옮겼어요
> 
> 코니는 서비스의 기능을 어떤 기준으로 나누시나요?

서비스는 이러한 기준으로 나눈다! 라고 명확히 말씀드리고 싶지만 당연하게도 현실에는 무수히 많고 또 다양한 상황들이 존재하지요 😌 지겹게 들으셨겠지만 당연히 정답은 없고, 클레이가 앞으로 미션 또는 프로젝트를 통해 다양한 상황과 방식을 직접 경험해 가며 스스로의 기준을 찾아가시게 될 거예요.

2022-06-06 08:05 UTC, merged

2022-06-06 08:12 UTC, yangdongjue5510 commented on src/test/java/woowacourse/shoppingcart/acceptance/AcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
헉 이 부분은 제가 어노테이션을 지운다는게 잘못 했네요!
바로 수정할게요!!!

2022-06-06 08:42 UTC, yangdongjue5510 commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
헉,, 이 부분도 반영하도록 할게요!!

2022-06-06 08:43 UTC, yangdongjue5510 commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +        }
최소한의 영어 문법 🙀을 못지켰네요,,, 수정할게요!!