[Spring 장바구니 - 1단계] 라쿤(이병훈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #57
Opened 2022-06-02 07:30 UTC by nbalance97

안녕하세요 스티치! 이번에 리뷰 요청을 드리는 라쿤이라고 합니다😊
프론트와 처음 협업해보니 신기하기도 하고 어렵기도 하네요😂

질문이 한개 있습니다!!
저희가 이번에 user의 식별자로 username(로그인 시 사용하는 id)을 사용하도록 하였는데,  식별자를 id로 해야 할 지 username으로 해야 할 지 모호하게 느껴져서 스티치의 조언을 구하고자 합니다!
저는 개인적으로는 username 변경을 막아둔다면 충분히 식별자로 사용할 수 있다고 생각하는데, 일반적인 경우에는 식별자를 id로 사용한다고 하여 모호하게 느껴집니다😂

바쁜 시간 내주셔서 코드리뷰 해주셔서 감사합니다!! 🦝

2022-06-03 17:30 UTC, lxxjn0 requested changes
라쿤, 안녕하세요. 이번에 장바구니 리뷰를 맡게 된 스티치입니다 :)

이번 미션을 빠르게 잘 구현해주신 것 같아요!! 간단하게 몇가지 부분에 대해서만 피드백 남겨두었는데 한번 확인하고 피드백 반영 부탁드릴게요 :)

2022-06-03 17:30 UTC, lxxjn0 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private UserName name;
현재 코드에서는 name을 유니크한 값으로 관리하는 것 같아요. 그런데 동일한 이름을 가지는 회원은 충분히 존재할 수 있을 것 같은데 여기서 말하는 username은 우리가 로그인할 때 입력하는 아이디와 같은 개념일까요?

2022-06-04 09:15 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private UserName name;
맞습니다! username이 저희가 로그인에서 입력하는 아이디입니다😊

현재 username은 unique 처리가 되어 있으며, auto increment 설정이 되어있는 id 컬럼이 따로 존재하며 기본키로 설정되어 있습니다!
id라는 컬럼을 제거하고, username 컬럼을 기본키로 사용하는 것은 좋은 방법이 아닐까요?.. 
개인적으로는 크게 차이가 나지 않는 것 같은데, id 컬럼을 많이 사용하는 것 같아 궁금했습니다😅

2022-06-04 09:21 UTC, nbalance97 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    }
JwtTokenProvider의 경우는 따로 라이브러리를 사용하기 때문입니다! Service에서 라이브러리를 사용하는 것 보다는 JwtTokenProvider라는 클래스를 따로 구성하여서 사용하는 것이 추후 변경이 발생하더라도 서비스를 변경하지 않고 JwtTokenProvider를 수정하면 되니 더 좋을 거 같다고 생각하였습니다😀

2022-06-04 10:32 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        customerDao.deleteByName(customerName);
아래에 남겨주신 리뷰와 함께 고민해 보니 존재하지 않는 유저를 삭제하는 경우는 따로 커스텀 예외를 반환하도록 하였으며, 400 예외를 반환하도록 조치하였습니다!
 
이외의 경우(서버 이슈, DB 이슈, 네트워크 이슈)의 경우는 500 응답을 반환하도록 구성하였습니다!

2022-06-04 10:33 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    }
처음엔 dto로 사용하려고 구성하였다가 도메인으로 변경하다 보니 미처 삭제하지 못했던 것 같습니다😂

삭제하였습니다!!

2022-06-04 10:37 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private Long id;
컨벤션에 맞추어서 수정하였습니다!! 😓

defaultId의 경우, controller -> service로 전달된 경우에는 id가 생성되기 이전이라 Customer 객체를 생성하기 위한 Id가 존재하지 않아 id를 전달받을 필요가 없어 defaultid를 따로 설정해 주었습니다!

반대로, dao에서 데이터를 읽어들이는 경우는 id가 포함된 객체를 생성해야 하기 때문에 id도 같이 전달받는 생성자를 두었습니다😀

2022-06-04 14:38 UTC, nbalance97 commented on src/main/resources/schema.sql
>      username varchar(255) not null,
아하.. unique 설정은 존재하지만 index 설정은 존재하지 않았네요! unique 설정은 아래에 alter문으로 기존에 있어서 인덱스 부분만 따로 추가하였습니다!!

2022-06-04 15:13 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/Password.java
> +    private static final String regex = "^[a-z0-9!@#$%^&*-_]{8,16}$";
정규 표현식이 편하고 좋다는 이유로 사용하였는데 저 역시도 복잡한 정규 표현식을 가져다가 쓰면서도 추후에 규칙이 생기면 또 찾아봐야 하는건가? 하고 의구심이 들었었습니다.

스티치의 리뷰를 바탕으로 정규 표현식을 사용하던 코드에서 직접 문자를 비교하는 방식으로 코드를 변경하였습니다! 이전보다 코드가 길어지긴 했지만 마음은 편한거 같아요😃

2022-06-05 10:44 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        customerDao.deleteByName(customerName);
또한 기존 dao에서 try-catch로 묶어주지 않았었네요! DataAccessException을 RuntimeException으로 바꾸어서 예외를 던지도록 변경하였습니다!

2022-06-06 00:48 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        customerDao.deleteByName(customerName);
추가적으로 궁금한 점이 있습니다! 기존 코드에서는 DataAccessException을 직접 사용하는것 보다는 RuntimeException으로 치환하여 throw 해주는게 명확한 거 같다고 생각하였습니다!

하지만 이렇게 작성하면 select, update, insert, delete 구문을 실행하는 모든 메소드에 try-catch를 둘러주어야 하는데, controlleradvice에서 dataaccessexception을 잡아주는것도 괜찮지 않을까라는 생각이 들었습니다! DataAccessException 자체를 ControllerAdvice에서 잡는건 안좋은 방법일까요?

2022-06-06 16:30 UTC, lxxjn0 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private Long id;
만약 id가 존재하지 않는다면 null을 전달해주는 것이 좀 더 명확할 것 같아요! null의 의미가 존재하지 않는 값이라는 의미이니깐요. 물론 그에 따른 npe 문제가 발생하지 않도록 명확하게 nullable하다는 것, 관련 로직에서의 npe 발생 가능성 체크는 필요할 것 같아요!!

2022-06-06 16:33 UTC, lxxjn0 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private UserName name;
실제 비즈니스에서 key와 같이 사용하는 값이 있더라도 id를 따로 두는 것이 통상적인 방식인 것 같아요!! id를 가짐으로서 db 성능적인 부분에서도 장점을 가져올 수 있고 row를 식별하는 식별자의 의미로 두기도 하구요. 그리고 추후 비즈니스 로직이 변경됨에 따라 username이 더 이상 key로 사용되지 못하는 경우에서도 유연한 대처가 가능할 것 같아요 :)

2022-06-06 16:34 UTC, lxxjn0 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        customerDao.deleteByName(customerName);
저는 상관없다고 생각합니다. Exception을 상위 예외로 변경하는 것이 좋은지는 잘 모르겠어요. 만약 DataAccessException이 checked exception이라면 unchecked로 변경하는 것이 유의미할 수 있지만 그렇지 않다면 그대로 사용하는 것이 더 예외 상황을 명확하게 보여줄 수 있을 것 같습니다!! 👍🏼

2022-06-06 16:46 UTC, lxxjn0 requested changes
라쿤, 리뷰 반영해주신 부분 잘 봤습니다!!

전체적으로 대부분 잘 수정해주셔서 1단계는 여기서 마무리해도 될 것 같아요!! 단지 2단계 코드가 너무 많이 포함되어 있어서 해당 부분들만 조치해주시면 머지하도록 하겠습니다!!

2022-06-06 16:46 UTC, lxxjn0 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        throw new NoExistUserException();
```suggestion
        if (!customerDao.existsByName(userName)) {
            throw new NoExistUserException();
        }
        customerDao.deleteByName(userName);
```

이렇게 순서를 바꾸는게 코드가 좀 더 간결하게 보여질 것 같아요!! 한번 참고 부탁드려요 :)

2022-06-06 16:48 UTC, lxxjn0 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    }
아, 제가 드린 의견은 service에서 라이브러리를 사용하는 것이 아니라 service를 사용하는 곳에서 provider를 사용하는게 낫다고 생각이 들어서요. 지금의 service는 단순히 service라는 통일감을 맞추기 위한 목적 그 이상, 이하도 아닌 것으로 보여져요. service 객체는 비즈니스 로직을 관리하기 위한 목적으로 주로 사용됩니다. 하지만 현재 Service 객체는 그러한 목적도, 책임도 가지지 않는 것으로 보여져요. 그렇다면 굳이 Service 객체로 존재해야 할까요? 이에 대한 라쿤의 생각은 어떤가요?

2022-06-06 21:30 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/customer/Validator.java
> +class Validator {
처음에는 로직이 겹칠 줄 알고 Validator를 구성한 것이었는데 지금 보니 로직이 겹치지가 않았네요😅

Validators를 제거하겠습니다!🙂

2022-06-06 21:42 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    public List<CartItem> findCartsByCustomerName(final String customerName) {
넵!! 2단계 미션 관련 코드들을 제거 후 다시 push 하였습니다😅

2022-06-06 21:48 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        throw new NoExistUserException();
제 생각으로는 if문에 !를 쓰는 것이 생각보다 잘 안읽힐 거 같아 throw문을 밖으로 빼는 방식으로 구성하였습니다😅

2022-06-06 21:50 UTC, nbalance97 commented on src/main/java/woowacourse/shoppingcart/domain/Customer.java
> +    private Long id;
`값이 존재하지 않는다`라는 점에서 null이 더 명확할 수도 있겠네요!

이 부분은 null을 사용하도록 변경하였습니다~!

2022-06-06 21:54 UTC, nbalance97 commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    }
스티치의 의견이 맞는것 같아요! 저도 2단계 어느정도 진행하면서 AuthService랑 JwtTokenProvider을 혼용하여 사용하고 있더라구요😅 그 이유는 역시 두 클래스가 설명해주신 대로 완전히 똑같은 역할을 해서 그런 것 같아요!

이 부분은 JwtTokenProvider만 살려 두고, AuthService를 제거하는 방식으로 변경하였습니다🙂

2022-06-07 15:06 UTC, lxxjn0 approved these changes
라쿤, 1단계 진행하느라 수고 많으셨어요!! 👍🏼 

2단계에서 다시 뵐께요 :)

2022-06-07 15:06 UTC, merged