[Spring 장바구니 - 1단계] 오리(최진영) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #6
Opened 2022-05-30 11:53 UTC by jinyoungchoi95

안녕하세요 에단 :)

이번 미션은 처음으로 프론트와 협업하는 미션이었다보니 api 스펙에 대한 이야기가 자주 있었던 것 같아요. 처음 작성하다보니 스펙의 변경이 잦고 처음에 어떻게 설계를 했어야했는지를 반성하게 되는 미션이었던 것 같습니다.
그리고 가면갈수록 여러가지 의견들이 모두 좋아보여서 "정답이 없다"라는 무시무시한 말이 계속 나오게되는게 힘든점인 것 같아요 ㅎㅎ...

현재는 인증 관련된 api만 인터셉터를 통해 관리하고 있는점 참고 부탁드립니다 🙇‍♂️

개발하면서 느꼈던 내용 comment 더해서 풀리퀘 드려요 😄

### 1. Password
- 현재 패스워드는 `PasswordEncoder`에 의해서 인코딩된 패스워드 값이 DB에 저장이돼요. 그러다보니 인코딩된 비밀번호는 길이가 긴데요. 여기서 문제가 발생했어요.
- 저희가 협의한 스펙인 비밀번호는 8자 이상 20자 이하여야한다라는 스펙때문에 인코딩된 비밀번호가 길이가 길어 DB에서 가져올 때 예외가 발생한다라는 문제인데요.
- 이때 제가 생각한 해결할 수 있는 방법은 두가지였어요
```java
1. dao에 convertor를 두어 디코딩된 password를 가져오게 한다.

2. 정적팩토리메소드를 두어 인코딩되지 않은 password와 인코딩된 password의 생성위치를 다르게 둔다.

example
public static Password purePassword(final String password) {
    validateLength(password);
    validatePattern(password);
    return new Password(password);
}

public static Password encodedPassword(final String password) {
    return new Password(password);
}
```
- 현재는 두번째 방법을 사용했는데요. convertor를 두어 dao에서 로직을 타야하는가에 대한 생각이 들었기 때문인데요. (+ convertor가 필요한가)
- 그렇다고 두번째 방법이 좋다라고는 생각못한다는게 문제인데요 ㅎㅎ.... 입구자체가 두개이다보니 객체를 생성하는 입장에서 builder패턴을 쓴다라고 하더라도 잘못 사용할 수 있다보니 어떤 방향이 좋은지 잘 판단이 안되는 것 같아요.
- 그렇다고 도메인에 있던 길이관련 validation을 dto에 두고 도메인에서는 제거를 하자니 패스워드 패턴 자체의 책임은 도메인이 가져야하지 않느냐에 대한 생각도 들구요.
- password의 encoding관련해서 에단은 어떤 생각인지 궁금합니다 :)

### 2. AuthenciationContext
- 현재 인증관련된 로직은 다음의 순서를 두고 있어요.
```
- `LoginInterceptor`에서 Token에 대한 validation을 확인
- validation되지 않으면 exception / validation되면 token을 resolving하여 `AuthenticationContext`에 식별값 저장
- `@AuthenticationPrincipal`는 `AuthenticationPrincipalArgumentResolver`를 통해 `AuthenticationContext`에서 인증값을 가져옴
```

- 처음에는 인터셉터 없이 `AuthenticationPrincipalArgumentResolver`에서 모든 값을 관리하다가 이게 `MethodArgumentResolver` 가져야하는 책임이 너무 많지않은가라는 생각을 하게 되었어요. 그래서 인터셉터를 만들고 나니 굳이 resolver에서 또 `TokenProvider`를 통해서 resolving하지 않아도 되게 보였구요.
- 그래서 인터셉터가 `JwtTokenProvider`를 통해 가져온 토큰에 대한 모든 처리를 하고, `ApplicationContext`가 인증된 정보를 저장, `@AuthenticationPrincipal`는 단순히 인증된 정보를 가져오기만하는 책임을 통해서 분리했어요.
- 과도한 설계는 안하려고하는 편인데 불필요한 객체들을 많이 만든 것은 아닌지 에단은 어떻게 생각하시는지 궁금합니다 😀

감사합니다 🙇‍♂️

2022-05-30 14:38 UTC, Laterality requested changes
안녕하세요 오리.

리뷰어 에단입니다 👋 

잘 구현해주셨네요!

간단한 피드백 먼저 남겨드렸어요. 확인 부탁드려요.

궁금하신 점은 DM 주세요 :)

## Q&A

1. 만약 `Password.password` 필드가 암호화된 문자열만 갖는다는 원칙을 두면 어떨까요?
2. `AuthenticationPrincipalArgumentResolver`의 책임은 무엇인가요, 왜 책임이 많다고 생각하셨나요?

2022-05-30 14:38 UTC, Laterality commented on src/main/java/woowacourse/shoppingcart/domain/customer/Customer.java
> +    public Customer encodePassword(final PasswordEncoder passwordEncoder) {
`Password`가 암호화된 값만 갖는다면 `Customer`에서는 패스워드의 암호화에 대해서는 신경쓰지 않을 수 있을까요?

2022-05-30 14:38 UTC, Laterality commented on src/main/java/woowacourse/shoppingcart/domain/customer/PasswordEncoder.java
> +    boolean isMatchPassword(final String encodedPassword, final String password);
`password`라는 용어가 헷갈릴 소지가 있어보여요.

평문(plaintext, 암호화되지 않은 문자열)과 암호문(ciphertext, 암호화된문자열)로 용어를 구분하면 어떨까요?

2022-05-30 14:38 UTC, Laterality commented on src/main/resources/application-test.yml
> +spring:
테스트와 관련된 프로퍼티로 보이는데, main 소스셋에 둘 필요가 있을까요?

2022-05-30 14:38 UTC, Laterality commented on src/main/resources/schema.sql
> +    password     varchar(255)  not null,
현재 비밀번호의 제약사항으로 미루어봤을 때 이 칼럼에 필요한 최대 길이는 얼마일까요?

2022-06-01 07:04 UTC, jinyoungchoi95 commented on src/main/resources/application-test.yml
> +spring:
기존 스켈레톤 코드에 @Profile("test")가 있었어서 초기에는 거기에 최대한 맞추려다보니 만들었었는데요 😢 
기존코드에 대한 수정을 최소화하고 변경하려다가 누락되었던 부분인 것 같아요...

현재 상황에서 appllication-test같은 경우 굳이 main에서 관리할 필요가 따로 없어보이는 것 같아 test/resources/application.yml로 모든 설정을 이동 시켜두었습니다.

2022-06-01 11:43 UTC, jinyoungchoi95 commented on src/main/java/woowacourse/shoppingcart/domain/customer/Customer.java
> +    public Customer encodePassword(final PasswordEncoder passwordEncoder) {
Customer는 항상 암호화된 Password만 갖게하고 암호화자체를 밖으로 빼주었습니다 :) 
다만 패스워드에 대한 검증(평문패스워드 길이, 패턴)은 결국 암호화되기이전이지만 도메인에 필요한 비즈니스로직이라고 생각하여 `PlainPassword`를 만들어서 해당 객체에서 생성, `PasswordEncoder`가 각 VO들을 받아 인코딩, 검증을 하도록 변경하였습니다

2022-06-01 12:12 UTC, jinyoungchoi95 commented
안녕하세요 에단 :)

주셨던 피드백 반영하면서 느꼈던 내용 comment 더해서 풀리퀘 드려요 😄

### 1. Password
- 처음에는 감이 오지않아서 계속 고민하다가 Password를 분리했어요.
- 결국 Customer 저장될 때, 그이후로도 암호화된 password만을 가지기 때문에 말씀하신대로 평문의 암호를 가지는거 자체를 생각할 필요가 없었던 것 같아요.
- 따라서 평문의 암호에 대한 패턴을 검증할 수 있도록 `PlainPassword`를 두어 encoding시 해당 값을 받도록 하고, Customer에서는 평문에 대한 검증을 전부 지우고 암호화 시 길이인 64자에 대한 검증만 하도록 변경하였습니다 🙌

### 2. AuthenticationPrincipalArgumentResolver
- 이부분은 이전 pr을 날릴 때 이후에도 계속 머릿속으로 정리해보았는데요.
- HandlerMethodArgumentResolver는 원래 컨트롤러 메소드에서 필요한 파라미터가 있을 때 원하는 값을 바인딩해주는 역할을 하는데요.

- 분리했던 이유는 `JwtTokenProvider`가 여러군데서 반복적으로 사용되는 부분이 적절하지 않았다라고 생각해요. (첫 pr에서 생각이 많아져서 말을 잘못한 것 같아요 ㅜㅜ)
- `LoginInterceptor`에서 먼저 `JwtTokenProvider`를 가지고 요청된 access token을 다루는 역할을 하고 있는데 `AuthenticationPrincipalArgumentResolver`에서 또 원하는 파라미터가 access token의 subject이다보니 `JwtTokenProvider`를 써서 값을 꺼내와야했어요. 이미 `LoginInterceptor`에서 `JwtTokenProvider`를 가지고 검증하고 있다면 그냥 interceptor에서 subject까지 resolving하는 것이 맞다라는 생각이었던거죠. (JwtTokenProvider를 다른데서 반복해서 다시 사용하지 않구요.)

- 결론적으로 이러한 생각 끝에 `AuthenticationPrincipalArgumentResolver`의 역할은 `LoginInterceptor`가 인증하고 resolving한 subject를 가져온다라는 책임을 주게되었습니다.

감사합니다 🙇‍♂️

2022-06-02 11:19 UTC, Laterality approved these changes
안녕하세요 오리.

피드백 잘 반영해주셨어요 👍 

이번 단계는 이만 머지하도록 할게요.

남겨드린 코멘트는 다음 단계 진행하시면서 참고해주세요.

고생 많으셨습니다 :)

2022-06-02 11:19 UTC, Laterality commented on src/main/java/woowacourse/shoppingcart/dao/CustomerDao.java
> +            throw new InvalidCustomerException();
예외 메시지도 담아 던지면 어떨까요?

2022-06-02 11:19 UTC, merged