[Spring 장바구니 - 1단계] 호호(유현호) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #76
Opened 2022-06-02 08:38 UTC by yhh1056

안녕하세요 제이!! 호호입니다~😃

이번 미션은 프론트와 협업을 진행했는데요. 프론트 개발자 크루들과 협업하는 과정이 즐거웠어요.

[장바구니 API 문서](https://www.notion.so/0eae365f739f4751803c3e1084ce0a50) 
노션에 관련 API 정보를 정리해두었습니다.

이번 미션에서 비밀번호 암호화에 대한 고민이 많았어요.

처음에 비밀번호 객체가 비밀번호에 대한 규정을 검증하고 인코딩을 진행해요.
디비에서 조회해오는 비밀번호를 가지고 생성을 하려면 8~20자 사이의 비밀번호라는 검증에서 걸리게 되는 문제가 있었는데요.
여러가지 방법을 고민해봤지만 아직 최선의 방법을 찾지 못 했어요.
이 부분은 구조적인 부분을 수정하면서 방법을 찾아보겠습니다😀

리팩토링을 진행하면서 궁금한 점을 계속 물어볼게요!!!

리뷰 잘 부탁드립니다~

2022-06-05 10:08 UTC, jjj0611 requested changes
안녕하세요 호호. 리뷰어 제이입니다!

구현해주신 코드 잘 봤습니다.

간단하게 코멘트 몇 개 남겨드렸으니 확인 부탁드려요!

그리고 현재 테스트가 좀 깨지는 것 같은데, 한 번 확인 부탁드릴게요.

혹시 이해가지 않는 부분이 있다면 코멘트나 DM 부탁드려요 :)

2022-06-05 10:08 UTC, jjj0611 commented on src/main/resources/data.sql
> +insert into customer (account, nickname, password, address, phone_number)
data.sql을 만들어두신 이유가 테스트를 용이하게 하기 위함일 것 같은데,
어떤점이 단점으로 작용할까요??

2022-06-05 10:08 UTC, jjj0611 commented on src/main/resources/schema.sql
> +    phone_number varchar(255) not null,
회원 가입 시에 사용자의 이름은 따로 받지 않는건가요?

2022-06-06 06:15 UTC, yhh1056 commented on src/main/resources/data.sql
> +insert into customer (account, nickname, password, address, phone_number)
고민해보니 데이터를 넣어두면 이름이 중복되는 등 완전한 테스트 격리를 만들지 못 할 것 같아요.

크게 이 부분에 대해서 신경쓰지 않았지만 추후에 여러 데이터를 미리 저장해두는 것에 대해 고민해봐야겠네요!! 😃

2022-06-06 06:15 UTC, yhh1056 commented on src/main/resources/schema.sql
> +    phone_number varchar(255) not null,
네! 팀과 회의를 통해 나온 결론은 로그인id (account)와 닉네임을 사용하는 방향으로 결론이 났습니다!

실제 결제서비스가 되야한다면 실명이 필요할 것 같아요!

2022-06-06 06:15 UTC, yhh1056 commented on src/main/java/woowacourse/shoppingcart/domain/customer/Customer.java
> +        this.phoneNumber = phoneNumber;
null 값이 들어오게 되면 후에 에러가 발생합니다!!

동료가 해당 메서드를 사용할 때 null을 사용하지 않을 것이라는 생각으로 생성자와 메서드에서 null체크는 해주지 않는 방향으로 코드를 작성하는데 이에 대한 체크가 필요할까요?

2022-06-06 06:15 UTC, yhh1056 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        PhoneNumber phoneNumber = customerUpdateRequest.getPhoneNumber().toPhoneNumber();
처음에 DTO에서 도메인 객체를 반환하는 방식을 사용했어요.

그렇게 되면 서비스의 로직은 간단해지는데 아직도 DTO가 도메인까지 알아야 하는 생각이 들고있어서 수정하다가 통일성을 맞추지 못 했습니다.

DTO에서 반환해주는 로직이 있으면 어느 곳에서는 서비스에서 변환하고 어느곳에서는 DTO에서 변환하는 로직들이 혼잡하게 만들어질 것 같아요. 이건 팀원들간에 컨벤션 문제로 바라볼  수 있을까요?

2022-06-06 06:15 UTC, yhh1056 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    public TokenResponse signin(SigninRequest signinRequest) {
signIn으로 수정했습니다~!

2022-06-06 06:16 UTC, yhh1056 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        Customer customer = customerRepository.findById(customerId)
중복을 제거할게요~!!😃

2022-06-06 06:18 UTC, yhh1056 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    }
유니크 조건을  걸어야됩니다!
생성시 해당 메서드를 사용하지 않고 생성하게 된다면 여러 계정이 존재할 수 있어요.

체크해주는 이유는 디비에서 반환하는 에러를 받기보다 제가 작성한 커스텀 예외로 에러를 처리하여 클라이언트에게 전달하기 위해 체크를 진행합니다!!

2022-06-09 06:32 UTC, woowabrie approved these changes
호호~ 피드백 반영 잘 해주셔서 2단계 진행을 위해 이번 PR은 바로 merge 할게요.

2022-06-09 06:32 UTC, merged