[Spring 장바구니 - 1단계] 유콩(김유빈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #80
Opened 2022-06-02 08:53 UTC by kyukong

안녕하세요 제이
장바구니 미션 리뷰를 받게된 유콩입니다.
처음으로 프론트분들과 협업을 해봤는데 좀 어려웠어요.
어느정도까지 준비하고 회의를 해야하는지 가늠하기 어렵더라구요.
그래도 실제 웹 사이트에 제가 구현한 API 가 동작할거라 생각하니 뿌듯하기도 했습니다.ㅎㅎ

이번 미션 리뷰 잘 부탁드립니다. 🙇‍♀️

[API 명세](https://cactus-treatment-26e.notion.site/API-33d13631d6bf408b8f274c7e9ce85bb0)

2022-06-05 10:47 UTC, jjj0611 requested changes
안녕하세요 유콩! 리뷰어 제이입니다.

구현해주신 부분 잘 봤습니다.

간단하게 고민해볼만한 부분 코멘트 남겨드렸어요!

코멘트 확인해보시고 이해가지 않는 부분이나 어려운 점 있으면
코멘트나 DM 부탁드려요 :)

2022-06-05 10:47 UTC, jjj0611 commented on README.md
> +  - [ ] 토큰에 담긴 정보가 외부에서 수정되었는지 판단한다.
아직 완료되지 않은 기능일까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/auth/ui/AuthenticationPrincipalArgumentResolver.java
>      private AuthService authService;
final 이 걸려도 괜찮지 않을까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +public class LoginInterceptor extends HandlerInterceptorAdapter {
HandlerIntercepterAdapter를 사용하신 이유가 있을까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
로그인은 회원 컨트롤러의 역할일까요? 인증 컨트롤러의 역할일까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +    }
AuthController와 CustomerController의 역할이
인증과 회원일 것 같은데,

회원 정보 조회,
회원 정보 수정
비밀번호 변경
회원 탈퇴

라고 할 때 해당 역할을 인증의 역할일까요?
회원의 역할일까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        validateDuplicateNickname(customerUpdateRequest.getNickname());
여기서 이렇게 중복체크를 하면, db에 unique 조건이 안 걸려도 되지 않을까요?
만약 db에도 있어야 한다면, 여기서 체크할 때의 효용은 뭘까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/dto/TokenRequest.java
> +public class TokenRequest {
token request라는 이름이 모호한 것 같아요.
토큰 요청이 내부에 id만 갖고 있는데,
해당 id는 회원 id인지, product id인지, item id인지, cart id인지 order id인지 알 방법이 전혀 없어요!

더불어 customerRequest라고 했을 때,
customer를 생성하는 요청처럼 보여지지 않을까요?
TokenRequest가 적절한 이름인지 고민해봐주세요 :)

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    }
위에도 남겼지만, 이렇게 체크할 경우 db의 제약 조건은 없어도 될까요?
만약 여전히 존재해야한다면, 위와 같이 체크하는 이유는 뭘까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    }
다시 한 번, 로그인은 회원의 역할일까요? 인증의 역할일까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        customerDao.update(customerForUpdate.getId(), customerForUpdate.getNickname());
이름은 customer 자체를 update할 것처럼 보이는데,
실제로는 nickname만 update하네요.
옳바른 메서드명일까요??

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/domain/customer/Password.java
> +    private final String value;
이렇게 저장되면, DB에 read 권한을 가지고 있는 사람은 모든 사람들의 password를 날 것 그대로 볼 수가 있겠네요!

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/dto/CustomerResponse.java
> +    }
이 친구는 왜 존재하는걸까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/dto/LoginResponse.java
> +    }
이 친구도 사용하고 있을까요?

2022-06-05 10:47 UTC, jjj0611 commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +        Customer customer = findCustomerByUserId(loginRequest.getUserId());
id와 password 로 dao에서 확인하는 것이 아니라,
id로 찾아와서 password와 일치하는지를 보고, 토큰을 발급하는 것이 더 자연스럽지 않을까요?

2022-06-06 08:06 UTC, kyukong commented on src/main/java/woowacourse/shoppingcart/dto/TokenRequest.java
> +public class TokenRequest {
토큰의 정보를 활용하여 생성한 객체다보니 `TokenRequest` 로 지었습니다. 그러다보니 Service 에서 Token 의 정보를 알게 되는 점이 있었습니다..😂 사용자를 식별하는 정보이므로 `CustomerIdentificationRequest` 로 수정하였고 객체 이름에 Customer 이 포함되기 때문에 `id` 필드는 이름을 변경하지 않았습니다!

2022-06-06 08:38 UTC, kyukong commented on src/main/java/woowacourse/shoppingcart/ui/CustomerController.java
> +    }
토큰을 생성하는 로직이 있어 `AuthController` 로 옮겼습니다!

2022-06-06 08:39 UTC, kyukong commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +    }
처음 구현할 때는 단순하게 API URL 만 보고 구분지었던 것 같네요ㅠㅠ 토큰 관련 로직이 있을 경우에만 `AuthController` 에 두고 다른 사용자 기능은 모두 `CustomerController` 에 두었습니다!

2022-06-06 08:42 UTC, kyukong commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    }
디비에 저장된 사용자 정보 자체를 가져오는 것은 사용자의 기능이므로 그대로 `CustomerService` 에 두었습니다. 반환값을 CustomerResponse 로 바꾸고 토큰을 추가하는 과정은 인증의 역할이므로 `AuthController` 에 두어 `LoginResponse` 객체를 생성하였습니다.

2022-06-06 08:49 UTC, kyukong commented
안녕하세요 제이!
주신 피드백 열심히 반영해보았습니다.ㅎㅎ
이번 장바구니 미션은 구현해야할 기능에 비해 시간이 짧아 고민하는 지점이 적었는데 피드백을 보고 고민할 거리가 많이 생겨서 좋았어요.
주신 피드백 중에서 정리가 필요한 것들을 정리해보았습니다!

## 사용자 vs 인증
사용자와 인증의 기능이 밀접한 관련이 있다보니 둘을 혼동하여 쓰고 있더라구요.
특히나 API URL 에서 API 를 호출할 때 토큰을 받아오는 경우 앞에 `/auth` 를 붙이기로 하다보니 더 헷갈렸던 것 같습니다.
피드백을 보고 Controller 를 구분한 기준을 정리해보았습니다.

### AuthController
- 인증 관련 로직이 있을 경우에 해당 컨트롤러에 위치
- 예) 로그인 -> 토큰 발급 기능
- 로그인은 `사용자` 테이블에서 정보를 확인한 후, `토큰` 을 발급받으므로 `CustomerService` 와 `AuthService` 에서 각각 수행 후 반환 객체를 생성하였음

### CustomerController
- 인증 관련 로직이 없을 경우에 해당 컨트롤러에 위치
- 예) 회원가입, 사용자 정보 조회, 사용자 정보 수정, 회원 탈퇴 등
- 회원가입을 제외한 나머지 기능은 토큰을 받으나 해당 토큰을 처리하는 로직이 따로 없어 CustomerController 에 두었음

2022-06-06 09:34 UTC, kyukong commented on src/main/java/woowacourse/shoppingcart/application/CustomerService.java
> +    }
하단에 관련 내용 정리해두었습니다!

2022-06-06 10:21 UTC, kyukong commented on src/main/java/woowacourse/auth/ui/LoginInterceptor.java
> +public class LoginInterceptor extends HandlerInterceptorAdapter {
특정 사용자가 API 를 호출할 때 토큰을 받습니다. 토큰을 처리하는 과정에서 중복을 제거하고 Controller 로 넘기기 전에 올바른 토큰인지(로그인한 사용자인지) 검증하기 위해 사용하였습니다.

2022-06-09 06:30 UTC, woowabrie approved these changes
유콩~ 2단계 진행을 위해 이 PR은 merge 할게요.
피드백 반영한 사항은 제가 살펴보고 코멘트 드리겠습니다. ☺️

2022-06-09 06:30 UTC, merged