[Spring 장바구니 - 2단계] 헌치(박지우) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #87
Opened 2022-06-07 17:29 UTC by BETTERFUTURE4

안녕하세요 던!
DB 연결을 내일 적용해보고 싶어서 
오늘 우선적으로 2단계 기능 구현 후 pr 날리게 되었습니다!

기존 레거시 코드들을 테스트 코드부터 도메인까지 전부 리팩토링하고, 
새로운 테스트 코드를 추가하려니 정말 쉽지 않네요😂

부족한 코드이지만 잘 부탁드립니다!
[api 명세](https://www.notion.so/mima-o/API-SPEC-d1233b9e6e90489ab19c3dd94c9eb646)

## 2단계 기능 구현 목록

**상품 조회 기능**

- [x] 상품 조회 API
- [x] 해당 아이디의 상품을 반환하는 기능
    - [x] product table
    - [x] id, 상품명(name), 상품 가격(price), 상품 이미지(image)

**상품 목록 조회 기능**

- [x] 상품 목록 조회 API
- [x] 해당 페이지, 불러올 상품 갯수 만큼 목록을 반환하는 기능
    - [x] product table
    - [x] id, 상품명(name), 상품 이미지(image), 상품 가격(price)
- [x] JSON 배열 형식으로 아이템을 응답한다

**장바구니 목록 요청 기능**

- [x] 장바구니 목록 요청 API 기능
- [x] 로그인한 회원의 서버에 저장된 장바구니 목록을 반환하는 기능
    - [x] cart_item table
    - [x] id, 상품 아이디(productId), 상품명(name), 상품 이미지(image), 상품 가격(price), 장바구니에 담긴 갯수(quantity)
- [x] JSON 배열 형식으로 아이템을 응답한다
- [x] 액세스 토큰을 통한 유저 정보 확인 필요

**장바구니 추가 요청 기능**

- [x] 장바구니 추가 요청 API 기능
- [x] 상품 목록의 상품을 장바구니에 추가하는 기능
    - [x] cart_item table
    - [x] 상품 아이디(productId), 추가할 수량(quantity)
- [x] 장바구니에 이미 존재하는 물품이라면 개수를 1 증가시킨다.

**장바구니 정보 수정 기능**

- [x] 장바구니 정보 수정 API 기능
- [x] 장바구니에 담긴 아이템의 정보(갯수)를 수정하는 기능
    - [x] 상품 아이디(productId), 변경할 정보...

**장바구니 아이템 제거 기능**

- [x] 장바구니 아이템 제거 API 기능
- [x] 장바구니에 담긴 아이템들을 제거하는 기능
    - [x] 삭제할 장바구니 아이디 리스트
- [x] 제거에 성공한 아이디 목록을 응답하는 기능
- [x] 삭제 시 유저 자신의 장바구니 상품만 제거할 수 있어야 함

**상품 주문하기 기능**

- [x] 상품 주문하기 API 기능
- [x] 주문할 상품들을 주문하는 기능
    - [x] 상품 아이디(productId), 주문 수량(quantity)
- [x] 생성된 주문(Order)의 아이디를 반환

### 1단계 피드백 반영

- [x] JwtTokenProvider -> 공통 로직은 메서드로 분리할 수 있겠네요!
- [x] dao와 repository에서의 메서드명이 login일 필요가 있을까요?
    - -> 각각 역할에 맞게 메소드명 고민
- [x] 토큰을 생성하는것까지 Service에서 하는것이 맞지 않을까요~??
    - -> 서비스로 옮기자
- [x] TokenRequest -> 어떤 id를 의미하는지 명확하게 나타내면 좋을 것 같아요~
- [x] checkDuplicateUsername -> 파라미터 설정 값이 중복된게 아닌가 해요!
- [x] CustomerRepository -> 예외 메시지를 넣지 않고 비워둔 이유가 있을까요? :
    - controllerAdvice에서 해당 예외를 처리.
    - 하지만 예외 메세지를 throw 시점에서 명시적으로 적어주는 편이 좋을 것 같아 수정함.

### TODO

- [ ] Dao Optional 처리
- [x] repository 테스트 추가
- [x] 인수테스트 추가
- [x] 에러메세지 형식 변경
- [x] cart_item 안에 개수 요소 추가 -> quantity 추가

---

추가로 궁금한 사항들은 코멘트로 남기겠습니다. 
이번에도 잘 부탁드려요! 감사합니다🥺

2022-06-07 17:31 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/ui/OrdersController.java
> +}
이번에 프론트와 협의 하에 추가한 api에서 
주문하기 기능이 사실상 없기 때문에

관련된 테이블(orders, ordersDetail)을 삭제하고, 
기존 관련 코드들도(Service, Dao, 테스트코드) 삭제했습니다.
해당 방향에 대해 던은 어떻게 생각하시나요?

1. 필요없는 코드이니 지워도 된다
2. 현업에서도 레거시 코드라고 다 지울거냐. 쓸곳이 있을 수 었는데 DB는 냅둬라

2022-06-08 16:02 UTC, gch01410 requested changes
안녕하세요 헌치!
잘 구현해주셨네요!! 👍 
코멘트 남겼으니 확인부탁드릴게요~

2022-06-08 16:02 UTC, gch01410 commented on src/main/java/woowacourse/shoppingcart/ui/OrdersController.java
> +}
정말 정답이 없는 내용이네요!
현업이라고 생각하면 우선은 코드를 지우지않고 둘 것 같아요.
그리고 테이블을 삭제하는건 정말 신중해야해요. 테이블은 무조건 삭제하지않을 것 같아요

미션이긴하지만 굳이 삭제는 안할 것 같아요

2022-06-11 09:44 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/ProductService.java
>      }
Dao단에서 끊어 조회하도록 쿼리문을 수정했습니다!

2022-06-11 09:49 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/repository/CartItemRepository.java
> +        productDao.findById(productId);
레포지토리를 한 서비스에서 여러 Dao를 참조하는 상황을 줄이기 위해 사용하고 있었어서
레포지토리 이름을 CartTotalRepository로 바꾸고 여러 Dao 속 검증로직을 레포지토리에 추가해서 서비스 단에서 처리해줬습니다.
이런 방향도 괜찮을까요?

2022-06-11 09:50 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/repository/CartItemRepository.java
> +        }
그렇네요^^;;
수정했습니다!

2022-06-11 09:52 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    }
처음엔 in쿼리를 사용하려고 했는데 어떻게 활용할 수 있을지 방법이 잘 떠오르지 않고
기존의 batchUpdate 사용방식을 활용한 새로운 로직이 떠올라 해당 방식으로 적용했습니다...
혹시 현재 코드를 In 쿼리로 사용할 수 있는 방법이 있을까요?

2022-06-11 09:53 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/dto/CartProductInfoRequest.java
> +    private Long id;
이미 api 스펙 내에서 id라고 네이밍 되어있어 부득이하게 해당 네이밍을 따라가게 되었습니다ㅠㅠ
앞으로 api 스펙에서 들어오는 요청 이름들을 분명하게 짓도록 하겠습니다!

2022-06-11 09:53 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
>      }
고민 끝에 유효성 체크를 각 api에 추가하는 식으로 진행했습니다!

2022-06-11 09:54 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +                .contains(cartId)
로컬변수로 따로 빼 적용했습니다!

2022-06-11 09:57 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/repository/CartItemRepository.java
> +        System.err.println("cartEntity.getQuantity() = " + cartEntity.getQuantity());
실수로 잠시 사용한 print문을 삭제하지 않았습니다!
삭제했습니다ㅠㅠ 앞으로 잘 확인할게요!
추가적으로 controller advice 부분에서 에러메세지 관련해 로그로 출력하도록 코드수정을 했습니다!

2022-06-11 09:58 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/ui/OrdersController.java
> +}
역시 그렇군요ㅠㅠ 
지금 상황에서 sql문에서 테이블을 다시 추가하는 것은 의미가 없을 것 같아 그대로 뒀습니다.
앞으로는 레거시 코드들과 테이블을 함부로 지우지 않겠습니다...!!!

2022-06-11 10:00 UTC, BETTERFUTURE4 commented
안녕하세요 던!! 헌치입니다.
이번에 방학을 지나서까지 피드백을 반영 못해 시간을 끌었네요...
다시 한번 죄송합니다ㅠㅠ

## 2단계 피드백 반영 사항

- [x] 상품을 전부 조회한 뒤에 끊지않고,
    - 조회할때부터 끊어서 조회하도록 해볼 수 있을까요?
- [x] 장바구니 레포지토리에서는 Cart와 관련된 처리만하고
    - 나머지는 서비스 레이어에서 하는건 어떨까요?
- [x] 지금 로직에서는 모든 회원의 장바구니 수량이 변경되지않을까요~?
- [x] 요청 온 상품id 개수만큼 쿼리가 여러번 실행되겠네요!
    - in 쿼리를 사용해서 쿼리 수행 횟수를 줄여볼 수 있을까요?
    - -> for문을 batchUpdate를 사용해 쿼리 수행 횟수를 줄여봤습니다! 
    - -> 그 과정에서 카트에 해당 물품이 없는 경우와 있는 경우를 나눠 서비스로 비즈니스 로직을 추출했습니다!
- [x] 이 메서드는 readOnly=true 옵션을 설정하는게 좋을 것 같아요!
  - -> 조회 관련 서비스단 메서드에서, 데이터 변경을 막기 위해 붙이는 어노테이션
  - https://junhyunny.github.io/spring-boot/jpa/junit/transactional-readonly/
- [x] 어떤 id를 의미하는지 더 구체적으로 네이밍하면 좋을 것 같습니다
  - -> api 매핑 과정에서 같은 이름을 쓰기 위해 부득이하게 id라고 이름을 짓게됨
  - -> 앞으로는 초기 api 설계에서 이름 정하는 방법을 고민해볼 생각이다.
- [x] 회원 id가 유효한지를 확인해봐야하지 않을까요~?
    - 존재하지 않는 회원의 id가 요청올 수도 있을 것 같아요.
    - API마다 매번 회원id의 유효성 체크하는 로직이 있어야할텐데, 아규먼트 리졸버에서 처리해서 중복을 제거하는것도 하나의 방법이겠네요!
    - 이건 헌치가 고민해봐주세요!
- [x] 혹시 우테코에서 로그에 대해 아직 학습하지않았을까요??
  - -> print문을 실수로 지우지 않음
  - -> 공부내용 정리하기
- [x] 현업이라고 생각하면 우선은 코드를 지우지않고 둘 것 같아요.
    - 그리고 테이블을 삭제하는건 정말 신중해야해요. 테이블은 무조건 삭제하지않을 것 같아요
    - 미션이긴하지만 굳이 삭제는 안할 것 같아요
    - -> 이전 테이블들 다시 롤백

혹시 수정한 부분들에 대해 추가적인 피드백이 있으시다면 얼마든지 달아주세요!
항상 감사합니다!🥺

2022-06-11 13:14 UTC, gch01410 requested changes
안녕하세요 헌치!
피드백 잘 반영해주셨어요! 👍 
코멘트 남겼으니 확인 부탁드릴게요~

2022-06-11 13:14 UTC, gch01410 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    }
반복문 안에서 쿼리를 실행하는 로직은 지양해야합니다! 지금은 프론트에서 넘어온 상품ID 개수만큼 쿼리가 수행되고 있어서 서버에서 제어할 수 없는 외부요건에 의해서 서버,db에 무리가 갈 수 있어요. 잠재적으로 서버나 db가 죽을 가능성이 큽니다.
plusQuantityCarts 메서드를 이렇게 수정하면 프론트에서 상품ID가 몇개가 넘어오든지 서버에서는 일관되게 쿼리가 수행될 수 있어요.
```java
private void plusQuantityCarts(List<ProductIdRequest> productIdRequests, Long customerId) {
        List<Long> productIds = productIdRequests.stream()
                .map(ProductIdRequest::getId)
                .collect(Collectors.toList());
        List<Cart> carts = cartItemRepository.findIdByCustomerIdAndProductIds(customerId, productIds);
        ...
}
```

createCarts나 cartItemRepository.plusQuantityByIds 메서드도 반복문안에서 쿼리를 수행하지않고 in쿼리로 데이터를 전부 가져온 뒤에 처리하는게 좋아보여요!

2022-06-13 09:22 UTC, BETTERFUTURE4 commented on src/test/java/woowacourse/shoppingcart/acceptance/CartAcceptanceTest.java
> +    void updateCartItems_cartIdError() {
기존 에러메세지 출력 문구가 바뀐걸 처리를 안해준 것 같아요!
수정했습니다!

2022-06-13 09:23 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +        cartItemRepository.validateProductId(productId);
죄송합니다!ㅠㅠ
급히 pr 날리다가 마지막 커밋을 반영을 못한 채 push 했었네요...
다시 push 했습니다!

2022-06-13 09:26 UTC, BETTERFUTURE4 commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    }
앗... 저번 피드백에 대해 제가 잘못 이해한 부분이 있었던 것 같네요ㅠㅠ
말씀주신대로
for문이나 stream의 map, filter 등에서 
Dao에 반복적으로 접근하는 로직마다 계속 DB에 접근하는 것은 비효율적일 것 같아요!
Dao 단에서 ~all로 처리하도록 변경했습니다!
(where in 문 사용)

2022-06-13 09:29 UTC, BETTERFUTURE4 commented
안녕하세요, 던!

늦은 시간까지 친절하게 피드백 남겨주셔서 정말 감사합니다😭
덕분에 DB 접근 방향등에 대해 더 공부하고 고민해볼 수 있었어요!

다음은 2단계 피드백 2 반영사항 입니다!

### 2단계 피드백-2

- [x] 테스트 코드가 실패하네요!->레거시 테스트코드 수정
- [x] CartTotalRepository 안보이는데 다른 방법으로 처리한걸까요? -> 기존 커밋 일부가 안날라감... 다시 푸시
- [x] 하나의 트랜젝션으로 묶어줘야할 것 같아요! -> 모든 변경 지점들을 transaction 메소드로 묶어 처리
- [x] createCarts나 cartItemRepository.plusQuantityByIds 메서드도
    - 반복문안에서 쿼리를 수행하지않고
    - in쿼리로 데이터를 전부 가져온 뒤에 처리하는게 좋아보여요!
    - -> stream의 map, filter 등에서 Dao에 반복적으로 접근하는 로직들을 Dao 단에서 ~all로 처리(where in 문 사용)

### 추가 구현사항
- plusQuantity(이미 등록된 상품의 개수를 1 늘리는 로직) 을 서비스 단 안쪽으로 이동했습니다!
- Carts 도메인을 만들어 비즈니스 로직을 이동했습니다!

이번에도 잘 부탁드립니다! 항상 감사드려요🥺🔥

2022-06-13 13:37 UTC, gch01410 approved these changes
안녕하세요 헌치!
피드백 잘 반영해주셨네요! 👍 
질문에 대한 답변과 간단한 코멘트 남겼으니 확인부탁드릴게요!
궁금한 점 있으시면 DM주세요~
레벨2 미션 구현하시느라 정말 수고 많으셨습니다!!

2022-06-13 13:37 UTC, gch01410 commented on src/main/java/woowacourse/shoppingcart/repository/CartTotalRepository.java
> +
customer, product에 대한 검증은 각 도메인의 레포지토리에서 하는게 맞지않을까해요!
그리고 CartService에서 여러 도메인의 레포지토리를 이용하는 방향이 맞아보여요!

2022-06-13 13:37 UTC, gch01410 commented on src/main/java/woowacourse/shoppingcart/domain/Carts.java
> +    private final List<Cart> carts;
일급컬렉션 👍 
Cart리스트와 관련된 로직을 한곳에 모으니 코드가 훨씬 읽기 편해졌네요

2022-06-13 13:37 UTC, merged