[Spring 장바구니 - 1단계] 크리스(공병주) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #9
Opened 2022-05-31 15:51 UTC by Byeongju-Kong

미르! 레벨 1 로또 미션에서 만났었는데, 다시 만나뵙게 되어서 반갑습니다!
미션 진행하면서 궁금했던 부분 아래에 코멘트 남겨두겠습니다!!
이번 미션도 잘 부탁드립니다~!

### Service에서의 dto 사용
 저는 기본적으로, service에서 controller로 도메인을 반환하는 것을 선호하지 않습니다. domain을 사용하는 layer를 service까지로 제한해서, service 레이어의 범주에서 도메인의 응집도를 높일 수 있다고 생각해요. 따라서, service가 request를 받고 response를 반환하도록 했습니다.
 그런데, 여기서 고민이 생겼습니다. 지금 view-controller와 controller-service 사이의 dto가 동일합니다.
하지만 같은 dto를 사용할 경우, controller가 변경되었을시에 해당 service는 사용하지 못할거라고 생각했습니다.
controller가 하나만 사용된다고 하더라고, service 입장에서 자신의 상위레이어에 대해서 알아야할까? 라는 생각도 들었습니다.
따라서, view-controller와 controller-service의 dto를 분리했습니다.
이 부분에 대한 미르의 의견이 궁금합니다! 같은 dto를 사용해도 될까요? 아니면, 다른 dto를 사용해야할까요?
둘다 아니라면, service에서 controller로 도메인을 반환해도 될까요?

### dto에서의 검증
 현재, controller와 dto에서 값에 대한 검증을 하고, 도메인에서도 값에 대한 검증을 하는 로직입니다. 중복으로 검증이 들어갑니다.
중복 검증을 하게 한 이유는, Service가 모듈로 떨어졌을 때(controller가 변경이 되었을 시에) service와 domail은 도메인 로직을 수행할 수 있어야 하기 때문입니다. 검증을 하지 않는 controller가 연결되어도 도메인 로직을 수행할 수 있어야한다는 뜻입니다!
 하지만, 할 수 있다면 잘못된 값들에 대해서는 도메인 까지 들어오지 않고 controller와 dto에서 처리를 할 수 있다면 처리를 하는 것이 좋다고 생각이 들었습니다.
따라서, controller-dto 그리고 도메인에서 중복 검증을 하게 하였는데,
중복 검증이 과할까요? 저는 controller-dto에서 @NotBlank 혹은 @NotNull 체크 정도만 해주고 값의 구체적인 검증은 domail에서 처리해도 괜찮을 것 같다는 생각인데, 미르는 어떻게 생각하시나요?

### 인수테스트
 현재는 인수테스트에 공통되는 픽스쳐를 꼼꼼히 분리시키지 않은 상태입니다. 픽스쳐를 분리하는 과정에서, 오히려 픽스쳐로 분리하니까
테스트를 하는 구체적인 값들이 한눈에 들어오지 않더라고요! 픽스쳐를 어떤 식으로, 어느 정도로 분리하면 좋을까요?
인수테스트에서 미르는 픽스쳐를 어느정도로 분리하시나요?

2022-06-01 15:56 UTC, ddu0422 requested changes
안녕하세요 크리스 ! 잘 지내셨나요 ㅎ_ㅎ 다시 만나서 반가워요 😎 

1단계 미션 빠르게 구현 해주셨네요 !
간단한 코멘트 남겨드렸으니 확인해주시면 감사하겠습니다 🙏🏻 
Q & A는 관련있는 코드에 남겨드렸어요 !

궁금한 점이 있으면 언제든지 코멘트 남겨주시거나 DM주세요!

> 추가적으로, auth 패키지가 아닌 shopping-cart 패키지는 레거시를 건들지 않았는데, test가 깨지더라고요..! shopping-cart는 2단계 미션이니, 2단계에 구현하면서 테스트를 패스시켜도 될까요?

네네 ! 우선 해당 내용은 2단계에서 고쳐보아요 ㅎ_ㅎ

2022-06-01 15:56 UTC, ddu0422 commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +            new MemberCreateRequest("abc@woowahan.com", "1q2w3e4r!", "닉네임");
### Q & A

> 현재는 인수테스트에 공통되는 픽스쳐를 꼼꼼히 분리시키지 않은 상태입니다. 픽스쳐를 분리하는 과정에서, 오히려 픽스쳐로 분리하니까
테스트를 하는 구체적인 값들이 한눈에 들어오지 않더라고요! 픽스쳐를 어떤 식으로, 어느 정도로 분리하면 좋을까요?
인수테스트에서 미르는 픽스쳐를 어느정도로 분리하시나요?

저는 모든 내용을 Fixture로 만들어서 재사용하고 싶은 마음이 들어요. 그 이유는 각각마다 이름을 만들어 줄 수 있기 때문이예요.

`INVALIE_EMAIL`과 `VALID_EMAIL` 등과 같이 테스트 코드를 읽으면서 어떤 값이 유효하고 유효하지 않은지 객체 내부를 살펴보지 않고도 알 수 있지 않을까요?
가독성과 관련이 있다고 볼 수 있는데, 가독성은 개개인마다 다르다고 느낄 수 있지만 저는 처음보는 사람이 해당 코드를 보면 어떤 의미로 받아들일 수 있을지 고민하면서 작성해요 !

현재는 팀 내에서 각 테스트마다 객체를 생성해서 사용하자는 의견이 많아 해당 의견으로 따라가고 있어요.

2022-06-02 05:17 UTC, Byeongju-Kong commented on docs/API.md
> +1 ~ 5 모두 프론트에서 먼저 검증하지만 만약의 경우를 대비해 백엔드에서 한번 더 검증
감사합니다~!

2022-06-02 05:18 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +    @GetMapping("/members")
오늘 팀원들과 다시 회의해서 변경하였습니다!

2022-06-02 05:20 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/ui/AuthController.java
> +                new CheckResponse(!authService.existsEmail(email));
그렇네요..! 해당 부분도 오늘 팀원들과 회의해서, 기존에 success였던 값을 unique로 변경했습니다!

2022-06-02 05:22 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/exception/AuthorizationException.java
> +    public AuthorizationException() {
삭제했습니다!

2022-06-02 05:25 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    @Transactional(readOnly = true)
해당 부분 제가 readOnly를 사용하는 경우랑, 사용하지 않는 경우를 뒤집어서 복붙을 했더라고요!
제 불찰입니다.. 😢 앞으로 이런 사소한 실수는 더 신경써야할 것 같습니다..😢

2022-06-02 05:27 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/application/AuthService.java
> +    @Transactional
해당 부분도 마찬 가지 입니다😢 
C,U,D는 @Transactinal
R은 @Transactional(readOnly = true)
로 모두 변경해두었습니다!

2022-06-02 05:32 UTC, Byeongju-Kong commented on docs/API.md
> +문자 :
인텔리제이에서 커밋할때, Command+Option+L을 통해 자동완성을 하게 해두었습니다.
그래서 커밋할 때, 인텔리제이가 제 멋대로 개행을 쳐버린 것으로 보입니다ㅜ! 수정해두었습니다!

2022-06-02 06:56 UTC, Byeongju-Kong commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +        assertThat(message).contains("형식이 올바르지 않습니다.");
처음에는 어차피 test가 다 통과하는 것이 목표이기 때문에, assertAll이 무의미한 것이 아닌가라는 생각이었는데,
테스트가 통과하지 않으면 어느 것이 통과하고, 어느 것이 통과하지 않는지 체크하는 것도 중요하다는 생각이 드네요!
assertAll으로 변경하였습니다!

2022-06-02 07:30 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/dao/MemberDao.java
> +    }
Optional 사용을 하지 않고, Member를 반환하는 방향으로 수정하였습니다.
service에서 dao의 findByEmail 메서드를 사용하기 전에, existsEmail을 통해서 email에 해당하는 정보가 존재함을 보장했습니다.
 그런데, findByEmail의 관점에서만 본다면, 이를 사용하는 곳에서 existsEmail 체크 여부를 모르기 때문에 
Optional을 반환해야한다는 의견도 있는데 어떻게 생각하시나요?
 저는 이정도는 개발자가 충분히 신경을 쓸 수 있다는 생각입니다!

2022-06-02 08:49 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/application/dto/request/MemberCreateServiceRequest.java
> +public class MemberCreateServiceRequest {
### 1. domain의 응집도가 높아진다면 어떤 장점이 있을까요?
service layer의 경우에는 domain을 통해 로직을 수행하기 때문에 domain의 변경에 부수효과가 일어나는 것이 불가피하다고 생각해요.
그런데 domain이 controller까지 넘어간다면, domain의 변경이 발생했을 때, controller도 변경되어야 할 수 있다고 생각해요.
domain의 변경으로 인한 부수효과의 범위를 serivce layer까지로 제한하는 것이 좋다고 생각합니다.

### service의 dto와 controller의 dto를 분리할 것인가?
사실 이 부분에 대해서는 저만의 생각을 계속 정립해보려고 하고있어요!
기존의 생각은 service에 controller의 dto가 들어온다면, controller가 변경되었을 때 해당 service를 사용하지 못할 것이라는 생각이었는데, 과연 service를 사용하는 controller가 여러 개가 될까? 라는 생각이 들었어요. 제가 아직 이 부분에 대한 경험은 없지만, controller와 service가 1대 1로 매칭되지 않을까?라는 생각입니다. 따라서, view-controller의 dto와 controller-service의 dto의 인터페이스가 같을 것이기 때문에 둘을 분리하지 않고 하나로 사용해도 되겠다는 생각이 드네요! 해당 부분은 계속해서 고민을 해봐야할 것 같아요!

 사실 해당 부분은 모든 경우에 맞는, 모두가 공감하는 방식이 없다는 생각이 드네요. 
지금은 controller가 변경될 가능성이 보이지 않기 때문에, 유지 보수의 관점에서 동일한 dto를 사용해도 될 것이라고 생각이 드네요.
동일한 dto를 사용하도록 변경했습니다!

2022-06-02 13:18 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/application/AuthService.java
> +        validatePassword(member.getPassword(), loginServiceRequest.getPassword());
그렇네요! email과 password 두 조건에 해당하는 Member를 찾게하는 쿼리문을 작성했습니다!

2022-06-03 07:45 UTC, Byeongju-Kong commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +            new MemberCreateRequest("abc@woowahan.com", "1q2w3e4r!", "닉네임");
그렇네요! 상수의 이름만으로 유효하지 않다. 유효하다를 파악만 하면 테스트 하는데 전혀 지장이 없을 것이라는 생각이 드네요!
저도 픽스쳐 분리를 해보았는데, 훨씬 깔끔한 것 같아서 픽스쳐를 분리했습니다!

2022-06-03 08:03 UTC, Byeongju-Kong commented on src/main/java/woowacourse/auth/ui/dto/request/MemberCreateRequest.java
> +    private String nickname;
검증에 대해서 저만의 기준을 잡아보았어요 미르!

결론부터 말씀드리자면, 저는 dto에서 @NotBlank나 @NotNull 정도의 검증만 하고, 나머지는 도메인에게 맡기는 것이 좋다고 생각합니다.

 먼저, dto에서 모든 검증을 해주어도 도메인에서 값에 대한 검증이 필요하다는 생각이 들어요. dto가 변경되었을 때, 해당 dto에 검증이 어느정도로 되어있을지 도메인의 입장에서는 모르고, 유효한 값이라는 것은 중요한 도메인 로직이기 때문에 도메인에 위치하는 것이 좋다고 생각해요.

 그렇다면, dto에서 어느 정도의 검증을 해줄 것인가가 고민이었어요. 
 먼저 위에 제가 작성했던 코드처럼 dto에서 값에 대한 정규식이 노출되었을 경우, dto에 도메인 로직이 노출되기 때문에, 도메인 레이어의 캡슐화를 저해한다는 생각이 들어요.

다음으로, 미르가 추천해주신 방식처럼 dto가 도메인을 의존하는 방식으로 검증하는 방식에 대해서 고민을 해보았어요.
위의 방식을 사용한다면, 자연스럽게 controller와 service가 도메인을 통해서 협력을 하게 될 것이라고 생각해요.

 여기서, 갈팡질팡했던 domain을 controller까지 노출시켜도 될까? 라는 저 만의 생각을 조금 정립해보았어요. 
 저는 controller와 service가 dto를 통해서 협력하는 것이 좋다고 생각해요.
service layer의 범주로 도메인을 캡슐화함으로써, controller가 view에게 응답해야 하는 정보를
domain 넘겨받아 직접 response 객체로 매핑하는 것이 아닌, service에게 필요한 정보만을 요청하는 것이 좋다고 생각해요.
 controller까지 불필요한 정보가 넘어가지 않을 수가 있겠죠.
 
  따라서, 저는 dto에서 NotNull 혹은 NotBlank 정도의 검증만 해주는 방향이 좋다고 생각합니다!
 해당 부분은 앞으로 경험을 해보면서 계속 고민해보는 것이 좋을 것이라고 생각이 드네요!

2022-06-03 08:25 UTC, Byeongju-Kong commented
미르! 고민해본 부분들은 미르가 리뷰 주셨던 코멘트의 댓글로 남겨두었습니다!
리뷰 잘 부탁드리겠습니다~!

2022-06-04 04:06 UTC, ddu0422 approved these changes
안녕하세요 크리스 ! 미르예요 :)

피드백 반영해주셔서 감사합니다 🙏🏻 
간단한 코멘트 남겨드렸으니 다음 미션을 진행할 때 참고해주시면 감사하겠습니다 ㅎ_ㅎ

1단계 미션 고생하셨고 다음 미션도 화이팅해보아요 !
궁금한 점은 언제든지 DM주시거나 코멘트 남겨주세요!

2022-06-04 04:06 UTC, ddu0422 commented on src/test/java/woowacourse/auth/acceptance/AuthAcceptanceTest.java
> +    private static final String MEMBERS_URI = "/api/members/me";
테스트에 필요한 데이터가 많아지는 경우 상수 선언이 길어지겠네요 ㅜ
별도의 클래스로 분리하는건 어떨까요?

2022-06-04 04:06 UTC, ddu0422 commented on src/main/java/woowacourse/auth/ui/dto/request/MemberCreateRequest.java
> +    @NotBlank
👍🏻 👍🏻

2022-06-04 04:07 UTC, merged