[Spring 장바구니 - 2단계] 후니(최재훈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #90
Opened 2022-06-08 00:49 UTC by jayjaehunchoi

안녕하세요~ 닉!!!
후니입니다.

2단계 미션을 통해 레거시 코드를 리팩터링하는 경험을 했는데요.
기존의 코드를 변경한다는 것이 쉬운일은 아니더라구요 ㅎㅎ;;

그래도 좋은 경험을 했던 것 같습니다!!!
이번 미션을 진행하면서 제가 고민했던 점을 공유드리겠습니다.

## Cart의 Product 직접참조
현재 Cart 도메인에서 Product를 직접 참조하고 있습니다.
그 이유는 총 가격 계산을 위함인데요. (다른 메서드는 id만으로 충분히 개선할 수 있을 듯 합니다.)
이 부분을 간접 참조로 변경하고 싶은데 어떤 방법으로 도메인 로직을 분리할 수 있을 지 고민입니다.

단순히 계산이라는 일을 수행하기 위해 계산 클래스를 생성하여 ProductDao를 갖고 있고, 해당 클래스에서 계산의 책임을 가지는게 과한 분리는 아닐까? 하는 고민이 들더라구요.

닉은 주로 어떤 상황에서 간접참조를 하고, 간접참조를 했을 때 간접 참조한 객체와 관련한 도메인 로직이 존재한다면 어떻게 해결하는지 궁금합니다!!

## LazyOrders
Orders가 OrderDetails을 조회시점에 join으로 가져오지 않고 사용하는 시점에 Lazy Load할 수 있게 코드를 작성하였는데요. 
join을 하지 않을 경우 매번 Service에서 OrderDetails를 따로 조회하는 것이 도메인 관점에서 안정성이 떨어진다고 생각했습니다.
또 join을 사용한다면 OrderDetails 개수만큼 조회한 row를 Orders라는 객체로 변환해야한다는 귀찮음도 존재했구요.

그래서 이렇게 Lazy Load하는 방식을 선택했는데, 이 코드에 대한 닉의 생각은 어떤지 궁금합니다!!

## properties 분리
현재 저는 `application-prod.properties`와 `application-local.properties`로 로컬 실행, 프로덕션 실행 환경을 분리해두는데요. 매번 `application.properties`의 profile.include를 변경하여 커밋하는 것이 조금 비효율적이라고 생각이 들었습니다.

로컬과 배포환경을 분리하여 참조하는 환경설정 파일 변경을 자동화할 수 있는 방법이 있을까요?

2022-06-10 02:31 UTC, wbluke requested changes
2단계 미션도 잘 해주셨네요 ㅎㅎ Lazy loading 구현이 인상적이네요 👍 
소소한 코멘트 남겼으니 한번 확인 부탁드려요 🙂

2022-06-10 06:59 UTC, jayjaehunchoi commented on src/test/java/woowacourse/shoppingcart/application/CartServiceTest.java
> +public class CartServiceTest {
안녕하세요 닉!!

그렇다면 테스트 코드를 위해 deleteAll 메서드를 추가하나요?? 클렌징을 어떤 방식으로 진행하면 좋을지 고민되네요..

2022-06-10 08:57 UTC, wbluke commented on src/test/java/woowacourse/shoppingcart/application/CartServiceTest.java
> +public class CartServiceTest {
아 맞네요. 보통 기본 스펙에서 제공하는 deleteAll() 메서드를 사용하는데(ex. JPA) 지금은 따로 구현하긴 해야겠네요 :)

2022-06-13 12:22 UTC, wbluke approved these changes
수정 잘 해주셨네요 ㅎㅎ 프로파일 분리도 나중에 꼭 해보셔요
레벨2 정말 고생 많으셨습니다. 즐거운 방학 보내세요 🙂

2022-06-13 12:22 UTC, merged