[Spring 장바구니 - 2단계] 오찌(오지훈) 미션 제출합니다.
woowacourse/jwp-shopping-cart pull request #98
Opened 2022-06-08 09:56 UTC by Ohzzi

안녕하세요 핀! 오찌입니다 :)
레거시 걷어낼 것 걷어내면서 데모데이 전까지 배포까지 하려다 보니까 시간이 워낙 촉박해서 좋은 코드를 만들지 못한 것 같아요 😭 

우선 1단계 머지될 당시 남겨주신 리뷰 중에서 api 주소 관련된 리뷰들은 프런트와의 협의 사항이어서 따로 수정을 하지 않고 넘어갔어요!

개인적으로 코드에 맘에 안드는 부분은 레거시 코드에서 이어진 도메인들이 객체를 참조로 가진게 아니라 id값들을 가지고 있어서 객체지향적이지 못한 것 같아요. 다만 마감에 쫓겨서 우선은 그대로 두었습니다! 추후 리뷰 받는 과정에서 리팩토링 해 나가도록 할게요!

이번에도 잘 부탁드립니다 :)

2022-06-11 02:03 UTC, lalize requested changes
안녕하세요 오찌!
2단계 구현 잘 해주셨어요~
몇가지 코멘트 남겨두었으니 확인해주세요~

2022-06-11 02:03 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/Product.java
> +    private Integer stock;
Stock은 어떤 의도로 추가된건가요?

2022-06-11 06:08 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/application/OrderService.java
> -package woowacourse.shoppingcart.application;
프론트엔드와의 협업 과정에서 프론트엔드는 주문 기능이 선택 사항이어서 우선은 주문 기능을 제외하고 구현하기로 했는데요, 문제는 협업 과정에서 기존 도메인을 수정하다 보니 주문 관련 기능이 정상적으로 작동하지 않고 컴파일 및 테스트가 깨져버리는 상황이었어요. 그래서 일단 구현 기한이 촉박한 관계로 당장에 사용하지 않을 주문 도메인을 제거했습니다 😭

2022-06-11 06:09 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/Product.java
> +    private Integer stock;
협업 과정에서 프론트는 이미 재고 기능을 만들어 놓은 상태였기 때문에 (재고보다 많은 수량을 장바구니에 담을 수 없게 하거나 품절 상태를 구현) 해당 기능들을 구현하기 위해서 `Product`에도 `stock`이라는 필드를 추가하고 해당 필드를 바탕으로 재고를 체크하는 기능들을 만들었습니다.

2022-06-11 06:11 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/application/ProductService.java
> +                .collect(Collectors.toUnmodifiableList());
저는 예전에 리스트를 만들 때 해당 값이 변하지 않는 것을 보장해주려고 감쌌었는데요, 이번에는 습관적으로 `toUnmodifiableList` 메서드를 사용했네요!

그런데 혹시 여기서 `unmodifiableList`를 사용하면 단점이 있을까요??

2022-06-11 06:12 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/application/CartService.java
> +    public Long saveOrUpdateCartItem(Long memberId, CartItemRequest cartItemRequest) {
개수를 바꾸더라도 결국에는 장바구니에 상품을 추가하는 것이니 메서드명을 상품 추가에 관련된 메서드명으로만 바꿔볼게요 :)

2022-06-11 06:14 UTC, Ohzzi commented on src/main/java/woowacourse/auth/application/AuthService.java
>                  .orElseThrow(() -> new IllegalArgumentException("이메일과 비밀번호를 확인해주세요."));
회원 정보가 없으면 `존재하지 않는 회원입니다.`, 회원은 있는데 비밀번호가 틀리면 `비밀번호를 확인해주세요.`와 같이 하려고 생각하기도 했는데요, HTTP 관련된 스터디를 하면서 예외 메시지에 상세 정보를 담지 말라고 하면서 잘못된 사례로 이와 같이 아이디가 틀렸을 때와 비밀번호가 틀렸을 때의 메시지를 따로 따로 구분하는 사례를 보기도 했고요, 그래서 이 부분을 가지고 팀원들과 얘기를 하면서 이메일이 틀렸을 때와 비밀번호를 틀렸을 때 메시지를 통일하기로 결정했기 때문에 이렇게 만들었어요!

2022-06-13 08:38 UTC, lalize requested changes
안녕하세요 오찌!
리뷰 반영 잘 해주셨어요~
몇가지 추가 코멘트 남겨두었으니 확인 부탁드려요~

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    }
add, replaceQuantity 둘 다 수량을 변경하는 메서드인데 이름에 일관성이 없는 것 같아요 👀

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +            this.quantity = quantity;
도메인 생성 규칙에서는 0 수량을 입력할 수 없는데, 해당 메서드로 0 수량으로 변경이 가능해도 괜찮을까요?

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    private Integer quantity;
wrapper class를 사용한 이유가 있으실까요?
Nullable 하지 않으면 primitive 타입을 사용하는 건 어떨까요?

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    private Integer quantity;
wrapper class를 사용한 이유가 있으실까요?
Nullable 하지 않으면 primitive 타입을 사용하는 건 어떨까요?

다른 코드도 함께 살펴봐주세요 :)

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/Product.java
> +    private Integer stock;
주문 기능을 제거해서 재고를 증차감 시키는 로직을 사용하는 코드가 없는 것 같네요 😭 
2단계 미션은 기존 기능은 유지한채로 리팩토링 하는 경험을 하는 것이니 시간 되시면 주문 기능을 살려보시고 재고 기능을 활용해봐도 좋을 것 같아요.

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/value/Password.java
> +    public boolean isSameValue(String value) {
isSameValue -> match는 어떨까요?

2022-06-13 08:38 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/application/ProductService.java
> +                .collect(Collectors.toList());
unmodifiableList를 반환하면 컴파일 시점에 예외 발생을 예상하지 못해서 개인적으로 지양하는 편입니다 :)

2022-06-14 03:07 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +            this.quantity = quantity;
0이 될 때는 아예 삭제 요청이 들어온다고 가정하고 0을 허용 안하도록 바꿔볼게요!

2022-06-14 03:07 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    }
생각해보니 그렇네요! add쪽에도 Quantity를 붙이겠습니다 :)

2022-06-14 03:08 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    private Integer quantity;
레거시 코드에 wrapper class를 사용했어서 통일성을 갖자고 그대로 사용했는데요, 생각해보니 해당 필드들은 not null 처리가 되어 있기 때문에 굳이 wrapping을 할 필요가 없을 것 같네요! 그렇다고 id처럼 0 값이 의미가 없는 값도 아니고요! 다른 코드들도 primitive 타입으로 바꾸겠습니다!

2022-06-14 03:09 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/Product.java
> +    private Integer stock;
오늘까지 리뷰 요청을 보내라는 공지가 와서 우선은 다른 수정 사항만 반영한 채로 요청을 보내고 주문 기능을 다시 복원해보는 쪽으로 코드를 계속 수정해보겠습니다 😄

2022-06-14 03:10 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    private Integer quantity;
다만 이 경우에 id 값들은 지금 not null이긴 한데 어떤 식으로 사용하는게 좋을까요? 저는 그래도 id값은 0이 의미없는 값이라서 wrapper class를 그대로 사용하고 싶은 상황이에요!

2022-06-15 09:24 UTC, lalize approved these changes
안녕하세요~ 오찌
리뷰 반영 잘 해주셨어요 :)
pr은 여기서 마무리 할게요~
레벨 2 고생 많으셨어요!!

2022-06-15 09:24 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/dao/ProductDao.java
> +        int passedId = (page - 1) * limit;
스프링 Pageable을 학습해보시면 좋을 것 같네요!

2022-06-15 09:28 UTC, lalize commented on src/main/java/woowacourse/shoppingcart/domain/CartItem.java
> +    private Integer quantity;
값이 없다는 의미로 0을 쓸건지 null로 쓸건지에 따라 결정하시면 될 것 같아요.

2022-06-15 09:28 UTC, merged

2022-06-17 15:24 UTC, Ohzzi commented on src/main/java/woowacourse/shoppingcart/dao/ProductDao.java
> +        int passedId = (page - 1) * limit;
안그래도 이번에 따로 사이드 프로젝트를 하면서 Pageable을 처음 써봤는데(이 미션 이후에 써봤어요) 너무 좋더라고요! sort까지 들어있고요! 좋은 의견 감사합니다 😄